---
title: "BOLD MRI Comparisons for Viji"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
format:
  html:
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
    fig-width: 10
    fig-height: 10
editor: source
---

```{r}
#| include: false
library(tidyverse)
library(psych)
library(corrplot)
library(pander)
library(gtsummary)
```

```{r}
#| warning: false
# Import
df = read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv",na.strings = "")
dict = read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/data_dictionary_master.csv")
# Filter and select columns
bold_vars = c("bold_l_bl_cortex","bold_l_bl_kidney","bold_l_bl_medulla",
              "bold_l_pf_cortex","bold_l_pf_kidney","bold_l_pf_medulla",
              "bold_r_bl_cortex","bold_r_bl_kidney","bold_r_bl_medulla",
              "bold_r_pf_cortex","bold_r_pf_kidney","bold_r_pf_medulla",
              "fsoc_l_cortex", "fsoc_l_kidney", "fsoc_l_medulla", 
              "fsoc_r_cortex", "fsoc_r_kidney", "fsoc_r_medulla")
kidney_vars = c("erpf_bsa_plasma","erpf_raw_plasma","ff","glomerular_pressure")
df = df %>% 
  filter(sglt2i_ever=="No",visit=="baseline",!grepl("IT2D",co_enroll_id)) %>%
  select(record_id:study,visit:date,group,all_of(bold_vars),all_of(kidney_vars)) %>%
  group_by(record_id,visit) %>%
  summarise(across(all_of(c("group",bold_vars,kidney_vars)),~first(na.omit(.x))),.groups = "drop") %>%
  filter_at(all_of(c(bold_vars,kidney_vars)), any_vars(!is.na(.)))
# Save data for Viji
# write.csv(df,file = "/Users/timvigers/Library/CloudStorage/Dropbox/Work/Shared/Michigan/CHCO_Sample_IDs_Clinical/bold_mri_for_viji_2023_03_14.csv")
```

```{r table 1}
#| label: tbl-1
#| tbl-cap: Bold parameters by specific group
#| warning: false
df %>% 
  select(group,all_of(bold_vars)) %>%
  rename_at(all_of(bold_vars), ~ dict$label[match(bold_vars,dict$variable_name)]) %>%
  tbl_summary(by = group,missing_text = "Missing",
              statistic = list(all_continuous() ~ "{mean} ({sd})")) %>%
  add_overall() %>%
  add_p(all_continuous()~"aov") %>%
  bold_p() 
```

```{r figure 1}
#| label: fig-1
#| fig-cap: Boxplots by specific group
#| warning: false
fig_df = df %>% pivot_longer(all_of(bold_vars))
fig_df$name = factor(fig_df$name,levels = bold_vars,labels = dict$label[match(bold_vars,dict$variable_name)])
ggplot(fig_df,aes(x=group,y=value)) + 
  geom_boxplot() + 
  facet_wrap(~name,scales = "free",ncol=3) +
  xlab("Group") + ylab("Value") +
  theme_bw()
```

```{r table 2}
#| label: tbl-2
#| tbl-cap: Bold parameters by group
#| warning: false
df %>% 
  mutate(group = str_replace(group, "Lean |Obese ", "")) %>%
  select(group,all_of(bold_vars)) %>%
  rename_at(vars(bold_vars), ~ dict$label[match(bold_vars,dict$variable_name)]) %>%
  tbl_summary(by = group,missing_text = "Missing",
              statistic = list(all_continuous() ~ "{mean} ({sd})")) %>%
  add_overall() %>%
  add_p(all_continuous()~"t.test") %>%
  bold_p() 
```

```{r figure 2}
#| label: fig-2
#| fig-cap: Boxplots by group
#| warning: false
fig_df$group = factor(fig_df$group,
                      levels = c("Lean Control","Obese Control","Type 2 Diabetes"),
                      labels = c("Control","Control","Type 2 Diabetes"))
ggplot(fig_df,aes(x=group,y=value)) + 
  geom_boxplot() + 
  facet_wrap(~name,scales = "free",ncol=3) +
  xlab("Group") + ylab("Value") +
  theme_bw()
```

```{r figure 3}
#| label: fig-3
#| fig-cap: Pearson correlation with kidney measures
M <- corr.test(y = df[,kidney_vars],x = df[,bold_vars],method = "pearson")
r <- M$r
rownames(r) = sub("[*]","",dict$label[match(rownames(r),dict$variable_name)])
colnames(r) = dict$label[match(colnames(r),dict$variable_name)]
p <- M$p
rownames(p) = sub("[*]","",dict$label[match(rownames(p),dict$variable_name)])
colnames(p) = dict$label[match(colnames(p),dict$variable_name)]
corrplot(r,p.mat = p, method = "square",insig = "blank")
```

```{r}
#| label: tbl-3
#| tbl-cap: Pearson correlation with kidney measures (statistically significant values in bold)
emphasize.strong.cells(which(p <= 0.05, arr.ind = TRUE))
pander(r)
```