---
title: "SGLT2i manuscript"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

# read in CROCODILE
source("E:\\Petter Bjornstad\\T2D scRNA SGLT2i\\Data raw\\CROCODILE-SGLT2iDescriptiveSta_R_2021-12-02_1719.r")
croc <- data
data <- NULL

# read in IMPROVET2D
source("E:\\Petter Bjornstad\\T2D scRNA SGLT2i\\Data raw\\IMPROVET2D-SGLT2iManuscriptDesc_R_2021-12-02_1719.r")
improve <- data
data <- NULL

# read in RENALHEIR
source("E:\\Petter Bjornstad\\T2D scRNA SGLT2i\\Data raw\\RENALHEIR-SGLT2iManuscriptDesc_R_2021-12-02_1718.r")
heir <- data
data <- NULL

# read in Michigan data
michigan <- read.csv("E:\\Petter Bjornstad\\T2D scRNA SGLT2i\\Data raw\\data_set_without_hpi.csv")

# calculate pglo_abs
michigan$TotProtgdL <- michigan$total_protein
michigan$HCt <- michigan$hematocrit
michigan$MAP_clamp <- michigan$clamp_map
michigan$HCt_clamp <- michigan$HCt/100
michigan$GFRabsmLs <- michigan$gfr/60
michigan$ERPFabsmLs <- michigan$rpf/60
michigan$FFabs <- michigan$gfr/michigan$rpf
michigan$RBFabs <- michigan$rpf/(1-michigan$HCt_clamp)
michigan$RBFGomabs <- michigan$ERPFabsmLs/(1-michigan$HCt_clamp)
michigan$RVRAbs <- michigan$MAP_clamp/michigan$RBFabs
michigan$Kfg <- ifelse(michigan$Group %in% c("T1D","T2D"),0.1012,0.1733)
michigan$deltaPFabs <- michigan$GFRabsmLs/michigan$Kfg
michigan$Cm_abs <- (michigan$TotProtgdL/michigan$FFabs)*log(1/(1-michigan$FFabs))
michigan$Pg_abs <- 5*(michigan$Cm_abs-2)
michigan$Pglo_abs <- michigan$Pg_abs+michigan$deltaPFabs+10
michigan$Ra_abs <- ((michigan$MAP_clamp - michigan$Pglo_abs)/michigan$RBFGomabs)*1328
michigan$Re_abs <- (michigan$GFRabsmLs/(michigan$Kfg*(michigan$RBFGomabs-michigan$GFRabsmLs)))*1328

write.csv(michigan,"E:\\Petter Bjornstad\\T2D scRNA SGLT2i\\Data clean\\data_set_without_hpi_with_pgloabs.csv",na = "")
```

# Background

# Methods

# Results

```{r echo=FALSE}
#kable(t1,caption = "")
```
<br>
