---
title: "SGLT2i manuscript - clinical characteristics"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 5
    toc_float: yes
---

```{r setup, include=FALSE}
library(arsenal)
library(tidyverse)
library(broom)
library(performance)
library(knitr)
source("/Users/timvigers/GitHub/CHCO-Code/Petter Bjornstad/Data Harmonization/data_harmonization.R")
knitr::opts_chunk$set(echo = FALSE,fig.height = 10,fig.width = 10)
# Import data
bold_data = harmonize_data()
```

# BOLD MRI

## Data skim

```{r}
# List variables
demo_vars = c("age","gender", "eGFR_fas_cr", "gfr","gfr_bsa","bmi","bmi_percentile")
bold_vars = c("bold_r_bl_cortex","bold_r_bl_medulla","bold_r_bl_kidney",
              "bold_r_pf_cortex","bold_r_pf_medulla","bold_r_pf_kidney",
              "bold_l_bl_cortex","bold_l_bl_medulla","bold_l_bl_kidney",
              "bold_l_pf_cortex","bold_l_pf_medulla","bold_l_pf_kidney",
              "fsoc_r_cortex","fsoc_r_medulla","fsoc_r_kidney",
              "fsoc_l_cortex","fsoc_l_medulla","fsoc_l_kidney")
# Filter and select
bold_data = bold_data %>% 
  filter(group == "T2D",co_enroll == "No",!is.na(sglt2i),
         case_when(study=="IMPROVE" ~ visit=="Pre-Surgery",T ~ visit=="Baseline")) %>%
  select(subject_id,study,visit,group,sglt2i,all_of(demo_vars),all_of(bold_vars))
bold_data$gender = droplevels(bold_data$gender)
# Summarize
skimr::skim(bold_data)
# Write CSV in case Petter wants to check the data
write.csv(bold_data,file = "~/Documents/Work/CHCO/Petter Bjornstad/T2D scRNA SGLT2i/Data clean/bold_data.csv",
          row.names = F,na="")
```

## Group comparisons (T2D only)

```{r results='asis'}
f = as.formula(paste0("sglt2i~",
                      paste0(demo_vars,collapse = "+"),"+",
                      paste0(bold_vars,collapse = "+")))
t_bold <- tableby(formula = f,data = bold_data, control = list(digits = 2))
summary(t_bold,pfootnote = T)
```

## Plots

```{r results='asis',warning=FALSE}
names=list("bold_r_bl_cortex" = "Pre-furosemide R2* Right Cortex",
           "bold_r_bl_medulla" = "Pre-furosemide R2* Right Medulla",
           "bold_r_bl_kidney" = "Pre-furosemide R2* Right Kidney",
           "bold_r_pf_cortex" = "Post-furosemide R2* Right Cortex",
           "bold_r_pf_medulla" = "Post-furosemide R2* Right Medulla",
           "bold_r_pf_kidney" = "Post-furosemide R2* Right Kidney",
           "bold_l_bl_cortex" = "Pre-furosemide R2* Left Cortex",
           "bold_l_bl_medulla" = "Pre-furosemide R2* Left Medulla",
           "bold_l_bl_kidney" = "Pre-furosemide R2* Left Kidney",
           "bold_l_pf_cortex" = "Post-furosemide R2* Left Cortex",
           "bold_l_pf_medulla" = "Post-furosemide R2* Left Medulla",
           "bold_l_pf_kidney" = "Post-furosemide R2* Left Kidney",
           "fsoc_r_cortex" = "FSOC Right Cortex",
           "fsoc_r_medulla" = "FSOC Right Medulla",
           "fsoc_r_kidney" = "FSOC Right Kidney",
           "fsoc_l_cortex" = "FSOC Left Cortex",
           "fsoc_l_medulla" = "FSOC Left Medulla",
           "fsoc_l_kidney" = "FSOC Left Kidney")
# Loop through outcomes
for (var in bold_vars) {
  n = as.character(names[var])
  p = ggplot(bold_data,aes_string(y=var,x="sglt2i",fill = "sglt2i")) + 
    geom_boxplot() + theme_bw() + theme(legend.position = "none") + 
    xlab("SGLT2i") + ylab(n)
  cat("\n")
  cat(paste0("### ",var))
  cat("\n")
  print(p)
  cat("\n")
}
```
