---
title: "BMI-adjusted analyses for sleep R01 proposal"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

home_dir = ifelse(.Platform$OS.type != "unix","T:\\",
                  "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects")
knitr::opts_knit$set(root.dir = home_dir)

data <- read.csv("E:\\Melanie Green\\Grants\\Sleep R01\\data\\final data for power analysis 12-29-2020.csv",na.strings = c(".",""," "))

data$group <- c(rep("None",3),rep("Mild",24),rep("Moderate",17),rep("Severe",11))
data$group_num <- c(rep(0,3),rep(1,24),rep(2,17),rep(3,11))
data$osa <- ifelse(data$group %in% c("None","Mild"),"No OSA","OSA")

```

# HOMA-IR

## OSA vs. no OSA

```{r echo=FALSE,comment=""}
mod <- lm(HOMA..FPGxFPI..405 ~ osa, data=data)
anova(mod)
```

## Severity group

```{r echo=FALSE,comment=""}
mod <- lm(HOMA..FPGxFPI..405 ~ group, data=data)
anova(mod)
```

# Two hour glucose

## OSA vs. no OSA

```{r echo=FALSE,comment=""}
mod <- lm(Glucose.T.1000...120. ~ osa, data=data)
anova(mod)
```

## Severity group

```{r echo=FALSE,comment=""}
mod <- lm(Glucose.T.1000...120. ~ group, data=data)
anova(mod)
```

# Hepatic fat

## OSA vs. no OSA

```{r echo=FALSE,comment=""}
mod <- lm(liver.fat.. ~ osa, data=data)
anova(mod)
```

## Severity group

```{r echo=FALSE,comment=""}
mod <- lm(liver.fat.. ~ group, data=data)
anova(mod)
```

# Urine night cortisol

## OSA vs. no OSA

```{r echo=FALSE,comment=""}
mod <- lm(Urine.Cortisol.Ug.hr ~ osa, data=data)
anova(mod)
```

# Leptin

## OSA vs. no OSA

```{r echo=FALSE,comment=""}
mod <- lm(Leptin.0800...0. ~ osa, data=data)
anova(mod)
```

# Fasting FFA

## OSA vs. no OSA

```{r echo=FALSE,comment=""}
mod <- lm(FFA.T.0800...0. ~ osa, data=data)
anova(mod)
```

# OSTT 120 FFA

## OSA vs. no OSA

```{r echo=FALSE,comment=""}
mod <- lm(FFA.T.1000...120. ~ osa, data=data)
anova(mod)
```

# Fasting AdipoIR

## OSA vs. no OSA

```{r echo=FALSE,comment=""}
mod <- lm(ffa.insulin ~ osa, data=data)
anova(mod)
```
