---
title: "Preliminary CVD cytokine analysis"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(knitr)
library(dplyr)
library(data.table)
library(tidyr)

####################################################################################################
#Data Manipulation #
####################################################################################################

# read main data sheet
all <- read.csv("/Users/timvigers/Downloads/Jenny manifest v4 GRP2 9th Jan 2019.csv",na.strings = c("","NA"," "))
all$ANALYTICID <- as.character(all$ANALYTICID)
# delete records with missing data
all <- all[!is.na(all$IFN.g),]

# read in randomization
rand <- read.csv("/Users/timvigers/Downloads/metformin vs placebo.csv")
rand$ANALYTICID <- as.character(rand$ANALYTICID)

# merge datasets
alldata <- merge(all,rand,by=c("ANALYTICID"))

# get rid of unneeded variables
alldata <- select(alldata,-c("RN","PARENT_ID","SAMPLE_ID","STORAGETYPE","SAMPLEGROUP","BOX.ID","NO.","ROW","COL","pg.ml","X"))

# assign variable for pre vs. post treatment
alldata <- alldata[order(alldata$ANALYTICID,alldata$COLLECTIONDT),]
alldata <- alldata %>% group_by(ANALYTICID) %>% mutate(id=row_number())
alldata$prepost[alldata$id==1] <- "PRE"
alldata$prepost[alldata$id==2] <- "POST"


# calculate deltas
alldata$ANALYTICID <- factor(alldata$ANALYTICID)
test <- alldata[,c("ANALYTICID","IFN.g","prepost")]

# Tim deltas
nums <- unlist(lapply(alldata, is.numeric)) 
deltas <- alldata[alldata$prepost == "POST",nums] - alldata[alldata$prepost == "PRE",nums]
deltas$ANALYTICID <- alldata$ANALYTICID[alldata$prepost == "PRE"]
```

# Background

  

# Methods


# Results

There were `r N` subjects included in this analysis.  Descriptive statistics are shown in Table 1.

```{r, results='asis',tidy=TRUE, echo=FALSE}
kable(tab1,caption="Table 1.  Descriptive statistics.  Asterisks indicate that Fisher's exact test was used instead of the chi-square test due to small expected cell value.")
```


