#Libraries ----
library(data.table)
library(missForest)
library(plyr)
library(dplyr)
library(stringr)
library(forcats)
library(ggplot2)
library(readxl)
library(tidyverse)
# devtools::install_github("Goodrich-Lab/EnvirOmix")
library(EnvirOmix)
library(epiomics)
library(bkmr)
library(r.jive)
library(table1)
library(cowplot)
# library(ComplexHeatmap)
library(ggh4x)
#LUCIDus Version 3.0.1 is required for this analysis:
library(LUCIDus)
library(networkD3)
library(plotly)
library(htmlwidgets)
library(jsonlite)
library(mix)
# install.packages("mice")
library(mice)
# General Packages:
library(EnvirOmix)
library(tidyverse)
library(table1)
# Load plotting packages:
library(ggplot2)
library(cowplot)
# library(ComplexHeatmap)
library(ggh4x)
# Packages for Quasi-mediation:
#LUCIDus Version 3.0.1 is required for this analysis:
# library(htmltools)
library(purrr)
library(data.table) 
library(dplyr) 
library(glmnet)
library(ggplot2) 
library(caret) 
library(xgboost) 
library(e1071) 
library(cowplot) 
library(ISLR)
library(glmnet)
library(tidyr)
# install.packages("ltm")
library(ltm)
# install.packages("HIMA")
library(HIMA)
# install.packages("ranger")
library(ranger)
# install.packages("xtune")
library(xtune)
# install.packages("boot")
library(boot)
#Install pathview
# install.packages("BiocManager")
# library(BiocManager)
# # BiocManager::install(c("Rgraphviz", "png", "KEGGgraph", "org.Hs.eg.db"))
# # install.packages("pathview", repos="http://R-Forge.R-project.org")
# library(pathview)
# # BiocManager::install("AnnotationDbi",force=TRUE)
# # BiocManager::install("KEGGREST",force=T)
# library(KEGGREST)
# # BiocManager::install("metaboliteIDmapping",force=T)
# library(metaboliteIDmapping)
# # install.packages("fastmap")
# library(fastmap)
# # BiocManager::install("pathview",force=T)
# library(remotes)
# remotes::install_version("fastmap", version = "1.2.0")
# detach("package:fastmap", unload = TRUE)
# install.packages("psych")
library(psych)
