---
title: "Shanlee Davis - XXY GXT testing"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(knitr)
library(nlme)
library(emmeans)
library(ggplot2)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

# read in longitudinal data
alldata <- read.csv("E:\\Davis\\XXY exercise testing\\GXT variables (2).csv")

# drop AT and Peak rows
data <- alldata[!alldata$stage %in% c("AT","Peak"),]
# recode baseline as 0
data$stage <- ifelse(data$stage=="Baseline",0,data$stage)
# clean up
data$notes <- NULL
data$X <- NULL
data$X.1 <- NULL
data$X.2 <- NULL
data$X.3 <- NULL
data$stage <- as.factor(data$stage)
data$Case <- as.factor(data$Case)

# plot the data
p1 <- ggplot(data,aes(x = stage,y = VO2)) +
  geom_smooth(aes(group = Case, linetype=Case), se = T, color="black") + 
  theme_bw() + xlab("Stage") + ylab("VO2") + labs(linetype ='Case/Control')

# drop stages 11 and 12 - few observations
data <- data[data$stage != 12,]
data <- data[data$stage != 11,]
data$stage <- droplevels(data$stage)

# VO2 
vo2_mod <- lme(VO2 ~ stage*Case,random=~1|ID,data = data,na.action = na.omit)
vo2_mod_anova <- anova.lme(vo2_mod, type="marginal")
# use emmeans 
vo2_mod_means <- emmeans(vo2_mod,c("stage","Case"))
vo2_mod_pairs <-  pairs(vo2_mod_means,adjust="tukey",simple="each")

```

# Background



# Methods


# Results

## Differences between metformin and placebo groups in change in echo measures

```{r echo=FALSE}
kable(t1,caption = "Table 1.  Differences between metformin and placebo groups in change (visit 2-visit 1) in echo measures")
```
<br>

