---
title: "Voxel-wise distribution comparisons"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(knitr)
library(BSDA)

```

# K1 right cortex

```{r echo=FALSE}
tsum.test(
  mean.x = 1.1739,
  s.x = 0.1777,
  n.x = 10,
  mean.y = 1.1142,
  s.y = 0.1652,
  n.y = 16,
  alternative = "two.sided",
  mu = 0,
  var.equal = FALSE,
  conf.level = 0.95
)
```

# K1 right medulla

```{r echo=FALSE}
tsum.test(
  mean.x = 1.1739,
  s.x = 0.1777,
  n.x = 10,
  mean.y = 1.1142,
  s.y = 0.1652,
  n.y = 16,
  alternative = "two.sided",
  mu = 0,
  var.equal = FALSE,
  conf.level = 0.95
)
```

# K1 left cortex

```{r echo=FALSE}
tsum.test(
  mean.x = 1.1739,
  s.x = 0.1777,
  n.x = 10,
  mean.y = 1.1142,
  s.y = 0.1652,
  n.y = 16,
  alternative = "two.sided",
  mu = 0,
  var.equal = FALSE,
  conf.level = 0.95
)
```

# K1 left medulla

```{r echo=FALSE}
tsum.test(
  mean.x = 1.1739,
  s.x = 0.1777,
  n.x = 10,
  mean.y = 1.1142,
  s.y = 0.1652,
  n.y = 16,
  alternative = "two.sided",
  mu = 0,
  var.equal = FALSE,
  conf.level = 0.95
)
```

# K2 right cortex

```{r echo=FALSE}
tsum.test(
  mean.x = 1.1739,
  s.x = 0.1777,
  n.x = 10,
  mean.y = 1.1142,
  s.y = 0.1652,
  n.y = 16,
  alternative = "two.sided",
  mu = 0,
  var.equal = FALSE,
  conf.level = 0.95
)
```

# K2 right medulla

```{r echo=FALSE}
tsum.test(
  mean.x = 1.1739,
  s.x = 0.1777,
  n.x = 10,
  mean.y = 1.1142,
  s.y = 0.1652,
  n.y = 16,
  alternative = "two.sided",
  mu = 0,
  var.equal = FALSE,
  conf.level = 0.95
)
```

# K2 left cortex

```{r echo=FALSE}
tsum.test(
  mean.x = 1.1739,
  s.x = 0.1777,
  n.x = 10,
  mean.y = 1.1142,
  s.y = 0.1652,
  n.y = 16,
  alternative = "two.sided",
  mu = 0,
  var.equal = FALSE,
  conf.level = 0.95
)
```

# K2 left medulla

```{r echo=FALSE}
tsum.test(
  mean.x = 1.1739,
  s.x = 0.1777,
  n.x = 10,
  mean.y = 1.1142,
  s.y = 0.1652,
  n.y = 16,
  alternative = "two.sided",
  mu = 0,
  var.equal = FALSE,
  conf.level = 0.95
)
```