---
title: "EMERALD echo electro analysis"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}

library(knitr)

knitr::opts_chunk$set(echo = FALSE,cache = FALSE)
library(dplyr)
library(tableone)
library(reshape2)

# read in data
alldata <- read.csv("E:\\Nadeau\\Nadeau EMERALD\\Echo\\Raw data\\EMERALG_Echo_Electro.csv")

# drop unneeded variables
alldata$X <- NULL
alldata$first_name <- NULL
alldata$last_name <- NULL
alldata$screening_date <- NULL

# code randomization group
alldata$randgroup <- ifelse(alldata$randomization==1,"Metformin","Placebo")

# make sure everything is numeric
notecho <- c("subject_id","randomization","Visit","randgroup")
echovars <- colnames(alldata[,!colnames(alldata) %in% notecho])
#alldata[,!colnames(alldata) %in% notecho] <- as.numeric(as.character(alldata[,!colnames(alldata) %in% notecho]))

# calculate deltas
wide <- reshape(alldata,idvar = "subject_id",timevar = "Visit",direction = "wide") 
wide$randomization.2 <- NULL
wide$randomization <- wide$randomization.1
wide$randomization.1 <- NULL
wide$randgroup.2 <- NULL
wide$randgroup <- wide$randgroup.1
wide$randgroup.1 <- NULL

for(i in 1:length(echovars)) {
  wide[,paste0(echovars[i],"_delta")] <-  wide[,paste0(echovars[i],".2")] - wide[,paste0(echovars[i],".1")]
}

# compare changes in the treatment groups
t1_vars <- colnames(wide[,grep("delta",colnames(wide))])
t1 <- CreateTableOne(data=wide,vars=t1_vars,strata = "randgroup")
t1 <- print(t1,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,test = T,nonnorm=c("SSF_delta","SSF.1_delta","SSF.2_delta","SSF.3_delta",
                                                                                             "SSF.4_delta","SSF.5_delta","SSF.6_delta",
                                                                                             "DRF.1_delta","DRF.2_delta","DRF.3_delta",
                                                                                             "DRF.4_delta","DRF.5_delta","DRF.6_delta"))
t1 <- t1[,1:4]

p <- NULL
p_met <- NULL
for (i in 1:length(t1_vars)) {
  p <- round(t.test(wide[wide$randgroup=="Metformin",paste0(t1_vars[i])],mu=0)$p.value,4)
  p_met <- c(p_met,p)
}
p_met <- c("",p_met)
t1 <- cbind(t1,p_met)

p <- NULL
p_pla <- NULL
for (i in 1:length(t1_vars)) {
  p <- round(t.test(wide[wide$randgroup=="Placebo",paste0(t1_vars[i])],mu=0)$p.value,4)
  p_pla <- c(p_pla,p)
}
p_pla <- c("",p_pla)
t1 <- cbind(t1,p_pla)


# get baseline characteristics
emerald <- read.csv("E:\\Nadeau\\Nadeau EMERALD\\EMERALD_DATA_2017-08-24.csv",na.strings = c("","."))
keep <- emerald[,c("subject_id","age","gender","a1c","diabetes_duration","bmi_percentile","bmi_baseline_clamp","bmi_final_clamp",
                   "dexa_fat_perc","dexa_fat_perc_final","mg_kg_min_80_gluc_corrected","mg_kg_min_80_gluc_corrected_final",
                   "mg_kglean__min_80_gluc_corrected","mg_kglean__min_80_gluc_corrected_final")]
keep$bmi_delta <- keep$bmi_final_clamp - keep$bmi_baseline_clamp
keep$dexa_fat_perc_delta <- keep$dexa_fat_perc_final - keep$dexa_fat_perc
keep$mg_kg_min_80_gluc_corrected_delta <- keep$mg_kg_min_80_gluc_corrected_final - keep$mg_kg_min_80_gluc_corrected
keep$mg_kglean__min_80_gluc_corrected_delta <- keep$mg_kglean__min_80_gluc_corrected_final - keep$mg_kglean__min_80_gluc_corrected
wide <- merge(wide,keep,by="subject_id",all.x = T,all.y = F)

# table of demographic and clinical characteristics
wide$genderfactor <- as.factor(ifelse(wide$gender==1,"Female","Male"))
demovars <- c("age","genderfactor","a1c","diabetes_duration","bmi_percentile","bmi_baseline_clamp","bmi_final_clamp",
                   "dexa_fat_perc","dexa_fat_perc_final","mg_kg_min_80_gluc_corrected","mg_kg_min_80_gluc_corrected_final",
                   "mg_kglean__min_80_gluc_corrected","mg_kglean__min_80_gluc_corrected_final","bmi_delta","dexa_fat_perc_delta",
                    "mg_kg_min_80_gluc_corrected_delta","mg_kglean__min_80_gluc_corrected_delta")
demotable <- CreateTableOne(data=wide,vars=demovars,strata = "randgroup")
demotable <- print(demotable,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,test = T)
demotable <- demotable[,1:4]

# table of baseline factors by sex
sexvars <- c("age","a1c","diabetes_duration","bmi_percentile","bmi_baseline_clamp","dexa_fat_perc","mg_kg_min_80_gluc_corrected","mg_kglean__min_80_gluc_corrected")
sextable <- CreateTableOne(data=wide,vars=sexvars,strata = "genderfactor")
sextable <- print(sextable,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,test = T)
sextable <- sextable[,1:4]


 # for(i in 1:length(t1_vars)) {
 #     hist(wide[,noquote(t1_vars[i])],main=noquote(t1_vars[i]))
 # }

```

# Background
# also check...value of SSF.3 for 6377-52 visit 1 should be set to 0?  currently "?NAME"

# Methods

# Results

```{r, echo=FALSE}
kable(demotable,caption="Table 1a.  Descriptive statistics for demographic and clinical factors by treatment group.")
```

```{r, echo=FALSE}
kable(sextable,caption="Table 1b.  Descriptive statistics for baseline demographic and clinical factors by sex.")
```

```{r, echo=FALSE}
kable(t1,caption="Table 2.  Changes in echo parameters.  The column labeled 'p' is the p-value comparing the change in the metformin group to the change in the placebo group.  The column labeled 'p_met' tests whether the change in the metformin group is different from 0, and and the column labeled 'p_pla' tests whether the change in the placebo group is different from 0.")
```


