---
title: "CGM variables by Tanner stage"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plyr)
library(Hmisc)
library(tidyverse)
library(broom)
library(tableone)
library(ggplot2)
library(knitr)
library(sjlabelled)

# read in healthy control data
source("H:\\Endocrinology\\Chan\\CGM by Tanner in lean and obese healthy youth\\CGMInHealthyControls-HealthyControlCGMByT_R_2020-03-26_1255.r")
hc <- data
hc <- hc[!is.na(hc$total_sensor_readings),]
# create one variable for Tanner stage - girls by breast, boys by testicular volume
hc$breast_sum <- ifelse(hc$tanner_stage_female_breast___1==1,1,
                        ifelse(hc$tanner_stage_female_breast___2==1,2,
                               ifelse(hc$tanner_stage_female_breast___3==1,3,
                                      ifelse(hc$tanner_stage_female_breast___4==1,4,
                                             ifelse(hc$tanner_stage_female_breast___5==1,5,NA)))))
hc$test_sum <- ifelse(hc$tanner_stage_male_testicul___1==1,1,
                        ifelse(hc$tanner_stage_male_testicul___2==1,2,
                               ifelse(hc$tanner_stage_male_testicul___3==1,3,
                                      ifelse(hc$tanner_stage_male_testicul___4==1,4,
                                             ifelse(hc$tanner_stage_male_testicul___5==1,5,NA)))))
hc$tanner <- ifelse(hc$gender.factor=="Female",hc$breast_sum,hc$test_sum)
# decide which visit to keep
hc$newid <- substr(hc$subject_id,1,3)
hc <- hc[!is.na(hc$tanner),]
hc <- hc[!duplicated(hc$newid),]
hc$sex.factor <- hc$gender.factor
# subject 099 is an outlier - take him out
hc <- hc[!(hc$subject_id=="099"),]

# read in obese youth data - need to subset to those with normal OGTTs
source("H:\\Endocrinology\\Chan\\CGM by Tanner in lean and obese healthy youth\\A1cAndGlycemiaInObes-CGMByTannerStage_R_2020-03-26_1300.r")
obese <- data
obese <- obese[!is.na(obese$fpg) & obese$fpg<100,]
obese <- obese[!is.na(obese$hogtt) & obese$hogtt<140,]
obese <- obese[!is.na(obese$cgm_readings_48),]
# create one variable for Tanner stage
obese$tanner <- ifelse(obese$sex.factor=="Female",obese$tanner_br,obese$tanner_test_equ)

# now keep only the variables we need and make sure they are named the same
hc_keep <- hc[,c("subject_id","tanner","sex.factor","average_sensor",
 "standard_deviation","min_sensor","max_sensor", 
 "q1_sensor","median_sensor","q3_sensor","estimated_a1c" ,                       
 "percent_time_over_120","percent_time_over_140","percent_time_over_180",
 "percent_time_over_200","percent_time_over_250","avg_excur_over_140_per_day",
 "avg_excur_over_200_per_day","percent_time_under_54","percent_time_under_60",
 "percent_time_under_70","daytime_avg_sensor_glucose",           
 "daytime_min_sensor_glucose","daytime_max_sensor_glucose" ,          
 "daytime_sd","nighttime_avg_sens_glucose","nighttime_min_sens_glucose",           
 "nighttime_max_sens_glucose","nighttime_sd","average_auc_per_day",                 
 "mean_amp_glycemic_ex","r_mage","modd","lbgi","hbgi","age")]

obese_keep <- obese[,c("subject_id","tanner","sex.factor","asg_48","cgm_sd_48","min_sg_48",
                       "max_sg_48","q1_sensor_48","median_sensor_48","q3_sensor_48",
                       "estimated_a1c_48","perc_timegreater120_48","perc_timegreater140_48",
                       "percent_time_over_180_48","perc_timegreater200_48","percent_time_over_250_48",
                       "avg_ex_over_140_per_day_48","avg_ex_over_200_per_day_48",
                       "percent_time_under_54_48","percent_time_under_60_48",
                       "percent_time_under_70_48","asg_day_48","min_day_48","peak_day_48",
                       "sd_day_48","asg_night_48","min_night_48","peak_night_48","sd_night_48",
                       "average_auc_48","mage_48","r_mage_48","modd_48","lbgi_48","hbgi_48","age")]           
colnames(obese_keep) <- c("subject_id","tanner","sex.factor","average_sensor",
 "standard_deviation","min_sensor","max_sensor", 
 "q1_sensor","median_sensor","q3_sensor","estimated_a1c" ,                       
 "percent_time_over_120","percent_time_over_140","percent_time_over_180",
 "percent_time_over_200","percent_time_over_250","avg_excur_over_140_per_day",
 "avg_excur_over_200_per_day","percent_time_under_54","percent_time_under_60",
 "percent_time_under_70","daytime_avg_sensor_glucose",           
 "daytime_min_sensor_glucose","daytime_max_sensor_glucose" ,          
 "daytime_sd","nighttime_avg_sens_glucose","nighttime_min_sens_glucose",           
 "nighttime_max_sens_glucose","nighttime_sd","average_auc_per_day",                 
 "mean_amp_glycemic_ex","r_mage","modd","lbgi","hbgi","age")                 

cgmvars <- c("age","average_sensor", "standard_deviation","min_sensor","max_sensor", 
 "q1_sensor","median_sensor","q3_sensor","estimated_a1c" ,                       
 "percent_time_over_120","percent_time_over_140","percent_time_over_180",
 "percent_time_over_200","percent_time_over_250","avg_excur_over_140_per_day",
 "avg_excur_over_200_per_day","percent_time_under_54","percent_time_under_60",
 "percent_time_under_70","daytime_avg_sensor_glucose",           
 "daytime_min_sensor_glucose","daytime_max_sensor_glucose" ,          
 "daytime_sd","nighttime_avg_sens_glucose","nighttime_min_sens_glucose",           
 "nighttime_max_sens_glucose","nighttime_sd","average_auc_per_day",                 
 "mean_amp_glycemic_ex","r_mage","modd","lbgi","hbgi")

hc_keep <- remove_all_labels(hc_keep)
obese_keep <- remove_all_labels(obese_keep)

# write a file of the Tanner 1 HC data to see if there are outliers
tan1 <- hc_keep[hc_keep$tanner==1,]
write.csv(tan1,"H:\\Endocrinology\\Chan\\CGM by Tanner in lean and obese healthy youth\\tanner1.csv") 

# create a variable for Tanner stage with 2-4 combined
hc_keep$tanner_new <- ifelse(hc_keep$tanner %in% c(2,3,4),"2-4",
                             ifelse(hc_keep$tanner==1,"1","5"))
obese_keep$tanner_new <- ifelse(obese_keep$tanner %in% c(2,3,4),"2-4",
                             ifelse(obese_keep$tanner==1,"1","5"))

# need df of HC without Tanner 4 (N=1)
hc_keep_no4 <- hc_keep[hc_keep$tanner != 4,]

# dfs of HC by sex
hc_keep_girls <- hc_keep[hc_keep$sex.factor=="Female",]
hc_keep_boys <- hc_keep[hc_keep$sex.factor=="Male",]

hctab <- CreateTableOne(vars=cgmvars, data=hc_keep, strata = "tanner", test=TRUE)
hctab <- print(hctab,varLabels=FALSE)

hctab_no4 <- CreateTableOne(vars=cgmvars, data=hc_keep_no4, strata = "tanner", test=TRUE)
hctab_no4 <- print(hctab_no4,varLabels=FALSE)

hctab_24comb <- CreateTableOne(vars=cgmvars, data=hc_keep, strata = "tanner_new", test=TRUE)
hctab_24comb <- print(hctab_24comb,varLabels=FALSE)

hctab_age_girls <- CreateTableOne("age", data=hc_keep_girls, strata = "tanner", test=TRUE)
hctab_age_girls <- print(hctab_age_girls,varLabels=FALSE)

hctab_age_boys <- CreateTableOne("age", data=hc_keep_boys, strata = "tanner", test=TRUE)
hctab_age_boys <- print(hctab_age_boys,varLabels=FALSE)

obtab <- CreateTableOne(vars=cgmvars, data=obese_keep, strata = "tanner", test=TRUE)
obtab <- print(obtab,varLabels=FALSE)

obtab_24comb <- CreateTableOne(vars=cgmvars, data=obese_keep, strata = "tanner_new", test=TRUE)
obtab_24comb <- print(obtab_24comb,varLabels=FALSE)



```

Note: in this version of the analysis, subject 099 was excluded.

```{r, echo=FALSE}
kable(hctab,caption = "Table 1a.  Descriptive statistics for healthy controls by Tanner stage.")
```
<br>

```{r, echo=FALSE}
kable(hctab_no4,caption = "Table 1b.  Descriptive statistics for healthy controls by Tanner stage, excluding Tanner 4.")
```
<br>

```{r, echo=FALSE}
kable(hctab_24comb,caption = "Table 1c.  Descriptive statistics for healthy controls by Tanner stage, with Tanner stages 2-4 combined.")
```
<br>

```{r, echo=FALSE}
kable(hctab_age_girls,caption = "Table 1d.  Age for female healthy controls by Tanner stage.")
```
<br>

```{r, echo=FALSE}
kable(hctab_age_boys,caption = "Table 1e.  Age for male healthy controls by Tanner stage.")
```
<br>

```{r, echo=FALSE}
kable(obtab,caption = "Table 2a.  Descriptive statistics for obese adolescents with normal fasting glucose and normal 2 hour glucose, by Tanner stage.")
```
<br>

```{r, echo=FALSE}
kable(obtab_24comb,caption = "Table 2b.  Descriptive statistics for obese adolescents with normal fasting glucose and normal 2 hour glucose, by Tanner stage, with Tanner stages 2-4 combined.")
```
<br>


