---
title: "RPC2 Descriptive analysis"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    embed-resources: true
---

```{r libraries, echo=F, include = F}
library(tidyverse)
library(arsenal)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(readxl)
source("/Users/choiyej/GitHub/YC_CHCO/R Functions/label_harmonized_function.R")
```

```{r echo = F}
# REDCap token for RPC2
api_tok <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/api_tokens.csv")

rpc2_tok <- api_tok[api_tok$Study == "RPC2",]$Token
# uri for REDCap
uri <- "https://redcap.ucdenver.edu/api/"
# read from REDCap
rpc2 <- redcap_read(redcap_uri = uri, token = rpc2_tok)$data
rpc2_meta <- redcap_metadata_read(redcap_uri = uri, token = rpc2_tok)$data
rpc2_lab <- rpc2_meta %>%
  filter(form_name == "labs") %>%
  filter(is.na(select_choices_or_calculations))
rpc2_lab_names <- rpc2_lab$field_name

rpc2_subset_epic <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Exports/rpc2_biopsy_meds.csv") %>%
  dplyr::summarise(across(everything(), ~ ifelse(all(is.na(.x)), NA, first(na.omit(.x)))),
                   .by = subject_id) 

rpc2_dat <- rpc2 %>%
  rowwise() %>%
  dplyr::mutate(gender = case_when(gender == 0 ~ "Female", 
                            gender == 1 ~ "Male", 
                            gender == 2 ~ "Other"),
         race = case_when(sum(c_across(all_of(race_vars))) > 1 ~ "More than one",
                          race___1 == 1 ~ "American Indian or Alaskan Native",
                          race___2 == 1 ~ "Asian",
                          race___3 == 1 ~ "Hawaiian or Pacific Islander",
                          race___4 == 1 ~ "Black or African American",
                          race___5 == 1 ~ "White",
                          race___6 == 1 ~ "Unknown",
                          race___7 == 1 ~ "Other"),
         ethnicity = case_when(ethnicity___1 == 1 ~ "Hispanic",
                               ethnicity___2 == 1 ~ "Non-Hispanic",
                               ethnicity___3 == 1 ~ "Unknown/Not Reported"),
         group = case_when(diabetes_hx_type == 1 ~ "Type 1 Diabetes",
                           diabetes_hx_type == 2 ~ "Type 2 Diabetes"),
         across(contains("date"), as.character),
         diagnosis = as.character(diagnosis),
         surgery_hx_end = as.character(surgery_hx_end),
         medstart = as.character(medstart),
         medstop = as.character(medstop),
         dob = as.character(dob),
         avg_asl = mean(asl_right, asl_left, na.rm = T),
         avg_adc = mean(adc_right, adc_left, na.rm = T),
         tkv = sum(c(volume_right, volume_left), na.rm = F),
         avg_bl_c = mean(c(bold_r_bl_cortex, bold_l_bl_cortex), na.rm = T),
         avg_bl_k = mean(c(bold_r_bl_kidney, bold_l_bl_kidney), na.rm = T)) %>%
  ungroup() %>%
  dplyr::summarise(across(everything(), ~ ifelse(all(is.na(.x)), NA, first(na.omit(.x)))),
                   .by = subject_id) 

```

```{r echo = F}
summary(arsenal::tableby(~age_current + gender + race + ethnicity + group + weight + height + bmi + 
                           sys_bp + dys_bp + map + chol_base + hba1c + screen_egfr + kwt(screen_urine_acr, "Nmiss", "median", "q1q3"), data = rpc2_dat))
```

```{r echo = F}
# BOLD MRI
summary(arsenal::tableby(~avg_asl + avg_adc + tkv + avg_bl_c + avg_bl_k, data = rpc2_dat))
```

As of 1/28/25:
11 unique participants with biopsy, 3 with repeat biopsy? (redcap)
12 unique participants with biopsy, 9 with repeat biopsy? (spreadsheet)

```{r echo = F}
# Baseline meds for those with biopsies
med_vars <- rpc2_subset_epic %>%
  select(ends_with("_1"), -kidneybx_1) %>%
  names()

# Construct the formula
formula <- reformulate(med_vars)

summary(arsenal::tableby(formula, data = rpc2_subset_epic))
```

