---
title: "IGF and IGFBP in HC, OB, T2D"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes    
---

```{r libraries}
#| include: false
library(limma)
library(clusterProfiler)
library(ReactomePA)
library(enrichplot)
library(Hmisc)
library(knitr)
library(tidyverse)
library(gtsummary)
library(ggpubr)
library(lmerTest)
library(parallel)
library(emmeans)
library(RColorBrewer)
library(VennDiagram)
library(broom.mixed)
library(dplyr)
#library(xlsx)
```

```{r include=FALSE}
df <- read.csv("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv")
load("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Data Harmonization/Harmonized SomaScan/analytes.RData")

# use only baseline samples
df <- soma_harmonized %>% filter(visit=="baseline")

# identify columns corresponding to proteins
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(df))

# log transform
df <- df %>% modify_if(is_seq(names(.)), log)

# keep 3 groups
df <- df %>% filter(group %in% c("Lean Control", "Obese Control", "Type 2 Diabetes"))

# keep proteins of interest
analyte_igf <- analytes %>% filter(UniProt %in% c("P05019","P17936","P35858","P01241","P18065","P22692","P24593",
                                                         "P10912","P08833","P24592","P01019"))
apt_keep <- analyte_igf$AptName


```

```{r include=TRUE, echo=FALSE}
# need to make each boxplot independently, then combine
# then save
comparison_groups = list(c("Lean Control", "Obese Control"),
                         c("Lean Control", "Type 2 Diabetes"),
                         c("Obese Control", "Type 2 Diabetes"))

# note to self: need to figure out why y-axis labels are wrong
# also figure out why Ns don't match htn

# write a function to make each panel of the plot
panel_in_boxplot <- function(data, apt) {
  prot <- analytes %>%
  filter(AptName %in% apt) %>%
  pull(Target)
  analytes_temp <- analytes
  analytes_temp <- analytes_temp[analytes_temp$AptName %in% apt,]
  analytes_temp$Target_apt <- paste0(analytes_temp$Target, " (", analytes_temp$AptName, ")")
  #TA <- analytes_temp$Target_apt[match[analytes_temp$AptName, apt]]
  TA <- analytes_temp$Target_apt[analytes_temp$AptName==apt]
  p <- ggplot(data[!is.na(data$group),],
       aes(x = group,
                     y = .data[[apt]],
                     fill = group))  +
  geom_boxplot() +  
  labs(x = NULL,
       y = TA,
       fill = "group") + 
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 14),
        axis.text.x = element_text(size = 14,
                                   angle = -45), 
        legend.text = element_text(size = 16),
        panel.background = element_rect(fill = "#f2e9e4",
                                        color = "grey")) + 
  scale_fill_manual(values = c("#c2dfe3", "#fff9ec",
                                "#fcb1a6")) +
  geom_jitter() +
  stat_compare_means(comparisons = comparison_groups,
                     method = "t.test",
                     label = "p.signif", size = 4, hide.ns = T)   
  #+ 
  #scale_y_continuous(expand = expansion(mult = c(1.2, 1.2)))
}

# function call for above template
p_seq.13741.36 <- panel_in_boxplot(data = df, apt = "seq.13741.36")
p_seq.13741.36

p_seq.14088.38 <- panel_in_boxplot(data = df, apt = "seq.14088.38")
p_seq.14088.38

p_seq.19581.15 <- panel_in_boxplot(data = df, apt = "seq.19581.15")
p_seq.19581.15

p_seq.22985.160 <- panel_in_boxplot(data = df, apt = "seq.22985.160")
p_seq.22985.160

p_seq.2570.72 <- panel_in_boxplot(data = df, apt = "seq.2570.72")
p_seq.2570.72

p_seq.2571.12 <- panel_in_boxplot(data = df, apt = "seq.2571.12")
p_seq.2571.12

p_seq.2685.21 <- panel_in_boxplot(data = df, apt = "seq.2685.21")
p_seq.2685.21

p_seq.2686.67 <- panel_in_boxplot(data = df, apt = "seq.2686.67")
p_seq.2686.67

p_seq.2771.35 <- panel_in_boxplot(data = df, apt = "seq.2771.35")
p_seq.2771.35

p_seq.2948.58 <- panel_in_boxplot(data = df, apt = "seq.2948.58")
p_seq.2948.58

p_seq.2950.57 <- panel_in_boxplot(data = df, apt = "seq.2950.57")
p_seq.2950.57

p_seq.2952.75 <- panel_in_boxplot(data = df, apt = "seq.2952.75")
p_seq.2952.75

p_seq.3484.60 <- panel_in_boxplot(data = df, apt = "seq.3484.60")
p_seq.3484.60

p_seq.6605.17 <- panel_in_boxplot(data = df, apt = "seq.6605.17")
p_seq.6605.17

p_seq.8462.18 <- panel_in_boxplot(data = df, apt = "seq.8462.18")
p_seq.8462.18

p_seq.8469.41 <- panel_in_boxplot(data = df, apt = "seq.8469.41")
p_seq.8469.41

p_seq.8819.3 <- panel_in_boxplot(data = df, apt = "seq.8819.3")
p_seq.8819.3
```

