---
title: "IMPROVE ELISA IGF-1 results"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes    
---

```{r libraries}
#| include: false
library(limma)
library(clusterProfiler)
library(ReactomePA)
library(enrichplot)
library(Hmisc)
library(knitr)
library(tidyverse)
library(gtsummary)
library(ggpubr)
library(lmerTest)
library(parallel)
library(emmeans)
library(RColorBrewer)
library(VennDiagram)
library(broom.mixed)
library(dplyr)
#library(xlsx)

```

```{r include=FALSE}
total_igf1 <- read.csv("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/IMPROVE T2D/Data_Raw/Improve total IGF-1 results.csv")
total_igf1$Visit <- factor(total_igf1$Visit, levels=c("Baseline", "3 month", "12 month"))
free_igf1 <- read.csv("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/IMPROVE T2D/Data_Raw/Free igf.csv")
free_igf1$Visit <- factor(free_igf1$Visit, levels=c("Baseline", "3 month", "12 month"))

p_total <- ggplot(total_igf1,aes(Visit,Final.Result)) + 
                geom_boxplot(aes(fill=Visit)) + 
                ylab("Total IGF-1") + 
                theme(axis.title.x = element_text(size = 16),
                    axis.title.y = element_text(size = 14),
                    axis.text.x = element_text(size = 14,
                                   angle = -45), 
                    legend.text = element_text(size = 16),
                    panel.background = element_rect(fill = "#f2e9e4",
                                        color = "grey")) + 
                scale_fill_manual(values = c("#c2dfe3", "#fff9ec",
                                "#fcb1a6")) +
                geom_jitter() 


p_free <- ggplot(free_igf1,aes(Visit,Final.Results)) + 
                geom_boxplot(aes(fill=Visit)) + 
                ylab("Free IGF-1") + 
                theme(axis.title.x = element_text(size = 16),
                    axis.title.y = element_text(size = 14),
                    axis.text.x = element_text(size = 14,
                                   angle = -45), 
                    legend.text = element_text(size = 16),
                    panel.background = element_rect(fill = "#f2e9e4",
                                        color = "grey")) + 
                scale_fill_manual(values = c("#c2dfe3", "#fff9ec",
                                "#fcb1a6")) +
                geom_jitter() 
```

```{r include=TRUE, echo=FALSE}

# write a function to make each panel of the plot
panel_in_boxplot <- function(data, apt) {
  prot <- analytes %>%
  filter(AptName %in% apt) %>%
  pull(Target)
  analytes_temp <- analytes
  analytes_temp <- analytes_temp[analytes_temp$AptName %in% apt,]
  analytes_temp$Target_apt <- paste0(analytes_temp$Target, " (", analytes_temp$AptName, ")")
  #TA <- analytes_temp$Target_apt[match[analytes_temp$AptName, apt]]
  TA <- analytes_temp$Target_apt[analytes_temp$AptName==apt]
  p <- ggplot(data[!is.na(data$group),],
       aes(x = group,
                     y = .data[[apt]],
                     fill = group))  +
  geom_boxplot() +  
  labs(x = NULL,
       y = TA,
       fill = "group") + 
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 14),
        axis.text.x = element_text(size = 14,
                                   angle = -45), 
        legend.text = element_text(size = 16),
        panel.background = element_rect(fill = "#f2e9e4",
                                        color = "grey")) + 
  scale_fill_manual(values = c("#c2dfe3", "#fff9ec",
                                "#fcb1a6")) +
  geom_jitter() +
  stat_compare_means(comparisons = comparison_groups,
                     method = "t.test",
                     label = "p.signif", size = 4, hide.ns = T)   
  #+ 
  #scale_y_continuous(expand = expansion(mult = c(1.2, 1.2)))
}
```

```{r include=TRUE, echo=FALSE, warning=FALSE}
p_total
p_free
```
