--- 
title: "IMPROVE"
author: "Tim Vigers"
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    page-layout: full
editor: source
--- 

```{r}
#| include: false
library(tidyverse)
library(arsenal)
# Import and filter
df = read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv",na.strings = "")
df = df %>% filter(study == "IMPROVE",visit %in% c("baseline","12_months_post_surgery"))
# Select variables for T1
df = df %>% 
  select(record_id,visit,procedure,weight,bmi,
         dexa_body_fat,bod_pod_body_fat,gfr_raw_plasma,gfr_bsa_plasma,
         ff,acr_u,contains("fsoc_"),map,sbp,dbp,fbg,hba1c,airg,acprg,
         contains("glom_volume"),mes_matrix_area,mes_index,
         contains("mes_volume"),glom_nuc_count,
         metformin_timepoint,insulin_med_timepoint,
         sglti_timepoint,raasi_timepoint) %>%
  group_by(record_id,visit) %>%
  summarise_all(~first(na.omit(.x)))
# Additional formatting
df$visit = factor(df$visit,levels = c("baseline","12_months_post_surgery"),
                  labels = c("Baseline","12 Months Post Surgery"))
ids = df$record_id[which(duplicated(df$record_id))]
df = df %>% filter(record_id %in% ids)
```

```{r results='asis'}
f = as.formula(paste0("visit~",paste0(colnames(df)[4:ncol(df)],collapse = "+")))
t1 = paired(f,data = df,id=record_id,numeric.test = "notest", cat.test = "notest")
summary(t1)
```

# Questions
1. Do we have M-values for these clamps?
