---
title: "Microbiome Analysis"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, include=FALSE}
# Load libraries and functions
library(microbiome)
source('~/Documents/GitHub/Tim-and-Laura/tim_R_functions.R')
# Check OS and alter file path accordingly.
if (.Platform$OS.type == "windows") {pathstart <- "//ucdenver.pvt/"} else if (.Platform$OS.type == "unix"){pathstart <- "/Volumes/"}
```

```{r echo=FALSE,include=FALSE}
# Data management
filename <- paste0(pathstart,"som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura Tim projects/Melanie Green/Microbiome/Data_Raw/alltaxa_cts_29May2018.csv")
# Read microbiome data.
dat <- read.csv(filename,row.names = 1)
dat <- dat[-c(1),]
# Make OTU table.
otumat <- dat
otumat <- as.matrix(otumat)
OTU <- otu_table(otumat,taxa_are_rows = T)
# Make taxa table
taxmat <- str_split_fixed(rownames(dat),pattern = "/", n = 7)
rownames(taxmat) <- row.names(dat)
colnames(taxmat) <- 
  c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species")
taxmat[taxmat == ""] <- "Unknown"
TAX <- tax_table(taxmat)
# Read in sample data.
filename <- paste0(pathstart,"som/RI Biostatistics Core/Shared/Shared Projects/Laura Tim projects/Melanie Green/Microbiome/Data_Raw/Clinical data-9-2-2018.csv")
sammat <- read.csv(filename,row.names = 1,stringsAsFactors = F)
SAM <- sample_data(sammat)
# Combine into physeq object
pseq <- phyloseq(OTU, TAX, SAM)
```

```{r echo=FALSE,include=FALSE}
# Relative abundance.
relative <- transform_sample_counts(pseq, function(x) x / sum(x))
otus <- as.data.frame(otu_table(relative))
# Transpose.
otus <- as.data.frame(t(otus))
otus$subject.id <- rownames(otus)
# Free testosterone
otus$free.test <- sammat$FreeTesto
# Move columns
otus <- otus %>% select("subject.id",everything())
# Correlations
corrs <- corr.test(otus[,2:(ncol(otus)-1)],otus$free.test,method = "spearman",adjust = "fdr")
# Table
corr.table <- as.data.frame(cbind(corrs$r,corrs$n,corrs$p))
corr.table <- round(corr.table,3)
colnames(corr.table) <- c("R","n","P Value")
corr.table$Taxa <- rownames(corr.table)
corr.table <- select(corr.table,"Taxa",everything())
corr.table <- corr.table[order(corr.table$`P Value`),]
```

Table 1: Relative Abundance Spearman Correlation with Free Testosterone, FDR Adjusted P-Values
```{r echo=FALSE}
kable(corr.table,row.names = F)
```

```{r echo=FALSE,include=FALSE}
# Correlations unadjusted p
corrs <- corr.test(otus[,2:(ncol(otus)-1)],otus$free.test,method = "spearman",adjust = "none")
# Table
corr.table <- as.data.frame(cbind(corrs$r,corrs$n,corrs$p))
corr.table <- round(corr.table,3)
colnames(corr.table) <- c("R","n","P Value")
corr.table$Taxa <- rownames(corr.table)
corr.table <- select(corr.table,"Taxa",everything())
corr.table <- corr.table[order(corr.table$`P Value`),]
```

Table 2: Relative Abundance Spearman Correlation with Free Testosterone, Un-adjusted P-Values
```{r echo=FALSE}
kable(corr.table,row.names = F)
```

```{r echo=FALSE,include=FALSE}
# Make a matrix with samples in rows, OTUs in columns
transposed <- otumat
transposed <- t(transposed)
# Calculate centered log ratios
logs <- propr(transposed)
logs <- as.data.frame(logs@logratio)
# Combine log ratios and sample data.
logs$subject.id <- rownames(logs)
logs <- logs %>% select("subject.id",everything())
logs$free.test <- sammat$FreeTesto
# Correlations
corrs <- corr.test(logs[,2:(ncol(logs)-1)],logs$free.test,method = "spearman")
# Table
clr.corr.table <- as.data.frame(cbind(corrs$r,corrs$n,corrs$p))
clr.corr.table <- round(clr.corr.table,3)
colnames(clr.corr.table) <- c("R","n","P Value")
clr.corr.table$Taxa <- rownames(clr.corr.table)
clr.corr.table <- select(clr.corr.table,"Taxa",everything())
clr.corr.table <- clr.corr.table[order(clr.corr.table$`P Value`),]
```

```{r echo=FALSE,eval=FALSE}
kable(clr.corr.table,row.names = F)
```

```{r echo=FALSE,include=FALSE,eval=FALSE}
# Correlations unadjusted p
corrs <- corr.test(logs[,2:(ncol(logs)-1)],logs$free.test,method = "spearman",adjust = "none")
# Table
log.corr.table <- as.data.frame(cbind(corrs$r,corrs$n,corrs$p))
log.corr.table <- round(log.corr.table,3)
colnames(log.corr.table) <- c("R","n","P Value")
log.corr.table$Taxa <- rownames(log.corr.table)
log.corr.table <- select(log.corr.table,"Taxa",everything())
log.corr.table <- corr.table[order(corr.table$`P Value`),]
```

```{r echo=FALSE,eval=FALSE}
kable(log.corr.table,row.names = F)
```

```{r echo=FALSE,eval=FALSE}
# Merge CLR and non-transformed tables (unadjusted p values)
merged <- base::merge(corr.table,log.corr.table,by = "Taxa")
colnames(merged) <- c("Taxa","R","n","P","CLR R","CLR n","CLR P")
merged <- merged[,c("Taxa","R","P","CLR R","CLR P")]
```

```{r echo=FALSE,eval=FALSE}
kable(merged,row.names = F)
```

```{r echo=FALSE}
# Vegan package ordination
# Taxa in columns
distmat <- otumat
dist <- vegdist(distmat,method = "horn")
mds <- metaMDS(dist,trace = FALSE, distance = "horn")
plot(mds)

tree <- as.dendrogram(hclust(dist,"average"))
plot(tree, type = "t")
```