---
title: "ADC Summary"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    classoption: landscape
editor: visual

---
\begingroup
\setlength{\LTleft}{0pt minus 200pt}
\setlength{\LTright}{0pt minus 200pt}
\fontsize{5pt}{7pt}\selectfont
\addtolength{\tabcolsep}{-3pt}

```{r setup, include=F}
library(dplyr)
library(reticulate)
library(Hmisc)
library(tidyverse)
library(scales)
library(kableExtra)
library(gtools)
library(table1)
library(naniar)

setwd("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/")

# read in raw data
dat <- read.csv("./Data Clean/harmonized_dataset.csv")

panda <- read.csv("/Users/choiyej/GitHub/YC_CHCO/Harmonization/PANDA032323.csv")
panda <- panda %>% 
  replace_with_na_all(condition = ~.x %in% common_na_numbers) %>%
  mutate(group = case_when(group=="1" ~ "Type 1 Diabetes", group=="2" ~ "CRC-SUB")) %>%
  mutate(study = "PANDA") %>%
  select(record_id, study, group, adc_left, adc_right)

panther <- read.csv("/Users/choiyej/GitHub/YC_CHCO/Harmonization/PANTHER032323.csv")
panther <- panther %>% 
  replace_with_na_all(condition = ~.x %in% common_na_numbers) %>%
  mutate(group = case_when(group=="1" ~ "Type 2 Diabetes", 
                           group=="2" ~ "Obese Control", 
                           group=="3" ~ "Lean Control")) %>%
  mutate(study = "PANTHER") %>%
  select(record_id, study,  group, adc_left, adc_right)

renal_heiritage <- read.csv("/Users/choiyej/GitHub/YC_CHCO/Harmonization/RENALHEIRTAGE032323.csv")
renal_heiritage <- renal_heiritage %>% 
  replace_with_na_all(condition = ~.x %in% common_na_numbers) %>%
  mutate(study = "RENAL-HEIRitage") %>%
  group_by(record_id) %>%
  fill(names(renal_heiritage)) %>%
  summarise_all(last) %>%
  mutate(group = case_when(group=="1" ~ "Type 2 Diabetes", 
                           group=="2" ~ "Obese Control", 
                           group=="3" ~ "Lean Control", 
                           is.na(group) ~ "Type 2 Diabetes")) %>%
  select(record_id, study, group, adc_left, adc_right) %>%
  filter(!is.na(group))

# merge
dat <- bind_rows(dat, panda, panther, renal_heiritage)

# clean data
clean_dat <- dat %>%
  group_by(record_id) %>%
  fill(names(dat)) %>%
  summarise_all(last) %>%
  select(record_id, study, group, adc_left, adc_right) 

clean_dat$group <- factor(clean_dat$group, levels = c("Lean Control", "Obese Control", "Type 1 Diabetes", "Type 2 Diabetes", "PKD", "CRC-SUB", "PANDA", "Missing"))

# complete data only
complete_dat <- clean_dat %>%
  filter(!is.na(adc_left)|!is.na(adc_right))

label(clean_dat$adc_left) <- "ADC Left"
label(clean_dat$adc_right) <- "ADC Right"
label(complete_dat$adc_left) <- "ADC Left"
label(complete_dat$adc_right) <- "ADC Right"
```
{{< pagebreak >}}
## ADC Summary By Study

No ADC fields for:

-   ULTRA T2D
-   ATTEMPT

Missing *ALL* ADC entries for:

-   CASPER

-   COFFEE

-   IMPROVE

-   PENGUIN

```{r, warning=FALSE}
table1(~ adc_left + adc_right | study, data = clean_dat, overall=c(left="Total"))
```

## ADC Summary By Group

```{r}
table1(~ adc_left + adc_right | group, data = clean_dat, overall=c(left="Total"))
```

{{< pagebreak >}}

## ADC Summary By Study (Complete Only)

```{r}
table1(~ adc_left + adc_right | study, data = complete_dat, overall=c(left="Total"))
```

## ADC Summary By Group (Complete Only)

```{r}
table1(~ adc_left + adc_right | group, data = complete_dat, overall=c(left="Total"))
```
\endgroup