---
title: "TODAY Somalogic 10 year cross-sectional analyses - adjusted models"
author: "Laura Pyle and Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
# not sure how to present this - table of results? figure? just the top 10 from baseline analysis? top 10 for this analysis?

library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r, include=FALSE}
setwd(home_dir)

# load somalogic data, with QC samples already excluded
load("./Somalogic data raw/soma.Rdata")

# load analyte info
load("./Somalogic data raw/analytes.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# load year 10 covariates
load("./Clinical data/TODAY/yr10risk.Rdata")

# load baseline risk factors
load("./Clinical data/TODAY/baserisk.Rdata")

# find the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)

# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# merge in baseline risk factors
base <- left_join(base, baserisk, by="releaseid")

# identify columns corresponding to proteins and convert to numeric
is_seq <- function(.x) grepl("seq", .x)
base <- base %>%
       mutate(across(starts_with("seq"),
              ~ as.numeric(as.character(.))))

# only keep observations with nonmissing values of covariates
# otherwise size of contrast matrix will be incorrect
# for glycemia, the covariates are GLYC + bmi + si_1_ins0 + AGEBASE + sex
base <- base %>% filter(!is.na(bmi) & !is.na(si_1_ins0) & !is.na(AGEBASE) & !is.na(sex))

# find follow-up samples
fup <- soma %>% anti_join(base, soma, by=c("releaseid","Date.Drawn"))

# merge in nephropathy data
fup <- left_join(fup, comorb, by="releaseid")

# merge in year 10 covariates
fup <- left_join(fup, yr10risk, by="releaseid")

# identify columns corresponding to proteins and convert to numeric
fup <- fup %>%
       mutate(across(starts_with("seq"),
              ~ as.numeric(as.character(.))))

# log transform
fup_log <- fup %>% modify_if(is_seq(names(.)), log)

# create df of changes in proteins
base_for_deltas <- base
base_for_deltas <- base_for_deltas %>% filter(releaseid %in% fup_log$releaseid)
base_for_deltas <- base_for_deltas %>% modify_if(is_seq(names(.)), log)
fup_log <- fup_log %>% filter(releaseid %in% base_for_deltas$releaseid)
fup_log <- fup_log %>% arrange(releaseid)
base_for_deltas <- base_for_deltas %>% arrange(releaseid)
a <- fup_log %>% select(starts_with("seq"))
b <- base_for_deltas %>% ungroup() %>% select(starts_with("seq"))
deltas <- as.data.frame(a) - as.data.frame(b)
GLYC_vector <- fup_log$GLYC
```

## Change in proteins by outcome

```{r echo=FALSE, include=TRUE}

# UNADJUSTED
delta_glyc_contrast <- model.matrix(~ 1 + GLYC_vector)
# moderated t-tests with and without FDR adjustment
ymat <- t(deltas)
fit <- lmFit(ymat,delta_glyc_contrast)
fit <- eBayes(fit)
results_delta_glyc <- topTable(fit,coef = 2,number = nrow(ymat))
results_delta_glyc$AptName <- row.names(results_delta_glyc)
results_delta_glyc <- merge(results_delta_glyc,analytes,by="AptName",all.x = T, all.y = F)
results_delta_glyc <- results_delta_glyc[order(results_delta_glyc$P.Value),] 

# ADJUSTED
delta_glyc_contrast_adj <- model.matrix(~ 1 + GLYC_vector + bmi + si_1_ins0 + AGEBASE + sex, base_for_deltas)
# moderated t-tests with and without FDR adjustment
ymat <- t(deltas)
fit <- lmFit(ymat,delta_glyc_contrast_adj)
fit <- eBayes(fit)
results_delta_glyc_adj <- topTable(fit,coef = 2,number = nrow(ymat))
results_delta_glyc_adj$AptName <- row.names(results_delta_glyc_adj)
results_delta_glyc_adj <- merge(results_delta_glyc_adj,analytes,by="AptName",all.x = T, all.y = F)
results_delta_glyc_adj <- results_delta_glyc_adj[order(results_delta_glyc_adj$P.Value),] 

# WRITE RESULTS
wb <- createWorkbook()

addWorksheet(wb,"delta_glyc_unadjusted")
writeData(wb,"delta_glyc_unadjusted",results_delta_glyc,rowNames = F)

addWorksheet(wb,"delta_glyc_adjusted")
writeData(wb,"delta_glyc_adjusted",results_delta_glyc_adj,rowNames = F)

saveWorkbook(wb,"./Results/Linear and Cox models/TODAY somalogic limma delta glyc.xlsx",overwrite = TRUE)
saveWorkbook(wb,"/Users/pylell/Dropbox/TODAY glycemic manuscript [shared]/Analysis output/TODAY somalogic limma delta glyc.xlsx",overwrite = TRUE)
```
