---
title: "EMERALD echo data - Alex Nguyen"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: yeti
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(stringr)
library(Hmisc)
library(dplyr)
library(skimr)
library(tableone)
library(knitr)
library(tidyverse)
library(rstatix)
library(ggpubr)
library(car)
library(hablar)

options(scipen=999)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

# echo data
# need to fix variable names
cardiac <- read.csv("E:\\Nadeau\\Nadeau EMERALD\\Echo\\Alex\\Raw data\\EMERALD DATA SUMMARIZED cardiac.csv",na.strings = c(NA,""))
names <- colnames(cardiac)
names <- names[3:352]
rootnames <- NA
for (i in seq(1,length(names),by=2)) {
  rootnames <- c(rootnames,names[i])
  names[i+1] <- paste0(names[i],"2")
  names[i] <- paste0(names[i],"1")
}
rootnames <- rootnames[-1]
# fix column names  
numnames <- names
names <- c("Study.ID","randomization",names)
colnames(cardiac) <- names

# 4 variables have percent signs in values
# cardiac$GLS....1 cardiac$GLS....2 cardiac$GCS....1 cardiac$GCS....2
cardiac$GLS....1 <- as.numeric(gsub("\\%","",cardiac$GLS....1))
cardiac$GLS....2 <- as.numeric(gsub("\\%","",cardiac$GLS....2))
cardiac$GCS....1 <- as.numeric(gsub("\\%","",cardiac$GCS....1))
cardiac$GCS....2 <- as.numeric(gsub("\\%","",cardiac$GCS....2))

# calculate deltas
Study.ID <- as.matrix(cardiac$Study.ID)
for (x in rootnames)  {
  del.x <- paste0("delta.",x) 
  v2.x <- paste0(x,"2")
  v1.x <- paste0(x,"1")
  temp <- select(cardiac,v2.x) - select(cardiac,v1.x)
  colnames(temp) <- del.x
  Study.ID <- as.data.frame(cbind(Study.ID,temp))
}
cardiac <- merge(cardiac,Study.ID,by="Study.ID")
cardiac$group <- ifelse(cardiac$randomization==1,"Metformin","Placebo")

# merge in group sheet so we have last name and BMI percentile
# don't need treatment group since that is already in the cardiac sheet
groups <- read.csv("E:\\Nadeau\\Nadeau EMERALD\\Echo\\Alex\\Raw data\\EMERALD DATA SUMMARIZED groups.csv",na.strings = c(NA,""))
groups$Group <- NULL
cardiac <- merge(cardiac,groups,by="Study.ID",all.x = T,all.y = F)

# merge in extra views
extra <- read.csv("E:\\Nadeau\\Nadeau EMERALD\\Echo\\Alex\\Raw data\\tracedata_combined_REVISED_strain.csv",na.strings = c(NA,""))
extra_names <- colnames(extra)
extra_names <- extra_names[2:61]
extra_rootnames <- NA
for (i in seq(1,length(extra_names),by=2)) {
  extra_rootnames <- c(extra_rootnames,extra_names[i])
  extra_names[i+1] <- paste0(extra_names[i],"2")
  extra_names[i] <- paste0(extra_names[i],"1")
}
extra_rootnames <- extra_rootnames[-1]
# fix column names  
extra_numnames <- extra_names
extra_names <- c("name",extra_names)
colnames(extra) <- extra_names
# extract first and last names
extra$last_name <- sub(",.*", "", extra$name)   
extra$first_name <- sub(".*, ", "", extra$name)     
# calculate deltas
names <- as.matrix(cbind(extra$last_name,extra$first_name))
colnames(names) <- c("last_name","first_name")
for (x in extra_rootnames)  {
  del.x <- paste0("delta.",x) 
  v2.x <- paste0(x,"2")
  v1.x <- paste0(x,"1")
  temp <- select(extra,v2.x) - select(extra,v1.x)
  colnames(temp) <- del.x
  names <- as.data.frame(cbind(names,temp))
}
extra <- merge(extra,names,by=c("last_name","first_name"))
#extra[extra$last_name=="O#Dell",]$last_name <- "O'Dell"
extra[extra$last_name=="Debord",]$last_name <- "DeBord"
extra[extra$first_name=="Lucus",]$first_name <- "Lucas"

# get rid of spaces
cardiac$first_name <- gsub(" ", "", cardiac$first_name, fixed = TRUE)
cardiac$last_name <- gsub(" ", "", cardiac$last_name, fixed = TRUE)
extra$first_name <- gsub(" ", "", extra$first_name, fixed = TRUE)
extra$last_name <- gsub(" ", "", extra$last_name, fixed = TRUE)

# names don't match up
a <- cardiac[,c("first_name","last_name")]
a <- cbind(a,rep(1,nrow(a)))
colnames(a) <- c("first_name","last_name","in_cardiac_data")
b <- extra[,c("first_name","last_name")]
b <- cbind(b,rep(1,nrow(b)))
colnames(b) <- c("first_name","last_name","in_extra_views")
check <- merge(a,b,by=c("first_name","last_name"),all.x=T,all.y=T)

cardiac <- merge(cardiac,extra,by=c("first_name","last_name"),all.x = T,all.y=T)

# will not take BMI percentile from labs sheet b/c fewer missing data points on group sheet
labs <- read.csv("E:\\Nadeau\\Nadeau EMERALD\\Echo\\Alex\\Raw data\\EMERALD DATA SUMMARIZED labs.csv")
labs <- labs %>% convert(num(mg_kg_min_80_gluc_corrected_final,mg_kglean__min_80_gluc_corrected,
                     mg_kglean__min_80_gluc_corrected,mg_kglean__min_80_gluc_corrected_final))
labs$delta_gir <- labs$mg_kg_min_80_gluc_corrected_final - labs$mg_kglean__min_80_gluc_corrected
labs$delta_gir_lean <- labs$mg_kglean__min_80_gluc_corrected_final - labs$mg_kglean__min_80_gluc_corrected
labs$delta_bmi <- labs$bmi_final_clamp - labs$bmi_baseline_clamp
keep_labs <- labs[,c("subject_id","gender","diabetes_duration","a1c","first_name","last_name","mg_kg_min_80_gluc_corrected_final","mg_kglean__min_80_gluc_corrected",
                     "delta_gir","mg_kglean__min_80_gluc_corrected","mg_kglean__min_80_gluc_corrected_final","delta_gir_lean","bmi_final_clamp","bmi_baseline_clamp",
                     "delta_bmi")]
cardiac <- merge(cardiac,keep_labs,by=c("first_name","last_name"),all.x = T, all.y = F)

control <- read.csv("E:\\Nadeau\\Nadeau EMERALD\\Echo\\Alex\\Raw data\\EMERALD DATA SUMMARIZED control echo.csv")

# still not sure if we are using these variables
#trace <- read.csv("E:\\Nadeau\\Nadeau EMERALD\\Echo\\Alex\\Raw data\\tracedata_combined_trace")

# nonnorm <- c("delta.AV.CO","delta.AV.Diam","delta.AV.SV","delta.AV.Vmax","delta.HR","delta.LA.Diam","delta.LALd.A4c","delta.Lat.A",
#              "delta.LVEF.MOD.A2c","delta.LVLd.A4c","delta.Max.AV.CO","delta.Max.AV.meanPG","delta.Max.AV.SV","delta.Max.AV.Vmean",
#              "delta.Max.Lat.S","delta.Max.LVEDV.MOD.A2C","delta.Max.MV.Dec.T","delta.Max.Sep.A","delta.Max.Sep.E.E","delta.MV.A.Vel",
#              "delta.MV.Dec.T","delta.PA.maxPG","delta.Sep.S","delta.SupineRest.AV.CO.Dopp","delta.SupineRest.AV.maxPG","delta.SupineRest.AV.Vmax",
#              "delta.SupineRest.AV.Vmean","delta.SupineRest.LVESV.MOD.A4C","delta.SupineRest.MV.Dec.Slope","delta.SupineRest.MV.E.Vel",
#              "delta.SupineRest.Sep.A","delta.deltatime_SAX.MV_SC_TRACE")

# unadjusted group differences in delta variables
c1 <- cardiac[ , grepl( "delta" , names(cardiac))]
c1 <- c1[,!grepl("TRACE1",names(c1))]
c1 <- c1[,!grepl("TRACE2",names(c1))]
c1 <- cbind(cardiac$group,c1)
colnames(c1) = c("group",colnames(c1[,2:ncol(c1)]))

# remove variables with fewer than 3 observations 
c1 = c1[,-c(which(colMeans(is.na(c1))>=0.93))]

# make another dataframe with all of the c1 variables plus  BMI %ile, sex, diabetes duration, baseline A1c
cardiac$gender <- as.factor(cardiac$gender)
c1_adj <- cbind(c1,cardiac[,c("bmi_percentile","gender","diabetes_duration","a1c")])
# need to take out even more variables with reduced number of observations
c1_adj = c1_adj[,-c(which(colMeans(is.na(c1_adj))>=0.9069))]

# make a metformin only df
c1_adj_met <- c1_adj[c1_adj$group=="Metformin",]

t1 <- CreateTableOne(data=c1,vars=colnames(c1[,-1]),strata="group",test = T)
t1 <- print(t1,varLabels=TRUE,showAllLevels=TRUE)
t1 <- t1[,-5]

# unadjusted change within metformin group
p <- NA
for (i in 2:ncol(c1)) {
 temp <- round(t.test(c1[c1$group=="Metformin",i], mu = 0, alternative = "two.sided")$p.value,4)
 p <- c(p,temp)
}
p <- p[-1]
onesamp <- as.data.frame(cbind(colnames(c1[,2:ncol(c1)]),p))
colnames(onesamp) <- c("Variable","p-value")

# need to save the p-values from the group term in the adjusted models
# need to modify so it doesn't just print out
mod_save_temp <- NA
mod_save <- NA
for (i in 2:(ncol(c1_adj)-4)) {
  mod <- lm(data = c1_adj,c1_adj[,i]~group+bmi_percentile+diabetes_duration+a1c)
  try(ptemp <- Anova(mod)[1,4])
  mod_save_temp <- ifelse(ptemp<0.05,noquote(colnames(c1_adj)[i]) ,"")
  mod_save <- noquote(c(mod_save,mod_save_temp))
}
mod_save <- mod_save[!(mod_save %in% c(NA,""))]

# within metformin group adjusted for BMI %ile, sex, diabetes duration, baseline A1c
# these models are acting strangely - the intercept should be the mean change but is quite different from the point estimate in Table 1
# if they really want these models, will need to troublshoot
# for (i in 2:(ncol(c1_adj)-4)) {
#   mod <- lm(data = c1_adj_met,c1_adj_met[,i]~c1_adj_met[,"bmi_percentile"]+c1_adj_met[,"diabetes_duration"] + c1_adj_met[,"a1c"])
#   print(noquote(c("Adjusted model for: ", noquote(colnames(c1_adj)[i]))))
#   print(summary(mod))
# }

# if there are significant differences or changes, does improvement in SI or weight loss mediate (correlate with?) these changes?
# find variables that are significant
# need to combine unadjusted group comparisons, unadjusted within met, and adjusted group comparisons
# NOW DELTA_GIR, DELTA_GIR_LEAN, AND DELTA_BMI ARE INCLUDED IN THE MODELS ABOVE - need to REMOVE THEM
sig <- t1[as.numeric(t1[,4])<0.05,]
sig <- rownames(sig)
sig <- sig[!is.na(sig)]
sig <- noquote(sig)
sig <- sub("\\ .*", "", sig)
sig1 <- onesamp[onesamp$`p-value`<0.05,]
sig1 <- sig1[,1]
sig1 <- noquote(sig1)
final_sig <- unique(c(mod_save,sig,sig1))
final_sig <- final_sig[!(final_sig %in% c("delta_bmi","delta_gir","delta_gir_lean"))]

corrdata <- cardiac[,final_sig]
corrdata <- cbind(corrdata,cardiac[,c("delta_bmi","delta_gir","delta_gir_lean")])


```

# Background

# Methods

# Results

```{r echo=FALSE}
# checking distributions
#for (col in 2:ncol(c1)) {
#    try(hist(c1[,col],main = names(c1[col])))
#}
```

```{r echo=FALSE}
kable(t1,caption = "Table 1.  Differences between metformin and placebo groups in change (visit 2-visit 1) in echo variables.")
```
<br>

```{r echo=FALSE}
kable(onesamp,caption = "Table 2.  P-values for test of change  (visit 2-visit 1) within the metformin group.")
```
<br>

## Models comparing changes in echo variables between the groups, adjusted for baseline BMI percentile, diabetes duration, and A1c

```{r echo=FALSE,comment=''}
# group comparisons adjusted for BMI %ile, sex, diabetes duration, baseline A1c
# last var is delta.peakval_SAX.PM_SC_TRACE
for (i in 2:(ncol(c1_adj)-4)) {
  mod <- lm(data = c1_adj,c1_adj[,i]~group+bmi_percentile+diabetes_duration+a1c)
  print(noquote(c("Adjusted model for: ", noquote(colnames(c1_adj)[i]))))
  print(summary(mod))
}
```
<br>

## Models comparing changes in significant echo variables and changes in GIR

```{r echo=FALSE,comment=''}
# are variables that change significantly associated with change in GIR?
for (i in 1:length(final_sig)) {
  mod_gir <- lm(data = corrdata,corrdata[,i]~delta_gir)
  print(noquote(c("Model for: ", noquote(colnames(corrdata)[i]))))
  print(summary(mod_gir))
}
```
