---
title: "Frontiers clamp paper"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(tableone)
library(dplyr)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Melanie Green"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = ""
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = ""
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r}
# Import
data <- read.csv("./Frontiers clamp methods review paper/Data raw/Data template for paper_MelanieLaura.csv",na.strings = c(".",""," "))
data$Dexa...Lean.mass <- as.numeric(data$Dexa...Lean.mass)
data$Dexa...fat.mass <- as.numeric(data$Dexa...fat.mass)
data$Cholesterol <- as.numeric(data$Cholesterol)
data$Triglycerides <- as.numeric(data$Triglycerides)
data$LDL <- as.numeric(data$LDL)
data$Sex <- as.factor(data$Sex)

# who should be included in analysis? everyone or is there a minimum amount of data?
data <- data[!data$X %in% c("827-042","827-111"),]

# calculate age at diabetes onset - but I don't have DOB?  Can use Age but don't have date of visit?

# check BMI category
data$bmi_cat <- ifelse(is.na(data$BMI..),NA,
                       ifelse(data$BMI..<85,"<85th %ile",
                              ifelse(data$BMI..>=85 & data$BMI..<95,"85th - <95th %ile",">=95th %ile")))
data$bmi_twocat <- ifelse(is.na(data$bmi_cat),NA,
                          ifelse(data$bmi_cat=="<85th %ile","Lean","Overweight/Obese"))

# calculate means by BMI group
means <- data %>% group_by(bmi_twocat) %>% summarise_at(vars("Mean.Glucose.Basal","Basal.Insulin"),mean,na.rm=T)

```

```{r}

```

## Table 1

```{r results='asis'}
# table of demographics in those with at least one pre-CFRD OGTT
demovars <- c("Sex","Age","Race","Ethnicity","Age.diabetes.onset","Diabetes.duration_years","Dexa...Lean.mass",
              "Dexa...fat.mass","Most.recent.HbA1c","Cholesterol","Triglycerides","LDL")
t1 <- CreateTableOne(data=data,vars=demovars)
t1 <-  print(t1,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,test = F)

```

