---
title: "research_scientist_interview_scrna_subset"
author: "Ye Ji Choi"
format: html
editor: visual
---

```{r echo = F}
library(Seurat)
library(dplyr)
```

```{r echo = F}
so <- readRDS("/run/user/778527649/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/scRNA/data_raw/PB_90samples_Harmony_rpca_Fadhl_PhilApproved_091024.RDS")
pb90 <- read.csv("/run/user/778527649/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/scRNA/data_clean/PB90_record_ids_subset_researchscientist.csv")
all_genes <- sort(rownames(so))  # Sort gene names
subset_genes <- all_genes[seq(1, length(all_genes), by = 3)]
seurat_subset <- subset(so, features = subset_genes)
```

```{r echo = F}
so_subset <- subset(seurat_subset, record_id %in% pb90$record_id)

so_meta <- so_subset@meta.data %>%
  mutate(study = case_when(grepl("RH-", record_id) ~ "KEVIN",
                            grepl("RH2-", record_id) ~ "BOB",
                            grepl("IT_", record_id) ~ "STUART",
                            grepl("CRC", record_id) ~ "ALLIGATOR",
                            grepl("PNDA", record_id) ~ "BEAR",
                            grepl("30051", record_id) ~ "TRY"),
         record_id = case_when(study == "KEVIN"~ gsub("RH-", "K-", record_id),
                               study == "BOB"~ gsub("RH2-", "B-", record_id),
                               study == "STUART"~ gsub("IT_", "S-", record_id),
                               study == "ALLIGATOR"~ gsub("CRC-", "A-", record_id),
                               study == "BEAR"~ gsub("PNDA-", "BE-", record_id),
                               study == "TRY"~ gsub("30051", "T-51", record_id)),
         cryostor_id = gsub("S-", "C-3", cryostor_id),
         kit_id = gsub("KL-00", "I0", kit_id)) %>%
  dplyr::select(-orig.ident, -record_id_2, -barcode)

so_subset@meta.data <- data.frame(row.names = colnames(so_subset))
so_subset_meta <- AddMetaData(so_subset, so_meta)
View(so_subset_meta@meta.data)

saveRDS(so_subset_meta, file = "/run/user/778527649/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/scRNA/data_clean/subset/research_scientist_interview_subset/so.RDS")

```


```{r echo =FALSE}
dat <- read.csv("/run/user/778527649/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv")
dict <- read.csv("/run/user/778527649/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Ye Ji Choi/research_scientist_data_dictionary.csv")

dat_subset <- dat %>%
  filter(record_id %in% pb90$record_id) %>%
  mutate(study = case_when(grepl("RH-", record_id) ~ "KEVIN",
                            grepl("RH2-", record_id) ~ "BOB",
                            grepl("IT_", record_id) ~ "STUART",
                            grepl("CRC", record_id) ~ "ALLIGATOR",
                            grepl("PNDA", record_id) ~ "BEAR",
                            grepl("30051", record_id) ~ "TRY"),
         record_id = case_when(study == "KEVIN"~ gsub("RH-", "K-", record_id),
                               study == "BOB"~ gsub("RH2-", "B-", record_id),
                               study == "STUART"~ gsub("IT_", "S-", record_id),
                               study == "ALLIGATOR"~ gsub("CRC-", "A-", record_id),
                               study == "BEAR"~ gsub("PNDA-", "BE-", record_id),
                               study == "TRY"~ gsub("30051", "T-51", record_id)),
         cryostor_id = gsub("S-", "C-3", cryostor_id),
         kit_id = gsub("KL-00", "I0", kit_id)) %>%
  filter(!is.na(age)) %>%
  select(all_of(dict$variable))

write.csv(dat_subset, "/run/user/778527649/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Ye Ji Choi/research_scientist_clinical_dat.csv", row.names = F, na = "")
  
```