---
title: "PANTHER Grant Table"
author: "Tim Vigers"
date: "today"
format:
  html:
    toc: true
    toc-depth: 5
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
execute:
  echo: false
---

```{r include=FALSE}
library(tidyverse)
library(gtsummary)
library(redcapAPI)
# Import
tokens = read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/api_tokens.csv")
rcon <- redcapConnection(url = "https://redcap.ucdenver.edu/api/",
                         token = tokens$Token[tokens$Study == "PANTHER"])
df <- exportRecords(rcon)
# Exclude those who screen failed
df = df %>% 
  filter(participation_status != "Removed (screen failed, withdrawn, dropped out, etc.)"
         |is.na(participation_status))
# Risk groups
df$`Risk Group` = factor(as.character(df$group))
levels(df$`Risk Group`) = c("Low Risk","High Risk", "High Risk")
# Combine tanner stage
df = df %>% unite(`Tanner Stage`,tan_tveq,tan_fgd,na.rm = T)
df$`Tanner Stage`[df$`Tanner Stage`==""]=NA
```

```{r}
#| label: tbl-1
#| tbl-cap: Participant Characteristics
df %>% filter(redcap_event_name=="screening_arm_1") %>%
  select(age_consent,sex,`Tanner Stage`,group,`Risk Group`) %>%
  tbl_summary(type = list(age_consent ~ "continuous"),
              statistic = list(all_continuous() ~ "{mean} ({sd})"))
```



