---
title: "PANTHER descriptives for RPPR"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    embed-resources: true
editor: visual
---

```{r libraries, echo=F, include = F}
library(SomaDataIO)
library(tidyverse)
library(growthcleanr)
library(arsenal)
library(dplyr)
```

```{r load-data, echo = F, include = F}
# Load SOMAScan analytes data
load("/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/Data Harmonization/Combined SomaScan/analytes.Rdata")

# Load dictionary function and file
source("/Users/choiyej/GitHub/YC_CHCO/R Functions/label_harmonized_function.R")
```

```{r prep-data, echo = F, include = F}
# Load clinical data
harm_dat <- read.csv("/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/Data Harmonization/Data Clean/harmonized_dataset.csv", na.strings = "")
exclude <- read.csv("/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/PANTHER/Data_Cleaned/panther_withdrew_ltfu_list.csv")$record_id


exclude_dat <-  harm_dat %>% 
  filter(record_id %in% exclude) %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(mrn)) %>%
  mutate(age_mo = (age * 12),
         sex = case_when(sex == "Male" ~ "male",
                         sex == "Female" ~ "female")) %>%
  arrange(record_id)

bmi_percentile = ext_bmiz(data = subset(exclude_dat,
                                        select = c("record_id", "sex", "age_mo", "weight", "height", "bmi")), 
                          age = "age_mo", 
                          wt = "weight", 
                          ht = "height", 
                          bmi = "bmi", 
                          adjust.integer.age = F) %>% 
  dplyr:: select(record_id, bmip)
exclude_dat <- left_join(exclude_dat, bmi_percentile, by = "record_id")
exclude_dat <- exclude_dat %>%
  mutate(group_risk = case_when(bmip > 95 ~ "High", T ~ group_risk)) %>%
  dplyr::select(record_id, group, group_risk, bmip)
table(exclude_dat$group_risk)


dat <- harm_dat %>% 
  filter(study == "PANTHER" & visit %in% c("baseline", "screening")) %>%
  filter(record_id %nin% exclude) %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(mrn)) %>%
  # filter(participation_status!="Removed"|is.na(participation_status)) %>%
  dplyr::mutate(race_ethnicity_condensed = case_when(race == "White" & 
                                                       ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino White",
                                                     race == "Black or African American" & 
                                                       ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino Black",
                                                     ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
                                                     T ~ "Not Hispanic or Latino Other"),
                tanner_stage_comp = coalesce(tan_fgd, tan_fph, tan_tveq, tan_mgd, tan_mph, breast_tanner, ceiling(testicular_volume)),
                tanner_stage_comp_panther = case_when(tanner_stage_comp > 3 ~ 4, T~ tanner_stage_comp),
                tanner_stage_cat = case_when(tanner_stage_comp <3 ~ "I_II",
                                             tanner_stage_comp >=3 ~ "III_V"),
                tanner_stage_cat_2 = case_when(tanner_stage_comp == 1 ~ "I",
                                               tanner_stage_comp <4 ~ "II_III",
                                               tanner_stage_comp >=4 ~ "IV_V"),
                tanner_stage_cat_3 = case_when(tanner_stage_comp < 2 ~ "I_II",
                                               tanner_stage_comp == 3 ~ "III",
                                               tanner_stage_comp >= 4 ~ "IV_V"),
                tanner_stage_comp_panther_cat = 
                  case_when(tanner_stage_comp_panther == 4 ~ "4 & 5",
                            T ~ as.character(tanner_stage_comp_panther)),
                age_mo = (age * 12),
                sex = case_when(sex == "Male" ~ "male",
                                sex == "Female" ~ "female"),
                combined_tkv = coalesce(total_kidney_volume_ml, total_kidney_volume_ml_manual),
                combined_ht_tkv = coalesce(ht_adj_tkv, ht_adj_tkv_manual)) %>%
  arrange(record_id)

dat$tanner_stage_comp <- as.factor(dat$tanner_stage_comp)

bmi_percentile = ext_bmiz(data = subset(dat,
                                        select = c("record_id", "sex", "age_mo", "weight", "height", "bmi")), 
                          age = "age_mo", 
                          wt = "weight", 
                          ht = "height", 
                          bmi = "bmi", 
                          adjust.integer.age = F) %>% 
  dplyr:: select(record_id, bmip)
dat <- left_join(dat, bmi_percentile, by = "record_id")

dat <- dat %>%
  mutate(group_risk = case_when(bmip > 95 ~ "High", T ~ group_risk))

# Load and modify dictionary file
dict <- read.csv("/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/Data Harmonization/data_dictionary_master.csv") %>%
  dplyr::select(variable_name, label)

dict <- label_harmonized_dict(dat, dict) %>%
  dplyr::mutate(tanner_stage_comp = "Tanner stage",
                tanner_stage_comp_ord = "Tanner stage",
                tanner_stage_cat = "Tanner stage categorized (1/2, 3/4/5)",
                tanner_stage_cat2 = "Tanner stage categorized (1, 2/3, 4/5)",
                mm_airg = "AIRg",
                mm_bcell = "Beta cell function",
                mm_di = "DI",
                mm_ir = "Insulin resistance",
                mm_si = "Insulin sensitivity",
                bmip = "BMI percentile",
                total_kidney_volume_ml_manual = "Total Kidney Volume (mL; manual)",
                ht_adj_tkv_manual = "Height Adjusted Total Kidney Volume (mL/m; manual)",
                combined_tkv = "Collapsed Total Kidney Volume (mL)", 
                combined_ht_tkv = "Collapsed Height Adjusted Total Kidney Volume (mL/m)") %>%
  dplyr::select(-starts_with("seq."))

# Label data
dat <- label_harmonized(dat, dict)
# subset(panther, mm_di > 10000)$mm_di
# subset(panther, mm_si > 100)$mm_si
```

```{r echo = F}
# follow up on year 1 and 2
# Identify MRNs that have both baseline and year_1
mrn_year1 <- harm_dat %>%
  filter(study == "PANTHER") %>%
  filter(record_id %nin% exclude) %>%
  filter(visit == "year_1") %>%
    dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(mrn, visit)) %>%
  pull(mrn)

# follow up on year 2
mrn_year2 <- harm_dat %>%
  filter(study == "PANTHER") %>%
  filter(record_id %nin% exclude) %>%
  filter(visit == "year_2") %>%
    dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(mrn, visit)) %>%
  pull(mrn)

# Apply original processing but only for those with both visits
dat_year1 <- harm_dat %>%
  filter(study == "PANTHER",
         visit =="year_1",
         record_id %nin% exclude,
         mrn %in% mrn_year1) %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(mrn, visit)) %>%
  dplyr::mutate(
    race_ethnicity_condensed = case_when(
      race == "White" & ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino White",
      race == "Black or African American" & ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino Black",
      ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
      TRUE ~ "Not Hispanic or Latino Other"),
    tanner_stage_comp = coalesce(tan_fgd, tan_fph, tan_tveq, tan_mgd, tan_mph, breast_tanner, ceiling(testicular_volume)),
    tanner_stage_comp_panther = case_when(tanner_stage_comp > 3 ~ 4, TRUE ~ tanner_stage_comp),
    tanner_stage_cat = case_when(tanner_stage_comp < 3 ~ "I_II", tanner_stage_comp >= 3 ~ "III_V"),
    tanner_stage_cat_2 = case_when(tanner_stage_comp == 1 ~ "I", tanner_stage_comp < 4 ~ "II_III", tanner_stage_comp >= 4 ~ "IV_V"),
    tanner_stage_cat_3 = case_when(tanner_stage_comp < 2 ~ "I_II", tanner_stage_comp == 3 ~ "III", tanner_stage_comp >= 4 ~ "IV_V"),
    tanner_stage_comp_panther_cat = case_when(tanner_stage_comp_panther == 4 ~ "4 & 5", TRUE ~ as.character(tanner_stage_comp_panther)),
    age_mo = age * 12,
    sex = case_when(sex == "Male" ~ "male", sex == "Female" ~ "female"),
    combined_tkv = coalesce(total_kidney_volume_ml, total_kidney_volume_ml_manual),
    combined_ht_tkv = coalesce(ht_adj_tkv, ht_adj_tkv_manual)) %>%
  arrange(record_id)

dat_year1$tanner_stage_comp <- as.factor(dat_year1$tanner_stage_comp)

bmi_percentile = ext_bmiz(data = subset(dat_year1,
                                        select = c("record_id", "sex", "age_mo", "weight", "height", "bmi")),
                          age = "age_mo",
                          wt = "weight",
                          ht = "height",
                          bmi = "bmi",
                          adjust.integer.age = F) %>%
  dplyr::select(record_id, bmip)
dat_year1 <- left_join(dat_year1, bmi_percentile, by = "record_id")

dat_year1 <- dat_year1 %>%
  mutate(group_risk = case_when(bmip > 95 ~ "High", T ~ group_risk))

dat_year2 <- harm_dat %>%
  filter(study == "PANTHER",
         visit =="year_2",
         record_id %nin% exclude,
         mrn %in% mrn_year2) %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(mrn, visit)) %>%
  dplyr::mutate(
    race_ethnicity_condensed = case_when(
      race == "White" & ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino White",
      race == "Black or African American" & ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino Black",
      ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
      TRUE ~ "Not Hispanic or Latino Other"),
    tanner_stage_comp = coalesce(tan_fgd, tan_fph, tan_tveq, tan_mgd, tan_mph, breast_tanner, ceiling(testicular_volume)),
    tanner_stage_comp_panther = case_when(tanner_stage_comp > 3 ~ 4, TRUE ~ tanner_stage_comp),
    tanner_stage_cat = case_when(tanner_stage_comp < 3 ~ "I_II", tanner_stage_comp >= 3 ~ "III_V"),
    tanner_stage_cat_2 = case_when(tanner_stage_comp == 1 ~ "I", tanner_stage_comp < 4 ~ "II_III", tanner_stage_comp >= 4 ~ "IV_V"),
    tanner_stage_cat_3 = case_when(tanner_stage_comp < 2 ~ "I_II", tanner_stage_comp == 3 ~ "III", tanner_stage_comp >= 4 ~ "IV_V"),
    tanner_stage_comp_panther_cat = case_when(tanner_stage_comp_panther == 4 ~ "4 & 5", TRUE ~ as.character(tanner_stage_comp_panther)),
    age_mo = age * 12,
    sex = case_when(sex == "Male" ~ "male", sex == "Female" ~ "female"),
    combined_tkv = coalesce(total_kidney_volume_ml, total_kidney_volume_ml_manual),
    combined_ht_tkv = coalesce(ht_adj_tkv, ht_adj_tkv_manual)) %>%
  arrange(record_id)

dat_year2$tanner_stage_comp <- as.factor(dat_year2$tanner_stage_comp)

bmi_percentile = ext_bmiz(data = subset(dat_year2,
                                        select = c("record_id", "sex", "age_mo", "weight", "height", "bmi")),
                          age = "age_mo",
                          wt = "weight",
                          ht = "height",
                          bmi = "bmi",
                          adjust.integer.age = F) %>%
  dplyr::select(record_id, bmip)
dat_year2 <- left_join(dat_year2, bmi_percentile, by = "record_id")

dat_year2 <- dat_year2 %>%
  mutate(group_risk = case_when(bmip > 95 ~ "High", T ~ group_risk))
```

# Descriptive table

## PANTHER only

### By risk

```{r desc-risk, results = 'asis', echo = F}
# Descriptive tables
# baseline
# ## By risk
summary(tableby(group_risk ~ kwt(mm_di, "Nmiss", "medianq1q3", "range"), data = subset(dat, mm_di < 10000), total = T, test = F))
summary(tableby(group_risk ~ kwt(mm_ir, "Nmiss", "medianq1q3", "range"), data = subset(dat, mm_si < 100), total = T, test = F))

summary(tableby(group_risk ~ age + sex + tanner_stage_comp + group + weight + height + bmi + bmip + hba1c + gfr_raw_plasma + gfr_bsa_plasma + erpf_raw_plasma + erpf_bsa_plasma + total_kidney_volume_ml + ht_adj_tkv + mm_airg + mm_bcell + mm_di + mm_ir + mm_si, data = dat, total = T, test = F))

# # year 1
summary(tableby(group_risk ~ age + sex + tanner_stage_comp + group + weight + height + bmi + bmip + hba1c + gfr_raw_plasma + gfr_bsa_plasma + erpf_raw_plasma + erpf_bsa_plasma + total_kidney_volume_ml + ht_adj_tkv + mm_airg + mm_bcell + mm_di + mm_ir + mm_si, data = subset(dat_year1, visit == "year_1"), total = T, test = F))

# # year 2
summary(tableby(group_risk ~ age + sex + tanner_stage_comp + group + weight + height + bmi + bmip + hba1c + gfr_raw_plasma + gfr_bsa_plasma + erpf_raw_plasma + erpf_bsa_plasma + total_kidney_volume_ml + ht_adj_tkv + mm_airg + mm_bcell + mm_di + mm_ir + mm_si, data = subset(dat_year2, visit == "year_2"), total = T, test = F))


```

### By tanner stage

```{r desc-tanner-stage, results = 'asis', echo = F}
# By tanner stage
summary(tableby(tanner_stage_comp ~ age + sex + group + group_risk + weight + height + bmi + bmip + hba1c + gfr_raw_plasma + gfr_bsa_plasma + erpf_raw_plasma + erpf_bsa_plasma + total_kidney_volume_ml + ht_adj_tkv + mm_airg + mm_bcell + mm_di + mm_ir + mm_si, data = dat, total = T, test = F))
```

### By tanner stage (4 & 5 combined)

```{r desc-tanner-stage-45, results = 'asis', echo = F}
# By tanner stage
summary(tableby(tanner_stage_comp_panther_cat ~ age + sex + group + group_risk + weight + height + bmi + bmip + hba1c + gfr_raw_plasma + gfr_bsa_plasma + erpf_raw_plasma + erpf_bsa_plasma + total_kidney_volume_ml + ht_adj_tkv + mm_airg + mm_bcell + mm_di + mm_ir + mm_si, data = dat, total = T, test = F))
```
