---
title: "Pima Data Check"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#knitr::opts_knit$set(root.dir = "Z:/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects")
knitr::opts_knit$set(root.dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Pima/Master data/Raw data/")
library(arsenal)
library(skimr)
library(knitr)
library(tidyverse)
```

```{r include=FALSE}
# Import data
source("/Users/timvigers/GitHub/CHCO-Code/Petter Bjornstad/Pima/master_data/tim_merge/vital_status.R")
source("/Users/timvigers/GitHub/CHCO-Code/Petter Bjornstad/Pima/master_data/tim_merge/losartan.R")
source("/Users/timvigers/GitHub/CHCO-Code/Petter Bjornstad/Pima/master_data/tim_merge/group4.R")
source("/Users/timvigers/GitHub/CHCO-Code/Petter Bjornstad/Pima/master_data/tim_merge/ficoll.R")
source("/Users/timvigers/GitHub/CHCO-Code/Petter Bjornstad/Pima/master_data/tim_merge/ddn.R")
data = list(vital_status,losartan,group4,ficoll,ddn)
names(data) = c("Vital Status","Losartan","Group 4","Ficoll","DDN")
```

```{r}
# Plotting function
plot_var = function(var){
  invisible(lapply(names(data),function(n){
    d = data[[n]]
    if (var %in% colnames(d)){
      d = d[,c("record_id","redcap_event_name.factor",var)]
      d = d[complete.cases(d),]
      p = ggplot(d,aes_string(x="redcap_event_name.factor",y=var,color="factor(record_id)")) +
        geom_line(aes(group=factor(record_id)),alpha = 0.5) +
        theme_bw() +
        theme(legend.position = "none",axis.text.x=element_blank()) +
        xlab("REDCap Event") + ylab("GFR") + ggtitle(n)
      print(p)
    } else {
      return(NULL) 
    }
  }))
}
```

# GFR plots

```{r warning=FALSE,message=FALSE}
plot_var("gfr")
```

# RPF



# PIE



# PIGC



# SBP



# DBP



# BMI 



# HbA1c