---
title: "Pima Master Data"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
library(DT)
library(arsenal)
library(skimr)
library(knitr)
library(tidyverse)
library(haven)
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
home_dir = ifelse(.Platform$OS.type != "unix",
                  "Z:/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Pima/Master data/Raw data",
                  "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Pima/Master data/Raw data")
knitr::opts_knit$set(root.dir = home_dir)
```

```{r}
# Import datasets
vital_status = read.csv('Vital Status.csv',na.strings = "")
g4 = read.csv('Group 4.csv',na.strings = "")
ficoll = read.csv('Ficoll.csv',na.strings = "")
ddn = read.csv('DDN.csv',na.strings = "")
losartan = read.csv('Losartan Clinical Trial.csv',na.strings = "")
drds = read_sas("drds05may2021.sas7bdat")
# List of required variable names
important_vars = 
  c("nih","sacaton","pimc","date","testint","protocol","stratum","dob",
    "date_dx","dod","underly","age","dmdur","sex","ht_cm","wt_kg",
    "sbp","dbp","pulse","sbp_6","dbp_6","pulse_6","medsnow","recent_illness","op",
    "op_spec","hosp_wo_surg","hosp_wo_surg_spec","hosp_w_surg","hosp_w_surg_spec",
    "med_probs","cad","cancer","cancer_spec","cvd","pvd","htn","seizures","gu_dz",
    "gu_dz_spec","lung_dz","surgery","surgery_spec","other_dz","other_dz_spec",
    "lungs","lungs_spec","heart","heart_spec","skin","skin_spec","edema",
    "edema_spec","smac_glu","smac_bun","smac_scr","smac_na","smac_k","smac_cl",
    "smac_ca","smac_tp","smac_alb","smac_chol","smac_tri","smac_hdl","smac_ldl",
    "smac_tbil","smac_alk","scr","hba1a","hba1b","hba1c","hba1o",
    "hbf","p0albumin","p0igg","p3albumin","p3igg","ucr","ualb","acr","u0igg",
    "u3albumin","u3igg","u3use_gfr","u3flow_gfr","u3gfr",
    "gfr","pah","p0pia","p3pia","wbc","rbc","hgb","hct","mcv","mch","mchc","plts","neut","lymph",
    "mono","eos","baso","stop_dt",
    "med_metformin","med_ras","med_htn","med_arb","med_orl","med_lipid","med_ace",
    "med_ins","med_ald","med_statin","med_nsai")
constant_vars = c("sacaton","pimc","dob","date_dx","sex","ht_cm")
# Med function
med_vars = tolower(paste0("F4DRUGCODE",1:20))
med_fun = function(df,bool){
  w = med_vars[which(med_vars %in% colnames(df))]
  if (length(w) > 0){
    d = df[,w]
    met = apply(d,1,function(r){
      if(all(is.na(r))){
        NA
      } else {
          ifelse(any(eval(parse(text = bool)),na.rm = T),1,0)
        }
    })
    return(met)
  } else {
    return(rep(NA,nrow(df)))
  }
}
```

```{r vital status}
# Collapse rows - get first non-NA element in each column by record ID
vital_status = vital_status %>% group_by('record_id') %>% 
  mutate(
    esrd_start_date = first(na.omit(esrd_start_date)),
    dod = first(na.omit(dod)),
    codunerlying = first(na.omit(codunerlying)),
    protocol = "Vital Status") %>% 
  fill(coddrunerlying,.direction = "updown") %>% ungroup() %>% 
  select(record_id,esrd_start_date,dod,coddrunerlying) %>% 
  rename(underly = coddrunerlying) %>% unique()
```

```{r g4}
# Sex as factor
g4$gender = factor(g4$gender,labels = c("Male","Non-Fertile Female","Fertile Female"))
# Unite date columns
date_cols = colnames(g4)[grep("f\\d{,2}visitdate$",colnames(g4))]
g4 = g4 %>% unite(date,all_of(date_cols),na.rm = T,remove = F)
g4$date = lubridate::ymd(sapply(strsplit(g4$date,"_"),function(x){unique(x)[1]}))
# Unite test interval columns
int_cols = colnames(g4)[grep("*testintrvl$|*testintvrl$|*testintvl$",colnames(g4))]
g4 = g4 %>% unite(testint,all_of(int_cols),na.rm = T,remove = F)
g4$testint = as.numeric(g4$testint)
# Protocol
g4$protocol = "Group 4"
# Unite heart rate columns
heart_cols = colnames(g4)[grep("heartrate$",colnames(g4))]
g4 = g4 %>% unite(pulse,all_of(heart_cols),na.rm = T,remove = F)
g4$pulse = as.numeric(sapply(strsplit(g4$pulse,"_"),unique))
g4$pulse_6 = g4$f6heartrate
# Calculate average BP (first and second readings)
## Systolic
g4$f2sys = rowMeans(g4[,c("f2frstmsrsys","f2scndmsrsys")],na.rm = T)
g4$f3sys = rowMeans(g4[,c("f3frstmsrsys","f3scndmsrsys")],na.rm = T)
g4$f4sys = rowMeans(g4[,c("f4frstmsrsys","f4scndmsrsys")],na.rm = T)
g4$f6sys = rowMeans(g4[,c("f6frstmsrsty","f6scndmsrsys")],na.rm = T)
g4[,c("f2sys","f3sys","f4sys","f6sys")] = 
  lapply(g4[,c("f2sys","f3sys","f4sys","f6sys")], function(c){
    c[which(is.nan(c))] = NA
    c
  })
g4 = g4 %>% unite(sbp,f2sys,f3sys,f4sys,f6sys,na.rm = T,remove = F)
g4$sbp = as.numeric(sapply(strsplit(g4$sbp,"_"),unique))
g4$sbp_6 = as.numeric(g4$f6sys)
## Diastolic
g4$f2dia = rowMeans(g4[,c("f2frstmsrdia","f2scndmsrdia")],na.rm = T)
g4$f3dia = rowMeans(g4[,c("f3frstmsrdia","f3scndmsrdia")],na.rm = T)
g4$f4dia = rowMeans(g4[,c("f4frstmsrdia","f4scndmsrdia")],na.rm = T)
g4$f6dia = rowMeans(g4[,c("f6frstmsrdia","f6scndmsrdia")],na.rm = T)
g4[,c("f2dia","f3dia","f4dia","f6dia")] = 
  lapply(g4[,c("f2dia","f3dia","f4dia","f6dia")], function(c){
    c[which(is.nan(c))] = NA
    c
  })
g4 = g4 %>% unite(dbp,f2dia,f3dia,f4dia,f6dia,na.rm = T,remove = F)
g4$dbp = as.numeric(sapply(strsplit(g4$dbp,"_"),function(x){unique(x)[1]}))
g4$dbp_6 = as.numeric(g4$f6dia)
# BUN
g4 = g4 %>% unite(smac_bun,f8bun,f16bun,na.rm = T,remove = F)
g4$smac_bun = as.numeric(g4$smac_bun)
# Creatinine
g4 = g4 %>% unite(smac_scr,scr,f10serumcreat,na.rm = T,remove = F)
g4$smac_scr = as.numeric(g4$smac_scr)
# Meds
# Metformin
g4$med_metformin = med_fun(g4,"r == 70292")
# RAS
g4$med_ras = med_fun(g4,"(20320 <= r & r < 20340) | r %in% c(20371,20372,20374)")
# HTN
g4$med_htn = med_fun(g4,"(20080 <= r & r <= 20380) | (20420 <= r & r <= 20560)")
# ARB
g4$med_arb = med_fun(g4,"(20333 <= r & r <= 20340)")
# ORL
g4$med_orl = med_fun(g4,"(70231 <= r & r <= 70300)")
# Lipid
g4$med_lipid = med_fun(g4,"(20570 <= r & r < 20640)")
# ACE
g4$med_ace = med_fun(g4,"(20320 <= r & r <= 20333) | r==20371 | r==20372")
# Ins
g4$med_ins = med_fun(g4,"r==70230")
# ALD
g4$med_ald = med_fun(g4,"r==20530 | r==20540")
# Statin
g4$med_statin = med_fun(g4,"r %in% c(20631,20632,20634,20635,20638,20639)")
# NSAID
g4$med_nsai = med_fun(g4,"(90050 <= r & r <= 90130) | r==90150")
```

```{r ficoll}
# Sex as factor
ficoll$gender = factor(ficoll$gender,labels = c("Male","Non-Fertile Female","Fertile Female"))
# Unite date columns
ficoll = ficoll %>% rename(date = f8visitdate)
ficoll$date = lubridate::ymd(ficoll$date)
# Unite test interval columns
int_cols = colnames(ficoll)[grep("*testintrvl$|*testintvrl$|*testintvl$",colnames(ficoll))]
ficoll = ficoll %>% unite(testint,all_of(int_cols),na.rm = T,remove = F)
ficoll$testint = as.numeric(ficoll$testint)
# Protocol
ficoll$protocol = "Ficoll"
# Unite heart rate columns
heart_cols = colnames(ficoll)[grep("heartrate$",colnames(ficoll))]
ficoll = ficoll %>% unite(pulse,all_of(heart_cols),na.rm = T,remove = F)
ficoll$pulse = as.numeric(sapply(strsplit(ficoll$pulse,"_"),unique))
ficoll$pulse_6 = ficoll$f6heartrate
# Calculate average BP (first and second readings)
## Systolic
ficoll$f4sys = rowMeans(ficoll[,c("f4frstmsrsys","f4scndmsrsys")],na.rm = T)
ficoll$f6sys = rowMeans(ficoll[,c("f6frstmsrsty","f6scndmsrsys")],na.rm = T)
ficoll[,c("f4sys","f6sys")] = 
  lapply(ficoll[,c("f4sys","f6sys")], function(c){
    c[which(is.nan(c))] = NA
    c
  })
ficoll = ficoll %>% unite(sbp,f4sys,f6sys,na.rm = T,remove = F)
ficoll$sbp = as.numeric(sapply(strsplit(ficoll$sbp,"_"),unique))
ficoll$sbp_6 = as.numeric(ficoll$f6sys)
## Diastolic
ficoll$f4dia = rowMeans(ficoll[,c("f4frstmsrdia","f4scndmsrdia")],na.rm = T)
ficoll$f6dia = rowMeans(ficoll[,c("f6frstmsrdia","f6scndmsrdia")],na.rm = T)
ficoll[,c("f4dia","f6dia")] = 
  lapply(ficoll[,c("f4dia","f6dia")], function(c){
    c[which(is.nan(c))] = NA
    c
  })
ficoll = ficoll %>% unite(dbp,f4dia,f6dia,na.rm = T,remove = F)
ficoll$dbp = as.numeric(sapply(strsplit(ficoll$dbp,"_"),function(x){unique(x)[1]}))
ficoll$dbp_6 = as.numeric(ficoll$f6dia)
# BUN
ficoll = ficoll %>% unite(smac_bun,f8bun,f16bun,na.rm = T,remove = F)
ficoll$smac_bun = as.numeric(ficoll$smac_bun)
# Creatinine
ficoll = ficoll %>% rename(smac_scr = scr)
# Meds
# Metformin
ficoll$med_metformin = med_fun(ficoll,"r == 70292")
# RAS
ficoll$med_ras = med_fun(ficoll,"(20320 <= r & r < 20340) | r %in% c(20371,20372,20374)")
# HTN
ficoll$med_htn = med_fun(ficoll,"(20080 <= r & r <= 20380) | (20420 <= r & r <= 20560)")
# ARB
ficoll$med_arb = med_fun(ficoll,"(20333 <= r & r <= 20340)")
# ORL
ficoll$med_orl = med_fun(ficoll,"(70231 <= r & r <= 70300)")
# Lipid
ficoll$med_lipid = med_fun(ficoll,"(20570 <= r & r < 20640)")
# ACE
ficoll$med_ace = med_fun(ficoll,"(20320 <= r & r <= 20333) | r==20371 | r==20372")
# Ins
ficoll$med_ins = med_fun(ficoll,"r==70230")
# ALD
ficoll$med_ald = med_fun(ficoll,"r==20530 | r==20540")
# Statin
ficoll$med_statin = med_fun(ficoll,"r %in% c(20631,20632,20634,20635,20638,20639)")
# NSAID
ficoll$med_nsai = med_fun(ficoll,"(90050 <= r & r <= 90130) | r==90150")
```

```{r ddn}
# Sex as factor
ddn$gender = factor(ddn$gender,labels = c("Male","Non-Fertile Female","Fertile Female"))
# Unite date columns
ddn = ddn %>% rename(date = f8visitdate)
ddn$date = lubridate::ymd(ddn$date)
# Unite test interval columns
ddn = ddn %>% rename(testint = clrnctestintvrl)
# Protocol
ddn$protocol = "DDN"
# Unite heart rate columns
heart_cols = colnames(ddn)[grep("heartrate$",colnames(ddn))]
ddn = ddn %>% unite(pulse,all_of(heart_cols),na.rm = T,remove = F)
ddn$pulse = as.numeric(sapply(strsplit(ddn$pulse,"_"),unique))
ddn$pulse_6 = ddn$f6heartrate
# Calculate average BP (first and second readings)
## Systolic
ddn$f4sys = rowMeans(ddn[,c("f4frstmsrsys","f4scndmsrsys")],na.rm = T)
ddn$f6sys = rowMeans(ddn[,c("f6frstmsrsty","f6scndmsrsys")],na.rm = T)
ddn[,c("f4sys","f6sys")] = 
  lapply(ddn[,c("f4sys","f6sys")], function(c){
    c[which(is.nan(c))] = NA
    c
  })
ddn = ddn %>% unite(sbp,f4sys,f6sys,na.rm = T,remove = F)
ddn$sbp = as.numeric(sapply(strsplit(ddn$sbp,"_"),function(x){
  if (length(x)>0){x[1]}else{NA}
}))
ddn$sbp_6 = as.numeric(ddn$f6sys)
## Diastolic
ddn$f4dia = rowMeans(ddn[,c("f4frstmsrdia","f4scndmsrdia")],na.rm = T)
ddn$f6dia = rowMeans(ddn[,c("f6frstmsrdia","f6scndmsrdia")],na.rm = T)
ddn[,c("f4dia","f6dia")] = 
  lapply(ddn[,c("f4dia","f6dia")], function(c){
    c[which(is.nan(c))] = NA
    c
  })
ddn = ddn %>% unite(dbp,f4dia,f6dia,na.rm = T,remove = F)
ddn$dbp = as.numeric(sapply(strsplit(ddn$dbp,"_"),function(x){unique(x)[1]}))
ddn$dbp_6 = as.numeric(ddn$f6dia)
# BUN
ddn = ddn %>% unite(smac_bun,f8bun,f16bun,na.rm = T,remove = F)
ddn$smac_bun = as.numeric(ddn$smac_bun)
# Meds
# Metformin
ddn$med_metformin = med_fun(ddn,"r == 70292")
# RAS
ddn$med_ras = med_fun(ddn,"(20320 <= r & r < 20340) | r %in% c(20371,20372,20374)")
# HTN
ddn$med_htn = med_fun(ddn,"(20080 <= r & r <= 20380) | (20420 <= r & r <= 20560)")
# ARB
ddn$med_arb = med_fun(ddn,"(20333 <= r & r <= 20340)")
# ORL
ddn$med_orl = med_fun(ddn,"(70231 <= r & r <= 70300)")
# Lipid
ddn$med_lipid = med_fun(ddn,"(20570 <= r & r < 20640)")
# ACE
ddn$med_ace = med_fun(ddn,"(20320 <= r & r <= 20333) | r==20371 | r==20372")
# Ins
ddn$med_ins = med_fun(ddn,"r==70230")
# ALD
ddn$med_ald = med_fun(ddn,"r==20530 | r==20540")
# Statin
ddn$med_statin = med_fun(ddn,"r %in% c(20631,20632,20634,20635,20638,20639)")
# NSAID
ddn$med_nsai = med_fun(ddn,"(90050 <= r & r <= 90130) | r==90150")
```

```{r losartan}
# Sex as factor
losartan$gender = factor(losartan$gender,labels = c("Male","Non-Fertile Female","Fertile Female"))
# Unite date columns
date_cols = colnames(losartan)[grep("f\\d{,2}visitdate$",colnames(losartan))]
losartan = losartan %>% unite(date,all_of(date_cols),na.rm = T,remove = F)
losartan$date = lubridate::ymd(sapply(strsplit(losartan$date,"_"),function(x){unique(x)[1]}))
# Protocol
losartan$protocol = "Losartan"
# Unite test interval columns
int_cols = colnames(losartan)[grep("*testintrvl$|*testintvrl$|*testintvl$|*tstintrvl$",
                                   colnames(losartan))]
losartan = losartan %>% unite(testint,all_of(int_cols),na.rm = T,remove = F)
losartan$testint = as.numeric(losartan$testint)
# Unite heart rate columns
heart_cols = colnames(losartan)[grep("heartrate$",colnames(losartan))]
losartan = losartan %>% unite(pulse,all_of(heart_cols),na.rm = T,remove = F)
losartan$pulse = as.numeric(sapply(strsplit(losartan$pulse,"_"),unique))
losartan$pulse_6 = losartan$f6heartrate
# Calculate average BP (first and second readings)
## Systolic
losartan$f2sys = rowMeans(losartan[,c("f2frstmsrsys","f2scndmsrsys")],na.rm = T)
losartan$f3sys = rowMeans(losartan[,c("f3frstmsrsys","f3scndmsrsys")],na.rm = T)
losartan$f4sys = rowMeans(losartan[,c("f4frstmsrsys","f4scndmsrsys")],na.rm = T)
losartan$f6sys = rowMeans(losartan[,c("f6frstmsrsty","f6scndmsrsys")],na.rm = T)
losartan[,c("f2sys","f3sys","f4sys","f6sys")] = 
  lapply(losartan[,c("f2sys","f3sys","f4sys","f6sys")], function(c){
    c[which(is.nan(c))] = NA
    c
  })
losartan = losartan %>% unite(sbp,f2sys,f3sys,f4sys,f6sys,na.rm = T,remove = F)
losartan$sbp = as.numeric(sapply(strsplit(losartan$sbp,"_"),unique))
losartan$sbp_6 = as.numeric(losartan$f6sys)
## Diastolic
losartan$f2dia = rowMeans(losartan[,c("f2frstmsrdia","f2scndmsrdia")],na.rm = T)
losartan$f3dia = rowMeans(losartan[,c("f3frstmsrdia","f3scndmsrdia")],na.rm = T)
losartan$f4dia = rowMeans(losartan[,c("f4frstmsrdia","f4scndmsrdia")],na.rm = T)
losartan$f6dia = rowMeans(losartan[,c("f6frstmsrdia","f6scndmsrdia")],na.rm = T)
losartan[,c("f2dia","f3dia","f4dia","f6dia")] = 
  lapply(losartan[,c("f2dia","f3dia","f4dia","f6dia")], function(c){
    c[which(is.nan(c))] = NA
    c
  })
losartan = losartan %>% unite(dbp,f2dia,f3dia,f4dia,f6dia,na.rm = T,remove = F)
losartan$dbp = as.numeric(sapply(strsplit(losartan$dbp,"_"),function(x){unique(x)[1]}))
losartan$dbp_6 = as.numeric(losartan$f6dia)
# BUN
losartan = losartan %>% unite(smac_bun,f8bun,f16bun,na.rm = T,remove = F)
losartan$smac_bun = as.numeric(losartan$smac_bun)
# Creatinine
losartan = losartan %>% unite(smac_scr,scr,f10serumcreat,na.rm = T,remove = F)
losartan$smac_scr = as.numeric(sapply(strsplit(losartan$smac_scr,"_"),function(x){unique(x)[1]}))
# Meds
# Metformin
losartan$med_metformin = med_fun(losartan,"r == 70292")
# RAS
losartan$med_ras = med_fun(losartan,"(20320 <= r & r < 20340) | r %in% c(20371,20372,20374)")
# HTN
losartan$med_htn = med_fun(losartan,"(20080 <= r & r <= 20380) | (20420 <= r & r <= 20560)")
# ARB
losartan$med_arb = med_fun(losartan,"(20333 <= r & r <= 20340)")
# ORL
losartan$med_orl = med_fun(losartan,"(70231 <= r & r <= 70300)")
# Lipid
losartan$med_lipid = med_fun(losartan,"(20570 <= r & r < 20640)")
# ACE
losartan$med_ace = med_fun(losartan,"(20320 <= r & r <= 20333) | r==20371 | r==20372")
# Ins
losartan$med_ins = med_fun(losartan,"r==70230")
# ALD
losartan$med_ald = med_fun(losartan,"r==20530 | r==20540")
# Statin
losartan$med_statin = med_fun(losartan,"r %in% c(20631,20632,20634,20635,20638,20639)")
# NSAID
losartan$med_nsai = med_fun(losartan,"(90050 <= r & r <= 90130) | r==90150")
# Cpnvert to characters
losartan$f10spturalbu = as.character(losartan$f10spturalbu)
```

```{r drds}
# Column names to lower case and fix HbA1c
colnames(drds) = tolower(colnames(drds))
drds_vars = setdiff(colnames(drds),important_vars)
drds_vars = 
  drds_vars[-which(drds_vars %in% c("bmi","fc_alb","fc_igg","smoke","alcohol"))]
# Format columns for merge
drds$date = lubridate::ymd(drds$date)
drds$dob = as.character(drds$dob)
drds$nih = as.integer(drds$nih)
drds$date_dx = lubridate::ymd(as.character(drds$date_dx))
drds$sex = factor(drds$sex,levels = c(0,1),labels = c("Male","Female"))
```

```{r merge,include=FALSE}
# Merge all datasets together
final = full_join(g4,vital_status,by = "record_id")
final = full_join(final,ficoll)
final = full_join(final,ddn)
final = full_join(final,losartan)
# Calculated variables
final = final %>% 
  rename(
    nih = record_id,sacaton = sacaton_no,pimc = phx_number,
    date_dx = dtdiabonset,sex = gender,ht_cm = height,
    wt_kg = f6weight,bsa = f6bsa,medsnow = f4medsnow,
    recent_illness = f5rcntillns,op = f5outpat,op_spec = f5outpatspec,
    hosp_wo_surg = f5hospwosrg,hosp_wo_surg_spec = f5hospwoexp,
    hosp_w_surg = f5hospwsrg,hosp_w_surg_spec = f5hospwexp,
    med_probs = f5medprbsdoc,cad = f5crnryartds,cancer = f5cancer,
    cancer_spec = f5cancerexp,cvd = f5crbrlvasds,pvd = f5peripvasds,
    htn = f5hypertensn,seizures = f5seizures,gu_dz = f5gnitrnryds,
    gu_dz_spec = f5gnitrnyexp,lung_dz = f5lungdsz,surgery = f5majsurg,
    surgery_spec = f5majsurgexp,other_dz = f5othrmeddia,
    other_dz_spec = f5othrmedexp,lungs = f5lungs,lungs_spec = f5lungsexp,
    heart = f5heart,heart_spec = f5heartexp,skin = f5skin,
    skin_spec = f5skinexp,edema = f5edema,edema_spec = f5edemaexp,
    smac_glu = f4srmglu,smac_na = f8sodium,smac_k = f4srmpotasm,
    smac_cl = f8chloride,smac_ca = f8calcium,smac_tp = f8totlprotn,
    smac_alb = f8albumin,smac_chol = f8cholestero,smac_tri = f8triglyceri,
    smac_hdl = f8hdl,smac_ldl = f8ldl,smac_tbil = f8totlbilrbn,
    smac_alk = f8alkp04,acr = f3_acratio,bsa = f6bsa,pah = pahclrnc,
    rpf = s_rpf,p0pia = p0oncoticprsr,p3pia = p3oncoticprsr,pie = s_pie,
    pigc = s_pigc,wbc = f9wbc,rbc = f9rbc,hgb = f9hemoglob,
    hct = f9hematocrit,mcv = f9mcv,mch = f9mch,mchc = f9mchc,
    plts = f9platelets,neut = f9neutrophil,lymph = f9lymphocyte,
    mono = f9monocytes,eos = f9eosinophil,baso = f9basophils,
    stop_dt = f13stoppntdt,gfrb = s_gfrb,pahb = s_pahb,rpfb = s_rpfb
  ) %>% filter(!is.na(date)) %>% arrange(nih, date)
final$date_dx = lubridate::ymd(final$date_dx)
levels(final$sex) = c("Male","Female","Female")
# Add DRDS
important_vars = c(important_vars,drds_vars)
final = full_join(final,drds) %>% select(all_of(important_vars))
# Conversions
final$date = lubridate::ymd(final$date)
# Enzymatic to Jaffe: used the Jaffe colorimetric method for measuring creatinine concentration until August 1, 2011 
final$smac_scr_jaffe = ifelse(final$date < lubridate::ymd("2011-08-01"),
                              final$smac_scr,exp((log(final$smac_scr)-0.1703)/1.0328))
final$smac_scr_enz = ifelse(final$date >= lubridate::ymd("2011-08-01"),
                              final$smac_scr,exp(0.1703 + 1.0328*log(final$smac_scr)))
# HbA1c to IFCC traceable HbA1c: IF HBA1C AND DATE NE . AND DATE LT MDY(08,10,2010) THEN IFCC_HBA1C=(0.9255*HBA1C)+0.1336;
final$hba1c_derived = ifelse(final$date >= lubridate::ymd("2010-08-10"),
                              final$hba1c,(0.9255*final$hba1c)+0.1336)
# Hemodynamic calculations 
final$bsa = 0.007184 * (final$ht_cm^0.725) * (final$wt_kg^0.425)
final$gfrb = (final$gfr * 1.73)/final$bsa
final$pahb = (final$pah * 1.73)/final$bsa
final$extract = cut(final$gfrb,c(-Inf,30,80,Inf),labels = c("0.6","0.7","0.85"),right = F)
final$extract = as.numeric(as.character(final$extract))
final$rpf = final$pah/final$extract
final$rpfb = (final$rpf * 1.73)/final$bsa
final$ff = round(final$gfr/final$rpf,2)
final$pie = final$p0pia/(1-final$ff)
final$pigc = (final$p0pia + final$pie)/2
# Fill and calculate age etc.
final = final %>% group_by(nih) %>% 
  fill(all_of(constant_vars),.direction = "downup") %>% ungroup() %>%
  mutate(
    age = as.numeric(difftime(date,dob,units = "days")/365.25),
    dmdur = as.numeric(difftime(date,date_dx,units = "days")/365.25))
# Round
final <- data.frame(lapply(final,function(x) if(is.numeric(x)) round(x, 2) else x))
# Write
write.csv(final,file = paste0("./Merged/merge_attempt_",Sys.Date(),".csv"),na = "")
```

# Final Dataset Skim

```{r}
skimr::skim(final)
```

```{r}
missing = c("med_nonras","smac_ast","fpg","fc_alb","fc_igg","ff","extract",
            "ua_glu","ua_bil","ua_ket","ua_sg","ua_ob","ua_ph",
            "ua_prot","ua_casts","ua_rbccasts","ua_wbccasts","ua_hyalinecasts",
            "ua_granularcasts","ua_othercasts","ua_otherexp","ua_wbc","ua_rbc","ua_epi",
            "ua_bact","stop_point","stop_esrd","stop_ndkd","stop_impdbladr",
            "stop_chf","stop_ascites","stop_dxrxn","stop_dxrxndt","stop_other","other_specify")
```