---
title: "Multiomics_DKD"
author: "Hailey Hampson"
date: "2024-11-04"
output: html_document
---
#1. Set Up Libraries & Directories
```{r setup, include=FALSE}
library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)
library(survival)
library(broom)
library(emmeans)
library(ggvenn)
library(stringr)
library(devtools)
library(mice)
# devtools::install_github("JingxuanH/xtune", 
#                          build_vignettes = TRUE)
library(xtune)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
home_dir <- c("/Volumes/Peds Endo/Petter Bjornstad/TODAY subaward")
```

#2. Load & Format Data
##a. Plamsa Proteomics & Covariates
```{r, include=FALSE}
# knitr::opts_knit$set(root.dir = "~/Volumes/Peds Endo-1/Petter Bjornstad/TODAY subaward")
# load somalogic data, with QC samples already excluded
# load("/Volumes/Peds Endo-1/Petter Bjornstad/TODAY subaward/Somalogic data raw/soma.Rdata")
load("/Volumes/Peds Endo/Petter Bjornstad/TODAY subaward/Somalogic data raw/soma.Rdata")

# load analyte info
load("/Volumes/Peds Endo/Petter Bjornstad/TODAY subaward/Somalogic data raw/analytes.Rdata")

# load comorbidity data
load("/Volumes/Peds Endo/Petter Bjornstad/TODAY subaward/Clinical data/comorb.Rdata")

# load baseline risk factors
load("/Volumes/Peds Endo/Petter Bjornstad/TODAY subaward/Clinical data/TODAY/baserisk.Rdata")

# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% dplyr::group_by(releaseid) %>% dplyr::filter(row_number()==1)
# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# the above section of code used to work but seems to have broken....this should accomplish the same thing?
#base <- soma %>% filter(visit==1)

# merge in complication data
base <- left_join(base, comorb, by="releaseid")
# this was previously:
# base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# merge in baseline risk factors
base <- left_join(base, baserisk, by="releaseid")
# this was previously:
#base <- merge(base, baserisk, by="releaseid",all.x=T, all.y=F)

# log transform UAlbCreat
base$log_UAlbCreat <- log(base$UAlbCreat + 0.0000001)

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# are there proteins with low variability?
no_var = caret::nearZeroVar(base[,seq])
# none

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)

# scale by SD
base_log_scale <- base_log
predictors <- colnames(base_log[seq])
for (i in 1:length(predictors)) {
  base_log_scale[,paste0(predictors[i])] <- base_log_scale[,paste0(predictors[i])]/sd(unlist(base_log[,paste0(predictors[i])]))
}

```

##b. Plasma Metabolomics
```{r, include=FALSE}
load("/Volumes/Peds Endo/Petter Bjornstad/TODAY subaward/Metabolomic data/plasma.Rdata")

# load comorbidity data
load("/Volumes/Peds Endo/Petter Bjornstad/TODAY subaward/Clinical data/comorb.Rdata")

# load baseline risk factors
load("/Volumes/Peds Endo/Petter Bjornstad/TODAY subaward/Clinical data/TODAY/baserisk.Rdata")

# take only the baseline samples
plasma$Date.Drawn <- as.Date(plasma$Date.Drawn,format = "%m/%d/%Y")
mbase <- plasma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)
mbase <- mbase %>% arrange(Date.Drawn)

# merge in complication data
mbase <- merge(mbase, comorb, by="releaseid",all.x=T, all.y=F)

# merge in mbaseline risk factors
mbase <- merge(mbase, baserisk, by="releaseid",all.x=T, all.y=F)

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("uM", .x)
seq <- is_seq(names(mbase))

# convert to numeric
mbase[,seq] <- apply(mbase[,seq],2,as.numeric)

# are there proteins with low variability?
no_var = caret::nearZeroVar(mbase[,seq])
mbase <- mbase[,-no_var]
# other metabolites have zero variance
mbase <- mbase %>% select(!Adenine.in.uM)
mbase <- mbase %>% select(!`DL-Homocystine.in.uM`)
mbase <- mbase %>% select(!Sulpiride.in.uM)
mbase <- mbase %>% select(!Nicotinic_acid.in.uM)
mbase <- mbase %>% select(!Quinolinic.Acid.in.uM)
mbase <- mbase %>% select(!`5-Hydroxyindoleacetic.Acid.in.uM`)
seq <- is_seq(names(mbase))

# log transform
mbase_log <- mbase %>% modify_if(is_seq(names(.)), log)

# scale by SD
mbase_log_scale <- mbase_log
predictors <- colnames(mbase_log[seq])
for (i in 1:length(predictors)) {
  mbase_log_scale[predictors[i]] <- mbase_log_scale[predictors[i]]/sd(mbase_log[,paste0(predictors[i])])
}

# now we need to change the format of the variable names
temp <- str_replace_all(colnames(mbase_log_scale[,seq]),"/","_")
colnames(mbase_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(mbase_log_scale[,seq]),"-","_")
colnames(mbase_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(mbase_log_scale[,seq]),"3","Three")
colnames(mbase_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(mbase_log_scale[,seq]),"2","Two")
colnames(mbase_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(mbase_log_scale[,seq]),"\\(s\\)","s")
colnames(mbase_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(mbase_log_scale[,seq]),"5","Five")
colnames(mbase_log_scale)[seq] <- temp

#Select only metabolomics from mbase dataset
mbase_log_scale_sub <- mbase_log_scale[c(1,5:44)]
met <- colnames(mbase_log_scale_sub)[-1]
base_log_scale_sub <- base_log_scale[c(7326,7348,7351,7379,7377,7381:7389,7397,7399,7404,38:7325)]
prot <- colnames(base_log_scale[38:7325])
dat <- tidylog::left_join(base_log_scale_sub,mbase_log_scale_sub,by="releaseid") #3 participants missing proteomics, remove
rm(base,base_log,base_log_scale,base_log_scale_sub,comorb,mbase,mbase_log,mbase_log_scale,mbase_log_scale_sub,baserisk,plasma,soma,analytes)
```

#3. Plasma Analysis
##a. Feature Selection
```{r,include=T}
#Protein feature seleciton
#Univariate protein to outcome & select top 1000 proteins (by pvalues)
features <- data.frame()
for (x in prot){
  M0 <- as.formula(paste0("MIC.OR.MAC~",x,"+HbA1c+bmi+sex+AGEBASE+log_trig+sbp+si_1_ins0"))
  M1 <- glm(M0,family="binomial",data=dat)
  coef <- summary(M1)$coef[2,1]
  p <- summary(M1)$coef[2,4]
  results <- data.frame(Feature=x,Beta=coef,Pvalue=p)
  features <- rbind(features,results)
}
#Select top 1000 features
features_top <- features %>% 
  slice_min(Pvalue, n = 1000)
features <- features_top$Feature


#Univariate metabolite to outcome& select top 20 metabolites (by pvalues)
features2 <- data.frame()
for (x in met){
  M0 <- as.formula(paste0("MIC.OR.MAC~",x,"+HbA1c+bmi+sex+AGEBASE+log_trig+sbp+si_1_ins0"))
  M1 <- glm(M0,family="binomial",data=dat)
  coef <- summary(M1)$coef[2,1]
  p <- summary(M1)$coef[2,4]
  results2 <- data.frame(Feature=x,Beta=coef,Pvalue=p)
  features2 <- rbind(features2,results2)
}
#Select top 1000 features
features2_top <- features2 %>% 
  slice_min(Pvalue, n = 20)
features2 <- features2_top$Feature

```

##b. Analysis
```{r, include=T}
#Define outcome vector: Albuminuria (Binary Occurance)
cov <- c("HbA1c","bmi","sex","AGEBASE","log_trig","sbp","si_1_ins0")
colnames(dat)[which(colnames(dat) %in% cov)] <- paste0("cov_",colnames(dat)[which(colnames(dat) %in% cov)])
covars <- paste0("cov_",c("HbA1c","bmi","sex","AGEBASE","log_trig","sbp","si_1_ins0"))
Y <- dat$MIC.OR.MAC
X <- dat[c(features2,features,covars)]
#Missing insulin sensitivity for two participants ("163" "298")
imputeX <- mice(X,m=1,method="pmm",maxit=5)
X <- complete(imputeX)
X <- as.matrix(X)#reduced omics sets
# X <- as.matrix(dat[c(met,prot)]) #Full omics sets
rownames(X) <- dat$releaseid
Z <- data.frame(predictors=colnames(X),metabolite=NA,protein=NA,covariate=NA)
rownames(Z) <- Z$predictors
Z <- Z %>% 
  select(-predictors)
Z <- Z %>% 
  mutate(metabolite=ifelse(grepl("seq",rownames(Z)) | rownames(Z) %in% covars,0,1),
         protein=ifelse(grepl("seq",rownames(Z)),1,0),
         covariate=ifelse(rownames(Z) %in% covars,1,0))
Z <- as.matrix(Z)
fit1 <- xtune(X,Y,Z, family = "binary", c = 0.5)
fit1$penalty.vector
coef_xtune(fit1,out="lambda.min")
predict_xtune(fit1, newX = X)
coef(cvfit, s = "lambda.min")
# s=“lambda.1se"



```

```{r}
teenlabs <- load("/Volumes/Peds Endo/Petter Bjornstad/Teen Labs/Data_Cleaned/analysis_dataset.RData")
df <- df %>% 
  distinct(ID)
write.csv(df,"/Users/hhampson/Documents/UW/1_Ongoing Projects/Omics_DKD_Glycemic_Control/0_Data/TeenLABs_IDs.csv")
```