---
title: "Melanie Cree - DNL mixed models"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(readxl)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

home_dir = ifelse(.Platform$OS.type != "unix","E:/Melanie Green/DNL-GLP1/data",
                  "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects")
knitr::opts_knit$set(root.dir = home_dir)
setwd(home_dir)

```

```{r data, include=FALSE}
data_2a <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 2A",skip=1)
data_2b <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 2B",skip=1)
data_2c <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 2C",skip=1)
data_2d <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 2D",skip=1)
data_2e <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 2E",skip=1)
data_2f <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 2F",skip=1)
data_2g <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 2G",skip=1)
data_2h <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 2H",skip=1)
data_3a <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 3A",skip=1)
data_3b <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 3B",skip=1)
data_3c <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 3C",skip=1)
data_3d <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 3D",skip=1)
data_3e <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 3E",skip=1)
data_3f <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 3F",skip=1)
data_3g <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 3G",skip=1)
data_3h <- read_xlsx("./For LP, PCOS DNL without pre-baseline.xlsx",sheet="Fig 3H",skip=1)
```

# Background

# Methods

# Results

```{r echo=FALSE}
kable(t1,caption = "")
```
<br>
