---
title: "Hepatic and pancreatic oxidative metabolism"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    embed-resources: true
editor: visual
---

```{r libraries, echo=F, include = F}
library(tidyverse)
library(arsenal)
library(dplyr)
```

```{r load-data, echo = F, include = F}
# Load dictionary function and file
source("/Users/choiyej/GitHub/YC_CHCO/R Functions/label_harmonized_function.R")

harm_dat <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/soma_harmonized_dataset.csv", na.strings = "")
```

```{r echo = F, include=F}
ids <- c("CRC-02", "CRC-10", "CRC-14", "CRC-55", "CRC-58", 
         "RH2-01-O", "RH2-04-O", "RH2-06-O", "RH2-36-O", "RH2-39-O", 
         "CRC-32", "CRC-35", "CRC-41", "CRC-44", "CRC-59", 
         "RH2-08-T", "RH2-19-T", "RH2-42-T", "RH2-44-T", "RH2-51-T")

dat <- harm_dat %>% filter(record_id %in% ids) %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(mrn, screen_date)) %>%
  # filter(participation_status!="Removed"|is.na(participation_status)) %>%
  dplyr::mutate(race_ethnicity_condensed = case_when(race == "White" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino White",
                                              race == "Black or African American" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino Black",
                                              ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
                                              T ~ "Not Hispanic or Latino Other"),
         combined_tkv = coalesce(total_kidney_volume_ml, total_kidney_volume_ml_manual),
         combined_ht_tkv = coalesce(ht_adj_tkv, ht_adj_tkv_manual)) %>%
  rowwise() %>%
  dplyr::mutate(avg_c_k1 = mean(c(lc_k1, rc_k1)),
                avg_c_k2 = mean(c(lc_k2, rc_k2)),
                avg_m_k1 = mean(c(lm_k1, rm_k1)),
                avg_m_k2 = mean(c(lm_k2, rm_k2)),
                avg_c_f = mean(c(lc_f, rc_f)),
                avg_m_f = mean(c(lm_f, rm_f)))
```

```{r echo = F, results='asis'}
summary(tableby(group ~ age + sex + race + ethnicity + eGFR_fas_cr + combined_tkv + combined_ht_tkv + avg_c_k1 + avg_m_k1 + avg_c_k2 + avg_m_k2 + avg_c_f + avg_m_f + p2_raw_m + diabetes_duration + insulin_pump_timepoint + insulin_injections_timepoint + insulin_med_timepoint, data = dat), test = F, total = F)
```
