---
title: "Harmonized dataset overview"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    embed-resources: true
---

```{r setup, include=F}
library(dplyr)
library(knitr)
library(Hmisc)
library(tidyverse)
library(arsenal)
library(kableExtra)

harm_dat <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/soma_harmonized_dataset.csv", na.strings = "")
source("/Users/choiyej/GitHub/YC_CHCO/R Functions/label_harmonized_function.R")

```

```{r echo = F}
dict <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/data_dictionary_master.csv") 
dict <- label_harmonized_dict(harm_dat, dict) %>%
  dplyr::mutate(race_ethnicity_condensed = "Race/Ethnicity",
                avg_c_t1 = "Avg cortex T1",
                avg_k_t1 = "Avg kidney T1",
                t1_l_cortex = "Left cortex T1",
                t1_r_cortex = "Right cortex T1",
                t1_l_kidney = "Left kidney T1",
                t1_r_kidney = "Right kidney T1",
                avg_tot_k1_wo_cyst = "Avg kidney k1 (wo cyst)",
                avg_tot_k2_wo_cyst = "Avg kidney k2 (wo cyst)",
                avg_c_k1_wo_cyst_vw = "Avg cortex k1 (wo cyst)",
                avg_m_k1_wo_cyst_vw = "Avg medulla k2 (wo cyst)",
                avg_c_k2_f = "Avg cortex k2/F",
                group_t2ob = "Group")
harm_dat <- label_harmonized(harm_dat, dict[1,])

dat <- harm_dat %>% 
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(record_id, visit)) %>%
  dplyr::mutate(race_ethnicity_condensed = case_when(race == "White" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino White",
                                              race == "Black or African American" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino Black",
                                              ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
                                              T ~ "Not Hispanic or Latino Other")) %>%
  arrange(record_id)
```

```{r echo=F}
# define variables of interest
clinical_vars <- c("age", "sex", "race_ethnicity_condensed", "weight", "height", "bmi",  "sbp", "dbp", "pulse", "creatinine_s", "eGFR_CKD_epi", "epic_sglti2_1", "epic_ever_sglt2i_1", "epic_glp1ra_1", "epic_ever_glp1ra_1", "diabetes_duration")

dexa_vars <- c("dexa_body_fat", "dexa_fat_kg", "dexa_lean_kg", "dexa_trunk_kg")

kidney_function_vars <- c("p2_raw_m", "p2_raw_leanm", "p2_gc_m", "p2_gc_leanm", "gfr_raw_plasma", "gfr_bsa_plasma", "erpf_raw_plasma", "erpf_bsa_plasma", "rvr", "glomerular_pressure", "baseline_ffa")

mri_vars <- c("total_kidney_volume_ml", "left_kidney_volume_ml", "right_kidney_volume_ml", "pcasl3d_left", "pcasl3d_right", "avg_c_r2", "bold_l_bl_cortex", "bold_r_bl_cortex", "avg_k_r2", "bold_l_bl_kidney", "bold_r_bl_kidney", "avg_m_r2", "bold_l_bl_medulla", "bold_r_bl_medulla", "avg_m_fsoc", "fsoc_l_medulla", "fsoc_r_medulla", "avg_c_adc", "adc_left", "adc_right")

pet_vars <- c("lc_f",	"rc_f",	"avg_c_f",	"lm_f",	"rm_f",	"avg_m_f",	"lc_k1",	"rc_k1",	"avg_c_k1",	"lm_k1",	"rm_k1", "avg_m_k1", "lc_k2", "rc_k2", "avg_c_k2", "lm_k2", "rm_k2", "avg_m_k2", "t1_l_cortex",	"t1_r_cortex",	"avg_c_t1", "t1_l_kidney",	"t1_r_kidney",	"avg_k_t1")

vw_vars <- c("lc_k2_wo_cyst_vw", "rc_k2_wo_cyst_vw", "avg_c_k2_wo_cyst_vw", "lm_k2_wo_cyst_vw", "rm_k2_wo_cyst_vw", "avg_m_k2_wo_cyst_vw", "lc_k1_wo_cyst_vw", "rc_k1_wo_cyst_vw", "avg_c_k1_wo_cyst_vw", "lm_k1_wo_cyst_vw", "rm_k1_wo_cyst_vw", "avg_m_k1_wo_cyst_vw", "ltot_k2_wo_cyst", "rtot_k2_wo_cyst", "avg_tot_k2_wo_cyst", "ltot_k1_wo_cyst", "rtot_k1_wo_cyst", "avg_tot_k1_wo_cyst")
```

## Clinical data overview
#### Demographics

```{r}
demographics <- arsenal::tableby(as.formula(paste("group ~", 
                                 paste(c(clinical_vars, 
                                         'kwt(acr_u, "Nmiss", "medianq1q3", "range")', 
                                         'kwt(hba1c, "Nmiss", "medianq1q3", "range")'), 
                                       collapse = " + "))), 
                                 strata = study,
                                 data = dat)
summary(demographics, test = F)
```

#### Meds


## Data availability

#### IVGTT

#### MRI

#### PET

#### Kidney biopsy

#### Liver biopsy


