---
title: "Data pull for Hongxu & Jesse"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    theme: default
    page-layout: full
    embed-resources: true
editor: visual
---

```{r, include = F}
library(dplyr)
library(tidyr)
```

```{r, include = F}
dat <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv", na.strings = c(" ", "", "-9999",-9999))
dict <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/data_dictionary_master.csv", na.strings = c(" ", "", "-9999",-9999)) %>%
  dplyr::select(variable_name, label)

ids <- read.csv("/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/Goodrich/Data requests/sample_id.csv")
vars <- read.csv("/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/Goodrich/Data requests/variables_020325.csv") %>%
  filter(variable_name!="")

dat_subset <- dat %>%
  filter(record_id %in% ids$record_id) %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
            across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
            .by = record_id) %>%
  mutate(egfr_hyper_135 = case_when(eGFR_fas_cr >= 135 ~ "Yes", eGFR_fas_cr < 135 ~ "No"),
         microalbumin_u_mgdL = microalbumin_u/10) %>%
  dplyr::select(record_id, group, vars$variable_name, creatinine_u, microalbumin_u_mgdL, acr_u, egfr_hyper_135,
                starts_with("u24_"), -u24_gluc, -u24_labs, sodium_u)

# hyperfiltration by mGFR
mgfr_sub <- subset(dat_subset, group == "Lean Control", select = gfr_bsa_plasma) %>% dplyr::ungroup() %>%
  dplyr::summarise(mgfr_mean = mean(gfr_bsa_plasma), mgfr_sd = sd(gfr_bsa_plasma)) %>%
  mutate(mgfr_cutoff = mgfr_mean + (2*mgfr_sd))
dat_subset <- dat_subset %>%
  mutate(mgfr_hyper_2sd = case_when(gfr_bsa_plasma >= mgfr_sub$mgfr_cutoff ~ "Yes",
                                gfr_bsa_plasma < mgfr_sub$mgfr_cutoff ~ "No"))

write.csv(dat_subset, "/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/Data Harmonization/Data Exports/rh_it_crc_HW_020425.csv", row.names = F, na = "")

dict_subset <- dict %>%
  filter(variable_name %in% colnames(dat_subset))
write.csv(dict_subset, "/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/Data Harmonization/Data Exports/rh_it_crc_dict_HW_020425.csv", row.names = F, na = "")
```
