---
title: "RH/IMP/RH2"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    theme: default
    page-layout: full
    embed-resources: true
---

```{r, include = F}
library(dplyr)
library(tidyr)
library(arsenal)
library(lubridate)
library(Hmisc)
library(purrr)
library(ggplot2)
```

```{r include = F}
dat <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv", na.strings = c(" ", "", "-9999",-9999))
dat <- dat %>%
  filter(study == "IMPROVE" | study == "RENAL-HEIR" | study == "RENAL-HEIRitage") %>%
  dplyr::summarise(dplyr::across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   dplyr::across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = mrn) %>%
  dplyr::select(improve_id, rh_id, rh2_id, group) %>%
  arrange(group)

write.csv(dat, "/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Exports/imp_rh_rh2_ids.csv", row.names = F, na = "")
table(dat$group)
```