---
title: "Kidney MR by Sex"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    embed-resources: true
---

```{r libraries, echo=F, include = F}
library(tidyverse)
library(arsenal)
library(dplyr)
library(ggplot2)
library(patchwork)
library(knitr)
```

```{r prep-data, echo = F, include = F}
# Load clinical data
harm_dat <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/soma_harmonized_dataset.csv", na.strings = "")

dat <- harm_dat %>% 
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(mrn, visit)) %>%
  dplyr::mutate(race_ethnicity_condensed = case_when(race == "White" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino White",
                                              race == "Black or African American" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino Black",
                                              ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
                                              T ~ "Not Hispanic or Latino Other")) %>%
  filter(group != "PKD") %>%
  filter(!is.na(mrn)) %>%
  arrange(record_id)

labs <- list(avg_c_adc = "Avg cortical ADC",
             avg_c_fsoc = "Avg cortical FSOC",
             avg_c_r2 = "Avg cortical R2*",
             avg_pcascl= "Avg cortical 3D pcasL",
             avg_k_fsoc = "Avg kidney FSOC",
             avg_k_r2 = "Avg kidney R2*",
             avg_m_fsoc = "Avg medulla FSOC",
             avg_m_r2 = "Avg medulla R2*")
```
# Descriptive tables
```{r echo = F, results='asis'}
summary(tableby(sex ~ age + group + kwt(acr_u, "median", "q1q3") +  albuminuria_cat + sbp + dbp + map + kwt(hba1c, "median", "q1q3") ,
                data = dat),
        labelTranslations = labs)
```

## Kidney MR params

```{r echo = F, include=F}
outcome <- c("avg_c_adc", "avg_c_fsoc", "avg_c_r2", "avg_pcascl",
             "avg_k_fsoc", "avg_k_r2", "avg_m_fsoc", "avg_m_r2")
plot_list <- list()

# Distribution of each outcome
for (i in outcome) {
  p <- ggplot(dat, aes_string(x = i)) + 
    geom_histogram(bins = 30, color = "black", fill = "lightblue") +
    theme_minimal() +
    labs(title = paste("Distribution of", outcome), x = i, y = "Frequency")
  plot_list[[i]] <- p
}
(plot_list[[1]] | plot_list[[2]]) / (plot_list[[3]] | plot_list[[4]])
(plot_list[[5]] | plot_list[[6]]) / (plot_list[[7]] | plot_list[[8]])
```

### By sex

```{r echo = F, results='asis'}
summary(tableby(sex ~ avg_c_adc + avg_c_fsoc + avg_c_r2 +
                  avg_k_fsoc + avg_k_r2 +
                  avg_m_fsoc + avg_m_r2 + avg_pcascl,
                data = dat),
        labelTranslations = labs)
```

### By group

```{r echo = F, results='asis'}
summary(tableby(group ~ avg_c_adc + avg_c_fsoc + avg_c_r2 +
                  avg_k_fsoc + avg_k_r2 +
                  avg_m_fsoc + avg_m_r2 + avg_pcascl,
                data = dat),
        labelTranslations = labs)
```

### By group and sex
```{r echo = F, results='asis'}
summary(tableby(sex ~ avg_c_adc + avg_c_fsoc + avg_c_r2 +
                  avg_k_fsoc + avg_k_r2 +
                  avg_m_fsoc + avg_m_r2 + avg_pcascl,
                data = dat, strata = group),
        labelTranslations = labs)
```


## Interactions with sex

### Severe albuminuria (A3) and NELL1
```{r echo = F, results='asis'}
dat$alb_sev <- case_when(dat$albuminuria_cat == "A3" ~ 1,
                         (dat$albuminuria_cat == "A1"| dat$albuminuria_cat == "A2") ~ 0)
mod <- glm(alb_sev ~ hba1c + log(triglycerides) + sbp + sex + seq.6544.33 + sex*seq.6544.33,
          data = dat, family = "binomial")
kable(broom::tidy(mod, conf.int = T, exponentiate = T), digits = 3)
```

### Severe albuminuria (A3) and CI061
```{r echo = F, results='asis'}
mod <- glm(alb_sev ~ hba1c + log(triglycerides) + sbp + sex + seq.5699.19 + sex*seq.5699.19,
          data = dat, family = "binomial")
kable(broom::tidy(mod, conf.int = T, exponentiate = T), digits = 3)
```

### Severe albuminuria (A3) and PSB3
```{r echo = F, results='asis'}
mod <- glm(alb_sev ~ hba1c + log(triglycerides) + sbp + sex + seq.18339.207 + sex*seq.18339.207,
          data = dat, family = "binomial")
kable(broom::tidy(mod, conf.int = T, exponentiate = T), digits = 3)
```

### Moderate albuminuria (A2) and NELL1
```{r echo = F, results='asis'}
dat$alb_mod <- case_when(dat$albuminuria_cat == "A2" ~ 1,
                         (dat$albuminuria_cat == "A1"| dat$albuminuria_cat == "A3") ~ 0)
mod <- glm(alb_mod ~ hba1c + log(triglycerides) + sbp + sex + seq.6544.33 + sex*seq.6544.33,
          data = dat, family = "binomial")
kable(broom::tidy(mod, conf.int = T, exponentiate = T), digits = 3)
```

### Moderate albuminuria (A2) and CI061
```{r echo = F, results='asis'}
mod <- glm(alb_mod ~ hba1c + log(triglycerides) + sbp + sex + seq.5699.19 + sex*seq.5699.19,
          data = dat, family = "binomial")
kable(broom::tidy(mod, conf.int = T, exponentiate = T), digits = 3)
```

### Moderate albuminuria (A2) and PSB3
```{r echo = F, results='asis'}
mod <- glm(alb_mod ~ hba1c + log(triglycerides) + sbp + sex + seq.18339.207 + sex*seq.18339.207,
          data = dat, family = "binomial")
kable(broom::tidy(mod, conf.int = T, exponentiate = T), digits = 3)
```