---
title: "pierre_hemodynamics_data_missing"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    embed-resources: true
---

```{r libraries, echo=F, include = F}
library(tidyverse)
library(arsenal)
library(dplyr)
library(ggplot2)
```

```{r prep-data, echo = F, include = F}
# Load clinical data
harm_dat <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv", na.strings = "")

dat <- harm_dat %>% 
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(record_id, visit)) %>%
  # filter(participation_status!="Removed"|is.na(participation_status)) %>%
  dplyr::mutate(race_ethnicity_condensed = case_when(race == "White" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino White",
                                              race == "Black or African American" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino Black",
                                              ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
                                              T ~ "Not Hispanic or Latino Other")) %>%
  arrange(record_id)

length(unique(subset(dat, study == "IMPROVE" & participation_status == "Participated")$record_id))


crc_rh_dat <- dat %>%
  filter(study == "CROCODILE" | study == "RENAL-HEIR")
```

```{r echo = F}
vis_miss(subset(crc_rh_dat, select = c(erpf_raw_plasma, ff, gfr_raw_plasma, glomerular_pressure, ra, rbf, re, rvr, acr_u)))
View(subset(crc_rh_dat, select = c(record_id, visit, ra, sbp, dbp, map, tot_protein, gfr_raw_plasma, erpf_raw_plasma, hct)))
```

```{r echo = F}
vis_miss(subset(crc_rh_dat, select = c(adc_left, adc_right, left_kidney_volume_ml, length_left, length_right, pasl2d_left, pasl2d_right, right_kidney_volume_ml, total_kidney_volume_ml, ht_adj_tkv, volume_left_manual, volume_right_manual, ht_adj_tkv_manual, total_kidney_volume_ml_manual)))

View(subset(crc_rh_dat, select = c(record_id, visit, ra, sbp, dbp, map, tot_protein, gfr_raw_plasma, erpf_raw_plasma, hct)))
```