---
title: "RH/RH2/IT/CRC subset for Jesse"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    embed-resources: true
---

```{r echo = F, include = F}
library(dplyr)
library(arsenal)
library(ggplot2)
library(purrr)
source("/Users/choiyej/GitHub/YC_CHCO/R Functions/label_harmonized_function.R")
```

```{r echo = F, include = F}
dat <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv", na.strings = "")

dat <- dat %>%
  filter(study %in% c("RENAL-HEIR", "RENAL-HEIRitage", "IMPROVE", "CROCODILE")) %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = record_id) %>%
  mutate(race_ethnicity_condensed = case_when(race == "White" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino White",
                                              race == "Black or African American" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino Black",
                                              ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
                                              T ~ "Not Hispanic or Latino Other"),
         albuminuria_yn = case_when(acr_u < 30 ~ "No", acr_u >= 30 ~ "Yes")) %>% 
  mutate_at(vars(starts_with("fsoc")), function(x) case_when(x < 0 ~ 0, T~x)) %>%
  select_if(~any(!is.na(.)))

dict <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/data_dictionary_master.csv") %>%
  filter(variable_name %in% colnames(dat)) %>%
  filter(!grepl("_timepoint", variable_name)) %>%
  filter(!grepl("_ever", variable_name))

dat_subset <- dat %>%
  select(record_id, co_enroll_id, group, race, ethnicity, age, sex, weight, height, bmi, diabetes_duration, acr_u, hba1c, sbp, dbp, map, creatinine_s, eGFR_CKD_epi)

write.csv(dat_subset, "/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Exports/harmonized_datset_rhrh2impcrc_subset.csv", row.names = F, na = "")
write.csv(dict, "/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Exports/harmonized_datset_rhrh2impcrc_subset_dict.csv", row.names = F, na = "")

```
