---
title: "MAST"
author: "Hailey Hampson"
date: "2025-02-06"
output: html_document
---


### ii. MAST + IPA
####a. All Cells
```{r,echo=F,warning=F,fig.width=15, fig.height=9}
#1. #UACR, SBP/DBP (MAP), GFR, RPF, BMI, Fat Mass, Lean Mass, HbA1C, TKV/htTKV
#  a. T2D
so_diab <- subset(so_kidney_sc,group=="Type 2 Diabetes")
exposure_vars <- c("sbp","dbp","map","erpf_raw_plasma","bmi","dexa_fat_kg","dexa_lean_kg","hba1c","ht_adj_tkv","total_kidney_volume_ml","acr_u")
for (exp in exposure_vars){
  mast <- mast_fxn(so=so_diab,cell=NULL,exposure=exp,covariate=NULL,gene_set=rownames(so_diab),batch_size=2000,exp_group=NULL,ref_group=NULL,additional_group="Type 2 Diabetes")
  print(mast)
}

#  b. T2D/OB - need to name additional group....
so_diab <- subset(so_kidney_sc,group2=="T2D + OB")
#"acr_u"
exposure_vars <- c("sbp","dbp","map","erpf_raw_plasma","bmi","dexa_fat_kg","dexa_lean_kg","hba1c","ht_adj_tkv","total_kidney_volume_ml")
for (exp in exposure_vars){
  mast <- mast_fxn(so=so_diab,cell=NULL,exposure=exp,covariate=NULL,gene_set=rownames(so_diab),batch_size=2000,exp_group=NULL,ref_group=NULL,additional_group="T2D_OB")
  print(mast)
}
```

####d. PT & TAL Pseudobulk
```{r,echo=F,warning=F,fig.width=15, fig.height=9}
#1. #UACR, SBP/DBP (MAP), GFR, RPF, BMI, Fat Mass, Lean Mass, HbA1C, TKV/htTKV
#  a. T2D
so_diab <- subset(so_kidney_sc,group=="Type 2 Diabetes")
exposure_vars <- c("sbp","dbp","map","erpf_raw_plasma","bmi","dexa_fat_kg","dexa_lean_kg","hba1c","ht_adj_tkv","total_kidney_volume_ml","acr_u")
for (exp in exposure_vars){
  for (celltype in cell_type2[-1]) {
    mast <- mast_fxn(so=so_diab,cell=celltype,exposure=exp,covariate=NULL,gene_set=rownames(so_diab),batch_size=2000,exp_group=NULL,ref_group=NULL,additional_group="Type 2 Diabetes")
    print(mast)
  }
}

#  b. T2D/OB - need to name additional group....
so_diab <- subset(so_kidney_sc,group2=="T2D + OB")
exposure_vars <- c("sbp","dbp","map","erpf_raw_plasma","bmi","dexa_fat_kg","dexa_lean_kg","hba1c","ht_adj_tkv","total_kidney_volume_ml","acr_u")
for (exp in exposure_vars){
  for (celltype in cell_type2[-1]) {
   mast <- mast_fxn(so=so_diab,cell=celltype,exposure=exp,covariate=NULL,gene_set=rownames(so_diab),batch_size=2000,exp_group=NULL,ref_group=NULL,additional_group="T2D_OB")
   print(mast)
  }
}
```

####c. KPMP Cells Old
```{r,echo=F,warning=F,fig.width=15, fig.height=9}
so_kidney_sc$celltype_rpca <- as.character(so_kidney_sc$celltype_rpca)
all_cell_types <- unique(so_kidney_sc$celltype_rpca)
Idents(so_kidney_sc) <- so_kidney_sc$celltype_rpca
all_cell_types <- all_cell_types[-29]
#Select full gene set
all_genes <- rownames(so_kidney_sc)

#1. #UACR, SBP/DBP (MAP), GFR, RPF, BMI, Fat Mass, Lean Mass, HbA1C, TKV/htTKV
#  a. T2D
so_diab <- subset(so_kidney_sc,group=="Type 2 Diabetes")
exposure_vars <- c("sbp","dbp","map","erpf_raw_plasma","bmi","dexa_fat_kg","dexa_lean_kg","hba1c","ht_adj_tkv","total_kidney_volume_ml","acr_u")

for (exp in exposure_vars){
  for (celltype in all_cell_types) {
    mast <- mast_fxn(so=so_diab,cell=NULL,exposure=exp,covariate=NULL,gene_set=rownames(so_diab),batch_size=2000,exp_group=NULL,ref_group=NULL,additional_group="Type 2 Diabetes")
    print(mast)
  }
}

#  b. T2D/OB - need to name additional group....
so_diab <- subset(so_kidney_sc,group2=="T2D + OB")
exposure_vars <- c("sbp","dbp","map","erpf_raw_plasma","bmi","dexa_fat_kg","dexa_lean_kg","hba1c","ht_adj_tkv","total_kidney_volume_ml","acr_u")
for (exp in exposure_vars){
  for (celltype in all_cell_types) {
    mast <- mast_fxn(so=so_diab,cell=NULL,exposure=exp,covariate=NULL,gene_set=rownames(so_diab),batch_size=2000,exp_group=NULL,ref_group=NULL,additional_group="T2D_OB")
    print(mast)
  }
}
```

####d. KPMP Cells New
```{r,echo=F,warning=F,fig.width=15, fig.height=9}
so_kidney_sc$celltype_rpca <- as.character(so_kidney_sc$celltype_rpca)
all_cell_types <- unique(so_kidney_sc$celltype_rpca)
Idents(so_kidney_sc) <- so_kidney_sc$celltype_rpca
all_cell_types <- all_cell_types[-29]
#Select full gene set
all_genes <- rownames(so_kidney_sc)

#1. #UACR, SBP/DBP (MAP), GFR, RPF, BMI, Fat Mass, Lean Mass, HbA1C, TKV/htTKV
#  a. T2D
so_diab <- subset(so_kidney_sc,group=="Type 2 Diabetes")
exposure_vars <- c("sbp","dbp","map","erpf_raw_plasma","bmi","dexa_fat_kg","dexa_lean_kg","hba1c","ht_adj_tkv","total_kidney_volume_ml","acr_u")

for (exp in exposure_vars){
  for (celltype in all_cell_types) {
    mast <- mast_fxn(so=so_diab,cell=NULL,exposure=exp,covariate=NULL,gene_set=rownames(so_diab),batch_size=2000,exp_group=NULL,ref_group=NULL,additional_group="Type 2 Diabetes")
    print(mast)
  }
}

#  b. T2D/OB - need to name additional group....
so_diab <- subset(so_kidney_sc,group2=="T2D + OB")
exposure_vars <- c("sbp","dbp","map","erpf_raw_plasma","bmi","dexa_fat_kg","dexa_lean_kg","hba1c","ht_adj_tkv","total_kidney_volume_ml","acr_u")
for (exp in exposure_vars){
  for (celltype in all_cell_types) {
    mast <- mast_fxn(so=so_diab,cell=NULL,exposure=exp,covariate=NULL,gene_set=rownames(so_diab),batch_size=2000,exp_group=NULL,ref_group=NULL,additional_group="T2D_OB")
    print(mast)
  }
}
```

