---
title: "TODAY Somalogic baseline analyses - adjusted Cox models (including eGFR)"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)
library(survival)
library(broom)
library(emmeans)
library(ggvenn)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward"
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r, include=FALSE}
setwd(home_dir)
# load somalogic data, with QC samples already excluded
load("./Somalogic data raw/soma.Rdata")

# load analyte info
load("./Somalogic data raw/analytes.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# load baseline risk factors
load("./Clinical data/TODAY/baserisk.Rdata")

# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% dplyr::group_by(releaseid) %>% dplyr::filter(row_number()==1)
# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# the above section of code used to work but seems to have broken....this should accomplish the same thing?
#base <- soma %>% filter(visit==1)

# merge in complication data
base <- left_join(base, comorb, by="releaseid")
# this was previously:
# base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# merge in baseline risk factors
base <- left_join(base, baserisk, by="releaseid")
# this was previously:
#base <- merge(base, baserisk, by="releaseid",all.x=T, all.y=F)

# log transform UAlbCreat
base$log_UAlbCreat <- log(base$UAlbCreat + 0.0000001)

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# are there proteins with low variability?
no_var = caret::nearZeroVar(base[,seq])
# none

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)

# scale by SD
base_log_scale <- base_log
predictors <- colnames(base_log[seq])
for (i in 1:length(predictors)) {
  base_log_scale[,paste0(predictors[i])] <- base_log_scale[,paste0(predictors[i])]/sd(unlist(base_log[,paste0(predictors[i])]))
}

# read in the proteins from the Joslin analysis and subset Soma data to those proteins
mma <- openxlsx::readWorkbook("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/Joslin collaboration/mma.xlsx")
analyte_keep <- analytes %>% filter(EntrezGeneSymbol %in% mma$EntrezGeneSymbol)
apt_keep <- analyte_keep$AptName
base_log_scale <- base_log_scale %>% select(all_of(c("releaseid", "DAYSTOMAC", "MAC", "AGEBASE", "HbA1c", "dxtime", "EstCreatClear", apt_keep)))
```

```{r, include=FALSE}
# Macroalbuminuria
result_MAC <- NULL
predictors <- colnames(base_log[apt_keep])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTOMAC, MAC)~",predictors[i],"+AGEBASE+HbA1c+dxtime+EstCreatClear")
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  tidymod <- tidymod[1,]
  result_MAC <- rbind(result_MAC,tidymod)
}
result_MAC$adj.p.value <- p.adjust(result_MAC$p.value, "fdr")
result_MAC$AptName <- result_MAC$term
result_MAC$term <- NULL
result_MAC <- merge(result_MAC,analytes,by="AptName",all.x = T, all.y = F)
result_MAC <- result_MAC[order(result_MAC$p.value),] 

# write all results to file
wb <- createWorkbook()
addWorksheet(wb,"MAC CPH")
writeData(wb,"MAC CPH",result_MAC,rowNames = F)
saveWorkbook(wb,"/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/Joslin collaboration/TODAY somalogic Cox models scaled Joslin.xlsx",overwrite = TRUE)

```