---
title: "BMD Analysis"
author: "Ye Ji Choi, Carson Platnick"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    theme: default
    page-layout: full
    embed-resources: true
editor: visual
---

```{r, include = F}
library(dplyr)
library(tidyr)
library(table1)
library(Hmisc)
library(rstatix)
library(purrr)
library(kableExtra)
library(knitr)
library(arsenal)
library(data.table)
library(ggpubr)
library(smplot2)
```

```{r, include = F}
dat <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv", na.strings = c(" ", "", "-9999",-9999))
coenroll_id <- read.csv("/Users/choiyej/GitHub/YC_CHCO/RH2/coenrolled_ids_LR.csv")
dict <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/data_dictionary_master.csv", na.strings = c(" ", "", "-9999",-9999)) %>%
  select(variable_name, label)

dat <- dat %>%
  filter(study != "PENGUIN") %>%
  summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
            across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
            .by = record_id) %>%
  mutate(race = case_when(grepl("&", race) ~ "More Than One",
                          T ~ race)) %>%
  mutate(ethnicity = case_when(grepl("Unknown", ethnicity) ~ "Unknown", 
                               T~ethnicity)) %>%
  filter(!is.na(dexa_bone_mineral_density)) %>%
  mutate(participation_status = case_when(is.na(participation_status) ~ "Unknown", T~participation_status)) %>%
  filter(participation_status!="Removed")


dict <- setNames(data.frame(t(dict[ , - 1])), dict[ , 1])
dict <- dict[intersect(names(dat), names(dict))]
dict[setdiff(names(dat), names(dict))] <- ""
Hmisc::label(dat) = dict[match(names(dat), names(dict))]
```

```{r include = F}
# Distribution check
dat %>%
  select(age, bmi, weight, height, waistcm, hba1c, sbp, dbp, cholesterol, ldl, hdl, triglycerides ,eGFR_fas_cr, eGFR_fas_cr_cysc, acr_u) %>% 
  gather() %>% 
  ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_histogram()

dat %>%
  select(dexa_lean_kg, dexa_fat_kg, dexa_body_fat, dexa_trunk_kg, fasting_ffa, ffa_suppression, fasting_insulin, steady_state_insulin, steady_state_cpeptide, raw_m, m_i, di, airg, acprg) %>% 
  gather() %>% 
  ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_histogram()

dat %>%
  select(gfr_raw_plasma,  gfr_bsa_plasma,  erpf_raw_plasma,  erpf_bsa_plasma,  ff,  glomerular_pressure,  ra,  re,  rvr,  total_kidney_volume_ml, ht_adj_tkv, pcasl3d_left, pcasl3d_right, adc_left, adc_right, bold_l_bl_cortex, bold_r_bl_cortex,  bold_l_bl_medulla, bold_r_bl_medulla,   fsoc_l_medulla, fsoc_r_medulla, fsoc_l_medulla, fsoc_r_medulla) %>% 
  gather() %>% 
  ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_histogram()

dat %>%
  select(ends_with(c("vw")))%>% 
  gather() %>% 
  ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_histogram()
```


# Table 1

## All Participants

```{r, include=F}
table_one <- tableby(group ~ study + sex + age + race + ethnicity + kwt(hba1c, "Nmiss", "median", "q1q3", "range") + bmi + dexa_body_fat + dexa_lean_mass + dexa_bone_mineral_density + map, data = dat)
```

```{r results='asis'}
table_one <- summary(table_one, pfootnote = T, digits=3, digits.pct=0)
table_one
```

```{r}
ggplot(dat, aes(hba1c, dexa_bone_mineral_density, size = age)) +
  labs(x = Hmisc::label(dat$hba1c),
       y = Hmisc::label(dat$dexa_bone_mineral_density),
       color  = "Group") +
  geom_point(aes(color=group), alpha = 0.6) +
  scale_color_brewer(palette = "Set1") +
  sm_statCorr(color = '#5A5A5A', corr_method = 'pearson',
              linetype = 'dashed') +
  sm_corr_theme()

summary(lm(hba1c ~ dexa_bone_mineral_density, data = dat))
summary(lm(hba1c ~ dexa_bone_mineral_density + age + sex + bmi + dexa_body_fat + dexa_lean_mass, data = dat))

```