---
title: "TODAY Somalogic baseline analyses - moderated t-tests by sex"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = ""
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r, include=FALSE}
# load somalogic data, with QC samples already excluded
load("./Somalogic data raw/soma.Rdata")

# load analyte info
load("./Somalogic data raw/analytes.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# load baseline risk factors
load("./Clinical data/TODAY/baserisk.Rdata")

# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)

# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# merge in complication data
base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# merge in baseline risk factors
base <- merge(base, baserisk, by="releaseid",all.x=T, all.y=F)

# only keep observations with nonmissing values of covariates
# otherwise size of contrast matrix will be incorrect
#base <- base %>% filter(!is.na(HbA1c) & !is.na(log_trig) & !is.na(sbp) & !is.na(si_1_ins0))

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# are there proteins with low variability?
#no_var = caret::nearZeroVar(base[,seq])
# none

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)

# make separate df for males and females
base_log_females <- base_log %>% filter(sex==1)
base_log_males <- base_log %>% filter(sex==2)

```

```{r, include=FALSE}
# sex
# Make design matrix
sex_contrast <- model.matrix(~sex,base)
# moderated t-tests with and without FDR adjustment
ymat <- t(base_log[,seq])
fit <- lmFit(ymat,sex_contrast)
fit <- eBayes(fit)
results_sex <- topTable(fit,coef = 2,number = nrow(ymat))
results_sex$AptName <- row.names(results_sex)
results_sex <- merge(results_sex,analytes,by="AptName",all.x = T, all.y = F)
results_sex <- results_sex[order(results_sex$P.Value),] 

# MIC within sex
# FEMALES
# Make design matrix
MIC_contrast_females <- model.matrix(~MIC,base_log_females)
# moderated t-tests with and without FDR adjustment
ymat <- t(base_log_females[,seq])
fit <- lmFit(ymat,MIC_contrast_females)
fit <- eBayes(fit)
results_MIC_females <- topTable(fit,coef = 2,number = nrow(ymat))
results_MIC_females$AptName <- row.names(results_MIC_females)
results_MIC_females <- merge(results_MIC_females,analytes,by="AptName",all.x = T, all.y = F)
results_MIC_females <- results_MIC_females[order(results_MIC_females$P.Value),] 
# MALES
# Make design matrix
MIC_contrast_males <- model.matrix(~MIC,base_log_males)
# moderated t-tests with and without FDR adjustment
ymat <- t(base_log_males[,seq])
fit <- lmFit(ymat,MIC_contrast_males)
fit <- eBayes(fit)
results_MIC_males <- topTable(fit,coef = 2,number = nrow(ymat))
results_MIC_males$AptName <- row.names(results_MIC_males)
results_MIC_males <- merge(results_MIC_males,analytes,by="AptName",all.x = T, all.y = F)
results_MIC_males <- results_MIC_males[order(results_MIC_males$P.Value),] 

# MAC within sex
# FEMALES
# Make design matrix
MAC_contrast_females <- model.matrix(~MAC,base_log_females)
# moderated t-tests with and without FDR adjustment
ymat <- t(base_log_females[,seq])
fit <- lmFit(ymat,MAC_contrast_females)
fit <- eBayes(fit)
results_MAC_females <- topTable(fit,coef = 2,number = nrow(ymat))
results_MAC_females$AptName <- row.names(results_MAC_females)
results_MAC_females <- merge(results_MAC_females,analytes,by="AptName",all.x = T, all.y = F)
results_MAC_females <- results_MAC_females[order(results_MAC_females$P.Value),] 
# MALES
# Make design matrix
MAC_contrast_males <- model.matrix(~MAC,base_log_males)
# moderated t-tests with and without FDR adjustment
ymat <- t(base_log_males[,seq])
fit <- lmFit(ymat,MAC_contrast_males)
fit <- eBayes(fit)
results_MAC_males <- topTable(fit,coef = 2,number = nrow(ymat))
results_MAC_males$AptName <- row.names(results_MAC_males)
results_MAC_males <- merge(results_MAC_males,analytes,by="AptName",all.x = T, all.y = F)
results_MAC_males <- results_MAC_males[order(results_MAC_males$P.Value),] 

# write all results to file
wb <- createWorkbook()
addWorksheet(wb,"sex_moderated_FDR")
writeData(wb,"sex_moderated_FDR",results_sex,rowNames = F)
addWorksheet(wb,"MIC_moderated_FDR_females")
writeData(wb,"MIC_moderated_FDR_females",results_MIC_females,rowNames = F)
addWorksheet(wb,"MIC_moderated_FDR_males")
writeData(wb,"MIC_moderated_FDR_males",results_MIC_males,rowNames = F)
addWorksheet(wb,"MAC_moderated_FDR_females")
writeData(wb,"MAC_moderated_FDR_females",results_MAC_females,rowNames = F)
addWorksheet(wb,"MAC_moderated_FDR_males")
writeData(wb,"MAC_moderated_FDR_males",results_MAC_males,rowNames = F)
saveWorkbook(wb,"./Results/TODAY proteomics moderated t-tests by sex.xlsx",overwrite = TRUE)

```

# Results

## Volcano plots

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_sex[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Females vs. Males",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_MIC_females[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Microalbuminuria vs. normoalbuminuria in females",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_MIC_males[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Microalbuminuria vs. normoalbuminuria in males",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```


```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_MAC_females[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Macroalbuminuria vs. normoalbuminuria in females",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_MAC_males[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Macroalbuminuria vs. normoalbuminuria in males",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```
