---
title: "Proteomics and HTN - SOMAScan correlation"
author: "Laura Pyle, Ye Ji Choi & Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
execute:
  echo: false
  message: false
---

```{r libraries}
#| include: false
library(psych)
library(corrplot)
library(pander)
# Print all pander tables
panderOptions("knitr.auto.asis", FALSE)
```

```{r data import}
#| include: false
# source("~/GitHub/CHCO-Code/Petter Bjornstad/Proteomics and DKD/create_today_dkd_analysis_dataset.R")
load("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Proteomics and HTN/Data_Cleaned/analysis_dataset.RData")
```

```{r functions}
cor_and_plot_soma <- function(data = df, vars) {
  # Format matrix
  d <- data[, c(vars, "acr_u", "map", "gfr_raw_plasma", "gfr_bsa_plasma")]
  n <- c(
    analytes$EntrezGeneSymbol[match(vars, analytes$AptName)],
    "acr_u", "map", "gfr_raw_plasma", "gfr_bsa_plasma"
  )
  n[duplicated(n)] <- paste0(n[duplicated(n)], "(2)")
  names(d) <- n
  # Correlations
  M <- corr.test(data.matrix(d), normal = F, method = "spearman")
  corrplot(round(M$r, 3),
    p.mat = M$p, method = "circle", type = "lower", insig = "blank",
    addCoef.col = "white", diag = FALSE
  )
  # Print a nice looking table
  r <- data.frame(round(M$r, 3))
  emphasize.strong.cells(which(M$p <= 0.05, arr.ind = TRUE))
  cat("\n")
  pander(r, caption = "Coefficients")
  cat("\n")
   # print Ns
  n <- data.frame(round(M$n, 3))
  cat("\n")
  pander(n, caption = "Number of observations")
  cat("\n")
}
```


# HTN

The proteins with the largest absolute effect size and adjusted p value $\leq 0.05$ for hypertension were: `r toString(analytes$TargetFullName[match(top_htn,analytes$AptName)])` (associated with genes `r toString(analytes$EntrezGeneSymbol[match(top_htn,analytes$AptName)])`, respectively).

```{r results='asis', dpi=1200}
cor_and_plot_soma(vars = top_htn)
```

