---
title: "Proteomics and HTN - Soluble Omics"
author: "Laura Pyle, Ye Ji Choi & Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
execute:
  echo: false
  message: false
---

```{r libraries}
#| include: false
library(tidyverse)
library(arsenal)
library(dplyr)
```

```{r data import}
#| include: false
# source("~/GitHub/CHCO-Code/Petter Bjornstad/Proteomics and DKD/create_today_dkd_analysis_dataset.R")
load("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Proteomics and HTN/Data_Cleaned/analysis_dataset.RData")
df_t2d <- df %>% filter(group=="Type 2 Diabetes")
df_lc <- df %>% filter(group=="Lean Control")
df_oc <- df %>% filter(group=="Obese Control")
```

```{r functions}
# Compare soluble omics by SGLT2i status
soluble_comp <- function(data = df, vars) {
  data <- data.frame(data)
  f <- as.formula(paste0("sglt2i_ever~", paste0(vars, collapse = "+")))
  labs <- analytes$EntrezGeneSymbol[match(vars, analytes$AptName)]
  names(labs) <- vars
  t <- tableby(f,
    data = data, numeric.test = "kwt",
    numeric.stats = c("Nmiss", "median", "q1q3")
  )
  summary(t, pfootnote = T, labelTranslations = labs)
}
```

# Soluble omics in SGLT2i+ vs. SGLT2i-

No lean controls were ever on SGLT2i, and only one obese control was ever on SGLT2i, so only the comparisons within the T2D group are shown.

## HTN

```{r message=FALSE,warning=FALSE,dpi=1200,results='asis'}
soluble_comp(vars = top_htn)
```

