---
title: "EAA primary analysis - carry-over effects"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

library(nlme)

data <- read.csv("E:\\Melanie Green\\EAA primary outcome\\Raw data\\liver fat data 7-7-21.csv")
data$delta <- data$PLA.liver.fat.. - data$AA.liver.fat..
data$order <- data$ï..med.order.A..amino.acid.first..P..placebo.first
data$ï..med.order.A..amino.acid.first..P..placebo.first <- NULL

data$ptid <- data$X
data$X.1 <- NULL
data$X.10 <- NULL
data$X.11 <- NULL
data$X.12 <- NULL
data$X.13 <- NULL
data$X.2 <- NULL
data$X.3 <- NULL
data$X.4 <- NULL
data$X.5 <- NULL
data$X.6 <- NULL
data$X.7 <- NULL
data$X.8 <- NULL
data$X.9 <- NULL
data$X <- NULL

mod1 <- lm(delta ~ order, data=data)
mod2 <- lm(AA.liver.fat.. ~ PLA.liver.fat.. + order, data=data)

summary(data[data$order=="A",]$delta)
summary(data[data$order=="P",]$delta)

long <- reshape(data, direction = "long",varying = c("AA.liver.fat..","PLA.liver.fat.."),v.names="liver_fat")
long$tx <- ifelse(long$time==1,"AA","PL")
long <- long[!is.na(long$ptid),]
long <- long[long$ptid != "",]

mm <- lme(liver_fat ~ tx*order,random=~1|ptid,data = long,na.action = na.omit)
insptot_mod_anova <- anova.lme(mm, type="marginal")

```

# Background

# Methods

# Results

```{r echo=FALSE}
kable(t1,caption = "")
```
<br>
