---
title: "Proteomics and DKD - SOMAScan correlation"
author: "Laura Pyle, Ye Ji Choi & Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
execute:
  echo: false
  message: false
---

```{r libraries}
#| include: false
library(psych)
library(corrplot)
library(pander)
library(dplyr)
library(tableone)
library(knitr)
library(gtools)
library(ggpubr)
library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)
library(survival)
library(broom)
library(emmeans)
library(ggvenn)

# Print all pander tables
panderOptions("knitr.auto.asis", FALSE)
```

```{r data import}
# load dataset for TODAY HTN analysis
# don't need the deps but df contains all protein data and harmonized data
load("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Proteomics and DKD/Data_Cleaned/analysis_dataset.RData")
top_htn_df <- NULL
top_htn <- NULL
df <- df %>% filter(visit == "baseline")
prot_include <- c("NELL1",
"CI061",
"VP9D1",
"PSG4",
"5HT6R",
"PCDG1",
"CTHR1",
"ZPLD1",
"RELM-beta",
"CLU",
"Fibrinogen",
"D-dimer",
"HACL1",
"Fibrinogen g-chain dimer",
"Ephrin-B3:CD",
"ACAM:ECD",
"SPR1",
"Cystatin C",
"PEDF",
"PEDF",
"RNase 1",
"b2-Microglobulin",
"COFA1",
"MP2K2",
"MYOC",
"FBLN3",
"IGFBP-6")

seq_include <- c("seq.6544.33",
"seq.5699.19",
"seq.24900.46",
"seq.5649.83",
"seq.13561.5",
"seq.6457.50",
"seq.15467.10",
"seq.5590.11",
"seq.22007.1",
"seq.24941.14",
"seq.2796.62",
"seq.4907.56",
"seq.23645.49",
"seq.4989.7",
"seq.7785.1",
"seq.10440.26",
"seq.12503.5",
"seq.2609.59",
"seq.9211.19",
"seq.7735.17",
"seq.7211.2",
"seq.3485.28",
"seq.8974.172",
"seq.3628.3",
"seq.16558.2",
"seq.8480.29",
"seq.2686.67")

df_t2d <- df %>% filter(group=="Type 2 Diabetes")

```

```{r functions}
cor_and_plot_soma <- function(data, vars) {
  # Format matrix
  analytes_temp <- analytes
  analytes_temp$Target_apt <- paste0(analytes_temp$Target, " (", analytes_temp$AptName, ")")
  d <- data[, c(vars, "acr_u", "gfr_raw_plasma", "gfr_bsa_plasma")]
  n <- c(
    analytes_temp$Target_apt[match(vars, analytes_temp$AptName)],
    "acr_u", "gfr_raw_plasma", "gfr_bsa_plasma"
  )
  n[duplicated(n)] <- paste0(n[duplicated(n)], "(2)")
  n[duplicated(n)] <- paste0(n[duplicated(n)], "(3)")
  names(d) <- n
  # Correlations
  M <- corr.test(data.matrix(d), normal = F, method = "spearman", adjust = "none")
  corrplot(round(M$r, 3),
    p.mat = M$p, method = "circle", type = "lower", insig = "blank",
    addCoef.col = "white", diag = FALSE
  )
  #prot_heatmap <- top_htn_df %>%
  #filter(Target %in% c("WFKN2","SEZ6L","SCG3","LSAMP","T132B","Nr-CAM","PEDF","IGLO5",
  #                     "PCD10:ECD","UNC5H4","SLIK1",
  #                     "Secretoglobin family 3A member 1","sICAM-5")) %>%
  #pull(AptName)
  #colnames_M <- top_htn_df %>%
  #  filter(AptName %in% prot_heatmap) %>%
  # pull(Target)
  #colnames_M <- paste0(colnames_M,"_",prot_heatmap)
  # Print a nice looking table
  r <- data.frame(round(M$r, 3))
 # colnames(r)[1:length(colnames_M)] <- colnames_M
  #rownames(r)[1:length(colnames_M)] <- colnames_M
  emphasize.strong.cells(which(M$p <= 0.05, arr.ind = TRUE))
  cat("\n")
  pander(r, caption = "Coefficients")
  cat("\n")
  # print p-values
  p <- data.frame(round(M$p, 3))
  #colnames(p)[1:length(colnames_M)] <- colnames_M
 # rownames(p)[1:length(colnames_M)] <- colnames_M
  cat("\n")
  pander(p, caption = "P-values")
  cat("\n")
   # print Ns
  n <- data.frame(round(M$n, 3))
  #colnames(n)[1:length(colnames_M)] <- colnames_M
  #rownames(n)[1:length(colnames_M)] <- colnames_M
  cat("\n")
  pander(n, caption = "Number of observations")
  cat("\n")
}
```

```{r, include=FALSE}
corr_plot_modified_nodict <- function(data, X, Y, cor_method = "spearman", adj_var = NULL, 
                               method = "color", insig = "pch", coef_col = NULL,
                               pch = 4, pch.col = "black", pch.cex = 0, colnames_M, rownames_M) {
  prot_heatmap <- seq_include
  analytes_temp <- analytes
  analytes_temp$Target_apt <- paste0(analytes_temp$Target, " (", analytes_temp$AptName, ")")
  TA <- analytes_temp$Target_apt[match(prot_heatmap, analytes_temp$AptName)]
  colnames(Y) <- TA
  n_cols = length(Y)
  M <- cor(y = Y,
           x = X,
           use = "pairwise.complete.obs",
           method = cor_method)
  M <- M[,order(colnames(M))]
  if (!is.na(adj_var)){
    x_vars <- rep(X, times = length(Y))
    x_coord <- rep(seq(1,length(Y)), each = length(X))
    y_vars <- rep(Y, each = length(X))
    y_coord <- rep(seq(length(X),1), times = length(Y))
    lm_extracted <- data.frame(yName = character(0),
                               xName = character(0),
                               x = numeric(0),
                               y = numeric(0),
                               adj_var = character(0),
                               adj_x_coef = numeric(0),
                               adj_x_pval = numeric(0))
    for (i in 1:length(x_vars)) {
      if(x_vars[i] != y_vars[i]) {
        lm_formula <- as.formula(paste0(y_vars[i], "~", x_vars[i], "+", adj_var))
        lm_model <- lm(lm_formula, data = data)
        lm_summary <- summary(lm_model)
        lm_coef <- lm_summary$coefficient[x_vars[i], "Estimate"]
        lm_p_val <- lm_summary$coefficient[x_vars[i], "Pr(>|t|)"]
        lm_extracted <- rbind(lm_extracted,
                              data.frame(
                                yName = y_vars[i],
                                xName = x_vars[i],
                                x = x_coord[i],
                                y = y_coord[i],
                                adj_var = adj_var,
                                adj_x_coef = lm_coef,
                                adj_x_pval = lm_p_val))
      }
    }
  }
  
  correlation_p_value <- correlation_p_value_matrix(data, relevant_vars = c(colnames(Y),colnames(X)), n_cols = n_cols, cor_method = cor_method, Y=Y, X=X)

  corrplot(M,
           p.mat = correlation_p_value,
           method = method,
           tl.col = "black",
           tl.srt = 45,
           tl.cex = 1.2,
           insig = insig,
           addCoef.col = coef_col,
           addgrid.col = 'lightgray',
           number.digits = 2,
           pch.col = pch.col, 
           pch = pch,
           pch.cex = pch.cex)$corrPos -> p1
  p1_sub <- subset(p1, p.value <= 0.05)
  p1_sub2 <- subset(p1, p.value <= 0.05 & abs(corr) >= 0.7)
  
  if (nrow(p1) > 0) {
    graphics::text(p1$x, p1$y, sprintf("%.2f", p1$corr), adj = c(0.5, 0), cex=1.2)
    if (nrow(p1_sub > 0)) {
      graphics::text(p1_sub$x, p1_sub$y, stars.pval(p1_sub$p.value), adj = c(0.5, 2), cex=1.2)
    }
  }
  if (nrow(p1_sub2) > 0) {
    graphics::text(p1_sub2$x, p1_sub2$y, sprintf("%.2f", p1_sub2$corr), col = "white", adj = c(0.5, 0), cex=1.2)
    graphics::text(p1_sub2$x, p1_sub2$y, stars.pval(p1_sub2$p.value), col = "white", adj = c(0.5, 2), cex=1.2)
  }
  if (!is.na(adj_var)) {
    lm_extracted <- subset(lm_extracted, adj_x_pval <= 0.05)
    if (nrow(lm_extracted) > 0){
      graphics::rect(xleft = lm_extracted$x-.45, 
                     ybottom = lm_extracted$y-.45,
                     xright = lm_extracted$x+.45,
                     ytop = lm_extracted$y+.45)
    }
  }
}


correlation_p_value_matrix <- function(data, relevant_vars, n_cols, cor_method = "spearman", Y=Y, X=X) {
  analytes_temp <- analytes
  analytes_temp$Target_apt <- paste0(analytes_temp$Target, " (", analytes_temp$AptName, ")")
  # Filter relevant variables for the correlation matrix
  #relevant_vars_apt <- analytes_temp$AptName[match(colnames(Y), analytes_temp$Target_apt)]
  Y <- Y[,order(colnames(Y))]
  dat_correlation <- cbind(Y,X) %>%
    dplyr::select(all_of(relevant_vars))
    # Compute p-values 
  res2 <- Hmisc::rcorr(as.matrix(dat_correlation),
                       type = cor_method)
  corr_pval <- as.data.frame(res2$P) %>%
    dplyr::select(all_of(relevant_vars[1:n_cols]))
  corr_pval = corr_pval[(n_cols + 1):nrow(corr_pval),]
  corr_pval <- corr_pval[,order(colnames(corr_pval))]
  return(as.matrix(corr_pval))
}
```

# Correlations

```{r results='asis', dpi=1200}
cor_and_plot_soma(data = df_t2d, vars = seq_include)

#colnames_M <- paste0(colnames_M,"_",prot_heatmap)
png(height = 3000, width = 6000, file = "/Users/pylell/Dropbox/TODAY HTN and DKD output/local_T2D_DKD_heatmap.png", res = 300)
corr_plot_modified_nodict(data=df_t2d, 
                   Y=df_t2d[,seq_include], 
                 X=df_t2d[,c("acr_u", "gfr_raw_plasma", "gfr_bsa_plasma")],
                 cor_method="spearman", adj_var = NA,
                 colnames_M=prot_include,
                 rownames_M=c("acr_u", "gfr_raw_plasma", "gfr_bsa_plasma"))
dev.off()


lm_co_UACR_unadj <- lm(data = df_t2d, acr_u ~ seq.6544.33)
lm_co_UACR_adj <- lm(data = df_t2d, UAlbCreat ~ seq.6544.33 + HbA1c + log_trig + sbp + si_1_ins0)

lm_co_egfr_unadj <- lm(data = df_t2d, EstCreatClear ~ seq.6544.33)
lm_co_egfr_adj <- lm(data = df_t2d, EstCreatClear ~ seq.6544.33 + HbA1c + log_trig + sbp + si_1_ins0)
```


```{r, include=FALSE}
setwd(home_dir)
# load somalogic data, with QC samples already excluded
load("./Somalogic data raw/soma.Rdata")

# load analyte info
load("./Somalogic data raw/analytes.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# load baseline risk factors
load("./Clinical data/TODAY/baserisk.Rdata")

# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% dplyr::group_by(releaseid) %>% dplyr::filter(row_number()==1)
# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# the above section of code used to work but seems to have broken....this should accomplish the same thing?
#base <- soma %>% filter(visit==1)

# merge in complication data
base <- left_join(base, comorb, by="releaseid")
# this was previously:
# base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# merge in baseline risk factors
base <- left_join(base, baserisk, by="releaseid")
# this was previously:
#base <- merge(base, baserisk, by="releaseid",all.x=T, all.y=F)

# log transform UAlbCreat
base$log_UAlbCreat <- log(base$UAlbCreat + 0.0000001)

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# are there proteins with low variability?
no_var = caret::nearZeroVar(base[,seq])
# none

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)

# scale by SD
base_log_scale <- base_log
predictors <- colnames(base_log[seq])
for (i in 1:length(predictors)) {
  base_log_scale[,paste0(predictors[i])] <- base_log_scale[,paste0(predictors[i])]/sd(unlist(base_log[,paste0(predictors[i])]))
}

mod_unadj <- coxph(data = base_log_scale, formula = Surv(DAYSTOMIC.OR.MAC, MIC.OR.MAC) ~ seq.6544.33)
mod_adj <- coxph(data = base_log_scale, formula = Surv(DAYSTOMIC.OR.MAC, MIC.OR.MAC) ~ seq.6544.33 + HbA1c + log_trig + sbp + si_1_ins0)

hist(base_log_scale[base_log_scale$MIC.OR.MAC==0, "DAYSTOMIC.OR.MAC"])
hist(base_log_scale[base_log_scale$MIC.OR.MAC==1, "DAYSTOMIC.OR.MAC"])

lm_unadj <- lm(data = base_log_scale, DAYSTOMIC.OR.MAC ~ seq.6544.33)
lm_adj <- lm(data = base_log_scale, DAYSTOMIC.OR.MAC ~ seq.6544.33 + HbA1c + log_trig + sbp + si_1_ins0)

lm_UACR_unadj <- lm(data = base_log_scale, UAlbCreat ~ seq.6544.33)
lm_UACR_adj <- lm(data = base_log_scale, UAlbCreat ~ seq.6544.33 + HbA1c + log_trig + sbp + si_1_ins0)

lm_egfr_unadj <- lm(data = base_log_scale, EstCreatClear ~ seq.6544.33)
lm_egfr_adj <- lm(data = base_log_scale, EstCreatClear ~ seq.6544.33 + HbA1c + log_trig + sbp + si_1_ins0)

```