---
title: "Proteomics and DKD - Soluble Omics"
author: "Laura Pyle, Ye Ji Choi & Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
execute:
  echo: false
  message: false
---

```{r libraries}
#| include: false
library(tidyverse)
library(arsenal)
```

```{r data import}
#| include: false
# source("~/GitHub/CHCO-Code/Petter Bjornstad/Proteomics and DKD/create_today_dkd_analysis_dataset.R")
load("/Volumes/Peds Endo/Petter Bjornstad/Proteomics and DKD/Data_Cleaned/analysis_dataset.RData")
```

```{r functions}
# Compare soluble omics by SGLT2i status
soluble_comp = function(data = df, vars){
  data = data.frame(data)
  f = as.formula(paste0("sglt2i_ever~",paste0(vars,collapse = "+")))
  labs = analytes$EntrezGeneSymbol[match(vars,analytes$AptName)]
  names(labs) = vars
  t = tableby(f,data = data,numeric.test="kwt",
              numeric.stats=c("Nmiss", "median", "q1q3"))
  summary(t,pfootnote = T,labelTranslations = labs)
}
```

# Soluble omics in SGLT2i+ vs. SGLT2i-

## MAC

```{r message=FALSE,warning=FALSE,dpi=1200,results='asis'}
soluble_comp(vars = top_mac)
```

## MIC

```{r message=FALSE,warning=FALSE,dpi=1200,results='asis'}
soluble_comp(vars = top_mic)
```

## HYP

```{r message=FALSE,warning=FALSE,dpi=1200,results='asis'}
soluble_comp(vars = top_hyp)
```

## RAPID

```{r message=FALSE,warning=FALSE,dpi=1200,results='asis'}
soluble_comp(vars = top_rapid)
```

## HTN

```{r message=FALSE,warning=FALSE,dpi=1200,results='asis'}
soluble_comp(vars = top_htn)
```

## HTN with SBP

```{r message=FALSE,warning=FALSE,dpi=1200,results='asis'}
soluble_comp(vars = top_htn_sbp)
```
