---
title: "Proteomics and DKD LOCAL DESC"
format: html
editor: visual
---

```{r libraries}
#| include: false
library(tidyverse)
library(table1)
```

```{r setup, include=F}
# Import and clean data
df <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv",na.strings = "")
df = df %>% filter(study %in% c("CROCODILE","IMPROVE","RENAL-HEIR"),
                   !grepl("IT2D",co_enroll_id)) %>%
  filter(visit == "baseline") %>%
  filter(participation_status == "Participated") %>%
  select(record_id,co_enroll_id,visit,group, age, sex, race, ethnicity, race_ethnicity, 
         diabetes_duration, albuminuria_cat,
         bmi, hba1c, sbp, triglycerides, 
         p1_gc_leanm, p1_gc_m, p1_raw_leanm, p1_raw_m, p2_gc_leanm, p2_gc_m, 
         p2_raw_leanm, p2_raw_m, eGFR_Zap, eGFR_CKD_epi, eGFR_fas_cr, 
         eGFR_fas_cr_cysc, eGFR_bedside_Schwartz, alb_base, 
         gfr_bsa_plasma, gfr_raw_plasma, gfr_bsa_plasma_urine, gfr_raw_plasma_urine,
         acr_u, glom_nuc_count, glom_tuft_area, glom_volume_con, glom_volume_weibel, 
         glom_volume_wiggins, gloms_gs, gloms) %>%
  mutate(race_ethnicity_condensed = case_when(race == "White" & startsWith(ethnicity, "Not") ~ "Non-Hispanic White",
                                              race == "Black or African American" & startsWith(ethnicity, "Not") ~ "Non-Hispanic Black",
                                              ethnicity == "Hispanic or Latino" ~ "Hispanic",
                                              T ~ "Other")) %>%
  group_by(record_id,visit) %>%
  summarise(across(where(is.character),~last(na.omit(.x))),
            across(where(is.factor),~last(na.omit(.x))),
            across(where(is.numeric),~mean(.x,na.rm = T)),.groups = "drop") %>%
  mutate_all(~ifelse(is.nan(.), NA, .))

label(df$age) <- "Age"
label(df$sex) <- "Sex"
label(df$race_ethnicity_condensed) <- "Race/Ethnicity"
label(df$diabetes_duration) <- "Diabetes Duration (Years)"
label(df$bmi) <- "BMI"
label(df$hba1c) <- "HbA1c"
label(df$acr_u) <- "UACR"
label(df$albuminuria_cat) <- "Albuminuria"
```

```{r}
local_desc <- table1(~ age + sex + race_ethnicity_condensed + diabetes_duration + bmi + hba1c + acr_u + albuminuria_cat| group, data = df)
local_desc
write.table(local_desc , "/Users/choiyej/GitHub/YC_CHCO/Descriptives/TODAY/local_descriptions_updated.csv", col.names = T, row.names= F, append = T, sep=',')
```
