---
title: "Baby Study growth curves"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(readr)
library(ggplot2)
library(quantregGrowth)
library(tidyverse)
library(skimr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

home_dir = ifelse(.Platform$OS.type != "unix","H:\\Tartaglia\\Growth curves\\",
                  "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects")
knitr::opts_knit$set(root.dir = home_dir)

```

```{r echo=FALSE}
ds <- read.csv("./Baby study GSV scores.csv")
```

# BSID_GSV_COG

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
mform <-gcrq(data=ds, bsid_gsv_cog ~ ps(age_visit_m, monotone=1), tau=tau2)
```

## Very basic plots

```{r echo=FALSE}
# very basic plots
# plot curves - res option controls whether individual data points are plotted
plot(mform, res=TRUE)
plot(mform, res=FALSE)
```

## Plot as in package vignette

```{r echo=FALSE}
# plot per vignette
p <- plot(mform, legend=TRUE, overlap=15, grid=list(x=15,y=10), col=2, lty=1,ylab="BSID GSV COG", xlab="AGE (MONTHS)")
```

## Custom plot

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="BSID GSV COG", xlab="AGE (MONTHS)", xlim=c(0,42),ylim=c(300,700))
axis(1, at=2:42, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(300,700,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(300,700,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
# axis(3, at=3:19, lwd=0.5, tck=1, cex.axis=0.95, padj=3.65)
```

# BSID_GSV_RC

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
mform <-gcrq(data=ds, bsid_gsv_rc ~ ps(age_visit_m, monotone=1), tau=tau2)
```

## Very basic plots

```{r echo=FALSE}
# very basic plots
# plot curves - res option controls whether individual data points are plotted
plot(mform, res=TRUE)
plot(mform, res=FALSE)
```

## Plot as in package vignette

```{r echo=FALSE}
# plot per vignette
p <- plot(mform, legend=TRUE, overlap=15, grid=list(x=15,y=10), col=2, lty=1,ylab="BSID GSV RC", xlab="AGE (MONTHS)")
```

## Custom plot

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="BSID GSV RC", xlab="AGE (MONTHS)", xlim=c(0,42),ylim=c(300,700))
axis(1, at=2:42, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(300,700,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(300,700,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
# axis(3, at=3:19, lwd=0.5, tck=1, cex.axis=0.95, padj=3.65)
```

# BSID_GSV_EC

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
mform <-gcrq(data=ds, bsid_gsv_ec ~ ps(age_visit_m, monotone=1), tau=tau2)
```

## Very basic plots

```{r echo=FALSE}
# very basic plots
# plot curves - res option controls whether individual data points are plotted
plot(mform, res=TRUE)
plot(mform, res=FALSE)
```

## Plot as in package vignette

```{r echo=FALSE}
# plot per vignette
p <- plot(mform, legend=TRUE, overlap=15, grid=list(x=15,y=10), col=2, lty=1,ylab="BSID GSV EC", xlab="AGE (MONTHS)")
```

## Custom plot

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="BSID GSV EC", xlab="AGE (MONTHS)", xlim=c(0,42),ylim=c(300,700))
axis(1, at=2:42, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(300,700,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(300,700,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
# axis(3, at=3:19, lwd=0.5, tck=1, cex.axis=0.95, padj=3.65)
```

# BSID_GSV_FM

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
mform <-gcrq(data=ds, bsid_gsv_fm ~ ps(age_visit_m, monotone=1), tau=tau2)
```

## Very basic plots

```{r echo=FALSE}
# very basic plots
# plot curves - res option controls whether individual data points are plotted
plot(mform, res=TRUE)
plot(mform, res=FALSE)
```

## Plot as in package vignette

```{r echo=FALSE}
# plot per vignette
p <- plot(mform, legend=TRUE, overlap=15, grid=list(x=15,y=10), col=2, lty=1,ylab="BSID GSV FM", xlab="AGE (MONTHS)")
```

## Custom plot

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="BSID GSV FM", xlab="AGE (MONTHS)", xlim=c(0,42),ylim=c(300,700))
axis(1, at=2:42, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(300,700,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(300,700,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
# axis(3, at=3:19, lwd=0.5, tck=1, cex.axis=0.95, padj=3.65)
```

# BSID_GSV_GM

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
mform <-gcrq(data=ds, bsid_gsv_gm ~ ps(age_visit_m, monotone=1), tau=tau2)
```

## Very basic plots

```{r echo=FALSE}
# very basic plots
# plot curves - res option controls whether individual data points are plotted
plot(mform, res=TRUE)
plot(mform, res=FALSE)
```

## Plot as in package vignette

```{r echo=FALSE}
# plot per vignette
p <- plot(mform, legend=TRUE, overlap=15, grid=list(x=15,y=10), col=2, lty=1,ylab="BSID GSV GM", xlab="AGE (MONTHS)")
```

## Custom plot

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="BSID GSV GM", xlab="AGE (MONTHS)", xlim=c(0,42),ylim=c(300,700))
axis(1, at=2:42, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(300,700,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(300,700,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
# axis(3, at=3:19, lwd=0.5, tck=1, cex.axis=0.95, padj=3.65)
```