---
title: "TODAY Somalogic descriptive analyses"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(SomaDataIO)
library(skimr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY proteomics and metabolomics/Data_raw/WUS-22-001_Somalogic_normalized"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = ""
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = ""
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r, include=FALSE}
# read in data - we want to use the fully processed, normalized file ending in "anmlSMP.adat"
alldata <- read_adat("./WUS-22-001_v4.1_EDTAPlasma.hybNorm.medNormInt.plateScale.calibrate.anmlQC.qcCheck.anmlSMP.adat")
skim(alldata)

```


# Questions



# Results

```{r echo=FALSE}
#kable(t1,caption = "")
```
<br>
