---
title: "TODAY Somalogic Pathway Analyses"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
format:
  html:
    self-contained: true
editor: visual
---

```{r echo=FALSE}
library(clusterProfiler)
library(readxl)
```

# Enrichment

Enrichment analyses were performed on nominally significant proteins using the R package `clusterProfiler` and a gene set ranked by log FC. Entrez gene IDs were used for all annotation. All genes in the `org.Hs.eg.db`

## TODAY proteomics moderated adjusted linear models

```{r}
f = "/Users/timvigers/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/CHCO/Petter Bjornstad/TODAY subaward/Results/TODAY proteomics moderated adjusted linear models.xlsx"
```

### MAC

#### Molecular function

```{r}
# Prepare gene list
mac = read_excel(f,sheet = "MAC_moderated_FDR")
mac = mac[!is.na(mac$EntrezGeneID) & mac$P.Value <= 0.05,]
geneList = mac$logFC
names(geneList) = mac$EntrezGeneID
geneList = sort(geneList, decreasing = TRUE)
# Enrichment
enrich = enrichGO(geneList,OrgDb = "org.Hs.eg.db",ont = "ALL")
```

