---
title: "TODAY Somalogic follow-up analyses"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)
library(beepr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward"
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r}
# Tim's code playground
# Import
load("./Somalogic data raw/soma.Rdata")
load("./Somalogic data raw/analytes.Rdata")
load("./Clinical data/comorb.Rdata")

soma = soma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% 
  mutate(timepoint = row_number()) %>%
  select(releaseid,timepoint,Date.Drawn,seq.10000.28:seq.9999.1)
```

```{r, include=FALSE}
# load somalogic data, with QC samples already excluded
load("./Somalogic data raw/soma.Rdata")

# load analyte info
load("./Somalogic data raw/analytes.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)

# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# find follow-up samples
fup <- soma %>% anti_join(base, soma, by=c("releaseid","Date.Drawn"))

# identify columns corresponding to proteins and convert to numeric
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(base))
base[,seq] <- apply(base[,seq],2,as.numeric)
fup[,seq] <- apply(fup[,seq],2,as.numeric)

# filter out any releaseids that are not in both dataframes
b <- as.data.frame(base$releaseid)
colnames(b) <- "releaseid"
f <- as.data.frame(fup$releaseid)
colnames(f) <- "releaseid"
both <- merge(b,f,by="releaseid",all.x=F,all.y=F)
base <- base %>% filter(releaseid %in% both$releaseid)
base_x <- base
base_x$time <- "B"
fup <- fup %>% filter(releaseid %in% both$releaseid)
fup_x <- fup
fup_x$time <- "F"

# take the difference
deltas <- fup[,seq] - base[,seq]
deltas <- cbind(base$releaseid,deltas)
colnames(deltas)[1] <- "releaseid"
deltas <- merge(deltas, comorb, by="releaseid",all.x=T, all.y=F)

# combine baseline and followup data for participants who have both 
all <- rbind(base_x,fup_x)

# merge in nephropathy data
all <- merge(all, comorb, by="releaseid",all.x=T, all.y=F)
# recode comorbidity variables to character
all$MAC <- ifelse(all$MAC==0,"NO_MAC","MAC")
all$MIC <- ifelse(all$MIC==0,"NO_MIC","MIC")
all$HYP <- ifelse(all$HYP==0,"NO_HYP","HYP")
all$RAPID <- ifelse(all$RAPID==0,"NO_RAPID","RAPID")
all$HTN <- ifelse(all$HTN==0,"NO_HTN","HTN")
all$NEURO <- ifelse(all$NEURO==0,"NO_NEURO","NEURO")
all$RETINO <- ifelse(all$RETINO==0,"NO_RETINO","RETINO")

# log transform
all <- all %>% modify_if(is_seq(names(.)), log)
```

```{r, include=FALSE, cache=TRUE}
# MAC
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(all))
model_data <- cbind(all[,c("releaseid","time","MAC")], all[,seq])
model_data$time <- factor(model_data$time, levels=c("B","F"))
model_data$releaseid <- factor(model_data$releaseid)
model_data$MAC <- factor(model_data$MAC)
seq <- is_seq(names(model_data))
model_data[,seq] <- apply(model_data[,seq],2,as.numeric)
model_data$MAC_by_time <- factor(paste(model_data$MAC,model_data$time,sep="."))
design <- model.matrix(~0+MAC_by_time, data = model_data)
colnames(design) <- levels(model_data$MAC_by_time)
ymat <- t(model_data[,seq])
# estimate correlation between measurements on the same subject
corfit <- duplicateCorrelation(ymat,design,block=model_data$releaseid)
fit <- lmFit(ymat, design, block=model_data$releaseid, correlation=corfit$consensus.correlation)
cm <- makeContrasts(
      delta_MAC_vs_delta_noMAC    = (MAC.F - MAC.B) - (NO_MAC.F - NO_MAC.B), 
      levels=design
)
fit2 <- contrasts.fit(fit, cm)
fit2 <- eBayes(fit2)
results_MAC <- topTable(fit2,coef="delta_MAC_vs_delta_noMAC",number = nrow(ymat))
results_MAC$AptName <- row.names(results_MAC)
results_MAC <- merge(results_MAC,analytes,by="AptName",all.x = T, all.y = F)
results_MAC <- results_MAC[order(results_MAC$P.Value),] 

# MIC
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(all))
model_data <- cbind(all[,c("releaseid","time","MIC")], all[,seq])
model_data$time <- factor(model_data$time, levels=c("B","F"))
model_data$releaseid <- factor(model_data$releaseid)
model_data$MIC <- factor(model_data$MIC)
seq <- is_seq(names(model_data))
model_data[,seq] <- apply(model_data[,seq],2,as.numeric)
model_data$MIC_by_time <- factor(paste(model_data$MIC,model_data$time,sep="."))
design <- model.matrix(~0+MIC_by_time, data = model_data)
colnames(design) <- levels(model_data$MIC_by_time)
ymat <- t(model_data[,seq])
# estimate correlation between measurements on the same subject
corfit <- duplicateCorrelation(ymat,design,block=model_data$releaseid)
fit <- lmFit(ymat, design, block=model_data$releaseid, correlation=corfit$consensus.correlation)
cm <- makeContrasts(
      delta_MIC_vs_delta_noMIC    = (MIC.F - MIC.B) - (NO_MIC.F - NO_MIC.B), 
      levels=design
)
fit2 <- contrasts.fit(fit, cm)
fit2 <- eBayes(fit2)
results_MIC <- topTable(fit2,coef="delta_MIC_vs_delta_noMIC",number = nrow(ymat))
results_MIC$AptName <- row.names(results_MIC)
results_MIC <- merge(results_MIC,analytes,by="AptName",all.x = T, all.y = F)
results_MIC <- results_MIC[order(results_MIC$P.Value),] 

# HYP
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(all))
model_data <- cbind(all[,c("releaseid","time","HYP")], all[,seq])
model_data$time <- factor(model_data$time, levels=c("B","F"))
model_data$releaseid <- factor(model_data$releaseid)
model_data$HYP <- factor(model_data$HYP)
seq <- is_seq(names(model_data))
model_data[,seq] <- apply(model_data[,seq],2,as.numeric)
model_data$HYP_by_time <- factor(paste(model_data$HYP,model_data$time,sep="."))
design <- model.matrix(~0+HYP_by_time, data = model_data)
colnames(design) <- levels(model_data$HYP_by_time)
ymat <- t(model_data[,seq])
# estimate correlation between measurements on the same subject
corfit <- duplicateCorrelation(ymat,design,block=model_data$releaseid)
fit <- lmFit(ymat, design, block=model_data$releaseid, correlation=corfit$consensus.correlation)
cm <- makeContrasts(
      delta_HYP_vs_delta_noHYP    = (HYP.F - HYP.B) - (NO_HYP.F - NO_HYP.B), 
      levels=design
)
fit2 <- contrasts.fit(fit, cm)
fit2 <- eBayes(fit2)
results_HYP <- topTable(fit2,coef="delta_HYP_vs_delta_noHYP",number = nrow(ymat))
results_HYP$AptName <- row.names(results_HYP)
results_HYP <- merge(results_HYP,analytes,by="AptName",all.x = T, all.y = F)
results_HYP <- results_HYP[order(results_HYP$P.Value),] 

# RAPID
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(all))
model_data <- cbind(all[,c("releaseid","time","RAPID")], all[,seq])
model_data$time <- factor(model_data$time, levels=c("B","F"))
model_data$releaseid <- factor(model_data$releaseid)
model_data$RAPID <- factor(model_data$RAPID)
seq <- is_seq(names(model_data))
model_data[,seq] <- apply(model_data[,seq],2,as.numeric)
model_data$RAPID_by_time <- factor(paste(model_data$RAPID,model_data$time,sep="."))
design <- model.matrix(~0+RAPID_by_time, data = model_data)
colnames(design) <- levels(model_data$RAPID_by_time)
ymat <- t(model_data[,seq])
# estimate correlation between measurements on the same subject
corfit <- duplicateCorrelation(ymat,design,block=model_data$releaseid)
fit <- lmFit(ymat, design, block=model_data$releaseid, correlation=corfit$consensus.correlation)
cm <- makeContrasts(
      delta_RAPID_vs_delta_noRAPID    = (RAPID.F - RAPID.B) - (NO_RAPID.F - NO_RAPID.B), 
      levels=design
)
fit2 <- contrasts.fit(fit, cm)
fit2 <- eBayes(fit2)
results_RAPID <- topTable(fit2,coef="delta_RAPID_vs_delta_noRAPID",number = nrow(ymat))
results_RAPID$AptName <- row.names(results_RAPID)
results_RAPID <- merge(results_RAPID,analytes,by="AptName",all.x = T, all.y = F)
results_RAPID <- results_RAPID[order(results_RAPID$P.Value),] 

# HTN
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(all))
model_data <- cbind(all[,c("releaseid","time","HTN")], all[,seq])
model_data$time <- factor(model_data$time, levels=c("B","F"))
model_data$releaseid <- factor(model_data$releaseid)
model_data$HTN <- factor(model_data$HTN)
seq <- is_seq(names(model_data))
model_data[,seq] <- apply(model_data[,seq],2,as.numeric)
model_data$HTN_by_time <- factor(paste(model_data$HTN,model_data$time,sep="."))
design <- model.matrix(~0+HTN_by_time, data = model_data)
colnames(design) <- levels(model_data$HTN_by_time)
ymat <- t(model_data[,seq])
# estimate correlation between measurements on the same subject
corfit <- duplicateCorrelation(ymat,design,block=model_data$releaseid)
fit <- lmFit(ymat, design, block=model_data$releaseid, correlation=corfit$consensus.correlation)
cm <- makeContrasts(
      delta_HTN_vs_delta_noHTN    = (HTN.F - HTN.B) - (NO_HTN.F - NO_HTN.B), 
      levels=design
)
fit2 <- contrasts.fit(fit, cm)
fit2 <- eBayes(fit2)
results_HTN <- topTable(fit2,coef="delta_HTN_vs_delta_noHTN",number = nrow(ymat))
results_HTN$AptName <- row.names(results_HTN)
results_HTN <- merge(results_HTN,analytes,by="AptName",all.x = T, all.y = F)
results_HTN <- results_HTN[order(results_HTN$P.Value),] 

# NEURO
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(all))
model_data <- cbind(all[,c("releaseid","time","NEURO")], all[,seq])
model_data$time <- factor(model_data$time, levels=c("B","F"))
model_data$releaseid <- factor(model_data$releaseid)
model_data$NEURO <- factor(model_data$NEURO)
seq <- is_seq(names(model_data))
model_data[,seq] <- apply(model_data[,seq],2,as.numeric)
model_data$NEURO_by_time <- factor(paste(model_data$NEURO,model_data$time,sep="."))
design <- model.matrix(~0+NEURO_by_time, data = model_data)
colnames(design) <- levels(model_data$NEURO_by_time)
ymat <- t(model_data[,seq])
# estimate correlation between measurements on the same subject
corfit <- duplicateCorrelation(ymat,design,block=model_data$releaseid)
fit <- lmFit(ymat, design, block=model_data$releaseid, correlation=corfit$consensus.correlation)
cm <- makeContrasts(
      delta_NEURO_vs_delta_noNEURO    = (NEURO.F - NEURO.B) - (NO_NEURO.F - NO_NEURO.B), 
      levels=design
)
fit2 <- contrasts.fit(fit, cm)
fit2 <- eBayes(fit2)
results_NEURO <- topTable(fit2,coef="delta_NEURO_vs_delta_noNEURO",number = nrow(ymat))
results_NEURO$AptName <- row.names(results_NEURO)
results_NEURO <- merge(results_NEURO,analytes,by="AptName",all.x = T, all.y = F)
results_NEURO <- results_NEURO[order(results_NEURO$P.Value),] 

# RETINO
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(all))
model_data <- cbind(all[,c("releaseid","time","RETINO")], all[,seq])
model_data$time <- factor(model_data$time, levels=c("B","F"))
model_data$releaseid <- factor(model_data$releaseid)
model_data$RETINO <- factor(model_data$RETINO)
seq <- is_seq(names(model_data))
model_data[,seq] <- apply(model_data[,seq],2,as.numeric)
model_data$RETINO_by_time <- factor(paste(model_data$RETINO,model_data$time,sep="."))
design <- model.matrix(~0+RETINO_by_time, data = model_data)
colnames(design) <- levels(model_data$RETINO_by_time)
ymat <- t(model_data[,seq])
# estimate correlation between measurements on the same subject
corfit <- duplicateCorrelation(ymat,design,block=model_data$releaseid)
fit <- lmFit(ymat, design, block=model_data$releaseid, correlation=corfit$consensus.correlation)
cm <- makeContrasts(
      delta_RETINO_vs_delta_noRETINO    = (RETINO.F - RETINO.B) - (NO_RETINO.F - NO_RETINO.B), 
      levels=design
)
fit2 <- contrasts.fit(fit, cm)
fit2 <- eBayes(fit2)
results_RETINO <- topTable(fit2,coef="delta_RETINO_vs_delta_noRETINO",number = nrow(ymat))
results_RETINO$AptName <- row.names(results_RETINO)
results_RETINO <- merge(results_RETINO,analytes,by="AptName",all.x = T, all.y = F)
results_RETINO <- results_RETINO[order(results_RETINO$P.Value),] 

# write all results to file
wb <- createWorkbook()

addWorksheet(wb,"MAC_moderated_FDR")
writeData(wb,"MAC_moderated_FDR",results_MAC,rowNames = F)

addWorksheet(wb,"MIC_moderated_FDR")
writeData(wb,"MIC_moderated_FDR",results_MIC,rowNames = F)

addWorksheet(wb,"hyperfilt_moderated_FDR")
writeData(wb,"hyperfilt_moderated_FDR",results_HYP,rowNames = F)

addWorksheet(wb,"rapid_moderated_FDR")
writeData(wb,"rapid_moderated_FDR",results_RAPID,rowNames = F)

addWorksheet(wb,"htn_moderated_FDR")
writeData(wb,"htn_moderated_FDR",results_HTN,rowNames = F)

addWorksheet(wb,"neuro_moderated_FDR")
writeData(wb,"neuro_moderated_FDR",results_NEURO,rowNames = F)

addWorksheet(wb,"retino_moderated_FDR")
writeData(wb,"retino_moderated_FDR",results_RETINO,rowNames = F)

saveWorkbook(wb,"./Results/TODAY proteomics moderated t-tests deltas.xlsx",overwrite = TRUE)

```

# Results

## Descriptive statistics

```{r echo=FALSE, include=FALSE}
# add table of count of outcomes
t1data <- all[,c("releaseid","MAC","MIC","HYP","RAPID","NEURO","RETINO")]
t1data <- unique(t1data)
t1data$MAC <- as.factor(t1data$MAC)
t1data$MIC <- as.factor(t1data$MIC)
t1data$HYP <- as.factor(t1data$HYP)
t1data$RAPID <- as.factor(t1data$RAPID)
t1data$NEURO <- as.factor(t1data$NEURO)
t1data$RETINO <- as.factor(t1data$RETINO)
t1 <- CreateTableOne(data=t1data, vars=c("MAC","MIC","HYP","RAPID","NEURO","RETINO"))
t1 <- print(t1)
```

```{r echo=FALSE, include=TRUE}
kable(t1)
```

## Volcano plots

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_MAC[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Macroalbuminuria vs. normoalbuminuria",
                pCutoff = 0.05,
                FCcutoff=0.5,
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_MIC[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Microalbuminuria vs. normoalbuminuria",
                pCutoff = 0.05,
                FCcutoff=0.5,
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_HYP[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Hyperfiltration vs. normofiltration",
                pCutoff = 0.05,
                FCcutoff=0.5,
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_RAPID[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Rapid eGFR decline vs. no rapid eGFR decline",
                pCutoff = 0.05,
                FCcutoff=0.5,
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_HTN[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Hypertension vs. no hypertension",
                pCutoff = 0.05,
                FCcutoff=0.5,
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_NEURO[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Neuropathy vs. no neuropathy",
                pCutoff = 0.05,
                FCcutoff=0.5,
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_RETINO[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Retinopathy vs. no retinopathy",
                pCutoff = 0.05,
                FCcutoff=0.5,
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
beep("complete")
```