---
title: "TODAY Somalogic descriptive analyses"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = ""
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r, include=FALSE}
# load somalogic data, with QC samples already excluded
load("./Somalogic data raw/soma.Rdata")

# load analyte info
load("./Somalogic data raw/analytes.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)

# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# identify columns corresponding to proteins
is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# merge in nephropathy data
base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# are there proteins with low variability?
no_var = caret::nearZeroVar(base[,seq])
# none

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)
```

```{r, include=FALSE}
MIC.OR.MAC_contrast <- ifelse(base$MIC.OR.MAC==1,1,0)
MIC.OR.MAC_contrast <- cbind(rep(1,nrow(base)),MIC.OR.MAC_contrast)

# untargeted metabolites
ymat <- t(base[,seq])
fit <- lmFit(ymat,MIC.OR.MAC_contrast)
fit <- eBayes(fit)
results_MIC.OR.MAC <- topTable(fit,coef = 2,number = nrow(ymat))
results_MIC.OR.MAC$AptName <- row.names(results_MIC.OR.MAC)
results_MIC.OR.MAC <- merge(results_MIC.OR.MAC,analytes,by="AptName",all.x = T, all.y = F)
results_MIC.OR.MAC <- results_MIC.OR.MAC[order(results_MIC.OR.MAC$P.Value),] 
# trying permutation test based adjustment
resT_MIC.OR.MAC<-mt.maxT(ymat,MIC.OR.MAC_contrast[,2])
resT_MIC.OR.MAC$AptName <- row.names(resT_MIC.OR.MAC)
resT_MIC.OR.MAC <- merge(resT_MIC.OR.MAC,analytes,by="AptName",all.x = T, all.y = F)
resT_MIC.OR.MAC <- resT_MIC.OR.MAC[order(resT_MIC.OR.MAC$adjp),] 

resP_MIC.OR.MAC<-mt.minP(ymat,MIC.OR.MAC_contrast[,2])
resP_MIC.OR.MAC$AptName <- row.names(resP_MIC.OR.MAC)
resP_MIC.OR.MAC <- merge(resP_MIC.OR.MAC,analytes,by="AptName",all.x = T, all.y = F)
resP_MIC.OR.MAC <- resP_MIC.OR.MAC[order(resP_MIC.OR.MAC$adjp),] 
ymat <- NULL
fit <- NULL
```

# Results

```{r echo=FALSE}

```

