---
title: "TODAY adenine analyses"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = ""
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r, include=FALSE}
# load urine and plasma data
load("./Metabolomic data/urine.Rdata")
load("./Metabolomic data/plasma.Rdata")
urine$Date.Drawn <- as.Date(urine$Date.Drawn,format = "%m/%d/%Y")
plasma$Date.Drawn <- as.Date(plasma$Date.Drawn,format = "%m/%d/%Y")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# take only the baseline samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
urine_base <- urine %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)
plasma_base <- plasma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)



# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# merge in nephropathy data
base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# are there proteins with low variability?
no_var = caret::nearZeroVar(base[,seq])
# none

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)
```

```{r, include=FALSE}
# microalbuminuria or macroalbuminuria
MIC.OR.MAC_contrast <- ifelse(base$MIC.OR.MAC==1,1,0)
MIC.OR.MAC_contrast <- cbind(rep(1,nrow(base)),MIC.OR.MAC_contrast)
# moderated t-tests with and without FDR adjustment
ymat <- t(base_log[,seq])
fit <- lmFit(ymat,MIC.OR.MAC_contrast)
fit <- eBayes(fit)
results_MIC.OR.MAC <- topTable(fit,coef = 2,number = nrow(ymat))
results_MIC.OR.MAC$AptName <- row.names(results_MIC.OR.MAC)
results_MIC.OR.MAC <- merge(results_MIC.OR.MAC,analytes,by="AptName",all.x = T, all.y = F)
results_MIC.OR.MAC <- results_MIC.OR.MAC[order(results_MIC.OR.MAC$P.Value),] 
# permutation test based adjustment
# maxT
# resT_MIC.OR.MAC<-mt.maxT(ymat,MIC.OR.MAC_contrast[,2])
# resT_MIC.OR.MAC$AptName <- row.names(resT_MIC.OR.MAC)
# resT_MIC.OR.MAC <- merge(resT_MIC.OR.MAC,analytes,by="AptName",all.x = T, all.y = F)
# resT_MIC.OR.MAC <- resT_MIC.OR.MAC[order(resT_MIC.OR.MAC$adjp),] 
# minP
# resP_MIC.OR.MAC<-mt.minP(ymat,MIC.OR.MAC_contrast[,2])
# resP_MIC.OR.MAC$AptName <- row.names(resP_MIC.OR.MAC)
# resP_MIC.OR.MAC <- merge(resP_MIC.OR.MAC,analytes,by="AptName",all.x = T, all.y = F)
# resP_MIC.OR.MAC <- resP_MIC.OR.MAC[order(resP_MIC.OR.MAC$adjp),] 
ymat <- NULL
fit <- NULL

# MAC alone
MAC_contrast <- ifelse(base$MAC==1,1,0)
MAC_contrast <- cbind(rep(1,nrow(base)),MAC_contrast)
# moderated t-tests with and without FDR adjustment
ymat <- t(base_log[,seq])
fit <- lmFit(ymat,MAC_contrast)
fit <- eBayes(fit)
results_MAC <- topTable(fit,coef = 2,number = nrow(ymat))
results_MAC$AptName <- row.names(results_MAC)
results_MAC <- merge(results_MAC,analytes,by="AptName",all.x = T, all.y = F)
results_MAC <- results_MAC[order(results_MAC$P.Value),] 

# MIC alone
MIC_contrast <- ifelse(base$MIC==1,1,0)
MIC_contrast <- cbind(rep(1,nrow(base)),MIC_contrast)
# moderated t-tests with and without FDR adjustment
ymat <- t(base_log[,seq])
fit <- lmFit(ymat,MIC_contrast)
fit <- eBayes(fit)
results_MIC <- topTable(fit,coef = 2,number = nrow(ymat))
results_MIC$AptName <- row.names(results_MIC)
results_MIC <- merge(results_MIC,analytes,by="AptName",all.x = T, all.y = F)
results_MIC <- results_MIC[order(results_MIC$P.Value),] 

# hyperfiltration
hyperfilt_contrast <- ifelse(base$HYP==1,1,0)
hyperfilt_contrast <- cbind(rep(1,nrow(base)),hyperfilt_contrast)
hyperfilt_contrast <- hyperfilt_contrast[!is.na(hyperfilt_contrast[,2]),]
# moderated t-tests with and without FDR adjustment
y <- base_log %>% filter(!is.na(base_log$HYP))
ymat <- t(y[,seq])
fit <- lmFit(ymat,hyperfilt_contrast)
fit <- eBayes(fit)
results_hyperfilt <- topTable(fit,coef = 2,number = nrow(ymat))
results_hyperfilt$AptName <- row.names(results_hyperfilt)
results_hyperfilt <- merge(results_hyperfilt,analytes,by="AptName",all.x = T, all.y = F)
results_hyperfilt <- results_hyperfilt[order(results_hyperfilt$P.Value),] 
# permutation test based adjustment
# maxT
# resT_hyperfilt<-mt.maxT(ymat,hyperfilt_contrast[,2])
# resT_hyperfilt$AptName <- row.names(resT_hyperfilt)
# resT_hyperfilt <- merge(resT_hyperfilt,analytes,by="AptName",all.x = T, all.y = F)
# resT_hyperfilt <- resT_hyperfilt[order(resT_hyperfilt$adjp),] 
# minP
# resP_hyperfilt<-mt.minP(ymat,hyperfilt_contrast[,2])
# resP_hyperfilt$AptName <- row.names(resP_hyperfilt)
# resP_hyperfilt <- merge(resP_hyperfilt,analytes,by="AptName",all.x = T, all.y = F)
# resP_hyperfilt <- resP_hyperfilt[order(resP_hyperfilt$adjp),] 
ymat <- NULL
fit <- NULL

# rapid eGFR decline
rapid_contrast <- ifelse(base$RAPID==1,1,0)
rapid_contrast <- cbind(rep(1,nrow(base)),rapid_contrast)
rapid_contrast <- rapid_contrast[!is.na(rapid_contrast[,2]),]
# moderated t-tests with and without FDR adjustment
y <- base_log %>% filter(!is.na(base_log$RAPID))
ymat <- t(y[,seq])
fit <- lmFit(ymat,rapid_contrast)
fit <- eBayes(fit)
results_rapid <- topTable(fit,coef = 2,number = nrow(ymat))
results_rapid$AptName <- row.names(results_rapid)
results_rapid <- merge(results_rapid,analytes,by="AptName",all.x = T, all.y = F)
results_rapid <- results_rapid[order(results_rapid$P.Value),] 
# permutation test based adjustment
# maxT
# resT_rapid<-mt.maxT(ymat,rapid_contrast[,2])
# resT_rapid$AptName <- row.names(resT_rapid)
# resT_rapid <- merge(resT_rapid,analytes,by="AptName",all.x = T, all.y = F)
# resT_rapid <- resT_rapid[order(resT_rapid$adjp),] 
# minP
# resP_rapid<-mt.minP(ymat,rapid_contrast[,2])
# resP_rapid$AptName <- row.names(resP_rapid)
# resP_rapid <- merge(resP_rapid,analytes,by="AptName",all.x = T, all.y = F)
# resP_rapid <- resP_rapid[order(resP_rapid$adjp),] 
ymat <- NULL
fit <- NULL

# hypertension
htn_contrast <- ifelse(base$HTN==1,1,0)
htn_contrast <- cbind(rep(1,nrow(base)),htn_contrast)
htn_contrast <- htn_contrast[!is.na(htn_contrast[,2]),]
# moderated t-tests with and without FDR adjustment
y <- base_log %>% filter(!is.na(base_log$HTN))
ymat <- t(y[,seq])
fit <- lmFit(ymat,htn_contrast)
fit <- eBayes(fit)
results_htn <- topTable(fit,coef = 2,number = nrow(ymat))
results_htn$AptName <- row.names(results_htn)
results_htn <- merge(results_htn,analytes,by="AptName",all.x = T, all.y = F)
results_htn <- results_htn[order(results_htn$P.Value),] 
# permutation test based adjustment
# maxT
# resT_htn<-mt.maxT(ymat,htn_contrast[,2])
# resT_htn$AptName <- row.names(resT_htn)
# resT_htn <- merge(resT_htn,analytes,by="AptName",all.x = T, all.y = F)
# resT_htn <- resT_htn[order(resT_htn$adjp),] 
# minP
# resP_htn<-mt.minP(ymat,htn_contrast[,2])
# resP_htn$AptName <- row.names(resP_htn)
# resP_htn <- merge(resP_htn,analytes,by="AptName",all.x = T, all.y = F)
# resP_htn <- resP_htn[order(resP_htn$adjp),] 
ymat <- NULL
fit <- NULL

# neuropathy
neuro_contrast <- ifelse(base$NEURO==1,1,0)
neuro_contrast <- cbind(rep(1,nrow(base)),neuro_contrast)
neuro_contrast <- neuro_contrast[!is.na(neuro_contrast[,2]),]
# moderated t-tests with and without FDR adjustment
y <- base_log %>% filter(!is.na(base_log$NEURO))
ymat <- t(y[,seq])
fit <- lmFit(ymat,neuro_contrast)
fit <- eBayes(fit)
results_neuro <- topTable(fit,coef = 2,number = nrow(ymat))
results_neuro$AptName <- row.names(results_neuro)
results_neuro <- merge(results_neuro,analytes,by="AptName",all.x = T, all.y = F)
results_neuro <- results_neuro[order(results_neuro$P.Value),] 
# permutation test based adjustment
# maxT
# resT_neuro<-mt.maxT(ymat,neuro_contrast[,2])
# resT_neuro$AptName <- row.names(resT_neuro)
# resT_neuro <- merge(resT_neuro,analytes,by="AptName",all.x = T, all.y = F)
# resT_neuro <- resT_neuro[order(resT_neuro$adjp),] 
# minP
# resP_neuro<-mt.minP(ymat,neuro_contrast[,2])
# resP_neuro$AptName <- row.names(resP_neuro)
# resP_neuro <- merge(resP_neuro,analytes,by="AptName",all.x = T, all.y = F)
# resP_neuro <- resP_neuro[order(resP_neuro$adjp),] 
ymat <- NULL
fit <- NULL

# retinopathy
retino_contrast <- ifelse(base$RETINO==1,1,0)
retino_contrast <- cbind(rep(1,nrow(base)),retino_contrast)
retino_contrast <- retino_contrast[!is.na(retino_contrast[,2]),]
# moderated t-tests with and without FDR adjustment
y <- base_log %>% filter(!is.na(base_log$RETINO))
ymat <- t(y[,seq])
fit <- lmFit(ymat,retino_contrast)
fit <- eBayes(fit)
results_retino <- topTable(fit,coef = 2,number = nrow(ymat))
results_retino$AptName <- row.names(results_retino)
results_retino <- merge(results_retino,analytes,by="AptName",all.x = T, all.y = F)
results_retino <- results_retino[order(results_retino$P.Value),] 
# permutation test based adjustment
# maxT
# resT_retino<-mt.maxT(ymat,retino_contrast[,2])
# resT_retino$AptName <- row.names(resT_retino)
# resT_retino <- merge(resT_retino,analytes,by="AptName",all.x = T, all.y = F)
# resT_retino <- resT_retino[order(resT_retino$adjp),] 
# minP
# resP_retino<-mt.minP(ymat,retino_contrast[,2])
# resP_retino$AptName <- row.names(resP_retino)
# resP_retino <- merge(resP_retino,analytes,by="AptName",all.x = T, all.y = F)
# resP_retino <- resP_retino[order(resP_retino$adjp),] 
ymat <- NULL
fit <- NULL

# write all results to file
wb <- createWorkbook()

addWorksheet(wb,"MIC.OR.MAC_moderated_FDR")
writeData(wb,"MIC.OR.MAC_moderated_FDR",results_MIC.OR.MAC,rowNames = F)
# addWorksheet(wb,"MIC.OR.MAC_moderated_maxT")
# writeData(wb,"MIC.OR.MAC_moderated_maxT",resT_MIC.OR.MAC,rowNames = F)
# addWorksheet(wb,"MIC.OR.MAC_moderated_minP")
# writeData(wb,"MIC.OR.MAC_moderated_minP",resP_MIC.OR.MAC,rowNames = F)

addWorksheet(wb,"MAC_moderated_FDR")
writeData(wb,"MAC_moderated_FDR",results_MAC,rowNames = F)

addWorksheet(wb,"MIC_moderated_FDR")
writeData(wb,"MIC_moderated_FDR",results_MIC,rowNames = F)

addWorksheet(wb,"hyperfilt_moderated_FDR")
writeData(wb,"hyperfilt_moderated_FDR",results_hyperfilt,rowNames = F)
# addWorksheet(wb,"hyperfilt_moderated_maxT")
# writeData(wb,"hyperfilt_moderated_maxT",resT_hyperfilt,rowNames = F)
# addWorksheet(wb,"hyperfilt_moderated_minP")
# writeData(wb,"hyperfilt_moderated_minP",resP_hyperfilt,rowNames = F)

addWorksheet(wb,"rapid_moderated_FDR")
writeData(wb,"rapid_moderated_FDR",results_rapid,rowNames = F)
# addWorksheet(wb,"rapid_moderated_maxT")
# writeData(wb,"rapid_moderated_maxT",resT_rapid,rowNames = F)
# addWorksheet(wb,"rapid_moderated_minP")
# writeData(wb,"rapid_moderated_minP",resP_rapid,rowNames = F)

addWorksheet(wb,"htn_moderated_FDR")
writeData(wb,"htn_moderated_FDR",results_htn,rowNames = F)
# addWorksheet(wb,"htn_moderated_maxT")
# writeData(wb,"htn_moderated_maxT",resT_htn,rowNames = F)
# addWorksheet(wb,"htn_moderated_minP")
# writeData(wb,"htn_moderated_minP",resP_htn,rowNames = F)

addWorksheet(wb,"neuro_moderated_FDR")
writeData(wb,"neuro_moderated_FDR",results_neuro,rowNames = F)
# addWorksheet(wb,"neuro_moderated_maxT")
# writeData(wb,"neuro_moderated_maxT",resT_neuro,rowNames = F)
# addWorksheet(wb,"neuro_moderated_minP")
# writeData(wb,"neuro_moderated_minP",resP_neuro,rowNames = F)

addWorksheet(wb,"retino_moderated_FDR")
writeData(wb,"retino_moderated_FDR",results_retino,rowNames = F)
# addWorksheet(wb,"retino_moderated_maxT")
# writeData(wb,"retino_moderated_maxT",resT_retino,rowNames = F)
# addWorksheet(wb,"retino_moderated_minP")
# writeData(wb,"retino_moderated_minP",resP_retino,rowNames = F)

saveWorkbook(wb,"./Results/TODAY proteomics moderated t-tests.xlsx",overwrite = TRUE)

```

# Results

## Descriptive statistics

```{r echo=FALSE, include=FALSE}
# add table of count of outcomes
t1data <- base
t1data$MIC.OR.MAC <- as.factor(t1data$MIC.OR.MAC)
t1data$MAC <- as.factor(t1data$MAC)
t1data$MIC <- as.factor(t1data$MIC)
t1data$HYP <- as.factor(t1data$HYP)
t1data$RAPID <- as.factor(t1data$RAPID)
t1data$NEURO <- as.factor(t1data$NEURO)
t1data$RETINO <- as.factor(t1data$RETINO)
t1 <- CreateTableOne(data=t1data, vars=c("MIC.OR.MAC","MAC","MIC","HYP","RAPID","NEURO","RETINO"))
t1 <- print(t1)
```

```{r echo=FALSE, include=TRUE}
kable(t1)
```

## Volcano plots

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_MIC.OR.MAC[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Micro/macroalbuminuria vs. normoalbuminuria",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_MAC[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Macroalbuminuria vs. normoalbuminuria",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_MIC[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Microalbuminuria vs. normoalbuminuria",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_hyperfilt[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Hyperfiltration vs. normofiltration",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_rapid[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Rapid eGFR decline vs. no rapid eGFR decline",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_htn[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Hypertension vs. no hypertension",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.7,0.7),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_neuro[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Neuropathy vs. no neuropathy",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_retino[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Retinopathy vs. no retinopathy",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```