---
title: "TODAY Somalogic descriptive analyses"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(SomaDataIO)
library(skimr)
library(SmartEDA)
library(factoextra)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY proteomics and metabolomics/Data_raw/WUS-22-001_Somalogic_normalized"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY proteomics and metabolomics/Data_raw/WUS-22-001_Somalogic_normalized"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = ""
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r, include=FALSE}
# read in data - we want to use the fully processed, normalized file ending in "anmlSMP.adat"
alldata <- read_adat("./WUS-22-001_v4.1_EDTAPlasma.hybNorm.medNormInt.plateScale.calibrate.anmlQC.qcCheck.anmlSMP.adat")
```

```{r, include=FALSE}
# things to look at - before we have any of the clinical data
# eventually it would be good to look at distributions by sex, etc.

# number of missing
# distributions
# PCA
```

# Questions/comments

- There do not appear to be any missing values in the proteomics variables.

# Results

## Distributions

```{r echo=FALSE}
#ExpData(data=alldata,type=2,fun=c("mean","median","var"))
plot1 <- ExpNumViz(alldata,target = NULL)
plot1
```

```{r echo=FALSE}
res.pca <- prcomp(alldata[,38:7633], scale.=TRUE)
fviz_eig(res.pca)
fviz_pca_ind(res.pca)

# loadings on the first 2 PCs
loadings <- res.pca$rotation[,1:2]
# need to merge back with the protein information
```
