---
title: "TODAY Somalogic and miRNA overlap"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = ""
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r, include=FALSE}
# load somalogic data, with QC samples already excluded
load("./Somalogic data raw/soma.Rdata")

# load analyte info
load("./Somalogic data raw/analytes.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# load baseline risk factors
load("./Clinical data/TODAY/baserisk.Rdata")

# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)

# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# read in miRNA samples
miRNA <- read.csv("./miRNA/TODAY groups 1-3 M00 visit.csv")
miRNA$releaseid <- miRNA$Release.ID

# check for overlap
in_soma <- as.data.frame(base[,c("releaseid")])
in_soma$in_soma <- 1
names(in_soma) <- c("releaseid","in_soma")
in_miRNA <- as.data.frame(miRNA$releaseid)
in_miRNA$in_miRNA <- 1
names(in_miRNA) <- c("releaseid","in_miRNA")

merged <- merge(in_soma, in_miRNA, by="releaseid",all.x = T, all.y = T)

table(merged$in_soma)
table(merged$in_miRNA)
table(merged$in_soma, merged$in_miRNA)

```
