---
title: "eGFR vs. mGFR"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(dplyr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

home_dir = ifelse(.Platform$OS.type != "unix","E:/Petter Bjornstad/eGFR vs mGFR/Data raw",
                  "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects")
knitr::opts_knit$set(root.dir = home_dir)

```

```{r, include=FALSE}
# read in data

###############
#  CROCODILE  #
###############

# CYSTATIN-C IS CURRENTLY MISSING SO SET TO NA - WILL NEED TO FIX THIS LATER

# CROCODILE
crocodile <- read.csv("./CROCODILE-EGFRVsMGFR_DATA_2022-02-25_1840.csv")
crocodile$gfr <- crocodile$gfr_raw
crocodile$gfr_raw <- NULL
crocodile$age <- crocodile$age_consent
crocodile$age_consent <- NULL
crocodile$sex_MF <- ifelse(crocodile$sex==1,"M",
                           ifelse(!is.na(crocodile$sex),"F",NA))
crocodile$sex <- NULL
# did anyone check more than one race/ethnicity category
crocodile$race_sum <- rowSums(crocodile[,c("race___1","race___2","race___3","race___4","race___5","race___6","race___7")],na.rm = T)
# create new race/ethnicity variable
# anyone who checked Hispanic ethnicity will be considered Hispanic
crocodile$race_eth <- ifelse(crocodile$ethnicity___1==1,"Hispanic/Latino",
                             ifelse(crocodile$race_sum>1,"Other",
                                    ifelse(crocodile$race___1==1,"American Indian/Alaska Native",
                                           ifelse(crocodile$race___2==1,"Asian",
                                                  ifelse(crocodile$race___3==1,"Hawaiian/Pacific Islander",
                                                    ifelse(crocodile$race___4==1,"Black/African American",
                                                         ifelse(crocodile$race___5==1,"White",
                                                                ifelse(crocodile$race___6==1,"Other","Unknown"))))))))
crocodile <- crocodile %>% select(-c(ethnicity___1,ethnicity___2,ethnicity___3,race___1,race___2,race___3,race___4,race___5,
                                     race___6,race___7,race_other,race_sum))
crocodile$clamp_weight <- crocodile$clamp_wt
crocodile$clamp_wt <- NULL
crocodile$clamp_height <- crocodile$clamp_ht
crocodile$clamp_ht <- NULL
crocodile$leanmass_kg <- NULL
crocodile$fatmass_kg <- NULL
crocodile$clamp_sbp <- crocodile$visit_sbp
crocodile$clamp_dbp <- crocodile$visit_dbp
crocodile$clamp_map <- crocodile$phys_map
crocodile$visit_dbp <- NULL
crocodile$visit_dbp <- NULL
crocodile$phys_map <- NULL
crocodile$length_of_diabetes <- crocodile$diabetes_duration
crocodile$diabetes_duration <- NULL
crocodile$fbg <- crocodile$bl_bg
crocodile$bl_bg <- NULL
crocodile$hba1c <- crocodile$bl_a1c
crocodile$bl_a1c <- NULL
crocodile$serum_creatinine <- crocodile$bl_creatinine_s
crocodile$bl_creatinine_s <- NULL
crocodile$cystatin_c <- NA
crocodile$clamp_acr_baseline <- crocodile$bl_uacr
crocodile$bl_uacr <- NULL

############
#  CASPER  #
############

# CASPER
casper <-  read.csv("./CASPER-EGFRVsMGFR_DATA_2022-02-25_1839.csv")
casper$age <- casper$age_current
casper$age_current <- NULL
casper$sex_MF <- ifelse(casper$gender==1,"M",
                           ifelse(!is.na(casper$gender),"F",NA))
casper$gender <- NULL
# did anyone check more than one race/ethnicity category - yes, 2 people
casper$race_sum <- rowSums(casper[,c("race___1","race___2","race___3","race___4","race___5","race___6","race___7")],na.rm = T)
# create new race/ethnicity variable
# anyone who checked Hispanic ethnicity will be considered Hispanic
casper$race_eth <- ifelse(casper$ethnicity___1==1,"Hispanic/Latino",
                             ifelse(casper$race_sum>1,"Other",
                                    ifelse(casper$race___1==1,"American Indian/Alaska Native",
                                           ifelse(casper$race___2==1,"Asian",
                                                  ifelse(casper$race___3==1,"Hawaiian/Pacific Islander",
                                                    ifelse(casper$race___4==1,"Black/African American",
                                                         ifelse(casper$race___5==1,"White",
                                                                ifelse(casper$race___6==1,"Other","Unknown"))))))))
casper <- casper %>% select(-c(ethnicity___1,ethnicity___2,ethnicity___3,race___1,race___2,race___3,race___4,race___5,
                                     race___6,race___7,other_races,race_sum))
casper$leanmass_percent <- casper$lean_mass
casper$bodyfat_percent <- casper$body_fat
casper$lean_kg <- NULL
casper$lean_mass <- NULL
casper$fat_kg <- NULL
casper$body_fat <- NULL
casper$hba1c <- casper$clamp_a1c
casper$clamp_a1c <- NULL

############
#  COFFEE  #
############

# COFFEE - get DXA from CASEPER
coffee <- read.csv("./COFFEE-EGFRVsMGFR_DATA_2022-02-25_1841.csv")
coffee_dxa <- read.csv("./CASPER-BaselineCOFFEEDXAs_DATA_2022-02-25_1837.csv")
# get coffee IDs for merging with other COFFEE data
link <-  read.csv("./coffee casper link.csv")
link$subject_id <- link$ID.CASPER
coffee_dxa <- merge(coffee_dxa,link,by="subject_id",all.x = T, all.y = T)
coffee_dxa <- coffee_dxa %>% select(!(c(subject_id,ID.CASPER)))
coffee_dxa$subject_id <- coffee_dxa$ID.COFFEE
coffee_dxa <- coffee_dxa %>% select(!(ID.COFFEE))
coffee <- merge(coffee,coffee_dxa,by="subject_id",all.x = T,all.y = T)
coffee$gfr <- coffee$gfr_abs
coffee$gfr_abs <- NULL
coffee$age <- coffee$age_current
coffee$age_current <- NULL
coffee$sex_MF <- ifelse(coffee$gender==1,"M",
                           ifelse(!is.na(coffee$gender),"F",NA))
coffee$gender <- NULL
# did anyone check more than one race/ethnicity category 
coffee$race_sum <- rowSums(coffee[,c("race___1","race___2","race___3","race___4","race___5","race___6","race___7")],na.rm = T)
coffee$leanmass_percent <- coffee$lean_mass
coffee$bodyfat_percent <- coffee$body_fat
coffee$lean_kg <- NULL
coffee$lean_mass <- NULL
coffee$fat_kg <- NULL
coffee$body_fat <- NULL

################
#  RENAL-HEIR  #
################

# RENAL-HEIR
renal_heir <- read.csv("./RENALHEIR-EGFRVsMGFR_DATA_2022-02-25_1841.csv")
renal_heir$age <- renal_heir$age_current
renal_heir$age_current <- NULL
renal_heir$sex_MF <- ifelse(renal_heir$gender==1,"M",
                           ifelse(!is.na(renal_heir$gender),"F",NA))
renal_heir$gender <- NULL
# did anyone check more than one race/ethnicity category - yes, 4 people
renal_heir$race_sum <- rowSums(renal_heir[,c("race___1","race___2","race___3","race___4","race___5","race___6","race___7")],na.rm = T)
renal_heir$leanmass_percent <- renal_heir$lean_mass
renal_heir$bodyfat_percent <- renal_heir$body_fat
renal_heir$lean_kg <- NULL
renal_heir$lean_mass <- NULL
renal_heir$fat_kg <- NULL
renal_heir$body_fat <- NULL

############
#  IMPROVE #
############

# IMPROVE
improve <- read.csv("./IMPROVET2D-EGFRVsMGFR_DATA_2022-02-25_1842.csv")
improve$age <- improve$age_current
improve$age_current <- NULL
improve$sex_MF <- ifelse(improve$gender==1,"M",
                           ifelse(!is.na(improve$gender),"F",NA))
improve$gender <- NULL
# did anyone check more than one race/ethnicity category - yes, 1 person
improve$race_sum <- rowSums(improve[,c("race___1","race___2","race___3","race___4","race___5","race___6","race___7")],na.rm = T)
improve$leanmass_percent <- improve$lean_mass
improve$bodyfat_percent <- improve$body_fat
improve$lean_kg <- NULL
improve$lean_mass <- NULL
improve$fat_kg <- NULL
improve$body_fat <- NULL
improve$hba1c <- improve$mmtt_hba1c_base
improve$mmtt_hba1c_base <- NULL

############
#   PGN    #
############

# PGN
# for now, we'll exclude PGN, since GFR measures haven't been received yet
pgn <- read.csv("./PENGUIN-EGFRVsMGFR_DATA_2022-02-25_1843.csv")
pgn$gfr <- as.numeric(pgn$gfr)
pgn$age <- pgn$age_consent
pgn$age_consent <- NULL
pgn$sex_MF <- ifelse(pgn$sex==2,"M",
                           ifelse(!is.na(pgn$sex),"F",NA))
pgn$sex <- NULL
# did anyone check more than one race/ethnicity category
pgn$race_sum <- rowSums(pgn[,c("race___1","race___2","race___3","race___4","race___5","race___6","race___7")],na.rm = T)
pgn$clamp_weight <- pgn$clamp_wt
pgn$clamp_wt <- NULL
pgn$clamp_height <- pgn$clamp_ht
pgn$clamp_ht <- NULL
pgn$leanmass_kg <- NULL
pgn$fatmass_kg <- NULL
pgn$clamp_sbp <- pgn$visit_sbp
pgn$clamp_dbp <- pgn$visit_dbp
pgn$clamp_map <- pgn$visit_map
pgn$visit_dbp <- NULL
pgn$visit_dbp <- NULL
pgn$visit_map <- NULL
pgn$fbg <- pgn$bl_bg
pgn$bl_bg <- NULL
pgn$hba1c <- pgn$bl_a1c
pgn$bl_a1c <- NULL
pgn$serum_creatinine <- pgn$bl_creatinine_s
pgn$bl_creatinine_s <- NULL
pgn$cystatin_c <- pgn$bl_cystatin_c_s
pgn$bl_cystatin_c_s <- NULL
pgn$clamp_acr_baseline <- pgn$bl_uacr
pgn$bl_uacr <- NULL

############
#   BMT    #
############

# BMT
bmt <- read.csv("./177844RenalBloodFlow-EGFRVsMGFR_DATA_2022-02-25_1843.csv")
bmt$gfr <- bmt$igfr_ab
bmt$igfr_ab <- NULL
bmt$sex_MF <- ifelse(bmt$sex==2,"M",
                           ifelse(!is.na(bmt$sex),"F",NA))
# did anyone check more than one race/ethnicity category
#bmt$race_sum <- rowSums(bmt[,c("race___1","race___2","race___3","race___4","race___5","race___6","race___7")],na.rm = T)
bmt$clamp_weight <- bmt$wt
bmt$wt <- NULL
bmt$clamp_height <- bmt$ht
bmt$ht <- NULL
bmt$leanmass_percent <- NA
bmt$bodyfat_percent <- NA
bmt$clamp_sbp <- bmt$sbp
bmt$clamp_dbp <- bmt$dbp
bmt$clamp_map <- ((2*bmt$clamp_dbp) + bmt$clamp_sbp)/3
bmt$sbp <- NULL
bmt$dbp <- NULL
bmt$fbg <- bmt$sglu
bmt$sglu <- NULL
bmt$serum_creatinine <- bmt$screat
bmt$screat <- NULL
bmt$cystatin_c <- bmt$scystc
bmt$scystc <- NULL
bmt$clamp_acr_baseline
# read in race/ethnicity
bmt_race_eth <- read.csv("./BMT race_eth.csv")
bmt <- merge(bmt,bmt_race_eth,by="record_id",all.x = T, all.y = T)

################
# COMBINE DATA #
################

# combine all datasets
alldata <- rbind(crocodile,casper,coffee,improve,renal_heir,pgn,bmt)

# calculate BMI (percentile and Z-score?)


```

# Background

# Methods

# Results

```{r echo=FALSE}
kable(t1,caption = "")
```

