---
title: "1 hour OGTT glucose"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(rspiro)
library(dplyr)
library(childsds)
library(tableone)

# read in separate data files

ogtt <- read.csv("E:\\Christine Chan\\1 hour OGTT in CFRD\\Data_raw\\ogtt.csv")
pft <- read.csv("E:\\Christine Chan\\1 hour OGTT in CFRD\\Data_raw\\pfts.csv")
a1c <- read.csv("E:\\Christine Chan\\1 hour OGTT in CFRD\\Data_raw\\a1c.csv")
demo <- read.csv("E:\\Christine Chan\\1 hour OGTT in CFRD\\Data_raw\\demographics.csv")

# checking for dups
t <- ogtt[,c("MRN","FName","LName")]
t <- unique(t)
ct <- t %>% group_by(LName,FName) %>% count(unique(MRN))

# merge ogtt and demo
demo$FName <- NULL
demo$LName <- NULL
ogtt_demo <- merge(ogtt,demo,by="MRN",all.x = T, all.y = T)

# merge ogtt, demo, and A1c
ogtt_demo$Date <- ogtt_demo$Date.of.OGTT
ogtt_demo$Date.of.OGTT <- NULL
a1c$Date.of.OGTT <- NULL
a1c$Days.Between.A1C.and.OGTT <- NULL
a1c$Date <- a1c$Date.of.A1C
a1c$Date.of.A1C  <- NULL
a1c$FName <- NULL
a1c$LName <- NULL
ogtt_demo_a1c <- merge(ogtt_demo,a1c,by=c("MRN","Date"),all.x=T,all.y=T)

# add in PFTs
pft$Date.of.OGTT <- NULL
pft$FName <- NULL
pft$LName <- NULL
pft$Date <- pft$Date.of.PFT
pft$Date.of.PFT <- NULL
# get predicted spirometry values
pft$FVC...Pred <- NULL
pft$FEV1...Pred <- NULL
pft$FEF.25.75...Pred <- NULL
pft$DOB <- as.Date(as.character(pft$DOB),format="%m/%d/%Y")
pft$ht_m <- pft$Height..cm./100
sex <- demo[,c("MRN","Sex")]
pft <- merge(pft, sex, by="MRN",all.x=T,all.y = F)
pft$sexnum <- ifelse(pft$Sex=="Male",1,2)
pft$FEV1.pred <- pred_GLI(age=pft$Age.at.PFT,height=pft$ht_m,gender=pft$sexnum,param="FEV1")
pft$FVC.pred <- pred_GLI(age=pft$Age.at.PFT,height=pft$ht_m,gender=pft$sexnum,param="FVC")
pft$FEF.25.75.pred <- pred_GLI(age=pft$Age.at.PFT,height=pft$ht_m,gender=pft$sexnum,param="FEF2575")
pft$FEV1.per.pred <- (pft$FEV1.Raw / pft$FEV1.pred)*100
pft$FVC.per.pred <- (pft$FVC.Raw / pft$FVC.pred)*100
pft$FEF.25.75.per.pred <- (pft$FEF.25.75.Raw / pft$FEF.25.75.pred)*100
pft$Sex <- NULL
alldata <- merge(ogtt_demo_a1c,pft,by=c("MRN","Date"),all.x=T,all.y=T)

# merge back all baseline characteristics
d <- alldata[,c("MRN","FName","LName","Sex","Race","Latino.a.","Mutation.1","Mutation.2")]
d <- d[!is.na(d$FName),]
d <- unique(d)
alldata$FName <- NULL
alldata$Latino.a. <- NULL
alldata$LName <- NULL
alldata$Sex <- NULL
alldata$Race <- NULL
alldata$Mutation.1 <- NULL
alldata$Mutation.2 <- NULL
alldata <- merge(alldata,d,by="MRN",all.x = T,all.y = T)

# checking for dups
t <- alldata[,c("MRN","FName","LName")]
t <- unique(t)
ct <- t %>% group_by(LName,FName) %>% count(unique(MRN))

# find first OGTT
o <- alldata[!is.na(alldata$Age.At.Test..years.) & !is.na(alldata$X1.hour.Glucose),c("MRN","Date")]
o <- o[order(o$MRN,o$Date),]
o <- o %>% group_by(MRN) %>% filter(row_number() == 1)
colnames(o) <- c("MRN","Date of first OGTT")
alldata <- merge(alldata,o,by="MRN",all.x = T,all.y = T)
alldata <- alldata[!is.na(alldata$`Date of first OGTT`),]

# remove all visits before first OGTT
alldata$Date <- as.Date(as.character(alldata$Date),format="%m/%d/%Y")
alldata$`Date of first OGTT` <- as.Date(as.character(alldata$`Date of first OGTT`),format="%m/%d/%Y")
alldata <- alldata[alldata$Date >= alldata$`Date of first OGTT`,]

# calculate BMI
alldata$BMI <- alldata$Weight..kg./((alldata$Height..cm./100)^2)

# reorder columns
colorder <- c("MRN","FName","LName","Sex","Race","Latino.a.","Mutation.1","Mutation.2","Date of first OGTT",
              "Date","Age.At.Test..years.","Fasting.Glucose","X1.hour.Glucose","X2.hour.Glucose","A1C",
              "DOB","Age.at.PFT","FVC.Raw","Height..cm.","Weight..kg.","FEV1.Raw","FEF.25.75.Raw","ht_m",
              "sexnum","FEV1.pred","FVC.pred","FEF.25.75.pred","FEV1.per.pred","FVC.per.pred","FEF.25.75.per.pred","BMI")
alldata <- alldata[,colorder]
alldata <- alldata[order(alldata$MRN,alldata$Date),]

# get BMI percentile
alldata$age <- ifelse(is.na(alldata$Age.at.PFT),alldata$Age.At.Test..years.,alldata$Age.at.PFT)
alldata$bmip = sds(alldata$BMI,
              age = alldata$age,
              sex = alldata$Sex, male = "Male", female =  "Female",
              ref = cdc.ref,
              item = "bmi",
              type = "perc")

# classify CFRD at each visit
alldata$cfrd_visit <- NA
alldata$cfrd_visit <- ifelse(is.na(alldata$X2.hour.Glucose),NA,ifelse(alldata$X2.hour.Glucose>=200,1,0))

# find people with CFRD at baseline
cfrdbase <- alldata[alldata$Date==alldata$`Date of first OGTT` & alldata$cfrd_visit==1,]
alldata <- alldata[!(alldata$MRN %in% cfrdbase$MRN),]

# create variable for CFRD groups (i.e., those who developed CFRD vs those who did not)
# and get date of first OGTT with CFRD
cfrdcheck <- alldata[alldata$cfrd_visit==1,c("MRN","Date","cfrd_visit")]
cfrdcheck <- cfrdcheck[order(cfrdcheck$MRN,desc(cfrdcheck$cfrd_visit)),]
cfrdcheck <- cfrdcheck[!is.na(cfrdcheck$MRN),]
cfrdcheck <- cfrdcheck %>% group_by(MRN) %>% filter(row_number() == 1)                              
colnames(cfrdcheck) <- c("MRN","Date of CFRD diagnosis","CFRD")      
alldata <- merge(alldata,cfrdcheck,by="MRN",all.x=T,all.y=T)
alldata$CFRD <- ifelse(is.na(alldata$CFRD),0,1)

# create variable for time to develop CFRD
# in those who do not develop CFRD, this is the time between first and last OGTT, and they are censored
lastogtt <- alldata[!is.na(alldata$Fasting.Glucose) | !is.na(alldata$X1.hour.Glucose) | !is.na(alldata$X2.hour.Glucose),
                    c("MRN","Date")]
lastogtt <- lastogtt[order(lastogtt$MRN,desc(lastogtt$Date)),]
lastogtt <- lastogtt %>% group_by(MRN) %>% filter(row_number() == 1)  
colnames(lastogtt) <- c("MRN","Date of last OGTT")
alldata <- merge(alldata,lastogtt,by="MRN",all.x = T,all.y=T)

# for analyses about prediction of CFRD, we need to exclude those who only have one OGTT
# can use alldata for mixed models of PFTs and BMI
oneogtt <- alldata[alldata$`Date of first OGTT`==alldata$`Date of last OGTT`,]
multogtt <- alldata[!(alldata$MRN %in% oneogtt$MRN),]

# create dataset with baseline only 
baseline_mult <- multogtt[multogtt$Date==multogtt$`Date of first OGTT`,]
baseline_all <- alldata[alldata$Date==alldata$`Date of first OGTT`,]

# table of demographics in those with at least one pre-CFRD OGTT
demovars <- c("Sex","Race","Latino.a.","age")
# Taking out these clinical variables - if they are to be added to table 1, need to figure out how
# because they come from PFT visits, not the same date as OGTT
#              "BMI","FEV1.per.pred","FVC.per.pred","FEF.25.75.per.pred","bmip")
t1_alldata <- CreateTableOne(data=baseline_all,vars=demovars)
t1_alldata <-  print(t1_alldata,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,test = F)

# table of demographics in those with more than OGTT
t1_multogtt <- CreateTableOne(data=baseline_mult,vars=demovars)
t1_multogtt <-  print(t1_multogtt,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,test = F)

# compare baseline glucose values in those who developed CFRD and those who did not
gluctable <- CreateTableOne(baseline_mult,vars=c("X1.hour.Glucose","X2.hour.Glucose"),strata="CFRD")
gluctable <-  print(gluctable,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,test = T)

```

# Background

# Methods

describe who is excluded
difference between entire cohort and those with follow-up OGTTs

# Results

```{r, echo=FALSE}
kable(t1_alldata,caption = "Table 1a.  Descriptive statistics for entire cohort.")
```

<br>

```{r, echo=FALSE}
kable(t1_multogtt,caption = "Table 1b.  Descriptive statistics for participants with at least one follow-up OGTT.")
```

<br>

```{r, echo=FALSE}
kable(gluctable,caption = "Table 2.  Glucose values from baseline OGTT in those who developed CFRD vs. those who did not, among the participants with at least one follow-up OGTT.")
```


