---
title: "LRG1 analyses"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(knitr)
library(stringr)
library(ggplot2)
library(ggpubr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
}
knitr::opts_knit$set(root.dir = home_dir)
setwd(home_dir)
```

```{r data, include=FALSE}
lrg1 <- read.csv("./Metabolomic data/TODAY study Serum LRG1 levels (6-16-2022).csv")
names(lrg1) <- c("releaseid","Serum.LRG1.level..mg.mL.")

# load baseline risk factors
load("./Clinical data/TODAY/baserisk.Rdata")
baserisk$releaseid <- str_remove(baserisk$releaseid,"-")
baserisk$log_UACR <- log(baserisk$UAlbCreat + 0.000001)

# merge
lrg1 <- merge(lrg1, baserisk, by="releaseid", all.x=T, all.y=F)

# create var for microalbuminuria
lrg1$micro <- ifelse(is.na(lrg1$UAlbCreat), NA, 
                     ifelse(lrg1$UAlbCreat>=30, "Y", "N"))
# no one has microalbuminuria at baseline

# load comorbidity data
load("./Clinical data/comorb.Rdata")
comorb$releaseid <- str_remove(comorb$releaseid,"-")
lrg1 <- merge(lrg1, comorb, by="releaseid", all.x = T, all.y=F)
```

# Estimated insulin sensitivity (1/fasting insulin)

```{r echo=FALSE, warning=FALSE, message=FALSE}
sp <- ggscatter(lrg1, x = "si_1_ins0", y = "Serum.LRG1.level..mg.mL.",
   add = "reg.line",  # Add regression line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE # Add confidence interval
   )
# Add correlation coefficient
sp + stat_cor(method = "pearson", label.x = 0.15, label.y = 200)
```

# BMI

```{r echo=FALSE, warning=FALSE, message=FALSE}
sp <- ggscatter(lrg1, x = "bmi", y = "Serum.LRG1.level..mg.mL.",
   add = "reg.line",  # Add regression line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE # Add confidence interval
   )
# Add correlation coefficient
sp + stat_cor(method = "pearson", label.x = 50, label.y = 200)
```

# Age

```{r echo=FALSE, warning=FALSE, message=FALSE}
sp <- ggscatter(lrg1, x = "AGEBASE", y = "Serum.LRG1.level..mg.mL.",
   add = "reg.line",  # Add regression line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE # Add confidence interval
   )
# Add correlation coefficient
sp + stat_cor(method = "pearson", label.x = 15, label.y = 200)
```

# Sex

```{r echo=FALSE, warning=FALSE, message=FALSE}
p <- ggboxplot(lrg1[!is.na(lrg1$sex),], x = "sex", y = "Serum.LRG1.level..mg.mL.",add = "jitter")
#  Add p-value
p + stat_compare_means(method = "t.test")
```

# HbA1c

```{r echo=FALSE, warning=FALSE, message=FALSE}
sp <- ggscatter(lrg1, x = "HbA1c", y = "Serum.LRG1.level..mg.mL.",
   add = "reg.line",  # Add regression line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE # Add confidence interval
   )
# Add correlation coefficient
sp + stat_cor(method = "pearson", label.x = 7, label.y = 200)
```

# UACR

```{r echo=FALSE, warning=FALSE, message=FALSE}
sp <- ggscatter(lrg1, x = "log_UACR", y = "Serum.LRG1.level..mg.mL.",
   add = "reg.line",  # Add regression line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE # Add confidence interval
   )
# Add correlation coefficient
sp + stat_cor(method = "pearson", label.x = -3, label.y = 200)
```

# Microalbuminuria (at baseline)

```{r echo=FALSE, warning=FALSE, message=FALSE}
p <- ggboxplot(lrg1[!is.na(lrg1$MIC0),], x = "MIC0", y = "Serum.LRG1.level..mg.mL.",add = "jitter")
#  Add p-value
p + stat_compare_means(method = "t.test")
```

# Microalbuminuria (at any point during TODAY/TODAY2)

```{r echo=FALSE, warning=FALSE, message=FALSE}
p <- ggboxplot(lrg1[!is.na(lrg1$MIC),], x = "MIC", y = "Serum.LRG1.level..mg.mL.",add = "jitter")
#  Add p-value
p + stat_compare_means(method = "t.test")
```