---
title: "ORANGE multiomics data merge"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r, include=FALSE}
library(readxl)
library(dplyr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

```

```{r, include=FALSE}
# clinical data
clinical <- read_xlsx("/Volumes/Peds Endo/Melanie Green/ORANGE/Data raw/ORANGE Multiomics for LP 3.18.2023/ORANGE Clinical Data - Targeted.xlsx")

# plasma metabolomics - amino acids
plasma_aa <- read_xlsx("/Volumes/Peds Endo/Melanie Green/ORANGE/Data raw/ORANGE Multiomics for LP 3.18.2023/ORANGE Plasma Metabolomics - Amino Acid Absolute Report.xlsx")
original_cols <- colnames(plasma_aa)
colnames(plasma_aa)[3:ncol(plasma_aa)] <- paste("plasma_aa" ,original_cols[3:ncol(plasma_aa)],sep="_")
colnames(plasma_aa)[1] <- "ID"
alldata <- merge(clinical, plasma_aa, by=c("ID","Treatment Arm PLA = 0, EAA=1"))

# plasma metabolomics - carnitine
plasma_carnitine <- read_xlsx("/Volumes/Peds Endo/Melanie Green/ORANGE/Data raw/ORANGE Multiomics for LP 3.18.2023/ORANGE Plasma Metabolomics - Carnitine Absolute Report.xlsx")
original_cols <- colnames(plasma_carnitine)
colnames(plasma_carnitine)[3:ncol(plasma_carnitine)]  <- paste("plasma_carnitine" ,original_cols[3:ncol(plasma_carnitine)] ,sep="_")
colnames(plasma_carnitine)[1] <- "ID"
alldata <- merge(alldata, plasma_carnitine, by=c("ID","Treatment Arm PLA = 0, EAA=1"))

# plasma metabolomics - lipids absolute
plasma_lipids_abs <- read_xlsx("/Volumes/Peds Endo/Melanie Green/ORANGE/Data raw/ORANGE Multiomics for LP 3.18.2023/ORANGE Plasma Metabolomics - Lipid Absolute Report.xlsx")
original_cols <- colnames(plasma_lipids_abs)
colnames(plasma_lipids_abs)[3:ncol(plasma_lipids_abs)] <- paste("plasma_lipids_abs" ,original_cols[3:ncol(plasma_lipids_abs)],sep="_")
colnames(plasma_lipids_abs)[1] <- "ID"
alldata <- merge(alldata, plasma_lipids_abs, by=c("ID","Treatment Arm PLA = 0, EAA=1"))

# plasma metabolomics - lipids global
plasma_lipids_global <- read_xlsx("/Volumes/Peds Endo/Melanie Green/ORANGE/Data raw/ORANGE Multiomics for LP 3.18.2023/ORANGE Plasma Metabolomics - Lipid Global Report.xlsx")
original_cols <- colnames(plasma_lipids_global)
colnames(plasma_lipids_global)[3:ncol(plasma_lipids_global)] <- paste("plasma_lipids_global" ,original_cols[3:ncol(plasma_lipids_global)],sep="_")
colnames(plasma_lipids_global)[1] <- "ID"
alldata <- merge(alldata, plasma_lipids_global, by=c("ID","Treatment Arm PLA = 0, EAA=1"))

# plasma metabolomics - semi-targeted
plasma_semitargeted_metab <- read_xlsx("/Volumes/Peds Endo/Melanie Green/ORANGE/Data raw/ORANGE Multiomics for LP 3.18.2023/ORANGE Plasma Metabolomics - Semi-Targeted Report.xlsx")
original_cols <- colnames(plasma_semitargeted_metab)
colnames(plasma_semitargeted_metab)[3:ncol(plasma_semitargeted_metab)]  <- paste("plasma_semitargeted_metab" ,original_cols[3:ncol(plasma_semitargeted_metab)] ,sep="_")
colnames(plasma_carnitine)[1] <- "ID"
alldata <- merge(alldata, plasma_carnitine, by=c("ID","Treatment Arm PLA = 0, EAA=1"))

# stool lipidomics normalized
stool_lipids_norm <- read_xlsx("/Volumes/Peds Endo/Melanie Green/ORANGE/Data raw/ORANGE Multiomics for LP 3.18.2023/ORANGE Stool Metabolomics with Lipidomics - Normalized.xlsx")
original_cols <- colnames(stool_lipids_norm)
colnames(stool_lipids_norm)[3:ncol(stool_lipids_norm)] <- paste("stool_lipids_norm" ,original_cols[3:ncol(stool_lipids_norm)],sep="_")
colnames(stool_lipids_norm)[1] <- "ID"
alldata <- merge(alldata, stool_lipids_norm, by=c("ID","Treatment Arm PLA = 0, EAA=1"))

# stool microbiome alpha diversity
stool_microbiome_alpha <- read_xlsx("/Volumes/Peds Endo/Melanie Green/ORANGE/Data raw/ORANGE Multiomics for LP 3.18.2023/ORANGE Stool Microbiome - Alpha Diversity.xlsx")
original_cols <- colnames(stool_microbiome_alpha)
colnames(stool_microbiome_alpha)[3:ncol(stool_microbiome_alpha)] <- paste("stool_microbiome_alpha" ,original_cols[3:ncol(stool_microbiome_alpha)],sep="_")
colnames(stool_microbiome_alpha)[1] <- "ID"
alldata <- merge(alldata, stool_microbiome_alpha, by=c("ID","Treatment Arm PLA = 0, EAA=1"))

# stool microbiome family
stool_microbiome_family <- read_xlsx("/Volumes/Peds Endo/Melanie Green/ORANGE/Data raw/ORANGE Multiomics for LP 3.18.2023/ORANGE Stool Microbiome - Family.xlsx")
original_cols <- colnames(stool_microbiome_family)
colnames(stool_microbiome_family)[3:ncol(stool_microbiome_family)]  <- paste("stool_microbiome_family" ,original_cols[3:ncol(stool_microbiome_family)] ,sep="_")
colnames(stool_microbiome_family)[1] <- "ID"
alldata <- merge(alldata, stool_microbiome_family, by=c("ID","Treatment Arm PLA = 0, EAA=1"))

# stool microbiome genus
stool_microbiome_genus <- read_xlsx("/Volumes/Peds Endo/Melanie Green/ORANGE/Data raw/ORANGE Multiomics for LP 3.18.2023/ORANGE Stool Microbiome - Genus.xlsx")
original_cols <- colnames(stool_microbiome_genus)
colnames(stool_microbiome_genus)[3:ncol(stool_microbiome_genus)] <- paste("stool_microbiome_genus" ,original_cols[3:ncol(stool_microbiome_genus)],sep="_")
colnames(stool_microbiome_genus)[1] <- "ID"
alldata <- merge(alldata, stool_microbiome_genus, by=c("ID","Treatment Arm PLA = 0, EAA=1"))

# stool microbiome order
stool_microbiome_order <- read_xlsx("/Volumes/Peds Endo/Melanie Green/ORANGE/Data raw/ORANGE Multiomics for LP 3.18.2023/ORANGE Stool Microbiome - Order.xlsx")
original_cols <- colnames(stool_microbiome_order)
colnames(stool_microbiome_order)[3:ncol(stool_microbiome_order)] <- paste("stool_microbiome_order" ,original_cols[3:ncol(stool_microbiome_order)],sep="_")
colnames(stool_microbiome_order)[1] <- "ID"
alldata <- merge(alldata, stool_microbiome_order, by=c("ID","Treatment Arm PLA = 0, EAA=1"))

# stool microbiome phyla
stool_microbiome_phyla <- read_xlsx("/Volumes/Peds Endo/Melanie Green/ORANGE/Data raw/ORANGE Multiomics for LP 3.18.2023/ORANGE Stool Microbiome - Phyla.xlsx")
original_cols <- colnames(stool_microbiome_phyla)
colnames(stool_microbiome_phyla)[3:ncol(stool_microbiome_phyla)] <- paste("stool_microbiome_phyla" ,original_cols[3:ncol(stool_microbiome_phyla)],sep="_")
colnames(stool_microbiome_phyla)[1] <- "ID"
alldata <- merge(alldata, stool_microbiome_phyla, by=c("ID","Treatment Arm PLA = 0, EAA=1"))

# write dataset
write.csv(alldata, "/Volumes/Peds Endo/Melanie Green/ORANGE/Data clean/merged multiomics data.csv")
```


