---
title: "ADA Type 2 Diabetes in Youth Innovative Clinical or Translational Science Award"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
---

```{r}
#| include: false
library(tidyverse)
library(sas7bdat)
library(gt)
library(gtsummary)
```

# Teen-LABS

Per Todd, samples "FAF001634 0200" and "FAF001855 0200" were excluded due to "invalid draw date information that prevented the DCC from linking these specimens with study data."

```{r}
# Import
df = read.sas7bdat("/Volumes/Peds Endo/Petter Bjornstad/Teen Labs/Data_Cleaned/bjornstadancillary.sas7bdat")
# Format 
df = df %>% 
  filter(!SAMPLE_ID %in% c("FAF001634 0200","FAF001855 0200")) %>%
  select(ID,visit,age,SEX,RACE,ETHN,HBA1C,UACRATIO) %>%
  mutate(Albuminuria = case_when(UACRATIO*1000 < 30 ~ "A1",
                                 UACRATIO*1000 >= 30 & UACRATIO*1000 <=300 ~ "A2",
                                 UACRATIO*1000 >300 ~ "A3"))
# Categorical levels
df$SEX = factor(df$SEX,levels = 1:2,labels = c("Male","Female"))
df = df %>% unite(`Race/Ethnicity`,RACE,ETHN)
df$`Race/Ethnicity` = factor(df$`Race/Ethnicity`,levels = c("1_1", "1_2", "2_2","8_2"),
                             labels = c("Hispanic White","Non-Hispanic White","Non-Hispanic Black","More Than One Race"))
# Summary
df %>% group_by(ID) %>%
  summarise_all(.funs=first) %>%
  select(-ID,-visit,-UACRATIO) %>% 
  tbl_summary(
    statistic = list(
      age ~ "{mean} ({sd})",
      HBA1C ~ "{median} [{p25}, {p75}]"
    ),
    label = list(
      age ~ "Age",
      HBA1C ~ "HbA1c",
      SEX~"Sex"
    ))
```

# Renal-HEIR

```{r}
# Import
df = read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv",na.strings = "")
load("/Volumes/Peds Endo/Petter Bjornstad/Renal HERITAGE/Somalogic data/rh_soma.Rdata")
load("/Volumes/Peds Endo/Petter Bjornstad/Renal HERITAGE/Olink Data/rh_olink_plasma.Rdata")
load("/Volumes/Peds Endo/Petter Bjornstad/Renal HERITAGE/Olink Data/rh_olink_urine.Rdata")
# Filter and select
df = df %>% select(record_id,co_enroll_id,study,visit,age,sex,race_ethnicity,hba1c,acr_u)%>%
  filter(study == "RENAL-HEIR",!grepl("IT",co_enroll_id)) %>%
  group_by(record_id,visit) %>% 
  summarise_all(~ first(na.omit(.x))) %>% ungroup() %>%
  filter(visit=="baseline")
# Format levels
df$race_ethnicity=factor(df$race_ethnicity,levels = c("Black or African American, Not Hispanic or Latino",
                                    "More Than One, Hispanic or Latino",
                                    "More Than One, Not Hispanic or Latino",
                                    "Other, Hispanic or Latino","Other, Not Hispanic or Latino",
                                    "Unknown, Hispanic or Latino","White, Hispanic or Latino",
                                    "White, Not Hispanic or Latino"),
       labels = c("Non-Hispanic Black",
                  "More Than One, Hispanic or Latino",
                  "More Than One, Not Hispanic or Latino",
                  "Other","Other","Other","Hispanic White","Non-Hispanic White"))
df = df %>%
  mutate(Albuminuria = case_when(acr_u < 30 ~ "A1",
                                 acr_u >= 30 & acr_u <=300 ~ "A2",
                                 acr_u >300 ~ "A3"))
# Add counts for omics data
df$`Somalogic Data Available` = ifelse(df$record_id %in% rh_soma$SampleDescription,"Yes","No")
df$`Olink Plasma Data Available` = ifelse(df$record_id %in% rh_olink_plasma$record_id,"Yes","No")
df$`Olink Urine Data Available` = ifelse(df$record_id %in% rh_olink_urine$record_id,"Yes","No")
# Summary
df %>% filter(`Somalogic Data Available`=="Yes") %>%
  select(age:`Olink Urine Data Available`,-`Somalogic Data Available`,-acr_u) %>% 
  tbl_summary(
    statistic = list(
      age ~ "{mean} ({sd})",
      hba1c ~ "{median} [{p25}, {p75}]"
    ),
    label = list(
      age ~"Age",
      sex~"Sex",
      race_ethnicity~"Race/Ethnicity",
      hba1c~"HbA1c"
    ))
```

# Improve

```{r}
# Import
df = read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv",na.strings = "")
load("/Volumes/Peds Endo/Petter Bjornstad/IMPROVE T2D/Somalogic data/improve_soma.Rdata")
improve_soma$SampleDescription = sub("2D-","_",improve_soma$SampleDescription)
load("/Volumes/Peds Endo/Petter Bjornstad/IMPROVE T2D/Olink Data/improve_olink_plasma.Rdata")
improve_olink_plasma$record_id = sub("_BL|_12M","",improve_olink_plasma$record_id)
load("/Volumes/Peds Endo/Petter Bjornstad/IMPROVE T2D/Olink Data/improve_olink_urine.Rdata")
improve_olink_urine$record_id = sub("_BL|_12M","",improve_olink_urine$record_id)
# Filter and select
df = df %>% select(record_id,co_enroll_id,study,visit,age,sex,race_ethnicity,hba1c,acr_u)%>%
  filter(study == "IMPROVE",) %>%
  group_by(record_id,visit) %>% 
  summarise_all(~ first(na.omit(.x))) %>% ungroup() %>%
  filter(visit=="baseline")
# Format levels
df$race_ethnicity=factor(df$race_ethnicity,levels = c("Black or African American, Not Hispanic or Latino",
                                    "More Than One, Hispanic or Latino",
                                    "More Than One, Not Hispanic or Latino",
                                    "Other, Hispanic or Latino","Other, Not Hispanic or Latino",
                                    "Unknown, Hispanic or Latino","White, Hispanic or Latino",
                                    "White, Not Hispanic or Latino"),
       labels = c("Non-Hispanic Black",
                  "More Than One, Hispanic or Latino",
                  "More Than One, Not Hispanic or Latino",
                  "Other","Other","Other","Hispanic White","Non-Hispanic White"))
df = df %>%
  mutate(Albuminuria = case_when(acr_u < 30 ~ "A1",
                                 acr_u >= 30 & acr_u <=300 ~ "A2",
                                 acr_u >300 ~ "A3"))
# Add counts for omics data
df$`Somalogic Data Available` = ifelse(df$record_id %in% improve_soma$SampleDescription,"Yes","No")
df$`Olink Plasma Data Available` = ifelse(df$record_id %in% improve_olink_plasma$record_id,"Yes","No")
df$`Olink Urine Data Available` = ifelse(df$record_id %in% improve_olink_urine$record_id,"Yes","No")
# Summary
df %>% filter(`Somalogic Data Available`=="Yes") %>% 
  select(age:`Olink Urine Data Available`,-`Somalogic Data Available`,-acr_u) %>% 
  tbl_summary(
    statistic = list(
      age ~ "{mean} ({sd})",
      hba1c ~ "{median} [{p25}, {p75}]"
    ),
    label = list(
      age ~"Age",
      sex~"Sex",
      race_ethnicity~"Race/Ethnicity",
      hba1c~"HbA1c"
    ))
```

