---
title: "Harmonized Colorado and RED Data Cleaning/Merge"
author: "Callie Rountree-Jablin"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
    toc_loc: left
---

This file includes all code used for cleaning and merging the RED Netherlands data with the Colorado harmonized dataset. Please reference the CO_RED_data_analysis rmd for a written description of the data cleaning methods utilized.

```{r setup, include=FALSE}
library(tidyverse)
library(kableExtra)
library(magrittr)
library(Hmisc)
pacman::p_load(naniar)

if(Sys.info()["sysname"] == "Windows"){
  home_dir = "B:/Petter Bjornstad"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/Peds Endo/Petter Bjornstad/"
} 
knitr::opts_knit$set(echo=FALSE, root.dir = home_dir)
```


```{r read, include=FALSE}
# # Colorado data
# CO_raw <- read.csv("./Data Harmonization/Data Clean/harmonized_dataset.csv", na.strings = c(" ", "", "-9999",-9999))
# 
# # Colorado data dictionary
# dict <- read.csv("./Data Harmonization/data_dictionary_master.csv", na.strings = c(" ", "", "-9999",-9999))
# 
# # co-enrolled IDs for Colorado data
# coenroll_id <- read.csv("./Renal HERITAGE/Data_Cleaned/coenrolled_ids.csv") %>%
#   pivot_longer(cols = 'improve_id':'crc_id',
#                values_to = "record_id") %>% 
#   select(merged_id, record_id) %>%
#   filter(record_id != "")

# Netherlands data
Neth_main <- haven::read_sav('./IHD/Raw Data/RED - Renal Hemodynamics and Clamp data + NEFA data.sav')
Neth_anthropometrics <- haven::read_sav('./IHD/Raw Data//RED - Anthropometrics.sav')
Neth_baseline_char <- haven::read_sav('./IHD/Raw Data/RED - Baseline characteristics.sav')
Neth_urine <- haven::read_sav('./IHD/Raw Data/RED - Tubular 24u urine.sav')
Neth_labs <- haven::read_sav('./IHD/Raw Data/RED - Lab results incl. calculated eGFR.sav')
Neth_clamp_additional <- haven::read_sav('./IHD/Raw Data/Insulin, glucose and infusion rates.sav')
```


<!-- ```{r Colorado data cleaning, include=FALSE} -->
<!-- CO_clean <- left_join(CO_raw, coenroll_id, by = 'record_id') %>%  -->
<!--   relocate(merged_id, .after = co_enroll_id) %>%  -->
<!--   filter(participation_status != 'Removed'|is.na(participation_status)) %>% -->
<!--   filter(group == 'Type 2 Diabetes') %>% -->
<!--   mutate(merged_id = ifelse(!is.na(merged_id), merged_id, record_id)) %>% # fill in missing merged_id with record_id -->
<!--   mutate(RH2_only_indicator = case_when(str_detect(record_id, "RH2-") & record_id == merged_id ~ 'Yes', -->
<!--                                    TRUE ~ 'No')) %>%  -->
<!--   filter(RH2_only_indicator != 'Yes') %>% # exclude subjects who are only on RH2 per Petter -->
<!--   rename('cardiac_mri_bsa' = 'bsa') %>% -->
<!--   mutate(#bsa_dubois = (0.007184 * (height^0.725))*(weight^0.425), # Du Bois and Du Bois BSA calculation -->
<!--          bsa = sqrt(weight * height / 3600)) %>% # formula used by Netherlands site -->

<!--   # collapse multiple entries for subjects to one row, where the earliest measurements are retained -->
<!--   # note that visit, date, demographics, etc. are only reflective of earliest available data after collapsing -->
<!--   mutate(date = as.Date(date, format = '%Y-%m-%d')) %>% -->
<!--   arrange(merged_id, date) %>%  -->
<!--   mutate(date = as.character(date)) %>%  -->
<!--   summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, first(na.omit(.x)))), -->
<!--             across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, first(na.omit(.x)))), .by = c(merged_id)) %>% -->
<!--   mutate(date = as.Date(date, format = '%Y-%m-%d')) -->

<!-- # variable cleaning, AER calculations -->
<!-- CO_clean <- CO_clean %>% -->
<!--   select(-c(record_id)) %>% # drop raw record ID var, rename merged ID as record ID for ease of combining dfs later on -->
<!--   rename('record_id' = 'merged_id') %>% -->
<!--   mutate(sex = as.factor(sex), -->
<!--          raasi_timepoint = factor(raasi_timepoint, levels = c('No','Yes')), -->
<!--          statin = factor(statin, levels = c('No','Yes')), -->
<!--          # calculate gender-adjusted estimate of AER based on https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2893069/ -->
<!--          AER_sex_adjusted = case_when(sex == 'Female' ~ (1.38*acr_u), sex == 'Male' ~ (2.09*acr_u)), -->
<!--          # calculate covariate-adjusted estimate of AER based on same article -->
<!--          ACE_or_ARB_indicator = case_when(ace_inhibitor == 'Yes'| angiotensin_receptor_blocker == 'Yes' ~ 'Yes', TRUE ~ 'No'), -->
<!--          ethnicity = recode(ethnicity, 'Not Hispanic or Latino' = 'Non-Hispanic or White')) %>% -->
<!--   mutate(ACR_alpha = case_when(sex == 'Female' & ACE_or_ARB_indicator == 'Yes' ~  -->
<!--                                  exp(-0.4 - (0.012*age) + (0.31*bsa) - (0.25*log(acr_u)) + (0.34*creatinine_s) + (0.0072*sbp) + 0.13), -->
<!--                                sex == 'Female' & ACE_or_ARB_indicator == 'No' ~  -->
<!--                                  exp(-0.4 - (0.012*age) + (0.31*bsa) - (0.25*log(acr_u)) + (0.34*creatinine_s) + (0.0072*sbp)), -->
<!--                                sex == 'Male' & ACE_or_ARB_indicator == 'Yes' ~  -->
<!--                                  exp(-0.13 - (0.012*age) + (0.31*bsa) - (0.25*log(acr_u)) + (0.34*creatinine_s) + (0.0072*sbp) + 0.13), -->
<!--                                sex == 'Male' & ACE_or_ARB_indicator == 'No' ~  -->
<!--                                  exp(-0.13 - (0.012*age) + (0.31*bsa) - (0.25*log(acr_u)) + (0.34*creatinine_s) + (0.0072*sbp)))) %>%  -->
<!--   mutate(AER_covariate_adjusted = ACR_alpha * acr_u) -->

<!-- # add site variable for differentiating between CO and Neth dfs -->
<!-- CO_clean <- cbind(site='Colorado', CO_clean) -->
<!-- ``` -->


```{r CO clean read}
# read in already cleaned CO data (obtained from commented out code above)
# 8.30.24 version of data is version used for manuscript
CO_clean <- read.csv('./IHD/Clean Data/collapsed_CO_clean_8.30.24.csv')
```


```{r CO additional data cleaning, include = FALSE}
# create updated rbf variable where if rbf is not missing it is retained but if missing, manually calculated
CO_clean <- CO_clean %>% mutate(
  rbf = ifelse(is.na(rbf), erpf_raw_plasma/(1-(hematocrit/100)), rbf)
)
```


```{r Netherlands data cleaning, include=FALSE}
# merge all Netherlands datasets
Neth_clean <- left_join(Neth_main, Neth_anthropometrics, by=c('record_id','Randomization'), suffix=c('.m','.a'))
Neth_clean <- left_join(Neth_clean, Neth_baseline_char, by=c('record_id','Randomization'), suffix=c('.c','.b'))
Neth_clean <- left_join(Neth_clean, Neth_clamp_additional, by=c('record_id','Randomization'), suffix=c('.c','.ca'))
Neth_clean <- left_join(Neth_clean, Neth_labs, by=c('record_id','Randomization'), suffix=c('.c','.l'))
Neth_clean <- left_join(Neth_clean, Neth_urine, by=c('record_id'), suffix=c('.c','.u'))
Neth_clean <- cbind(site='Netherlands', study='RED', Neth_clean, ethnicity='Non-Hispanic or White', group = 'Type 2 Diabetes')

# subset to only include variables of interest
Neth_clean <- Neth_clean %>% 
  select(site, study, record_id, ethnicity, group, INUorIOH, G_V2_Age.c, G_Sex.c, 
         Anthro_Length.c, Anthro_V2_BMI.a, Lab_2_1_Blood_LDL.c,
         Lab_2_1_Blood_HbA1c_percent.c, Renal_mGFR_V2_Eu, Renal_ERPF_V2_Eu, Renal_FF_V2_Eu, Renal_ERVR_V2_Eu,
         Renal_Pglo_V2_Eu, Renal_Ra_V2_Eu, Renal_Re_V2_Eu, CV_RR_V2_Eu_SBP, CV_RR_V2_Eu_DBP,
         CV_RR_V2_Eu_MAP, L_2_AVG_6_7_Blood_Insulin.c, NEFA_V2.1_Fasting, NEFA_V2.7_Eu, NEFA_delta,
         Anthro_V2_bodyweight, Anthro_V2_waist, Anthro_V2_BSA, Anthro_BIA_V2_eu_fatpercentage, Medication, Med_betablocker,
         Med_calciumantagonist, Med_metformindose, Med_RASi, Med_statin, Med_anticoagulant, Lab_2_1_Blood_creat.c,
         Lab_2_1_Blood_Cholesterol, Lab_2_1_Blood_HDL, L_2_0_24u_urine_mircoalb_quant.u, Lab_2_1_Blood_eGFR,
         Euclamp_V2_Mvalue_corr_minusglycosuria, DI_V2_secondphase, G_history_DM_duration, Renal_ERBF_V2_Eu)

# rename variables to match Colorado variables, if applicable
Neth_clean <- Neth_clean %>% 
  rename('age'='G_V2_Age.c', 'sex'='G_Sex.c', 'height'='Anthro_Length.c', 'bmi'='Anthro_V2_BMI.a',
         'hba1c'='Lab_2_1_Blood_HbA1c_percent.c', 'gfr_raw_plasma'='Renal_mGFR_V2_Eu', 'erpf_raw_plasma'='Renal_ERPF_V2_Eu',
         'ff'='Renal_FF_V2_Eu', 'glomerular_pressure'='Renal_Pglo_V2_Eu', 'ra'='Renal_Ra_V2_Eu',
         're'='Renal_Re_V2_Eu',
         'sbp'='CV_RR_V2_Eu_SBP', 'dbp'='CV_RR_V2_Eu_DBP', 'map'='CV_RR_V2_Eu_MAP',
         'weight'='Anthro_V2_bodyweight', 'waistcm'='Anthro_V2_waist', 'dexa_body_fat'='Anthro_BIA_V2_eu_fatpercentage',
         'cholesterol'='Lab_2_1_Blood_Cholesterol', 'raasi_timepoint'='Med_RASi', 'statin'='Med_statin',
         'steady_state_insulin'='L_2_AVG_6_7_Blood_Insulin.c', 'eGFR_fas_cr_cysc'='Lab_2_1_Blood_eGFR',
         'gir'='Euclamp_V2_Mvalue_corr_minusglycosuria', 'di'='DI_V2_secondphase', 'rvr'='Renal_ERVR_V2_Eu',
         'diabetes_duration'='G_history_DM_duration', 'bsa'='Anthro_V2_BSA', 'steady_state_ffa' = 'NEFA_V2.7_Eu',
         'urine_microalb_quant_24hr'='L_2_0_24u_urine_mircoalb_quant.u', 'rbf' = 'Renal_ERBF_V2_Eu')
  
# clean Netherlands variables as needed to match Colorado variables and units
Neth_clean <- Neth_clean %>% 
  mutate(sex = factor(sex, levels = c(1, 0), labels = c('Female', 'Male')), 
         Med_betablocker = factor(Med_betablocker, levels = c(0, 1), labels=c('No','Yes')),
         Med_calciumantagonist = factor(Med_calciumantagonist, levels=c(0, 1), labels=c('No','Yes')),
         metformin_timepoint = case_when(Med_metformindose > 0 ~ 'Yes', .default='No'),
         raasi_timepoint = factor(raasi_timepoint, levels = c(0, 1), labels = c('No','Yes')),
         statin = factor(statin, levels = c(0, 1), labels = c('No','Yes')),
         Med_anticoagulant = factor(Med_anticoagulant, levels=c(0, 1), labels=c('No','Yes')),
         creatinine_s = Lab_2_1_Blood_creat.c/88.4, # umol/l to mg/dL
         ldl = Lab_2_1_Blood_LDL.c*38.67, # mmol/L to mg/dL https://www.ncbi.nlm.nih.gov/books/NBK83505/
         hdl = Lab_2_1_Blood_HDL*38.67, # mmol/L to mg/dL
         cholesterol = cholesterol*38.67, # mmol/L to mg/dL
         ffa_suppression = (NEFA_delta/NEFA_V2.1_Fasting)*100,
         gfr_bsa_plasma = (gfr_raw_plasma/bsa)*1.73,
         erpf_bsa_plasma = (erpf_raw_plasma/bsa)*1.73,
         ff = ff/100,
         steady_state_ffa = steady_state_ffa*1000) %>% # mmol/l to uM  
  select(-c(Med_metformindose, Lab_2_1_Blood_creat.c, Lab_2_1_Blood_LDL.c, Lab_2_1_Blood_HDL))

# calculate AER (24 hr microalbuminuria quantity/(24*60)*1000)
Neth_clean <- Neth_clean %>% 
  mutate(AER = (urine_microalb_quant_24hr/1440)*1000) # times 1000 per Daniel
```


```{r workspace clean up}
rm(Neth_main, Neth_anthropometrics, Neth_baseline_char, Neth_clamp_additional, Neth_labs, Neth_urine)
```


```{r Colorado and Netherlands merge, include=FALSE}
# create two copies of Netherlands AER var: one to merge w/CO sex adj. AER and the other w/CO covariate adj. AER
# also create two copies of Netherlands gir var: one to merge w/gir_190 and the other w/gir_200
Neth_clean <- Neth_clean %>%
  rename(c('AER_sex_adjusted' = 'AER', 'gir_190' = 'gir')) %>% 
  mutate(AER_covariate_adjusted = AER_sex_adjusted,
         gir_200 = gir_190)

# check for matching IDs across datasets (none noted)
intersect(unique(CO_clean$record_id), unique(Neth_clean$record_id))

# merge datasets
combined_dat <- full_join(CO_clean, Neth_clean, by=c('record_id', 'site', 'study', 'age', 'sex', 'ethnicity', 'group', 
                                                     'height', 'bmi', 'hba1c', 'gfr_raw_plasma', 'erpf_raw_plasma', 
                                                     'ff', 'AER_sex_adjusted', 'AER_covariate_adjusted', 
                                                     'glomerular_pressure', 'ra', 're', 'sbp', 'dbp', 'map', 
                                                     'weight', 'waistcm', 'dexa_body_fat', 'cholesterol', 
                                                     'raasi_timepoint', 'statin', 'steady_state_insulin', 'eGFR_fas_cr_cysc',
                                                     'gir_190', 'gir_200', 'rvr', 'diabetes_duration', 
                                                     'bsa', 'metformin_timepoint', 'creatinine_s', 'ldl', 'hdl',
                                                     'ffa_suppression', 'gfr_bsa_plasma', 'erpf_bsa_plasma', 'steady_state_ffa', 'rbf'))
```


```{r combined data cleaning, include=FALSE}
# subset to variables of interest
combined_dat <- combined_dat %>% 
  select(c('record_id', 'site', 'study', 'group', 'age', 'diabetes_duration', 'sex', 'ethnicity', 'height', 
           'weight', 'waistcm', 'dexa_body_fat', 'bsa', 'bmi', 'hba1c', 'gfr_raw_plasma', 'gfr_bsa_plasma', 'eGFR_fas_cr_cysc',
           'erpf_raw_plasma', 'erpf_bsa_plasma', 'rbf', 'ff', 'rvr', 'ra', 're', 'glomerular_pressure', 'sbp', 'dbp',
           'map', 'creatinine_s', 'cholesterol', 'hdl', 'ldl',  'acprg', 'acr_u', 'AER_sex_adjusted',
           'AER_covariate_adjusted', 'urine_microalb_quant_24hr', 'gir_190', 'gir_200', 'steady_state_ffa',
           'ffa_suppression', 'steady_state_insulin', 'NEFA_V2.1_Fasting', 'NEFA_delta', 'INUorIOH',
           'metformin_timepoint', 'raasi_timepoint', 'statin', 'Med_betablocker', 'Med_calciumantagonist',
           'Med_anticoagulant', 'Medication')) %>% 
  rename('Body_Fat_Percentage'='dexa_body_fat') # dexa variable renamed to be more accurate (Netherlands not dexa)
```


```{r save, include=FALSE}
## save cleaned data

# combined datasets
readr::write_csv(combined_dat, file='./IHD/Clean Data/combined_CO_RED_clean.csv') 

# cleaned and collapsed harmonized dataset (saved a copy of this df since the main harmonized dataset is updated weekly)
# readr::write_csv(CO_clean, file = './IHD/Clean Data/collapsed_CO_clean.csv') 
```