---
title: "Intraglomerular hemodynamic models"
author: "Cameron Severn and Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)


data <- read.csv("E:\\Petter Bjornstad\\IHD\\raw_data\\Final Dataset for analysis.csv")

# there are 2 outliers
# RH-77-T has ACR>1000
# RH-42-O has O2 consumption cortex >8 and total kidney O2 consumption >9
# try removing them and fitting linear model
data_modeling <- data %>% filter(!Subject.ID %in% c("RH-77-T","RH-42-O"))

# translate and transform
data_log <- data
data_log$l.Percent.FFA.Suppression <- log(data$Percent.FFA.Suppression+11)
data_log$l.O2.Consumption...pre.post.furosemide.R2....medulla. <- log(data$O2.Consumption...pre.post.furosemide.R2....medulla.+11)
data_log$l.O2.Consumption...pre.post.furosemide.R2....cortex <- log(data$O2.Consumption..pre.post.furosemide.R2....cortex.+11)
data_log$l.O2.Consumption...pre.post.furosemide.R2....kidney <- log(data$O2.Consumption...pre.post.furosemide.R2....kidney.+11)

# inverse hypberbolic sine
data_ihs <- data
data_ihs$ihs.Percent.FFA.Suppression <- asinh(data$Percent.FFA.Suppression)
data_ihs$ihs.Baseline.ACR <- asinh(data$Baseline.ACR)
data_ihs$ihs.O2.Consumption...pre.post.furosemide.R2....medulla <- asinh(data$O2.Consumption...pre.post.furosemide.R2....medulla)
data_ihs$ihs.O2.Consumption...pre.post.furosemide.R2....cortex <- asinh(data$O2.Consumption..pre.post.furosemide.R2....cortex.)
data_ihs$ihs.O2.Consumption...pre.post.furosemide.R2....kidney <- asinh(data$O2.Consumption...pre.post.furosemide.R2....kidney.)
```

# Untransformed data

## Plotting entire dataset 

```{r echo=FALSE}

plot(data$Percent.FFA.Suppression,data$Baseline.ACR)
plot(data$Percent.FFA.Suppression,data$O2.Consumption..pre.post.furosemide.R2....cortex.)
plot(data$Percent.FFA.Suppression,data$O2.Consumption...pre.post.furosemide.R2....medulla.)
plot(data$Percent.FFA.Suppression,data$O2.Consumption...pre.post.furosemide.R2....kidney.)
```

## Plotting dataset after 2 outliers removed

```{r echo=FALSE}

plot(data_modeling$Percent.FFA.Suppression,data_modeling$Baseline.ACR)
plot(data_modeling$Percent.FFA.Suppression,data_modeling$O2.Consumption..pre.post.furosemide.R2....cortex.)
plot(data_modeling$Percent.FFA.Suppression,data_modeling$O2.Consumption...pre.post.furosemide.R2....medulla.)
plot(data_modeling$Percent.FFA.Suppression,data_modeling$O2.Consumption...pre.post.furosemide.R2....kidney.)
```

## Models on data after 2 outliers removed

### Baseline ACR

```{r echo=FALSE}
mod <- lm(Baseline.ACR ~ Percent.FFA.Suppression,data=data_modeling)
plot(mod)
```

### O2 consumption cortex

```{r echo=FALSE}
mod <- lm(Baseline.ACR ~ O2.Consumption..pre.post.furosemide.R2....cortex.,data=data_modeling)
plot(mod)
```

### O2 consumption medulla

```{r echo=FALSE}
mod <- lm(Baseline.ACR ~ O2.Consumption...pre.post.furosemide.R2....medulla.,data=data_modeling)
plot(mod)
```

### O2 consumption whole kidney

```{r echo=FALSE}
mod <- lm(Baseline.ACR ~ O2.Consumption...pre.post.furosemide.R2....kidney.,data=data_modeling)
plot(mod)
```

# Models on inverse hyperbolic sine transformed data

## Baseline ACR

```{r echo=FALSE,comment=""}
mod <- lm(Baseline.ACR ~ Percent.FFA.Suppression,data=data_ihs)
summary(mod)
plot(mod)
```

## O2 consumption cortex

```{r echo=FALSE,comment=""}
mod <- lm(ihs.Baseline.ACR ~ ihs.O2.Consumption...pre.post.furosemide.R2....cortex,data=data_ihs)
summary(mod)
plot(mod)
```

## O2 consumption medulla

```{r echo=FALSE,comment=""}
mod <- lm(ihs.Baseline.ACR ~ ihs.O2.Consumption...pre.post.furosemide.R2....medulla,data=data_ihs)
summary(mod)
plot(mod)
```

## O2 consumption whole kidney

```{r echo=FALSE,comment=""}
mod <- lm(ihs.Baseline.ACR ~ ihs.O2.Consumption...pre.post.furosemide.R2....kidney,data=data_ihs)
summary(mod)
plot(mod)
```