---
title: "Adipose insulin sensitivity in adolescents with extreme insulin resistance"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:   
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(tableone)
library(knitr)
library(dplyr)
library(ggplot2)
library(hrbrthemes)
library(tidyr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

data <- read.csv("E:/Melanie Green/Frontiers clamp methods review paper/Data raw/Data template for paper_MelanieLaura.csv",
                 na.strings = c("NA",".",""," ","#DIV/0!"))
data$Age.diabetes.onset <- NULL
data$BMI.category <- NULL
data$Sex <- as.factor(data$Sex)
data$bmi_cat <- ifelse(is.na(data$BMIp),NA,
                       ifelse(data$BMIp<85,"<85th %ile",
                              ifelse(data$BMIp>=85 & data$BMIp<95,"85th - <95th %ile",">=95th %ile")))
data$bmi_twocat <- ifelse(is.na(data$bmi_cat),NA,
                          ifelse(data$bmi_cat=="<85th %ile","Lean","Overweight/Obese"))

# who should be included in analysis? everyone or is there a minimum amount of data?
data <- data[!data$StudyID %in% c("827-042","827-111"),]
# exclude those with missing basal glucose
data <- data %>% filter(!is.na(Mean.Glucose.Basal))

# categorize overnight glucose
data$Mean.Glucose.Basal.cat <- ifelse(is.na(data$Mean.Glucose.Basal),NA,
                                      ifelse(data$Mean.Glucose.Basal>70 & data$Mean.Glucose.Basal<90,"70 - <90 mg/dL",
                                             ifelse(data$Mean.Glucose.Basal>=90 & data$Mean.Glucose.Basal<110,"90 - <110 mg/dL",
                                                    ifelse(data$Mean.Glucose.Basal>=110 & data$Mean.Glucose.Basal<130,"110 - <130 mg/dL",
                                                           ifelse(data$Mean.Glucose.Basal>=130 & data$Mean.Glucose.Basal<150,"130 - <150 mg/dl",
                                                                  ">150 mg/dl")))))
data$Mean.Glucose.Basal.cat <- as.factor(data$Mean.Glucose.Basal.cat)
data$Mean.Glucose.Basal.cat <- droplevels(data$Mean.Glucose.Basal.cat)

# calculate means by BMI group
means <- data %>% group_by(bmi_twocat) %>% summarise_at(vars("Mean.Glucose.Basal","Basal.Insulin",
                                                             "Basal.glucose.Ra","Basal.FFA","Basal.glycerol",
                                                             "Basal.glycerol.RA"),mean,na.rm=T)

# need to make a long dataset
for_long <- data %>% select(-c(Sex,Age,FFA.IC50,Glycerol.IC50,Glycerol.Ra.IC50,Race,Ethnicity,Diabetes.duration_years,Approximate.total.daily.insulin,
                               BMI,BMIp,Dexa...Lean.mass,Dexa...fat.mass,Most.recent.HbA1c,Cholesterol,Triglycerides,LDL,bmi_cat,
                               bmi_twocat,Mean.Glucose.Basal.cat,M.I.80,Glucose.IC50))
colnames(for_long) <- c("StudyID","Glucose.0","Glucose.10","Glucose.16","Glucose.80","Insulin.0","Insulin.10",
                        "Insulin.16","Insulin.80","GlucoseRa.0","GlucoseRa.10","GlucoseRa.16","GlucoseRa.80","FFA.0",
                        "FFA.10","FFA.16","FFA.80","Glycerol.0","Glycerol.10","Glycerol.16","Glycerol.80","GlycerolRa.0",
                        "GlycerolRa.10","GlycerolRa.16","GlycerolRa.80")
long <- reshape(for_long, idvar = "StudyID", varying=2:25, direction="long",sep=".")
long <- long %>% arrange(StudyID,time)
# merge in overnight glucose category
x <- data %>% select(StudyID,Mean.Glucose.Basal.cat)
long <- merge(long,x,by="StudyID",all.x = T,all.y = T)
long$time <- as.factor(long$time)

```

# Descriptive statistics, overall

```{r, include=F}
descdata <- data %>% select(-StudyID)
t1 <- CreateTableOne(data=descdata,vars=colnames(descdata))
t1 <- print(t1)
```

```{r, include=T}
kable(t1)
```

# Figure 1 - fasting data

## Glucose

```{r, include=T}
ggplot(data, aes(x=Basal.Insulin, y=Mean.Glucose.Basal, color=bmi_twocat)) + 
      geom_point(size=6) +
      theme_ipsum()
```

```{r, include=T}
ggplot(means, aes(x=Basal.Insulin, y=Mean.Glucose.Basal, color=bmi_twocat)) + 
      geom_point(size=6) +
      theme_ipsum()
```

## Glucose Ra

```{r, include=T}
ggplot(data, aes(x=Basal.Insulin, y=Basal.glucose.Ra, color=bmi_twocat)) + 
      geom_point(size=6) +
      theme_ipsum()
```

```{r, include=T}
ggplot(means, aes(x=Basal.Insulin, y=Basal.glucose.Ra, color=bmi_twocat)) + 
      geom_point(size=6) +
      theme_ipsum()
```

## Glycerol

```{r, include=T}
ggplot(data, aes(x=Basal.Insulin, y=Basal.glycerol, color=bmi_twocat)) + 
      geom_point(size=6) +
      theme_ipsum()
```

```{r, include=T}
ggplot(means, aes(x=Basal.Insulin, y=Basal.glycerol, color=bmi_twocat)) + 
      geom_point(size=6) +
      theme_ipsum()
```

## Glycerol Ra

```{r, include=T}
ggplot(data, aes(x=Basal.Insulin, y=Basal.glycerol.RA, color=bmi_twocat)) + 
      geom_point(size=6) +
      theme_ipsum()
```

```{r, include=T}
ggplot(means, aes(x=Basal.Insulin, y=Basal.glycerol.RA, color=bmi_twocat)) + 
      geom_point(size=6) +
      theme_ipsum()
```

## FFA

```{r, include=T}
ggplot(data, aes(x=Basal.FFA, y=Basal.glycerol.RA, color=bmi_twocat)) + 
      geom_point(size=6) +
      theme_ipsum()
```

```{r, include=T}
ggplot(means, aes(x=Basal.FFA, y=Basal.glycerol.RA, color=bmi_twocat)) + 
      geom_point(size=6) +
      theme_ipsum()
```

# Figure 2 - by overnight glucose and stage

## Glucose

```{r, include=T}
my_order <- c("70 - <90 mg/dL","90 - <110 mg/dL","90 - <110 mg/dL","110 - <130 mg/dL","130 - <150 mg/dl",">150 mg/dl")

p <- ggplot(long, aes(x=Mean.Glucose.Basal.cat, y=Glucose, fill=time)) +
      geom_boxplot() +
      scale_x_discrete(limits = function(x) my_order[my_order %in% x]) + 
      xlab("Overnight glucose") + ylab("Glucose") + theme_classic()
p

```

## Insulin

```{r, include=T}
p <- ggplot(long, aes(x=Mean.Glucose.Basal.cat, y=Insulin, fill=time)) +
      geom_boxplot() +
      scale_x_discrete(limits = function(x) my_order[my_order %in% x]) + 
      xlab("Overnight glucose") + ylab("Insulin") + theme_classic()
p

```

## Glucose Ra

```{r, include=T}
p <- ggplot(long, aes(x=Mean.Glucose.Basal.cat, y=GlucoseRa, fill=time)) +
      geom_boxplot() +
      scale_x_discrete(limits = function(x) my_order[my_order %in% x]) + 
      xlab("Overnight glucose") + ylab("Glucose Ra") + theme_classic()
p

```

## Glycerol

```{r, include=T}
p <- ggplot(long, aes(x=Mean.Glucose.Basal.cat, y=Glycerol, fill=time)) +
      geom_boxplot() +
      scale_x_discrete(limits = function(x) my_order[my_order %in% x]) + 
      xlab("Overnight glucose") + ylab("Glycerol") + theme_classic()
p

```

## Glycerol Ra

```{r, include=T}
p <- ggplot(long, aes(x=Mean.Glucose.Basal.cat, y=GlycerolRa, fill=time)) +
      geom_boxplot() +
      scale_x_discrete(limits = function(x) my_order[my_order %in% x]) + 
      xlab("Overnight glucose") + ylab("Glycerol Ra") + theme_classic()
p

```

## FFA

```{r, include=T}
p <- ggplot(long, aes(x=Mean.Glucose.Basal.cat, y=FFA, fill=time)) +
      geom_boxplot() +
      scale_x_discrete(limits = function(x) my_order[my_order %in% x]) + 
      xlab("Overnight glucose") + ylab("FFA") + theme_classic()
p

```

# Figure 3 - curves over time by overnight glucose

## Spaghetti plots

### Glucose

```{r, include=T}
p <- ggplot(long, aes(x=time, y=Glucose, group=StudyID, color=Mean.Glucose.Basal.cat)) +
      geom_line() 
p
```

### Insulin

```{r, include=T}
p <- ggplot(long, aes(x=time, y=Insulin, group=StudyID, color=Mean.Glucose.Basal.cat,)) +
      geom_line() 
p
```

### Glucose Ra

```{r, include=T}
p <- ggplot(long, aes(x=time, y=GlucoseRa, group=StudyID, color=Mean.Glucose.Basal.cat,)) +
      geom_line() 
p
```

### Glycerol

```{r, include=T}
p <- ggplot(long, aes(x=time, y=Glycerol, group=StudyID, color=Mean.Glucose.Basal.cat,)) +
      geom_line() 
p
```

### Glycerol Ra

```{r, include=T}
p <- ggplot(long, aes(x=time, y=GlycerolRa, group=StudyID, color=Mean.Glucose.Basal.cat,)) +
      geom_line() 
p
```

### FFA

```{r, include=T}
p <- ggplot(long, aes(x=time, y=FFA, group=StudyID, color=Mean.Glucose.Basal.cat,)) +
      geom_line() 
p
```

## Mean curves

### Glucose

```{r, include=T}
grouped <- long %>% group_by(Mean.Glucose.Basal.cat,time) %>% summarise(glucose_mean = mean(Glucose))
p <- ggplot(long, aes(x=time, y=Glucose, group=StudyID, color=Mean.Glucose.Basal.cat)) +
        geom_line() +
        geom_line(data=grouped)
p
```