---
title: "IDEAS"
author: "Hailey Hampson"
output: html_document
date: '2024-12-12'
---
#1. Set up Libraries & Directores
```{r libraries, echo=F, include = F}
library(reprex)
library(tidyverse)
library(BiocManager)        
library(arsenal)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(Seurat)
library(future)
library(colorspace)
library(patchwork)
library(ggdendro)
library(cowplot)
library(ggpubr)
library(rstatix)
library(table1)
library(Biobase)
library(ReactomeGSA)
library(GSEABase)
library(msigdbr)
library(kableExtra)
library(knitr)
library(SingleCellExperiment)
library(fgsea)
library(EnhancedVolcano)
library(openxlsx)
library(BiocManager)
library(MAST)
library(ggrepel)
# library(qpcR)
library(ggpubr)
library(devtools)

suppressPackageStartupMessages({
  library(ggplot2)
  library(GGally)
  library(GSEABase)
  library(limma)
  library(reshape2)
  library(data.table)
  library(knitr)
  library(TxDb.Hsapiens.UCSC.hg19.knownGene)
  library(stringr)
  library(NMF)
  library(rsvd)
  library(RColorBrewer)
  library(MAST)
})

# install_github("Sun-lab/ideas")
library(ideas)

#options(mc.cores = detectCores() - 1) #if you have multiple cores to spin
options(mc.cores = 1)
knitr::opts_chunk$set(message = FALSE,error = FALSE,warning = FALSE,cache = FALSE,fig.width=8,fig.height=6)

RNGkind("L'Ecuyer-CMRG")
library(doParallel)
registerDoParallel(cores=6)


#Local file path
# dir.dat <- c("/Volumes/Peds Endo/Petter Bjornstad")
# dir.dat2 <- c("/Volumes/Peds Endo/Petter Bjornstad/scRNA/data_clean")
# dir.code <- c("/Users/hhampson/Documents/CHCO-Code/Petter Bjornstad/Liver analysis/Liver scRNAseq")
# dir.results <- c("/Users/hhampson/Documents/UW/1_Ongoing Projects/Liver scRNAseq/2_Results")

#Lambda file path
dir.dat <- c("/run/user/1026/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad")
dir.code <- c("/home/Github_Repo/CHCO-Code/Petter Bjornstad/Liver analysis/Liver scRNAseq")
dir.results <- c(fs::path(dir.dat,"Liver project/Results"))


plan()
future::plan("sequential")
options(future.globals.maxSize = 3e9)

#Load functions
source("IDEAS_Function.R")

```


#2. Load Kidney ScRNA 
```{r}
#Increase Memory
mem.maxVSize(64000000000)
#Local
# dir.dat <- c("/Users/hhampson/Dropbox/Bjornstad data")
# so_kidney_sc <- readRDS(fs::path(dir.dat,"Kidney scRNA","PB_90samples_Harmony_rpca_Fadhl_PhilApproved_091024.RDS"))
# load("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Exports/PB90_clinical_metadata.RData")
# so_kidney_sc <- AddMetaData(so_kidney_sc, so_meta_combined)
# rm(so_meta_combined)
# gc()

#Lambda
so_kidney_sc <- readRDS(fs::path(dir.dat,"scRNA","data_raw","PB_90samples_Harmony_rpca_Fadhl_PhilApproved_091024.RDS"))
load(fs::path(dir.dat,"Data Harmonization","Data Exports","PB90_clinical_metadata_12_10.RData"))
so_kidney_sc <- AddMetaData(so_kidney_sc, so_meta_combined)
rm(so_meta_combined)
gc()

# #Create senesence so in all cell types
# sens_genes <- c(sens_genes,"CDKN1A")
# sens_gene_in_data <- intersect(sens_genes, rownames(so_kidney_sc))
# # Subset the Seurat object to include only genes in sens_gene_in_data
# so_sens_all <- subset(so_kidney_sc, features = sens_gene_in_data)
# rm(so_kidney_sc)
# # saveRDS(so_sens_all,fs::path(dir.dat,"so_sens_genes_all_cells_KIDNEY.RDS"))
# # rm(so_sens_all)
# # 
# # #Load sens all cells
# # so_sens <- readRDS(fs::path(dir.dat,"so_sens_genes_all_cells_KIDNEY.RDS"))
# # dat <- so_sens@meta.data
# # so_diab <- subset(so_sens, diagnosis_of_diabetes == "Yes")
# # 
# #PT Cells
# so_sens_all@meta.data$PT <- ifelse(grepl("PT-",so_sens_all@meta.data$celltype_rpca),"PT","Non-PT")
# Idents(so_sens_all) <- so_sens_all$PT
# so_sens <- subset(so_sens_all, PT=="PT")
# # saveRDS(so_sens,fs::path(dir.dat,"so_sens_genes_PT_Cells_KIDNEY.RDS"))
# rm(so_sens_all,so_sens)
# so_sens_PT <- readRDS(fs::path(dir.dat,"Liver Project","so_sens_genes_PT_Cells_KIDNEY.RDS"))
# so_sens_PT@meta.data$group1 <- ifelse(so_sens_PT@meta.data$group=="Type 2 Diabetes" | so_sens_PT@meta.data$group=="Lean Control" ,"Yes","No")
# so_sens_PT1 <- subset(so_sens_PT, group1=="Yes")
# so_sens_PT@meta.data$group2 <- ifelse(so_sens_PT@meta.data$group=="Type 2 Diabetes","Yes","No")
# so_sens_PT2 <- subset(so_sens_PT, group2=="Yes")
# so_sens_PT3 <- subset(so_sens_PT, group=="Type 2 Diabetes")
# 
# 
# 
# #TAL Cells
# so_sens_all@meta.data$TAL <- ifelse(grepl("TAL",so_sens_all@meta.data$celltype_rpca),"TAL","Non-TAL")
# Idents(so_sens_all) <- so_sens_all$TAL
# so_sens <- subset(so_sens_all, TAL=="TAL")
# # saveRDS(so_sens,fs::path(dir.dat,"so_sens_genes_TAL_Cells_KIDNEY.RDS"))
# rm(so_sens_all,so_sens,so_sens_TAL,so_sens_TAL1)
# so_sens_TAL <- readRDS(fs::path(dir.dat,"Liver Project","so_sens_genes_TAL_Cells_KIDNEY.RDS"))
# so_sens_TAL@meta.data$group1 <- ifelse(so_sens_TAL@meta.data$group=="Type 2 Diabetes"| so_sens_TAL@meta.data$group=="Lean Control","Yes","No")
# so_sens_TAL1 <- subset(so_sens_TAL, group1=="Yes")
# so_sens_TAL@meta.data$group2 <- ifelse(so_sens_TAL@meta.data$group=="Type 2 Diabetes","Yes","No")
# so_sens_TAL2 <- subset(so_sens_TAL, group2=="Yes")
# so_sens_TAL3 <- subset(so_sens_TAL, group=="Type 2 Diabetes")
```

#3. IDEAS Analysis 
```{r}
count_matrix = so_kidney_sc@assays$RNA$counts
meta_cell    = so_kidney_sc@meta.data
meta_ind     = sim_data$meta_ind

var2test      = "phenotype"
var2adjust    = "RIN"
var2test_type = "binary"
var_per_cell  = "cell_rd"

```


