---
title: "Kidney scRNA for Jenny Kanter"
author: "Hailey Hampson"
date: "2024-10-09"
output: html_document
---

```{r libraries, echo=F, include = F}
library(tidyverse)
library(BiocManager)
library(arsenal)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(Seurat)
library(future)
library(colorspace)
library(patchwork)
library(ggdendro)
library(cowplot)
library(ggpubr)
library(rstatix)
library(table1)
library(Biobase)
library(ReactomeGSA)
library(GSEABase)
library(msigdbr)
library(kableExtra)
library(knitr)

#Increase Memory
mem.maxVSize(64000000000)

#Set up directories
dir.dat <- c("/Users/hhampson/Dropbox/Bjornstad data")
```

# scRNA
```{r echo = F}
# Kidney scRNA data processing
so_kidney_sc <- readRDS(fs::path(dir.dat,"Kidney scRNA","PB_90samples_Harmony_rpca_Fadhl_PhilApproved_091024.RDS"))

# Add missing covariate meta data to Seurat object
meta_raw <- read.csv(fs::path(dir.dat,"Clinical Data","renal_clearance_biopsy.csv"))

#Filter out meta data participants without sc 
record_ids <- unique(so_kidney_sc@meta.data$record_id)
meta_raw <- meta_raw %>% 
  filter(record_id %in% record_ids) %>% 
  dplyr::select(-record_id)

#Merge new metadata with 
meta_kidney_sc <-  tidylog::left_join(so_kidney_sc@meta.data, meta_raw,by="cryostor_id")

#Check there are no duplicates
length(which(duplicated(meta_kidney_sc$barcode)))

#Add rownames back to metadata to merge back into saurat object 
rownames(meta_kidney_sc) <- rownames(so_kidney_sc@meta.data)

# Add new meta data to so 
so_kidney_sc <- AddMetaData(so_kidney_sc, meta_kidney_sc)

# #Filter to baseline visits only
# meta_kidney_sc <- meta_kidney_sc %>%
#   filter(visit!="12_months_post_surgery")
# 
# #Filter to only RH/RH2, IMPROVE & CROCODILE
# meta_kidney_sc <-  meta_kidney_sc %>%
#   filter(grepl("CRC",record_id) | grepl("RH",record_id) | grepl("IT",record_id))

so_kidney_sc <- NormalizeData(so_kidney_sc)
so_kidney_sc <- ScaleData(so_kidney_sc)
# PCA
so_kidney_sc <- RunPCA(so_kidney_sc, features = VariableFeatures(object = so_kidney_sc))
ElbowPlot(so_kidney_sc)
# Cluster cells
so_kidney_sc <- FindNeighbors(so_kidney_sc)
so_kidney_sc <- FindClusters(so_kidney_sc)
# Perform UMAP and tSNE
so_kidney_sc <- RunUMAP(so_kidney_sc, dims = 1:15)
DimPlot(so_kidney_sc, reduction = "umap") 
```

## Sex (M/F)
### Descriptive table
```{r echo = F}
# Descriptive stats
kidney_meta_raw_sc <- meta_kidney_sc %>%
  filter(cryostor_id!="")
form <- paste("sex", paste(colnames(kidney_meta_raw_sc)[c(15,18:27)], collapse = " + "), sep = " ~ ")

summary(arsenal::tableby(formula = as.formula(form), data = kidney_meta_raw_sc, test = F))

```


## SGLT2i Y/N
### Descriptive table
```{r echo = F}
# Descriptive stats
kidney_meta_raw_sc <- meta_raw %>%
  filter(Cryostor_ID!="")
form <- paste("sglt2i_ever", paste(colnames(kidney_meta_raw_sc)[c(15,18:25)], collapse = " + "), sep = " ~ ")

summary(arsenal::tableby(formula = as.formula(form), data = kidney_meta_raw_sc, test = F))

```


## Stratified UMAP scRNA 
### Obese vs. Obese + T2D
```{r echo = F}
so_kidney_sc <- RunUMAP(so_kidney_sc, dims = 1:15)
DimPlot(so_kidney_sc, reduction = "umap", group.by = "sex") 

```

### MASLD Y/N
```{r echo = F}
so_kidney_sc <- RunUMAP(so_kidney_sc, dims = 1:15)
DimPlot(so_kidney_sc, reduction = "umap", group.by = "diagnosis_of_MASLD") 

```

### OSA Y/N
```{r echo = F}
so_kidney_sc <- RunUMAP(so_kidney_sc, dims = 1:15)
DimPlot(so_kidney_sc, reduction = "umap", group.by = "diagnosis_of_osa") 

```

### GLP-1RA Y/N
```{r echo = F}
so_kidney_sc <- RunUMAP(so_kidney_sc, dims = 1:15)
DimPlot(so_kidney_sc, reduction = "umap", group.by = "glp1agonist") 

```

### Insulin Y/N
```{r echo = F}
so_kidney_sc <- RunUMAP(so_kidney_sc, dims = 1:15)
DimPlot(so_kidney_sc, reduction = "umap", group.by = "insulin") 

```

### Kidney disease Y/N
```{r echo = F}
so_kidney_sc <- RunUMAP(so_kidney_sc, dims = 1:15)
DimPlot(so_kidney_sc, reduction = "umap", group.by = "diagnosis_of_kidney_disease") 

```

## Differential Expression by Group

## Top 2000 genes
```{r}
de.markers(so, NULL, "Group", id1 = "T1D", id2 = "HC", "PT", "_top")
m_top <- m_top %>% head(2000)
```


### Obese vs. Obese + T2D
```{r}
so_kidney_sc@meta.data$hepatocyte <- ifelse(grepl("Hepatocyte",meta_liver_sc$celltype),"Hepatocyte","Non-Hepatocyte")
genes <- unique(rownames(so_kidney_sc))
Idents(so_kidney_sc) <- so_kidney_sc$celltype
de.markers(so_kidney_sc, genes, "diagnosis_of_diabetes", id2 = "No", id1 = "Yes", "Hepatocyte1", "")
de.markers(so_kidney_sc, genes, "diagnosis_of_diabetes", id2 = "No", id1 = "Yes", "Hepatocyte2", "")
de.markers(so_kidney_sc, genes, "diagnosis_of_diabetes", id2 = "No", id1 = "Yes", "Hepatocyte3", "")

Idents(so_kidney_sc) <- so_kidney_sc$hepatocyte
de.markers(so_kidney_sc, genes, "diagnosis_of_diabetes", id2 = "No", id1 = "Yes", "Hepatocyte", "")

```

### MASLD Y/N
```{r}
Idents(so_kidney_sc) <- so_kidney_sc$celltype
de.markers(so_kidney_sc, genes, "diagnosis_of_MASLD", id2 = "No", id1 = "Yes", "Hepatocyte1", "")
de.markers(so_kidney_sc, genes, "diagnosis_of_MASLD", id2 = "No", id1 = "Yes", "Hepatocyte2", "")
de.markers(so_kidney_sc, genes, "diagnosis_of_MASLD", id2 = "No", id1 = "Yes", "Hepatocyte3", "")

Idents(so_kidney_sc) <- so_kidney_sc$hepatocyte
de.markers(so_kidney_sc, genes, "diagnosis_of_MASLD", id2 = "No", id1 = "Yes", "Hepatocyte", "")

```

### OSA Y/N
```{r}
Idents(so_kidney_sc) <- so_kidney_sc$celltype
de.markers(so_kidney_sc, genes, "diagnosis_of_osa", id2 = "No", id1 = "Yes", "Hepatocyte1", "")
de.markers(so_kidney_sc, genes, "diagnosis_of_osa", id2 = "No", id1 = "Yes", "Hepatocyte2", "")
de.markers(so_kidney_sc, genes, "diagnosis_of_osa", id2 = "No", id1 = "Yes", "Hepatocyte3", "")

Idents(so_kidney_sc) <- so_kidney_sc$hepatocyte
de.markers(so_kidney_sc, genes, "diagnosis_of_osa", id2 = "No", id1 = "Yes", "Hepatocyte", "")

```

### GLP-1RA Y/N
```{r}
Idents(so_kidney_sc) <- so_kidney_sc$celltype
de.markers(so_kidney_sc, genes, "glp1agonist", id2 = "No", id1 = "Yes", "Hepatocyte1", "")
de.markers(so_kidney_sc, genes, "glp1agonist", id2 = "No", id1 = "Yes", "Hepatocyte2", "")
de.markers(so_kidney_sc, genes, "glp1agonist", id2 = "No", id1 = "Yes", "Hepatocyte3", "")

Idents(so_kidney_sc) <- so_kidney_sc$hepatocyte
de.markers(so_kidney_sc, genes, "glp1agonist", id2 = "No", id1 = "Yes", "Hepatocyte", "")

```

### Insulin Y/N
```{r}
# Idents(so_kidney_sc) <- so_kidney_sc$celltype
# de.markers(so_kidney_sc, genes, "insulin", id2 = "No", id1 = "Yes", "Hepatocyte1", "")
# de.markers(so_kidney_sc, genes, "insulin", id2 = "No", id1 = "Yes", "Hepatocyte2", "")
# de.markers(so_kidney_sc, genes, "insulin", id2 = "No", id1 = "Yes", "Hepatocyte3", "")
# 
# Idents(so_kidney_sc) <- so_kidney_sc$hepatocyte
# de.markers(so_kidney_sc, genes, "insulin", id2 = "No", id1 = "Yes", "Hepatocyte", "")
#All no's for insulin
```

### Kidney disease Y/N
```{r}
# Idents(so_kidney_sc) <- so_kidney_sc$celltype
# de.markers(so_kidney_sc, genes, "diagnosis_of_kidney_disease", id2 = "No", id1 = "Yes", "Hepatocyte1", "")
# de.markers(so_kidney_sc, genes, "diagnosis_of_kidney_disease", id2 = "No", id1 = "Yes", "Hepatocyte2", "")
# de.markers(so_kidney_sc, genes, "diagnosis_of_kidney_disease", id2 = "No", id1 = "Yes", "Hepatocyte3", "")
# 
# Idents(so_kidney_sc) <- so_kidney_sc$hepatocyte
# de.markers(so_kidney_sc, genes, "diagnosis_of_kidney_disease", id2 = "No", id1 = "Yes", "Hepatocyte", "")
#All no's for insulin
```

## Figures
### Obese vs. Obese + T2D
```{r}
Idents(so_kidney_sc) <- so_kidney_sc$celltype
pt.plot_table <- dp.formatted(seurat_object = so_kidney_sc, genes = genes, group.by = "diagnosis_of_diabetes",
                              celltype = "Hepatocyte1", m = m)
pt.plot_table <- dp.formatted(seurat_object = so_kidney_sc, genes = genes, group.by = "diagnosis_of_diabetes",
                              celltype = "Hepatocyte2", m = m)
pt.plot_table <- dp.formatted(seurat_object = so_kidney_sc, genes = genes, group.by = "diagnosis_of_diabetes",
                              celltype = "Hepatocyte3", m = m)
Idents(so_kidney_sc) <- so_kidney_sc$hepatocyte
pt.plot_table <- dp.formatted(seurat_object = so_kidney_sc, genes = genes, group.by = "diagnosis_of_diabetes",
                              celltype = "Hepatocyte", m = m)
```

### MASLD Y/N
```{r}
split.vp(seurat_object = so, genes = genes_subset, filepath = "/Users/hhampson/Library/Mobile Documents/com~apple~CloudDocs/UW/1_Ongoing Projects/Liver scRNAseq")
Idents(so_kidney_sc) <- so_kidney_sc$celltype
pt.plot_table <- dp.formatted(seurat_object = so_kidney_sc, genes = genes, group.by = "diagnosis_of_diabetes",
                              celltype = "Hepatocyte1", m = m)
pt.plot_table <- dp.formatted(seurat_object = so_kidney_sc, genes = genes, group.by = "diagnosis_of_diabetes",
                              celltype = "Hepatocyte2", m = m)
pt.plot_table <- dp.formatted(seurat_object = so_kidney_sc, genes = genes, group.by = "diagnosis_of_diabetes",
                              celltype = "Hepatocyte3", m = m)
Idents(so_kidney_sc) <- so_kidney_sc$hepatocyte
pt.plot_table <- dp.formatted(seurat_object = so_kidney_sc, genes = genes, group.by = "diagnosis_of_diabetes",
                              celltype = "Hepatocyte", m = m)
```

### OSA Y/N
```{r}
split.vp(seurat_object = so, genes = genes_subset, filepath = "/Users/hhampson/Library/Mobile Documents/com~apple~CloudDocs/UW/1_Ongoing Projects/Liver scRNAseq")
Idents(so_kidney_sc) <- so_kidney_sc$celltype
pt.plot_table <- dp.formatted(seurat_object = so_kidney_sc, genes = genes, group.by = "diagnosis_of_diabetes",
                              celltype = "Hepatocyte1", m = m)
pt.plot_table <- dp.formatted(seurat_object = so_kidney_sc, genes = genes, group.by = "diagnosis_of_diabetes",
                              celltype = "Hepatocyte2", m = m)
pt.plot_table <- dp.formatted(seurat_object = so_kidney_sc, genes = genes, group.by = "diagnosis_of_diabetes",
                              celltype = "Hepatocyte3", m = m)
Idents(so_kidney_sc) <- so_kidney_sc$hepatocyte
pt.plot_table <- dp.formatted(seurat_object = so_kidney_sc, genes = genes, group.by = "diagnosis_of_diabetes",
                              celltype = "Hepatocyte", m = m)
```


