---
title: "TODAY Somalogic baseline analyses - elastic net Cox models"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)
library(survival)
library(broom)
library(plsRcox)
library(forestmodel)
library(survC1)
library(naniar)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/Peds Endo/Petter Bjornstad/TODAY subaward/"
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r, include=FALSE}
# load somalogic data, with QC samples already excluded
load("./Somalogic data raw/soma.Rdata")

# load analyte info
load("./Somalogic data raw/analytes.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# load baseline risk factors
load("./Clinical data/TODAY/baserisk.Rdata")

# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)

# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# merge in complication data
base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# merge in baseline risk factors
base <- merge(base, baserisk, by="releaseid",all.x=T, all.y=F)

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# are there proteins with low variability?
no_var = caret::nearZeroVar(base[,seq])
# none

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)

# scale by SD
base_log_scale <- base_log
predictors <- colnames(base_log[seq])
for (i in 1:length(predictors)) {
  base_log_scale[predictors[i]] <- base_log_scale[predictors[i]]/sd(base_log[,paste0(predictors[i])])
}
```

# Severe albuminuria - retained proteins

## 5-fold cross validation

```{r, include=FALSE, comment=""}
source("~/Documents/Github/CHCO-Code/Petter Bjornstad/TODAY proteomics metabolomics/Proteomics analyses/easy_elasticnet.R")
base_log_scale_nozero <- base_log_scale[!base_log_scale$DAYSTOMAC == 0,]

mac_select = easy_elasticnet(data = base_log_scale_nozero,outcome = "MAC",
                           predictors = base_log_scale[,seq], out = "min.error",
                           model_type = "cox",time = "DAYSTOMAC", cv_method="kfold", folds = 5)
retained_vars = analytes[analytes$AptName %in% mac_select, c("Target","TargetFullName")]
```

```{r, include=TRUE, comment=""}
kable(retained_vars)
```

## 3-fold cross-validation

```{r, include=FALSE, comment=""}
mac_select = easy_elasticnet(data = base_log_scale_nozero,outcome = "MAC",
                           predictors = base_log_scale[,seq], out = "min.error",
                           model_type = "cox",time = "DAYSTOMAC", cv_method="kfold", folds = 3)
retained_vars = analytes[analytes$AptName %in% mac_select, c("Target","TargetFullName")]
```

```{r, include=TRUE, comment=""}
kable(retained_vars)
```

## 10-fold cross-validation

```{r, include=FALSE, comment=""}
mac_select = easy_elasticnet(data = base_log_scale_nozero,outcome = "MAC",
                           predictors = base_log_scale[,seq], out = "min.error",
                           model_type = "cox",time = "DAYSTOMAC", cv_method="kfold", folds = 10)
retained_vars = analytes[analytes$AptName %in% mac_select, c("Target","TargetFullName")]
```

```{r, include=TRUE, comment=""}
kable(retained_vars)
```

# Elevated albuminuria - retained proteins

```{r, include=FALSE, comment=""}
#base_log_scale_nozero <- base_log_scale[!base_log_scale$DAYSTOMIC == 0,]

#mic_select = easy_elasticnet(data = base_log_scale_nozero,outcome = "MIC",
#                           predictors = base_log_scale[,seq], out = "min.error",
#                           model_type = "cox",time = "DAYSTOMIC", cv_method="kfold", folds = 5)
#retained_vars = analytes[analytes$AptName %in% mic_select, c("Target","TargetFullName")]
```

```{r, include=TRUE, comment=""}
#kable(retained_vars)
```
