---
title: "TODAY Somalogic descriptive statistics"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)
library(data.table)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
}
knitr::opts_knit$set(root.dir = home_dir)
setwd(home_dir)
```

```{r, include=FALSE}
# load somalogic data, with QC samples already excluded
load("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/Somalogic data raw/soma.Rdata")

# load analyte info
load("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/Somalogic data raw/analytes.Rdata")

# load comorbidity data
load("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/Clinical data/comorb.Rdata")

# load baseline risk factors
load("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/Clinical data/TODAY/baserisk.Rdata")

# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)
#base <- data.table(soma)
#base <- base %>% setkey(releaseid,Date.Drawn) %>% arrange(releaseid,Date.Drawn)
#base <- base[J(unique(releaseid)), mult = "first"]

# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# merge in complication data
base <- left_join(base, comorb, by="releaseid")

# merge in baseline risk factors
base <- left_join(base, baserisk)

# only keep observations with nonmissing values of covariates
# otherwise size of contrast matrix will be incorrect
base <- base %>% filter(!is.na(HbA1c) & !is.na(log_trig) & !is.na(sbp) & !is.na(si_1_ins0))

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# are there proteins with low variability?
no_var = caret::nearZeroVar(base[,seq])
# none

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)

# df for descriptive statistics
t1data <- base
t1data$MIC.OR.MAC <- as.factor(t1data$MIC.OR.MAC)
t1data$MAC <- as.factor(t1data$MAC)
t1data$MAC0 <- as.factor(t1data$MAC0)
t1data$MIC <- as.factor(t1data$MIC)
t1data$MIC0 <- as.factor(t1data$MIC0)
t1data$HYP <- as.factor(t1data$HYP)
t1data$HYP0 <- as.factor(t1data$HYP0)
t1data$RAPID <- as.factor(t1data$RAPID)
t1data$RAPID0 <- as.factor(t1data$RAPID0)
t1data$NEURO <- as.factor(t1data$NEURO)
t1data$RETINO <- as.factor(t1data$RETINO)
t1data$GLYC <- as.factor(t1data$GLYC)
t1data$HTN <- as.factor(t1data$HTN)
t1data$sex <- as.factor(t1data$sex)
t1data$tg <- exp(t1data$log_trig)
t1data$tx <- as.factor(t1data$tx)
t1data$houseinc <- as.factor(t1data$houseinc)
t1data$race <- as.factor(t1data$race)
t1data$group[t1data$MIC==1 & t1data$MAC==0]<- "MIC"
t1data$group[t1data$MAC==1]<- "MAC"
t1data$group[t1data$MAC==0 & t1data$MIC==0]<- "None"
t1data$UAlbCreat <- t1data$UAlbCreat*1000
t1data$ge25yrs_baseline <- ifelse(t1data$AGEBASE >= 25, 1, 0)
# read in age at last visit
load("./Clinical data/TODAY/clinical_data_long.Rdata")
long <- long %>% group_by(releaseid) %>% filter(row_number()==1) %>% select(releaseid, fup_years, age_last_visit, ge25yrs)
t1data <- left_join(t1data, long, by = "releaseid")
t1data$ge26yrs <- ifelse(t1data$age_last_visit >= 26, 1, 0)
t1data$HTN0 <- as.factor(t1data$HTN0)
```

# Results

## Descriptive statistics

### Overall

```{r echo=FALSE, include=FALSE}
t1vars <- c("MIC0","MAC0","HYP0","RAPID0","HTN0","MIC.OR.MAC","MAC","MIC","HYP","RAPID","HTN","NEURO","RETINO","GLYC",
                                          "HbA1c","trig","sbp","dbp","map","si_1_ins0","glu0min","codi","ins0min",
                                          "AGEBASE","sex","tg","dxtime",
                                          "bmi","txdesc","houseincdesc","racedesc","UAlbCreat","ge25yrs", "ge26yrs",
                                          "SerumCreat","serumcystc","EstCreatClear")

t_overall <- CreateTableOne(data=t1data, vars=t1vars)
t_overall <- print(t_overall, nonnormal=c("UAlbCreat","dxtime","tg","HbA1c"))
```

```{r echo=FALSE, include=TRUE}
kable(t_overall)
```

### By DKD

```{r echo=FALSE, include=FALSE}
t1 <- CreateTableOne(data=t1data, vars=t1vars, strata="group")
t1 <- print(t1, nonnormal=c("UAlbCreat","dxtime","tg","HbA1c"))

```

```{r echo=FALSE, include=TRUE}
kable(t1)
```

### By glycemic outcome

```{r echo=FALSE, include=FALSE}
t1_glyc <- CreateTableOne(data=t1data, vars=t1vars, strata="GLYC")
t1_glyc <- print(t1_glyc, nonnormal=c("UAlbCreat","dxtime","tg","HbA1c"))
```

```{r echo=FALSE, include=TRUE}
kable(t1_glyc)
```

```{r}
file.copy("/Users/pylell/Documents/GitHub/CHCO-Code/Petter Bjornstad/TODAY proteomics metabolomics/Proteomics analyses/TODAY-somalogic-descriptive-statistics.html",
          "/Users/pylell/Dropbox/TODAY HTN and DKD output/TODAY-somalogic-descriptive-statistics.html",overwrite = TRUE)

file.copy("/Users/pylell/Documents/GitHub/CHCO-Code/Petter Bjornstad/TODAY proteomics metabolomics/Proteomics analyses/TODAY-somalogic-descriptive-statistics.html",
          "/Users/pylell/Dropbox/TODAY glycemic manuscript [shared]/Analysis output/TODAY-somalogic-descriptive-statistics.html",overwrite = TRUE)

file.copy("/Users/pylell/Documents/GitHub/CHCO-Code/Petter Bjornstad/TODAY proteomics metabolomics/Proteomics analyses/TODAY-somalogic-descriptive-statistics.html",
          "/Users/pylell/Dropbox/IMPROVE, Teen-LABS, TODAY combined analysis/TODAY results/TODAY-somalogic-descriptive-statistics.html",overwrite = TRUE)
```