---
title: "TODAY Somalogic baseline analyses - elastic net Cox models for glycemia with nested CV"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
knit: (function(rmdfile, ...) { rmarkdown::render(rmdfile, output_dir='/Users/pylell/Dropbox/TODAY glycemic manuscript [shared]/') })
output: rtf_document
---

```{r setup, include=FALSE}
library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)
library(survival)
library(broom)
library(plsRcox)
library(forestmodel)
library(survC1)
library(naniar)
library(rms)
library(readxl)
library(forester)
library(grid)
library(forestploter)
library(doParallel)
library(foreach)
library(readr)
library(nestedcv)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward"
}
knitr::opts_knit$set(root.dir = home_dir)

```

```{r, include=FALSE}
setwd(home_dir)
# load somalogic data, with QC samples already excluded
load("./Somalogic data raw/soma.Rdata")

# load analyte info
load("./Somalogic data raw/analytes.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# load baseline risk factors
load("./Clinical data/TODAY/baserisk.Rdata")

# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)

# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# merge in complication data
base <- left_join(base, comorb, by="releaseid")

# merge in baseline risk factors
base <- left_join(base, baserisk, by="releaseid")

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)
seq_names <- colnames(base[,seq])

# are there proteins with low variability?
no_var = caret::nearZeroVar(base[,seq])
# none

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)

# scale by SD
base_log_scale <- base_log
predictors <- colnames(base_log[seq])
for (i in 1:length(predictors)) {
  base_log_scale[,paste0(predictors[i])] <- base_log_scale[,paste0(predictors[i])]/sd(unlist(base_log[,paste0(predictors[i])]))
}

source("~/Documents/Github/CHCO-Code/Petter Bjornstad/TODAY proteomics metabolomics/Proteomics analyses/easy_elasticnet.R")
```

# Loss of glycemic control

## Elastic net 

### Model evaluation using nested cross-validation

```{r nestedcv,echo=TRUE, cache=TRUE, include = FALSE }
set.seed(3654)
file.remove("/Users/pylell/Dropbox/TODAY glycemic manuscript [shared]/Analysis output/glycemia_feature_selection.csv")

data_model <- base_log_scale %>% 
    select(releaseid, GLYC, DAYSTOGLYC, seq_names)  %>% ungroup()

y <- data_model %>% select(GLYC, DAYSTOGLYC)
x <- data_model %>% select(all_of(seq_names))

# screening function for univariable cox models
# should take x and y and return character vector of names of filtered predictors
cox_screen <- function(x, y) {
  data <- cbind(y, x)
  data <- cbind(data, base_log_scale$bmi, base_log_scale$si_1_ins0, base_log_scale$AGEBASE, base_log_scale$sex)
  predictors <- seq_names

  result_GLYC <- NULL
  for (i in 1:length(predictors)) {
    print(i)
    form <- paste0("Surv(DAYSTOGLYC, GLYC)~",predictors[i],"+bmi+si_1_ins0+AGEBASE+sex")
    mod <- coxph(data = base_log_scale, formula = as.formula(form))
    tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
    tidymod <- tidymod[1,]
    result_GLYC <- rbind(result_GLYC,tidymod)
  }
  result_GLYC$adj.p.value <- p.adjust(result_GLYC$p.value, "fdr")
  result_GLYC$AptName <- result_GLYC$term
  result_GLYC <- merge(result_GLYC,analytes,by="AptName",all.x = T, all.y = F)
  result_GLYC <- result_GLYC[order(result_GLYC$p.value),] 
  result_GLYC <- result_GLYC[1:100,]
  result_GLYC_vec_char <- result_GLYC$AptName
  result_GLYC_vec <- which(colnames(x) %in% result_GLYC_vec_char)
  return(result_GLYC_vec)
}

# test the screening function
y <- Surv(base_log_scale$DAYSTOGLYC, base_log_scale$GLYC)
result_GLYC <- cox_screen(x, y)

#res <- nestcv.glmnet(y = as.matrix(y), x = as.matrix(x),
#                         family = "cox", cv.cores = 16, outer_method = "cv", filterFUN = cox_screen, n_outer_folds = 10, 
#                     n_inner_folds = 10, final = T, verbose = T)
res <- nestcv.glmnet(y = as.matrix(y), x = as.matrix(x),
                         family = "cox", cv.cores = 16, outer_method = "LOOCV", filterFUN = cox_screen,  
                     n_inner_folds = 10, final = T, verbose = T)
selected_vars <- res$final_coef
selected_vars$AptName <- row.names(selected_vars)
selected_vars$Target <- analytes[analytes$AptName %in% selected_vars$AptName, ]$Target
```

```{r, comment = ""}
summary(res)
```

