---
title: "TODAY Somalogic baseline analyses - adjusted linear models"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)
library(data.table)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
}
knitr::opts_knit$set(root.dir = home_dir)
setwd(home_dir)
```

```{r, include=FALSE}
# load somalogic data, with QC samples already excluded
load("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/Somalogic data raw/soma.Rdata")

# load analyte info
load("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/Somalogic data raw/analytes.Rdata")

# load comorbidity data
load("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/Clinical data/comorb.Rdata")

# load baseline risk factors
load("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/Clinical data/TODAY/baserisk.Rdata")

# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)
#base <- data.table(soma)
#base <- base %>% setkey(releaseid,Date.Drawn) %>% arrange(releaseid,Date.Drawn)
#base <- base[J(unique(releaseid)), mult = "first"]

# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# merge in complication data
base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# merge in baseline risk factors
base <- merge(base, baserisk, by="releaseid",all.x=T, all.y=F)

# only keep observations with nonmissing values of covariates
# otherwise size of contrast matrix will be incorrect
base <- base %>% filter(!is.na(HbA1c) & !is.na(log_trig) & !is.na(sbp) & !is.na(si_1_ins0))

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# are there proteins with low variability?
no_var = caret::nearZeroVar(base[,seq])
# none

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)
```

```{r, include=FALSE}
# MAC alone
# Make design matrix
MAC_contrast <- model.matrix(~MAC+HbA1c+log_trig+sbp+si_1_ins0,base)
# moderated t-tests with and without FDR adjustment
ymat <- t(base_log[,seq])
fit <- lmFit(ymat,MAC_contrast)
fit <- eBayes(fit)
results_MAC <- topTable(fit,coef = 2,number = nrow(ymat))
results_MAC$AptName <- row.names(results_MAC)
results_MAC <- merge(results_MAC,analytes,by="AptName",all.x = T, all.y = F)
results_MAC <- results_MAC[order(results_MAC$P.Value),] 

# MIC alone
# Make design matrix
MIC_contrast <- model.matrix(~MIC+HbA1c+log_trig+sbp+si_1_ins0,base)
# moderated t-tests with and without FDR adjustment
ymat <- t(base_log[,seq])
fit <- lmFit(ymat,MIC_contrast)
fit <- eBayes(fit)
results_MIC <- topTable(fit,coef = 2,number = nrow(ymat))
results_MIC$AptName <- row.names(results_MIC)
results_MIC <- merge(results_MIC,analytes,by="AptName",all.x = T, all.y = F)
results_MIC <- results_MIC[order(results_MIC$P.Value),] 

# hyperfiltration
hyperfilt_contrast <- model.matrix(~HYP+HbA1c+log_trig+sbp+si_1_ins0,base)
# moderated t-tests with and without FDR adjustment
y <- base_log %>% filter(!is.na(base_log$HYP))
ymat <- t(y[,seq])
fit <- lmFit(ymat,hyperfilt_contrast)
fit <- eBayes(fit)
results_hyperfilt <- topTable(fit,coef = 2,number = nrow(ymat))
results_hyperfilt$AptName <- row.names(results_hyperfilt)
results_hyperfilt <- merge(results_hyperfilt,analytes,by="AptName",all.x = T, all.y = F)
results_hyperfilt <- results_hyperfilt[order(results_hyperfilt$P.Value),] 
ymat <- NULL
fit <- NULL

# rapid eGFR decline
rapid_contrast <- model.matrix(~RAPID+HbA1c+log_trig+sbp+si_1_ins0,base)
# moderated t-tests with and without FDR adjustment
y <- base_log %>% filter(!is.na(base_log$RAPID))
ymat <- t(y[,seq])
fit <- lmFit(ymat,rapid_contrast)
fit <- eBayes(fit)
results_rapid <- topTable(fit,coef = 2,number = nrow(ymat))
results_rapid$AptName <- row.names(results_rapid)
results_rapid <- merge(results_rapid,analytes,by="AptName",all.x = T, all.y = F)
results_rapid <- results_rapid[order(results_rapid$P.Value),] 
ymat <- NULL
fit <- NULL

# hypertension with SBP
htn_bp_contrast <- model.matrix(~HTN+HbA1c+log_trig+sbp+si_1_ins0,base)
# moderated t-tests with and without FDR adjustment
y <- base_log %>% filter(!is.na(base_log$HTN))
ymat <- t(y[,seq])
fit <- lmFit(ymat,htn_bp_contrast)
fit <- eBayes(fit)
results_htn_bp <- topTable(fit,coef = 2,number = nrow(ymat))
results_htn_bp$AptName <- row.names(results_htn_bp)
results_htn_bp <- merge(results_htn_bp,analytes,by="AptName",all.x = T, all.y = F)
results_htn_bp <- results_htn_bp[order(results_htn_bp$P.Value),] 
ymat <- NULL
fit <- NULL

# hypertension
# omit SBP
htn_contrast <- model.matrix(~HTN+HbA1c+log_trig+si_1_ins0,base)
# moderated t-tests with and without FDR adjustment
y <- base_log %>% filter(!is.na(base_log$HTN))
ymat <- t(y[,seq])
fit <- lmFit(ymat,htn_contrast)
fit <- eBayes(fit)
results_htn <- topTable(fit,coef = 2,number = nrow(ymat))
results_htn$AptName <- row.names(results_htn)
results_htn <- merge(results_htn,analytes,by="AptName",all.x = T, all.y = F)
results_htn <- results_htn[order(results_htn$P.Value),] 
ymat <- NULL
fit <- NULL

# neuropathy
neuro_contrast <- model.matrix(~NEURO+HbA1c+log_trig+sbp+si_1_ins0,base)
# moderated t-tests with and without FDR adjustment
y <- base_log %>% filter(!is.na(base_log$NEURO))
ymat <- t(y[,seq])
fit <- lmFit(ymat,neuro_contrast)
fit <- eBayes(fit)
results_neuro <- topTable(fit,coef = 2,number = nrow(ymat))
results_neuro$AptName <- row.names(results_neuro)
results_neuro <- merge(results_neuro,analytes,by="AptName",all.x = T, all.y = F)
results_neuro <- results_neuro[order(results_neuro$P.Value),] 
ymat <- NULL
fit <- NULL

# retinopathy
retino_contrast <- model.matrix(~RETINO+HbA1c+log_trig+sbp+si_1_ins0,base)
# moderated t-tests with and without FDR adjustment
y <- base_log %>% filter(!is.na(base_log$RETINO))
ymat <- t(y[,seq])
fit <- lmFit(ymat,retino_contrast)
fit <- eBayes(fit)
results_retino <- topTable(fit,coef = 2,number = nrow(ymat))
results_retino$AptName <- row.names(results_retino)
results_retino <- merge(results_retino,analytes,by="AptName",all.x = T, all.y = F)
results_retino <- results_retino[order(results_retino$P.Value),] 
ymat <- NULL
fit <- NULL

# glycemic failure
# omit A1c
glyc_contrast <- model.matrix(~GLYC+bmi+si_1_ins0,base)
# moderated t-tests with and without FDR adjustment
y <- base_log %>% filter(!is.na(base_log$GLYC))
ymat <- t(y[,seq])
fit <- lmFit(ymat,glyc_contrast)
fit <- eBayes(fit)
results_glyc <- topTable(fit,coef = 2,number = nrow(ymat))
results_glyc$AptName <- row.names(results_glyc)
results_glyc <- merge(results_glyc,analytes,by="AptName",all.x = T, all.y = F)
results_glyc <- results_glyc[order(results_glyc$P.Value),] 
ymat <- NULL
fit <- NULL

# glycemic failure
# with A1c
glyc_a1c_contrast <- model.matrix(~GLYC+HbA1c+si_1_ins0+bmi,base)
# moderated t-tests with and without FDR adjustment
y <- base_log %>% filter(!is.na(base_log$GLYC))
ymat <- t(y[,seq])
fit <- lmFit(ymat,glyc_a1c_contrast)
fit <- eBayes(fit)
results_glyc_a1c <- topTable(fit,coef = 2,number = nrow(ymat))
results_glyc_a1c$AptName <- row.names(results_glyc_a1c)
results_glyc_a1c <- merge(results_glyc_a1c,analytes,by="AptName",all.x = T, all.y = F)
results_glyc_a1c <- results_glyc_a1c[order(results_glyc_a1c$P.Value),] 
ymat <- NULL
fit <- NULL

# write all results to file
wb <- createWorkbook()

addWorksheet(wb,"MAC_moderated_FDR")
writeData(wb,"MAC_moderated_FDR",results_MAC,rowNames = F)

addWorksheet(wb,"MIC_moderated_FDR")
writeData(wb,"MIC_moderated_FDR",results_MIC,rowNames = F)

addWorksheet(wb,"hyperfilt_moderated_FDR")
writeData(wb,"hyperfilt_moderated_FDR",results_hyperfilt,rowNames = F)

addWorksheet(wb,"rapid_moderated_FDR")
writeData(wb,"rapid_moderated_FDR",results_rapid,rowNames = F)

addWorksheet(wb,"htn_with_SBP_moderated_FDR")
writeData(wb,"htn_with_SBP_moderated_FDR",results_htn_bp,rowNames = F)

addWorksheet(wb,"htn_moderated_FDR")
writeData(wb,"htn_moderated_FDR",results_htn,rowNames = F)

addWorksheet(wb,"neuro_moderated_FDR")
writeData(wb,"neuro_moderated_FDR",results_neuro,rowNames = F)

addWorksheet(wb,"retino_moderated_FDR")
writeData(wb,"retino_moderated_FDR",results_retino,rowNames = F)

addWorksheet(wb,"glyc_with_a1c_moderated_FDR")
writeData(wb,"glyc_with_a1c_moderated_FDR",results_glyc_a1c,rowNames = F)

addWorksheet(wb,"glyc_moderated_FDR")
writeData(wb,"glyc_moderated_FDR",results_glyc,rowNames = F)

saveWorkbook(wb,"./Results/Linear and Cox models/TODAY somalogic limma baseline adjusted.xlsx",overwrite = TRUE)

```

# Results

## Descriptive statistics

### By DKD

```{r echo=FALSE, include=FALSE}
# add table of count of outcomes
t1data <- base
t1data$MIC.OR.MAC <- as.factor(t1data$MIC.OR.MAC)
t1data$MAC <- as.factor(t1data$MAC)
t1data$MIC <- as.factor(t1data$MIC)
t1data$HYP <- as.factor(t1data$HYP)
t1data$RAPID <- as.factor(t1data$RAPID)
t1data$NEURO <- as.factor(t1data$NEURO)
t1data$RETINO <- as.factor(t1data$RETINO)
t1data$GLYC <- as.factor(t1data$GLYC)
t1data$HTN <- as.factor(t1data$HTN)
t1data$sex <- as.factor(t1data$sex)
t1data$tg <- exp(t1data$log_trig)
t1data$tx <- as.factor(t1data$tx)
t1data$houseinc <- as.factor(t1data$houseinc)
t1data$race <- as.factor(t1data$race)
t1data$group[t1data$MIC==1 & t1data$MAC==0]<- "MIC"
t1data$group[t1data$MAC==1]<- "MAC"
t1data$group[t1data$MAC==0 & t1data$MIC==0]<- "None"
t1data$UAlbCreat <- t1data$UAlbCreat*1000

t1 <- CreateTableOne(data=t1data, vars=c("MIC.OR.MAC","MAC","MIC","HYP","RAPID","HTN","NEURO","RETINO","GLYC",
                                          "HbA1c","trig","sbp","dbp","map","si_1_ins0","AGEBASE","sex","tg","dxtime",
                                          "bmi","txdesc","houseincdesc","racedesc","UAlbCreat"), strata="group")
t1 <- print(t1)

# full Table 1 above, below is for DKD paper
t1a <- CreateTableOne(data=t1data, vars=c("AGEBASE","sex","racedesc","dxtime","bmi","HbA1c","UAlbCreat","MAC","MIC",
                                          "sbp","dbp","map","EstCreatClear","HTN"))
t1a <- print(t1a, nonnormal=c("UAlbCreat"))
```

```{r echo=FALSE, include=TRUE}
#kable(t1)
```

### By glycemic outcome

```{r echo=FALSE, include=FALSE}
t2 <- CreateTableOne(data=t1data, vars=c("MIC.OR.MAC","MAC","MIC","HYP","RAPID","NEURO","RETINO","GLYC",
                                         "HbA1c","trig","sbp","si_1_ins0","AGEBASE","sex","tg","dxtime",
                                         "bmi","txdesc","houseincdesc","racedesc"), strata="GLYC")
t2 <- print(t2)
```

```{r echo=FALSE, include=TRUE}
kable(t2)
```

### Overall

```{r echo=FALSE, include=FALSE}
t2 <- CreateTableOne(data=t1data, vars=c("MIC.OR.MAC","MAC","MIC","HYP","RAPID","NEURO","RETINO","GLYC",
                                         "HbA1c","trig","sbp","si_1_ins0","AGEBASE","sex","tg","dxtime",
                                         "bmi","txdesc","houseincdesc","racedesc"))
t2 <- print(t2)
```

```{r echo=FALSE, include=TRUE}
kable(t2)
```

## Volcano plots

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_MAC[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Macroalbuminuria vs. normoalbuminuria",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_MIC[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Microalbuminuria vs. normoalbuminuria",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_hyperfilt[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Hyperfiltration vs. normofiltration",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_rapid[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Rapid eGFR decline vs. no rapid eGFR decline",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_htn[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Hypertension vs. no hypertension",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.7,0.7),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_neuro[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Neuropathy vs. no neuropathy",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_retino[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Retinopathy vs. no retinopathy",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```

```{r echo=FALSE, include=TRUE}
# Volcano plot
res <- results_glyc[,c("TargetFullName","logFC","adj.P.Val","P.Value")]
p <- EnhancedVolcano(res, 
                lab="",
                x="logFC",
                y="P.Value",
                title="Glycemic failure vs. no glycemic failure",
                pCutoff = 0.05,
                FCcutoff=0.5,
                xlim = c(-0.6,0.6),
                ylim = c(0,(-log10(min(res$P.Value))+1)),
                legendLabels=c('NS','Log(2) FC','p-value','p-value & log(2) FC'),
                ylab=bquote(~-Log[10] ~ italic(p)))
p
```