---
title: "ULTRA Analysis"
author: "Callie Rountree-Jablin"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
    toc_loc: left
---

```{r setup, include=FALSE}
library(tidyverse)
library(gtsummary)
library(kableExtra)
library(ggplot2)
library(Hmisc)
library(patchwork)
pacman::p_load(naniar)

if(Sys.info()["sysname"] == "Windows"){
  home_dir = "B:/Petter Bjornstad"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/Peds Endo/Petter Bjornstad/"
} 
knitr::opts_knit$set(echo=FALSE, root.dir = home_dir)
```

```{r read, include=FALSE}
# read raw data
raw_dat <- read_csv("./ULTRA/raw_data/ULTRAT2D_DATA_2023-10-19_1426.csv")
raw_dat <- raw_dat %>% 
  select(-c(name_last, name_first, mrn, dob, phone))
```

```{r data cleaning, include=FALSE}
## subset full raw df into separate screening and visit dfs for analysis

# screening cleaning
screening_dat <- raw_dat %>%
  filter(redcap_event_name=='screening_visit_arm_1') %>%
  mutate(Race=case_when(race___1==1~'American Indian or Alaskan Native',
                        race___2==1~'Asian',
                        race___3==1~'Hawaiian or Pacific Islander',
                        race___4==1~'Black or African American',
                        race___5==1~'White',
                        race___6==1~'Unknown',
                        race___7==1~'Other',
                        .default=NA),
         Ethnicity=case_when(ethnicity___1==1~'Hispanic',
                             ethnicity___2==1~'Non-Hispanic',
                             ethnicity___3==1~'Unknown/Not Reported',
                             .default=NA),
         t2d_less_21=factor(t2d_less_21, levels=c(0,1), labels=c('No','Yes')),
         diabetes_meds___1=factor(diabetes_meds___1, levels=c(0,1), labels=c('No','Yes')),
         diabetes_meds___2=factor(diabetes_meds___2, levels=c(0,1), labels=c('No','Yes')),
         diabetes_meds___3=factor(diabetes_meds___3, levels=c(0,1), labels=c('No','Yes')),
         diabetes_meds___4=factor(diabetes_meds___4, levels=c(0,1), labels=c('No','Yes')),
         diabetes_meds___5=factor(diabetes_meds___5, levels=c(0,1), labels=c('No','Yes')),
         diabetes_meds___6=factor(diabetes_meds___6, levels=c(0,1), labels=c('No','Yes')),
         diabetes_meds___7=factor(diabetes_meds___7, levels=c(0,1), labels=c('No','Yes')),
         insulin_type=case_when(insulin_type___1==1~'Long acting',
                                insulin_type___2==1~'Short acting',
                                insulin_type___3==1~'Other',
                                .default=NA),
         med_hx_hypertension=factor(med_hx_hypertension, levels=c(0,1), labels=c('No','Yes')),
         hypertension_meds=factor(hypertension_meds, levels=c(0,1), labels=c('No','Yes')),
         hypertension_med_type___1=factor(hypertension_med_type___1, levels=c(0,1), labels=c('No','Yes')),
         hypertension_med_type___2=factor(hypertension_med_type___2, levels=c(0,1), labels=c('No','Yes')),
         hypertension_med_type___3=factor(hypertension_med_type___3, levels=c(0,1), labels=c('No','Yes')),
         hypertension_med_type___4=factor(hypertension_med_type___4, levels=c(0,1), labels=c('No','Yes')),
         hypertension_med_type___5=factor(hypertension_med_type___5, levels=c(0,1), labels=c('No','Yes')),
         hypertension_med_type___6=factor(hypertension_med_type___6, levels=c(0,1), labels=c('No','Yes')),
         hypertension_med_type___7=factor(hypertension_med_type___7, levels=c(0,1), labels=c('No','Yes')),
         medhx_cvd=factor(medhx_cvd, levels=c(0,1), labels=c('No','Yes')),
         medhx_met=factor(medhx_met, levels=c(0,1), labels=c('No','Yes')),
         met_hx___1=factor(met_hx___1, levels=c(0,1), labels=c('No','Yes')),
         met_hx___3=factor(met_hx___3, levels=c(0,1), labels=c('No','Yes')),
         met_hx___4=factor(met_hx___4, levels=c(0,1), labels=c('No','Yes')),
         met_hx___5=factor(met_hx___5, levels=c(0,1), labels=c('No','Yes')),
         metdx_meds=factor(metdx_meds, levels=c(0,1), labels=c('No','Yes')),
         g6pd=factor(g6pd, levels=c(2,1), labels=c('Negative','Positive')),
         diabetes_yrs=(interval(as.Date(diabetes_diag, format='%Y-%m-%d'),
                                as.Date(consent_date, format='%Y-%m-%d'))/years(1))) %>% 
  select(-c(redcap_event_name:redcap_repeat_instance, 
            race___1:ethnicity___3,
            studyvisit_type:imaging_complete,
            insulin_type___1:insulin_other)) %>% 
  relocate(insulin_type, .before=insulin_tdd) %>% 
  relocate(c(Race,Ethnicity), .after=age) %>% 
  relocate(diabetes_yrs, .after=diabetes_months) %>%
  filter(record_id!='UT2D-02') %>% 
  filter(record_id!='UT2D-04')

# add labels
source('B:/Petter Bjornstad/ULTRA/raw_data/RedCap_labels_screeningdat.r')

# study visit cleaning
visit_dat <-raw_dat %>% 
  filter(redcap_event_name=='study_visit_arm_1') %>% 
  filter(record_id!='UT2D-02') %>% 
  mutate(studyvisit_type=factor(studyvisit_type, levels=c(1,2), labels=c('Baseline','1 Week'))) %>% 
  select(-c(redcap_repeat_instrument:screening_labs_complete)) %>%
  # HOMA-IR calculation (fasting insulin (mcIU/mL) * fasting glucose (mg/dl)/405)
  mutate(HOMA_IR = (labs_insulin * labs_bg)/405)

# drop peak strain values of 0 per Sungho
visit_dat$long_peak[visit_dat$long_peak == 0] <- NA

# add labels
source('B:/Petter Bjornstad/ULTRA/raw_data/RedCap_labels_visitdat.r')
Hmisc::label(visit_dat$HOMA_IR) <- "HOMA-IR" 

```

<!-- paper referenced for HOMA-IR calculation: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5018567/#:~:text=HOMA%2DIR%20and%20HOMA%2DB,diabetes%20risk%20across%20ethnic%20groups.&text=The%20formulas%20are%20as%20follows,%2Fdl)%20%E2%80%93%2063%5D. -->

```{r all subjects visit missingness summary, include=FALSE}
## look into missingness patterns 

visit_dat %>%
  select(c(record_id, studyvisit_type, vitals_weight, vitals_sbp, vitals_dbp, vitals_map,
         vitals_pulse, labs_bg, labs_s_na, labs_s_k, labs_s_cl, labs_s_hc03, labs_glucose, 
         labs_bun, labs_s_ca, labs_tot_prot, labs_albumin, labs_bili, labs_alk_phos, labs_got_ast, 
         labs_gpt_alt, labs_sua, labs_u_na, labs_u_glucose, labs_uua, labs_cystatinc, 
         labs_s_creatinine, labs_insulin, labs_cholesterol, labs_hdl, labs_ldl,
         labs_triglycerides, labs_u_creatinine, labs_u_microalbumin, labs_acr,
         pilabs_s_osmo, pilabs_u_osmo, pilabs_copeptin, egfr, iohexol_abs_gfr,
         iohexol_bsa_gfr, iohexol_ecv, iohexol_ecv_gfr, iohexol_gfr_ecv_std,
         edv_ml, esv_ml, sv_ml, ef_percent, cardiac_output, myo_mass_dias,
         myo_mass_syst, radial_peak, circum_peak, long_peak, HOMA_IR)) %>% 
  miss_var_summary() %>% 
  kable()

vars <- c('studyvisit_type', 'vitals_weight', 'vitals_sbp', 'vitals_dbp', 'vitals_map',
'vitals_pulse', 'labs_bg', 'labs_s_na', 'labs_s_k', 'labs_s_cl', 'labs_s_hc03', 'labs_glucose', 
'labs_bun', 'labs_s_ca', 'labs_tot_prot', 'labs_albumin', 'labs_bili', 'labs_alk_phos', 'labs_got_ast', 
'labs_gpt_alt', 'labs_sua', 'labs_u_na', 'labs_u_glucose', 'labs_uua', 'labs_cystatinc', 'labs_s_creatinine', 
'labs_insulin', 'labs_cholesterol', 'labs_hdl', 'labs_ldl', 'labs_triglycerides', 'labs_u_creatinine', 
'labs_u_microalbumin', 'labs_acr', 'pilabs_s_osmo', 'pilabs_u_osmo', 'pilabs_copeptin', 'egfr', 'iohexol_abs_gfr', 
'iohexol_bsa_gfr', 'iohexol_ecv', 'iohexol_ecv_gfr', 'iohexol_gfr_ecv_std', 'edv_ml', 'esv_ml', 'sv_ml', 'ef_percent', 
'cardiac_output', 'myo_mass_dias', 'myo_mass_syst', 'radial_peak', 'circum_peak', 'long_peak', 'HOMA_IR')

miss_plot <- expss::use_labels(visit_dat[,vars],
                              {gg_miss_var(..data, facet=studyvisit_type)})
```

```{r wide format, include=FALSE}
## create df with wide format for use with later plots/analyses

wide_visit <- visit_dat %>% 
  pivot_wider(id_cols=record_id,
              names_from=studyvisit_type,
              names_prefix='Study_Visit_',
              values_from=c(vitals_sbp, vitals_dbp, vitals_map, labs_sua, labs_uua, labs_bili, iohexol_abs_gfr,
                            iohexol_bsa_gfr, edv_ml, long_peak, HOMA_IR))
```


```{r responders dat, include=FALSE}
## create responders only dfs for sensitivity analyses

# subset data to include responders only (Delta SUA >= 3 mg/dL)
wide_visit <- wide_visit %>% 
  group_by(record_id) %>% 
  mutate(abs_delta_SUA=abs(`labs_sua_Study_Visit_1 Week`-labs_sua_Study_Visit_Baseline)) %>%
  ungroup() %>% 
  relocate(abs_delta_SUA, .after=`labs_sua_Study_Visit_1 Week`)

label(wide_visit$abs_delta_SUA) <- 'Week 1 - Baseline SUA (Abs Value)'

SUA_status <- wide_visit %>% 
  select(record_id, abs_delta_SUA)

screening_dat <- left_join(screening_dat, SUA_status, by='record_id')
responders_screening_dat <- screening_dat %>% 
  filter(abs_delta_SUA >=3)

visit_dat <- left_join(visit_dat, SUA_status, by='record_id')
responders_visit_dat <- visit_dat %>% 
  filter(abs_delta_SUA >= 3)

rm(SUA_status)
```

```{r responders visit missingness summary, message=FALSE, include=FALSE}
## look into missingness patterns 

responders_visit_dat %>%
  select(c(record_id, studyvisit_type, vitals_weight, vitals_sbp, vitals_dbp, vitals_map,
         vitals_pulse, labs_bg, labs_s_na, labs_s_k, labs_s_cl, labs_s_hc03, labs_glucose, 
         labs_bun, labs_s_ca, labs_tot_prot, labs_albumin, labs_bili, labs_alk_phos, labs_got_ast, 
         labs_gpt_alt, labs_sua, labs_u_na, labs_u_glucose, labs_uua, labs_cystatinc, 
         labs_s_creatinine, labs_insulin, labs_cholesterol, labs_hdl, labs_ldl,
         labs_triglycerides, labs_u_creatinine, labs_u_microalbumin, labs_acr,
         pilabs_s_osmo, pilabs_u_osmo, pilabs_copeptin, egfr, iohexol_abs_gfr,
         iohexol_bsa_gfr, iohexol_ecv, iohexol_ecv_gfr, iohexol_gfr_ecv_std,
         edv_ml, esv_ml, sv_ml, ef_percent, cardiac_output, myo_mass_dias,
         myo_mass_syst, radial_peak, circum_peak, long_peak, HOMA_IR)) %>% 
  miss_var_summary() %>% 
  kable()

miss_plot2 <- expss::use_labels(responders_visit_dat[,vars],
                              {gg_miss_var(..data, facet=studyvisit_type)})
```

# Results: All Subjects

## Descriptive Statistics of Participants

The below table summarizes the data on participants who completed both Visit 1 (Baseline) and Visit 2 (1 Week).

```{r table 1, echo=FALSE}
## descriptive stats table 
table1::table1(~ age + Race + Ethnicity + diabetes_yrs + diabetes_age + t2d_less_21 + diabetes_meds___1 +
                 diabetes_meds___2 + diabetes_meds___3 + diabetes_meds___4 + diabetes_meds___5 + diabetes_meds___6 +
                 diabetes_meds___7 + insulin_type + insulin_tdd + med_hx_hypertension + hypertension_meds + 
                 hypertension_med_type___1 + hypertension_med_type___2 + hypertension_med_type___3 + 
                 hypertension_med_type___4 + hypertension_med_type___5 + hypertension_med_type___6 + 
                 hypertension_med_type___7 + medhx_cvd + medhx_met + met_hx___1 + met_hx___3 + met_hx___4 +
                 met_hx___5 + metdx_meds + pe_bmi + pe_bmi_percent + pe_waist + pe_hip + pe_sbp + pe_dbp +
                 pe_map + pe_pulse + a1c + sua + g6pd, data=screening_dat)
```