---
title: "Moore - Phenteramine vs. Placebo"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(tableone)
library(stringr)
library(growthcleanr)
library(tidyr)
library(ggplot2)
library(arsenal)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

# Questions


# Methods

- Lab data for table 1 were taken from the Screening/Enrollment Visit, not Visit 1, as all data were missing at Visit 1.
- Some participants had more than one CESD administered at Visit 1. The most recent CESD was used.

```{r, include=FALSE}
# Demographics data
demo <- read.csv("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Moore/Phenteramine RCT/Data raw/PilotRCTPhentermineT-LPDemographics_DATA_LABELS_2024-02-05_1920.csv")
demo <- demo %>% filter(!(Record.ID %in% c("Jacky Test","Jacky Test 2")))
demo <- demo %>% filter(Repeat.Instrument=="Demographics Form")
demo <- demo %>% filter(!is.na(Age..completed.years..at.Enrollment))
# participant 28 withdrew before taking a single dose of study medication
demo <- demo %>% filter(!(Record.ID == "028"))
demo$Obesity.Class.at.Enrollment <- as.factor(demo$Obesity.Class.at.Enrollment)
# create combined race/ethnicity
# there are 3 people who checked Latino - 2 checked white and 1 checked other for race
# if they checked black (+/- white), classify them as black
demo <- demo %>% mutate(
  race_eth = case_when(
  Adolescent..Young.Adult.Ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
  Adolescent.Young.Adult.Race..choice.Black.or.African.American. == "Checked" &
   !(Adolescent.Young.Adult.Race..choice.White. == "Checked") ~ "Non-Hispanic Black",
  Adolescent.Young.Adult.Race..choice.White. == "Checked" & 
    !(Adolescent.Young.Adult.Race..choice.Black.or.African.American. == "Checked") ~ "Non-Hispanic White",
  Adolescent.Young.Adult.Race..choice.White. == "Checked" & 
    Adolescent.Young.Adult.Race..choice.Black.or.African.American. == "Checked" ~ "Non-Hispanic > 1 race"
  ))
# fix health insurance
demo <- demo %>% mutate(
  Health.Insurance.Type = case_when(
  Health.Insurance.Type == "" & Record.ID == "45" ~ "State-based (e.g. Medicaid, ACC, CHP+)",
  Health.Insurance.Type == "" & Record.ID == "011" ~ "State-based (e.g. Medicaid, ACC, CHP+)",
  .default = Health.Insurance.Type
  ))
# turn household income into numeric
demo$Estimated.yearly.household.income. <- str_remove(demo$Estimated.yearly.household.income., "\\$")
demo$Estimated.yearly.household.income. <- str_remove(demo$Estimated.yearly.household.income., ",")
demo <- demo %>% mutate(
  Household.income.numeric = case_when(
    Estimated.yearly.household.income. == "2850 per month" ~ 34200,
    !(Estimated.yearly.household.income. == "$2,850 per month") ~ as.numeric(Estimated.yearly.household.income.)
  )
)
# summary variable for food insecurity
demo <- demo %>% mutate (
  food_insecurity = case_when(
    X.Within.the.past.12.months..we.worried.about.whether.our.food.would.run.out.before.we.got.money.to.buy.more. == "YES" ~ "Yes",
    X.Within.the.past.12.months..the.food.we.bought.didn.t.last.and.we.didn.t.have.money.to.get.more. == "YES" ~ "Yes",
    .default = "No"
  )
)

# Drug tolerance - randomization assignment
drug_tol <- read.csv("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Moore/Phenteramine RCT/Data raw/PilotRCTPhentermineT-LPDrugTolerance_DATA_2024-09-07_2123.csv", na.strings = c("NA", "", " "))
drug_tol <- drug_tol %>% filter(!is.na(randomization_grp))
drug_tol$Record.ID <- drug_tol$record_id
drug_tol$Record.ID <- str_pad(drug_tol$Record.ID, 3, pad = "0")
drug_tol$Record.ID <- ifelse(drug_tol$Record.ID == "002", "0002", drug_tol$Record.ID)
drug_tol$Record.ID <- ifelse(drug_tol$Record.ID == "045", "45", drug_tol$Record.ID)
t1_data <- merge(demo, drug_tol, by="Record.ID", all.x = T, all.y = F)

# Height/weight/vitals
ht_wt_vitals <- read.csv("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Moore/Phenteramine RCT/Data raw/PilotRCTPhentermineT-LPHtWtVitals_DATA_LABELS_2024-02-06_1154.csv", na.strings = c("NA", "", " "))
# per Jaime, use 2nd record for participant 0002
ht_wt_vitals <- ht_wt_vitals %>% filter(!(Record.ID == "0002" & Repeat.Instance == 1))
# read in analysis height variable
analysis_ht <- read.csv("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Moore/Phenteramine RCT/Data raw/PilotRCTPhentermineT-LPHeightForAnalysis_DATA_2024-08-08_0908.csv", na.strings = c("NA", "", " "))
analysis_ht$Record.ID <- analysis_ht$record_id
analysis_ht <- analysis_ht %>% select(Record.ID, height_analysis)
ht_wt_vitals <- left_join(ht_wt_vitals, analysis_ht, by = "Record.ID")
num_vars <- c("height_analysis", "Weight.1..kg.", "Weight.2..kg.", "Weight.3..kg.",
              "Systolic.Blood.Pressure.1", "Systolic.Blood.Pressure.2", "Systolic.Blood.Pressure.3",
              "Diastolic.Blood.Pressure.1", "Diastolic.Blood.Pressure.2", "Diastolic.Blood.Pressure.3")
ht_wt_vitals[num_vars] <- apply(ht_wt_vitals[,num_vars],2,as.numeric)
ht_wt_vitals$height_m <- ht_wt_vitals$height_analysis/100
ht_wt_vitals$wt <- rowMeans(ht_wt_vitals[, c("Weight.1..kg.", "Weight.2..kg.", "Weight.3..kg.")])
ht_wt_vitals$sbp <- rowMeans(ht_wt_vitals[, c("Systolic.Blood.Pressure.1", "Systolic.Blood.Pressure.2", "Systolic.Blood.Pressure.3")])
ht_wt_vitals$dbp <- rowMeans(ht_wt_vitals[, c("Diastolic.Blood.Pressure.1", "Diastolic.Blood.Pressure.2", "Diastolic.Blood.Pressure.3")])
ht_wt_vitals$hr <- rowMeans(ht_wt_vitals[, c("Heart.Rate.1.", "Heart.Rate.2.", "Heart.Rate.3.")])
ht_wt_vitals_long <- ht_wt_vitals 
ht_wt_vitals_t3 <- ht_wt_vitals_long
ht_wt_vitals <- ht_wt_vitals %>% filter(Event.Name == "Study Visit 1")
ht_wt_vitals <- ht_wt_vitals %>% filter(!is.na(Repeat.Instrument))
sex_age <- demo[, c("Record.ID", "Biological.Sex", "AgeAtVisit1")]
ht_wt_vitals <- merge(sex_age, ht_wt_vitals, by="Record.ID", all.x = T, all.y = F)
ht_wt_vitals$sex <- ht_wt_vitals$Biological.Sex
ht_wt_vitals$bmi <- ht_wt_vitals$wt / (ht_wt_vitals$height_m * ht_wt_vitals$height_m)
ht_wt_vitals$agem <- ht_wt_vitals$AgeAtVisit1 * 12
ht_wt_vitals_bmiz <- ext_bmiz(ht_wt_vitals, ht = "height_analysis")
ht_wt_vitals_keep <- ht_wt_vitals_bmiz %>% select(Record.ID, height_m, wt, bmi, bmiz, bmip95, sbp, dbp)
t1_data <- merge(t1_data, ht_wt_vitals_keep, by="Record.ID", all.x = T, all.y = F)

# Labs
labs <- read.csv("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Moore/Phenteramine RCT/Data raw/PilotRCTPhentermineT-LPLabs_DATA_2024-02-16_2219.csv")
labs <- labs %>% filter(!(record_id %in% c("Jacky Test","Jacky Test 2")))
labs_long <- labs
labs <- labs %>% filter(redcap_event_name == "screeningenrollmen_arm_1")
labs <- labs %>% filter(redcap_repeat_instrument == "labs")
labs$Record.ID <- labs$record_id
labs_keep <- labs %>% select(Record.ID, labs_a1c, labs_trig, labs_hdl, labs_ldl, labs_alt)
labs_keep$labs_ldl <- ifelse(labs_keep$labs_ldl == 0, NA, labs_keep$labs_ldl)
t1_data <- merge(t1_data, labs_keep, by="Record.ID", all.x = T, all.y = F)

# CESD
cesd <- read.csv("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Moore/Phenteramine RCT/Data raw/PilotRCTPhentermineT-LPCESD_DATA_2024-02-16_2232.csv")
cesd$Record.ID <- cesd$record_id
cesd_long <- cesd
cesd <- cesd %>% filter(redcap_event_name == "study_visit_1_arm_1")
cesd <- cesd %>% filter(redcap_repeat_instrument == "cesd")
# some people have more than 1 CESD at this visit - keep the most recent
cesd <- cesd %>% arrange(record_id, desc(cesd_dateofvisit))
cesd <- cesd %>% group_by(record_id) %>% filter(row_number()==1)
cesd <- ungroup(cesd)
cesd_keep <- cesd %>% select(Record.ID, cesd_score)
t1_data <- merge(t1_data, cesd_keep, by="Record.ID", all.x = T, all.y = F)
t1_data$cesd_score_ge20 <- as.factor(ifelse(t1_data$cesd_score >= 20, 1, 0))

# DEXA
dxa <- read.csv("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Moore/Phenteramine RCT/Data raw/PilotRCTPhentermineT-LPDEXA_DATA_2024-02-16_2244.csv")
dxa <- dxa %>% filter(redcap_event_name == "study_visit_1_arm_1")

# RMR
rmr <- read.csv("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Moore/Phenteramine RCT/Data raw/PilotRCTPhentermineT-LPRMR_DATA_2024-02-16_2245.csv")

# simplified AE
simp_AE <- read.csv("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Moore/Phenteramine RCT/Data raw/PilotRCTPhentermineT-LPAESimplified_DATA_2024-08-08_1528.csv")
simp_AE <- simp_AE %>% select(!redcap_event_name) %>% select(!aes_simplified_version_complete)
simp_AE$aes_other_yn <- ifelse(!simp_AE$aes_other == "", 1, 0)
exclude_vars <- c("record_id", "aes_id", "severeae", "ae_dosereduce", "aes_other")
#simp_AE <- simp_AE %>% select(-one_of(exclude_vars)) %>% replace(is.na(.), 0) %>% mutate(aecount = max())
simp_AE$ae_count <- simp_AE %>% select(-one_of(exclude_vars)) %>% rowSums(na.rm = TRUE)
simp_AE$any_ae <- ifelse(simp_AE$ae_count > 0, 1, 0)
simp_AE$Record.ID <- simp_AE$record_id
simp_AE$record_id <- NULL
simp_AE$general <- simp_AE %>% select(aes_fever, aes_flushing, aes_sweating, aes_cooldown, aes_fatigue, aes_energy) %>% rowSums(na.rm = TRUE)
simp_AE$general <- as.factor(simp_AE$general)
simp_AE$ophthalmologic <- simp_AE %>% select(aes_vision, aes_eye) %>% rowSums(na.rm = TRUE)
simp_AE$ophthalmologic <- as.factor(simp_AE$ophthalmologic)
simp_AE$gastrointestinal <- simp_AE %>% select(nutrdifficult, aes_mouth, aes_taste, aes_abd, aes_nv, aes_dia, aes_const) %>% rowSums(na.rm = TRUE)
simp_AE$gastrointestinal <- as.factor(simp_AE$gastrointestinal)
simp_AE$cardiopulmonary <- simp_AE %>% select(aes_cp, aes_hr, aes_sob, aes_exin) %>% rowSums(na.rm = TRUE)
simp_AE$cardiopulmonary <- as.factor(simp_AE$cardiopulmonary)
simp_AE$genitourinary <- simp_AE %>% select(aes_cycle, aes_back, aes_swell) %>% rowSums(na.rm = TRUE)
simp_AE$genitourinary <- as.factor(simp_AE$genitourinary)
simp_AE$dermatologic <- simp_AE %>% select(aes_rash) %>% rowSums(na.rm = TRUE)
simp_AE$dermatologic <- as.factor(simp_AE$dermatologic)
simp_AE$neuropsychiatric <- simp_AE %>% select(aes_sleep, aes_tingle, aes_foggy, aes_conc, aes_mem, aes_words, aes_ir, aes_rest, aes_anx, aes_dep) %>% rowSums(na.rm = TRUE)
simp_AE$neuropsychiatric <- as.factor(simp_AE$neuropsychiatric)
simp_AE$allergic <- simp_AE %>% select(aes_allergy) %>% rowSums(na.rm = TRUE)
simp_AE$allergic <- as.factor(simp_AE$allergic)
simp_AE$other <- simp_AE %>% select(aes_other_yn) %>% rowSums(na.rm = TRUE)
simp_AE$other <- as.factor(simp_AE$other)

# create dataframe for Table 2
t2_data <- t1_data %>% select(Record.ID, topdose_tolerated, phentdose_tolerated, randomization_grp)
urineamp <- read.csv("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Moore/Phenteramine RCT/Data raw/PilotRCTPhentermineT-LPUrineAmphetamine_DATA_2024-08-08_1216.csv")
urineamp$Record.ID <- urineamp$record_id
adher <- left_join(urineamp, drug_tol, by = "Record.ID") 
adher$randomization_grp <- ifelse(adher$randomization_grp == 1, "Active", "Placebo")
adher <- adher %>% filter(randomization_grp == "Active")
adher <- adher %>% select(Record.ID, urine_v1result, urine_v2result, urine_v3result, urine_v4result)
adher$urine_v1_performed <- ifelse(adher$urine_v1result %in% c(0,1), 1, 0)
adher$urine_v2_performed <- ifelse(adher$urine_v2result %in% c(0,1), 1, 0)
adher$urine_v3_performed <- ifelse(adher$urine_v3result %in% c(0,1), 1, 0)
adher$urine_v4_performed <- ifelse(adher$urine_v4result %in% c(0,1), 1, 0)
adher$v1_pos <- ifelse(adher$urine_v1result == 1, 1, 0)
adher$v2_pos <- ifelse(adher$urine_v2result == 1, 1, 0)
adher$v3_pos <- ifelse(adher$urine_v3result == 1, 1, 0)
adher$v4_pos <- ifelse(adher$urine_v4result == 1, 1, 0)
adher$urine_amp_adherence <- (adher$v1_pos + adher$v2_pos + adher$v3_pos + adher$v4_pos) / 
  (adher$urine_v1_performed + adher$urine_v2_performed + adher$urine_v3_performed + adher$urine_v4_performed)
adher <- adher %>% select(Record.ID, urine_amp_adherence)
t2_data <- left_join(t2_data, adher, by = "Record.ID")
t2_data <- left_join(t2_data, simp_AE, by = "Record.ID")
t2_data$any_ae <- as.factor(t2_data$any_ae)
t2_data$severeae <- as.factor(t2_data$severeae)
t2_data$ae_dosereduce <- as.factor(t2_data$ae_dosereduce)
t2_data$ae_discont <- as.factor(t2_data$ae_discont)

# calculate AE vars based on vitals
ht_wt_vitals_long <- ht_wt_vitals_long %>% filter(Event.Name %in% c("Study Visit 1", "Study Visit 2", "Study Visit 3","Study Visit 4"))
ht_wt_vitals_long <- ht_wt_vitals_long %>% filter(!(Record.ID %in% c("Jacky Test","Jacky Test 2")))
ht_wt_vitals_long <- ht_wt_vitals_long %>% filter(!is.na(wt) & !is.na(sbp) & !is.na(dbp) & !is.na(hr))
ht_wt_vitals_long <- ht_wt_vitals_long %>% select(Record.ID, Event.Name, hr, sbp, dbp)
ht_wt_vitals_wide <- reshape(ht_wt_vitals_long, direction = "wide", idvar = "Record.ID", timevar = "Event.Name")
ht_wt_vitals_wide$delta_hr <- ht_wt_vitals_wide$`hr.Study Visit 4` - ht_wt_vitals_wide$`hr.Study Visit 1`
ht_wt_vitals_wide$delta_sbp <- ht_wt_vitals_wide$`sbp.Study Visit 4` - ht_wt_vitals_wide$`sbp.Study Visit 1`
ht_wt_vitals_wide$delta_dbp <- ht_wt_vitals_wide$`dbp.Study Visit 4` - ht_wt_vitals_wide$`dbp.Study Visit 1`
ht_wt_vitals_wide <- ht_wt_vitals_wide %>% rowwise() %>%
  mutate(hr_max = max(`hr.Study Visit 2`, `hr.Study Visit 3`, `hr.Study Visit 4`, na.rm = TRUE))
ht_wt_vitals_wide$hr_ge_100 <- as.factor(ifelse(is.infinite(ht_wt_vitals_wide$hr_max), NA, 
                                      ifelse(ht_wt_vitals_wide$hr_max >= 100, 1, 0)))
ht_wt_vitals_wide <- ht_wt_vitals_wide %>% rowwise() %>%
  mutate(dbp_max = max(`dbp.Study Visit 2`, `dbp.Study Visit 3`, `dbp.Study Visit 4`, na.rm = TRUE))
ht_wt_vitals_wide$dbp_ge_80 <- as.factor(ifelse(is.infinite(ht_wt_vitals_wide$dbp_max), NA, 
                                      ifelse(ht_wt_vitals_wide$dbp_max >= 80, 1, 0)))
ht_wt_vitals_wide$sbp_120_129 <- ifelse(is.na(ht_wt_vitals_wide$`sbp.Study Visit 2`) & is.na(ht_wt_vitals_wide$`sbp.Study Visit 3`) & is.na(ht_wt_vitals_wide$`sbp.Study Visit 4`), NA, 
  ifelse((!is.na(ht_wt_vitals_wide$`sbp.Study Visit 2`) & ht_wt_vitals_wide$`sbp.Study Visit 2` >= 120 & ht_wt_vitals_wide$`sbp.Study Visit 2` <= 129) |
  (!is.na(ht_wt_vitals_wide$`sbp.Study Visit 3`) & ht_wt_vitals_wide$`sbp.Study Visit 3` >= 120 & ht_wt_vitals_wide$`sbp.Study Visit 3` <= 129) |
  (!is.na(ht_wt_vitals_wide$`sbp.Study Visit 4`) & ht_wt_vitals_wide$`sbp.Study Visit 4` >= 120 & ht_wt_vitals_wide$`sbp.Study Visit 4` <= 129), 1, 0))
ht_wt_vitals_wide$sbp_120_129 <- as.factor(ht_wt_vitals_wide$sbp_120_129)
ht_wt_vitals_wide <- ht_wt_vitals_wide %>% rowwise() %>%
  mutate(sbp_max = max(`sbp.Study Visit 2`, `sbp.Study Visit 3`, `sbp.Study Visit 4`, na.rm = TRUE))
ht_wt_vitals_wide$sbp_ge_130 <- as.factor(ifelse(is.infinite(ht_wt_vitals_wide$sbp_max), NA, 
                                      ifelse(ht_wt_vitals_wide$sbp_max >= 130, 1, 0)))
t2_data <- left_join(t2_data, ht_wt_vitals_wide, by = "Record.ID")

# calculate AE vars based on labs
labs_long <- labs_long %>% filter(redcap_event_name %in% c("screeningenrollmen_arm_1", "study_visit_1_arm_1", "study_visit_2_arm_1", "study_visit_3_arm_1","study_visit_4_arm_1"))
labs_long$Record.ID <- labs_long$record_id
labs_long <- labs_long %>% filter(!(Record.ID %in% c("Jacky Test","Jacky Test 2")))
labs_long <- labs_long %>% filter(!is.na(labs_bicarbonate) & !is.na(labs_creatinine) & !is.na(labs_potassium))
labs_long <- labs_long %>% select(Record.ID, labs_date, redcap_event_name, labs_bicarbonate, labs_creatinine, labs_potassium, labs_ldl, labs_hdl, labs_alt, labs_a1c, labs_trig)
# deal with duplicates
labs_long <- labs_long %>% filter(!(Record.ID == "009" & labs_creatinine == 0.76))
labs_long <- labs_long %>% filter(!(Record.ID == "008" & labs_creatinine == 0.80))
labs_long <- labs_long %>% filter(!(Record.ID == "45" & labs_creatinine == 1.01))
labs_long_003 <- labs_long %>% filter(Record.ID == "003" & redcap_event_name == "study_visit_2_arm_1")  
labs_long <- labs_long %>% filter(!(Record.ID == "003" & redcap_event_name == "study_visit_2_arm_1"))
labs_long_003 <- labs_long_003 %>% group_by(Record.ID, redcap_event_name) %>% summarise(labs_bicarbonate = mean(labs_bicarbonate),
                                                                     labs_creatinine = mean(labs_creatinine),
                                                                     labs_potassium = mean(labs_potassium),
                                                                     labs_ldl = mean(labs_ldl),
                                                                     labs_hdl = mean(labs_hdl),
                                                                     labs_alt = mean(labs_alt),
                                                                     labs_a1c = mean(labs_a1c),
                                                                     labs_trig = mean(labs_trig))
labs_long$labs_date <- NULL
labs_long <- rbind(labs_long, labs_long_003)
labs_long <- labs_long %>% arrange(Record.ID, redcap_event_name)
t4_data <- labs_long

labs_wide <- reshape(labs_long, direction = "wide", idvar = "Record.ID", timevar = "redcap_event_name")
labs_wide$delta_bicarb <- labs_wide$labs_bicarbonate.study_visit_4_arm_1 - labs_wide$labs_bicarbonate.screeningenrollmen_arm_1
labs_wide$delta_creat <- labs_wide$labs_creatinine.study_visit_4_arm_1 - labs_wide$labs_creatinine.screeningenrollmen_arm_1
labs_wide$delta_K <- labs_wide$labs_potassium.study_visit_4_arm_1 - labs_wide$labs_potassium.screeningenrollmen_arm_1
labs_wide <- labs_wide %>% rowwise() %>%
  mutate(bicarb_min = min(labs_bicarbonate.study_visit_2_arm_1, labs_bicarbonate.study_visit_4_arm_1, na.rm = TRUE))
labs_wide$bicarb_lt_20 <- as.factor(ifelse(is.infinite(labs_wide$bicarb_min), NA, 
                                      ifelse(labs_wide$bicarb_min < 20, 1, 0)))
labs_wide <- labs_wide %>% rowwise() %>%
  mutate(K_min = min(labs_potassium.study_visit_2_arm_1, labs_potassium.study_visit_4_arm_1, na.rm = TRUE))
labs_wide$K_lt_3.5 <- as.factor(ifelse(is.infinite(labs_wide$K_min), NA, 
                                      ifelse(labs_wide$K_min < 3.5, 1, 0)))
t2_data <- left_join(t2_data, labs_wide, by = "Record.ID")

# calculate vars based on CESD
cesd_long <- cesd_long %>% filter(redcap_event_name %in% c("screeningenrollmen_arm_1", "study_visit_1_arm_1", "study_visit_2_arm_1", "study_visit_3_arm_1","study_visit_4_arm_1"))
#cesd_long$redcap_event_name <- as.factor(cesd_long$redcap_event_name)
cesd_long <- cesd_long %>% select(Record.ID, cesd_dateofvisit, redcap_event_name, cesd_score)
cesd_long$cesd_score_ge20 <- as.factor(ifelse(cesd_long$cesd_score >= 20, 1, 0))
cesd_long <- cesd_long %>% filter(!is.na(cesd_score))
# some people have more than 1 CESD at a visit - keep the most recent
# for some reason, when I group by record ID and redcap event name, filter, then ungroup, I get downstream errors
# am sidestepping by sorting in a way that gives me the results I need
cesd_long <- cesd_long %>% arrange(Record.ID, cesd_dateofvisit)
#cesd_long <- cesd_long %>% group_by(Record.ID, redcap_event_name) %>% filter(row_number()==1) %>% ungroup()
#cesd_long$cesd_dateofvisit <- NULL
cesd_wide <- reshape(cesd_long, direction = "wide", idvar = "Record.ID", timevar = "redcap_event_name", v.names = c("cesd_score","cesd_score_ge20"))
cesd_wide$delta_cesd <- cesd_wide$cesd_score.study_visit_4_arm_1- cesd_wide$cesd_score.study_visit_1_arm_1
cesd_wide$cesd_score_lt20_ge20 <- ifelse(is.na(cesd_wide$cesd_score.study_visit_1_arm_1) | is.na(cesd_wide$cesd_score.study_visit_4_arm_1), NA, 
                                    ifelse(cesd_wide$cesd_score_ge20.study_visit_1_arm_1==0 &
                                      cesd_wide$cesd_score_ge20.study_visit_4_arm_1==1, 1, 0))
cesd_wide$cesd_score_lt20_ge20 <- as.factor(cesd_wide$cesd_score_lt20_ge20)
cesd_wide <- cesd_wide %>% select(Record.ID, delta_cesd, cesd_score_lt20_ge20)
t2_data <- left_join(t2_data, cesd_wide, by = "Record.ID")

# CSSRS
cssrs <- read.csv("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Moore/Phenteramine RCT/Data raw/PilotRCTPhentermineT-LPCSSRS_DATA_2024-09-04_1721.csv")
cssrs <- cssrs %>% filter(!is.na(redcap_repeat_instance))
cssrs <- cssrs %>% filter(!(record_id %in% c("Jacky Test","Jacky Test 2")))
cssrs$pos_screen <- ifelse(is.na(cssrs$cssrs_1a) | is.na(cssrs$cssrs_2a) | is.na(cssrs$cssrs_6a), NA, 
                           ifelse(cssrs$cssrs_1a == 1 | cssrs$cssrs_2a == 1 | cssrs$cssrs_6a == 1, 1, 0))
cssrs$Record.ID <- cssrs$record_id
cssrs_long <- cssrs %>% select(Record.ID, cssrs_dateofvisit, redcap_event_name, pos_screen)
cssrs_long <- cssrs_long %>% group_by(Record.ID, redcap_event_name) %>% summarise(pos_screen = max(pos_screen)) %>% ungroup(Record.ID)
cssrs_long$visnum <- ifelse(cssrs_long$redcap_event_name == "screeningenrollmen_arm_1", 0, 
                            ifelse(cssrs_long$redcap_event_name == "study_visit_1_arm_1", 1, 4))
cssrs_long <- cssrs_long %>% complete(redcap_event_name, nesting(Record.ID))
cssrs_wide <- data.frame(unique(cssrs_long$Record.ID))
times <- unique(cssrs_long$redcap_event_name)
for (t in times) {
  values <- cssrs_long$pos_screen[cssrs_long$redcap_event_name == t]
  cssrs_wide <- cbind(cssrs_wide, values)
}
# Renaming of columns
colnames(cssrs_wide)[-1] <- paste0("pos_screen_", times)
colnames(cssrs_wide)[1] <- "Record.ID"
cssrs_wide$pos_CSSRS_v1_v4 <- ifelse(cssrs_wide$pos_screen_study_visit_1_arm_1 == 1 | cssrs_wide$pos_screen_study_visit_4_arm_1 == 1, 1, 
                                      ifelse(is.na(cssrs_wide$pos_screen_study_visit_1_arm_1) | is.na(cssrs_wide$pos_screen_study_visit_4_arm_1), NA, 0))
cssrs_wide$pos_CSSRS_v1_v4_new <- ifelse(cssrs_wide$pos_CSSRS_v1_v4 == 0 & is.na(cssrs_wide$pos_CSSRS_v1_v4), NA, 
                                          ifelse(cssrs_wide$pos_CSSRS_v1_v4 == 1 & cssrs_wide$pos_screen_screeningenrollmen_arm_1 == 0, 1, 0))
cssrs_wide <- cssrs_wide %>% select(Record.ID, pos_CSSRS_v1_v4, pos_CSSRS_v1_v4_new)
t2_data <- left_join(t2_data, cssrs_wide, by = "Record.ID")

# Satisfaction
satisfaction <- read.csv("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Moore/Phenteramine RCT/Data raw/PilotRCTPhentermineT-LPSatisfactionSurvey_DATA_2024-09-06_1152.csv")
satisfaction <- satisfaction %>% filter(!is.na(redcap_repeat_instance))
satisfaction$Record.ID <- satisfaction$record_id
satisfaction <- satisfaction %>% filter(!(record_id %in% c("Jacky Test","Jacky Test 2")))
satisfaction <- satisfaction %>% rowwise() %>% 
  mutate(med_score = median(c(ss1, ss2, ss3, ss4, ss5, ss6, ss7, ss8, ss9, ss10, ss11, ss12, ss13, ss14, ss15), na.rm = T)) 
satisfaction <- satisfaction %>% select(Record.ID, respondent, med_score)
satisfaction$respondent <- as.factor(ifelse(satisfaction$respondent == 1, "Caregiver", "Youth"))
satisfaction <- satisfaction %>% complete(respondent, nesting(Record.ID))
satisfaction_wide <- data.frame(unique(satisfaction$Record.ID))
times <- unique(satisfaction$respondent)
for (t in times) {
  values <- satisfaction$med_score[satisfaction$respondent == t]
  satisfaction_wide <- cbind(satisfaction_wide, values)
}
# Renaming of columns
colnames(satisfaction_wide)[-1] <- paste0("med_score_", times)
colnames(satisfaction_wide)[1] <- "Record.ID"
satisfaction_wide$Record.ID <- str_pad(satisfaction_wide$Record.ID, 3, pad = "0")
satisfaction_wide$Record.ID <- ifelse(satisfaction_wide$Record.ID == "002", "0002", satisfaction_wide$Record.ID)
satisfaction_wide$Record.ID <- ifelse(satisfaction_wide$Record.ID == "045", "45", satisfaction_wide$Record.ID)
t2_data <- left_join(t2_data, satisfaction_wide, by = "Record.ID")

t3_data <- ht_wt_vitals_t3
t3_data <- t3_data %>% filter(Record.ID %in% t2_data$Record.ID)
t3_data <- t3_data %>% filter(Event.Name %in% c("Study Visit 1", "Study Visit 2", "Study Visit 3", "Study Visit 4"))
t3_data <- t3_data %>% filter(!is.na(Date.of.Visit.))
r <- t2_data %>% select(Record.ID, randomization_grp)
r <- unique(r)
t3_data <- left_join(t3_data, r, by = "Record.ID")

fig1_data <- t3_data %>% select(Record.ID, Event.Name, wt, randomization_grp)
basewt <- fig1_data %>% filter(Event.Name == "Study Visit 1")
basewt$basewt <- basewt$wt
basewt <- basewt %>% select(Record.ID, basewt)
fig1_data <- left_join(fig1_data, basewt, by = "Record.ID")
fig1_data$percent_wt_loss <- ifelse(fig1_data$Event.Name == "Study Visit 1", 0, 
                                    ((fig1_data$basewt - fig1_data$wt)/fig1_data$basewt)*100)
fig1_data <- fig1_data %>% arrange(Record.ID, Event.Name)

t3_data <- t3_data %>% select(Record.ID, Event.Name, Date.of.Visit., randomization_grp, wt, height_m)
t3_data$bmi <- t3_data$wt / (t3_data$height_m * t3_data$height_m)
t3_data <- t3_data %>% filter(Event.Name %in% c("Study Visit 1", "Study Visit 4"))
t3_data_wide <- reshape(t3_data, direction = "wide", idvar = c("Record.ID", "randomization_grp"), timevar = "Event.Name")
t3_data_wide$delta_days <- as.Date(t3_data_wide$`Date.of.Visit..Study Visit 4`, format = "%m/%d/%Y") - as.Date(t3_data_wide$`Date.of.Visit..Study Visit 1`, format = "%m/%d/%Y")
t3_data_wide$percent_wt_change <- ((t3_data_wide$`wt.Study Visit 4` - t3_data_wide$`wt.Study Visit 1`) / t3_data_wide$`wt.Study Visit 1`) * 100
t3_data_wide$absolute_wt_change <- t3_data_wide$`wt.Study Visit 4` - t3_data_wide$`wt.Study Visit 1`
t3_data_wide$percent_bmi_change <- ((t3_data_wide$`bmi.Study Visit 4` - t3_data_wide$`bmi.Study Visit 1`) / t3_data_wide$`bmi.Study Visit 1`) * 100
t3_data_wide$absolute_bmi_change <- t3_data_wide$`bmi.Study Visit 4` - t3_data_wide$`bmi.Study Visit 1`
t3_data_wide$ge_5percent_wt_loss <- as.factor(ifelse(is.na(t3_data_wide$percent_wt_change), NA, 
                                           ifelse(t3_data_wide$percent_wt_change <= -5, 1, 0)))
t3_data_wide$ge_10percent_wt_loss <- as.factor(ifelse(is.na(t3_data_wide$percent_wt_change), NA, 
                                           ifelse(t3_data_wide$percent_wt_change <= -10, 1, 0)))

t4_data <- t4_data %>% filter(Record.ID %in% t2_data$Record.ID)
t4_data <- left_join(t4_data, r, by = "Record.ID")
t4_data_wide <- reshape(t4_data, direction = "wide", idvar = c("Record.ID", "randomization_grp"), timevar = "redcap_event_name")
t4_data_wide$delta_ldl <- t4_data_wide$labs_ldl.study_visit_4_arm_1 - t4_data_wide$labs_ldl.screeningenrollmen_arm_1
t4_data_wide$delta_hdl <- t4_data_wide$labs_hdl.study_visit_4_arm_1 - t4_data_wide$labs_hdl.screeningenrollmen_arm_1
t4_data_wide$delta_alt <- t4_data_wide$labs_alt.study_visit_4_arm_1 - t4_data_wide$labs_alt.screeningenrollmen_arm_1
t4_data_wide$delta_a1c <- t4_data_wide$labs_a1c.study_visit_4_arm_1 - t4_data_wide$labs_a1c.screeningenrollmen_arm_1
t4_data_wide$delta_trig <- t4_data_wide$labs_trig.study_visit_4_arm_1 - t4_data_wide$labs_trig.screeningenrollmen_arm_1
```

# Results

## Table 1

```{r, include=FALSE}
t1 <- CreateTableOne(data = t1_data, vars = c("AgeAtVisit1", "Biological.Sex", "race_eth", "Primary.Bariatric.Surgical.Procedure",
                                              "Months.post.MBS.at.Enrollment", "Obesity.Class.at.Enrollment", "Qualifying.Inclusion.Criteria",
                                              "Health.Insurance.Type", "Primary.caregiver.s.highest.level.of.education.",
                                              "Household.income.numeric", "food_insecurity", "height_m", "weight_kg", "sbp", "dbp",
                                              "hr", "labs_a1c", "labs_trig", "labs_hdl", "labs_ldl", "labs_alt",
                                              "cesd_score", "cesd_score_ge20"), 
                     strata = "randomization_grp")

```

```{r, include=TRUE, comment = ""}
#summary(t1)
```

```{r, include=FALSE}
t1 <- print(t1, nonnormal = c("Age..completed.years..at.Enrollment", "labs_a1c", "labs_trig", "labs_alt"), 
            showAllLevels = T)
```

```{r, include=TRUE}

kable(t1)
```

## Table 2

```{r, include=FALSE}
t2 <- CreateTableOne(data = t2_data, vars = c("urine_amp_adherence","phentdose_tolerated","topdose_tolerated",
                                              "any_ae", "severeae", "ae_dosereduce", "ae_discont", "general", "ophthalmologic", "gastrointestinal", 
                                              "cardiopulmonary", "genitourinary", "dermatologic", "neuropsychiatric", "allergic", "other", 
                                              "delta_hr", "hr_ge_100", "delta_sbp", "sbp_120_129", "sbp_ge_130", "delta_dbp", "dbp_ge_80",
                                              "delta_bicarb", "bicarb_lt_20", "delta_creat", "delta_K", "K_lt_3.5",
                                              "delta_cesd", "score_lt20_ge20", "pos_CSSRS_v1_v4", "pos_CSSRS_v1_v4_new",
                                              "med_score_Caregiver", "med_score_Youth"), 
                     strata = "randomization_grp")
t2 <- print(t2, showAllLevels = T, nonnormal = c("med_score_Caregiver", "med_score_Youth"))
```

```{r, include=TRUE}
kable(t2)
```

## Figure 1

```{r, include=TRUE, fig.width=6}
p <- ggplot(data = fig1_data, aes(x = Event.Name, y = percent_wt_loss, group = Record.ID, 
                                  col = as.factor(randomization_grp))) +
  geom_point() + geom_line() + xlab("") + ylab("Percent weight loss") + 
  scale_color_grey(name = "Randomization Assignment", labels = c("Placebo", "Active")) 

p
```

## Table 3 

```{r, include=FALSE}
t3 <- tableby(randomization_grp ~ delta_days + percent_wt_change + absolute_wt_change + percent_bmi_change + absolute_bmi_change +
                ge_5percent_wt_loss + ge_10percent_wt_loss, data = t3_data_wide)
```

```{r, include=TRUE, results='asis'}
summary(t3)
```

## Table 4 

```{r, include=FALSE}
t4 <- tableby(randomization_grp ~ delta_trig + delta_ldl + delta_hdl + delta_alt + delta_a1c, data = t4_data_wide)
```

```{r, include=TRUE, results='asis'}
summary(t4)
```