---
title: "CACTI estimates for power calculations"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(readxl)
library(tableone)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

```

```{r, include=FALSE}
data <- read_xls("/Volumes/Peds Endo/Petter Bjornstad/Grants/Sharma Bjornstad adenine R01/CACTI data/QJDRF_DKD_Consortium_Data.xls")

# read in CVD data from separate file
load("/Volumes/BDC/Projects/Janet Snell-Bergeon/AHA collaborative grant/aha_master_data_no_snps.Rdata")
cvd <- df %>% select(StudyID,CVD,HardCVD)
data <- merge(data,cvd,by="StudyID",all.x = TRUE,all.y = FALSE)

data$Deceased <- ifelse(is.na(data$Deceased),0,data$Deceased)
data$DialysisEver <- ifelse(is.na(data$DialysisEver),2,data$DialysisEver)
data$DialysisEver <- as.factor(data$DialysisEver)
data$DialysisEver <- relevel(data$DialysisEver, ref="1")
#data$Transplant <- ifelse(is.na(data$Transplant),0,data$Transplant)

# Casey's code for eGFR slope
# the goal is to transform each of these metrics into a slope (visit max - visit1)/(datemax - date 1) - dates in years
test = data %>% select(StudyID, Date_V1:Date_V4, CKDepiV1:CKDEpiV4)
test$CKDepiV1 = as.numeric(test$CKDepiV1)
test$ckdepiv2 = as.numeric(test$ckdepiv2)
test$ckdepiv3 = as.numeric(test$ckdepiv3)
test$CKDEpiV4 = as.numeric(test$CKDEpiV4)

options(scipen = 20)
test2 = test %>% mutate(slope_egfr = case_when(!is.na(Date_V4) & !is.na(CKDEpiV4) ~ (CKDEpiV4 - CKDepiV1)/(as.double(difftime(Date_V4, Date_V1, units = "days"))/365),
                                              !is.na(Date_V3) & !is.na(ckdepiv3) ~ (ckdepiv3 - CKDepiV1)/(as.double(difftime(Date_V3, Date_V1, units = "days"))/365),
                                              !is.na(Date_V2) & !is.na(ckdepiv2) ~ (ckdepiv2 - CKDepiV1)/(as.double(difftime(Date_V2, Date_V1, units = "days"))/365)))

test2_keep <- test2 %>% select(StudyID,slope_egfr)
data <- merge(data,test2_keep,by="StudyID",all.x = T,all.y = T)

data$slope_egfr_lt_minus_3 <- as.factor(ifelse(is.na(data$slope_egfr),NA,
                                     ifelse(data$slope_egfr <= -3, 1, 0)))
```

```{r echo=FALSE, include=FALSE}
data$Deceased <- as.factor(data$Deceased)
data$DialysisEver <- as.factor(data$DialysisEver)
data$Transplant <- as.factor(data$Transplant)
data$CAD <- as.factor(data$CAD)
data$HardCAD <- as.factor(data$HardCAD)
t1 <- CreateTableOne(data=data, vars=c("Deceased","DialysisEver","Transplant","CAD","HardCAD","CVD","HardCVD","slope_egfr_lt_minus_3"))
t1 <- print(t1, showAllLevels=TRUE)
```

```{r, echo=FALSE}
kable(t1)
```


