---
title: "CRIC and SMART2D estimates for power calculations"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(readxl)
library(tableone)
library(InteractionPoweR)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

```

```{r, include=FALSE}
#data <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Grants/Sharma Bjornstad adenine R01/Adenine data/data.cric.smart.0502.csv")
# data does not seem to contain eGFR decline, or patient ID!

data <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Grants/Sharma Bjornstad adenine R01/Adenine data/NIHDP3CRIC-ClinicalDataForAdeni_DATA_2023-05-03_1529.csv")
data_keep <- data %>% select(patientid,adeninecreat_in_nmmm)

# read in new dataset from Kumar which has all the eGFR data
newdata <- read_xlsx("/Volumes/Peds Endo/Petter Bjornstad/Grants/Sharma Bjornstad adenine R01/Adenine data/NIHDP3CRIC_DATA_2023-06-18_1003.xlsx", skip = 1)
newdata_keep <- newdata %>% select(patientid, 
                                   days_thisvisit_v3y0, egfr_ckd_epi_v3y0, urine_albumin_v3y0,urine_creatinine_v3y0,
                                   days_thisvisit_v5y1 ,egfr_ckd_epi_v5y1, urine_albumin_v5y1, urine_creatinine_v5y1,
                                   days_thisvisit_v7y2, egfr_ckd_epi_v7y2, urine_albumin_v7y2, urine_creatinine_v7y2,
                                   days_thisvisit_v9y3, egfr_ckd_epi_v9y3, urine_albumin_v9y3, urine_creatinine_v9y3,
                                   days_thisvisit_v11y4, egfr_ckd_epi_v11y4)
                                
combined <- merge(data_keep, newdata_keep, by="patientid",all.x = T, all.y=T)

# calculate rate of eGFR decline
test = combined 
test$egfr_ckd_epi_v3y0 = as.numeric(test$egfr_ckd_epi_v3y0)
test$egfr_ckd_epi_v5y1 = as.numeric(test$egfr_ckd_epi_v5y1)
test$egfr_ckd_epi_v7y2 = as.numeric(test$egfr_ckd_epi_v7y2)
test$egfr_ckd_epi_v9y3 = as.numeric(test$egfr_ckd_epi_v9y3)
test$egfr_ckd_epi_v11y4 = as.numeric(test$egfr_ckd_epi_v11y4)
test <- test %>% filter(!is.na(egfr_ckd_epi_v3y0))
options(scipen = 20)
test2 = test %>% mutate(slope_egfr = case_when(!is.na(days_thisvisit_v11y4) & !is.na(egfr_ckd_epi_v11y4) ~ 
                                                 (egfr_ckd_epi_v11y4 - egfr_ckd_epi_v3y0)/((days_thisvisit_v11y4-days_thisvisit_v3y0)/365),
                                              !is.na(days_thisvisit_v9y3) & !is.na(egfr_ckd_epi_v9y3) ~ 
                                                (egfr_ckd_epi_v9y3 - egfr_ckd_epi_v3y0)/((days_thisvisit_v9y3-days_thisvisit_v3y0)/365),
                                              !is.na(days_thisvisit_v7y2) & !is.na(egfr_ckd_epi_v7y2) ~ 
                                                (egfr_ckd_epi_v7y2 - egfr_ckd_epi_v3y0)/((days_thisvisit_v7y2-days_thisvisit_v3y0)/365),
                                              !is.na(days_thisvisit_v5y1) & !is.na(egfr_ckd_epi_v5y1) ~ 
                                                (egfr_ckd_epi_v5y1 - egfr_ckd_epi_v3y0)/((days_thisvisit_v5y1-days_thisvisit_v3y0)/365)))

test2_keep <- test2 %>% select(patientid,slope_egfr)
combined <- merge(combined,test2_keep,by="patientid",all.x = T,all.y = T)

# calculate baseline UACR
combined$uacr_v3y0 <- combined$urine_albumin_v3y0/combined$urine_creatinine_v3y0

# is slope less than -3?
combined$slope_egfr_le_minus_3 <- as.factor(ifelse(is.na(combined$slope_egfr),NA,
                                     ifelse(combined$slope_egfr <= -3, 1, 0)))
```

```{r, echo=FALSE, comment=""}
corYX1 <- cor(combined$slope_egfr,combined$adeninecreat_in_nmmm, use = "pairwise.complete.obs")
corYX2 <-  cor(combined$slope_egfr,combined$uacr_v3y0, use = "pairwise.complete.obs")
corX1X2 <- cor(combined$adeninecreat_in_nmmm,combined$uacr_v3y0, use = "pairwise.complete.obs")
```

# Results

## Correlation slope eGFR and baseline adenine

```{r, echo=FALSE, comment=""}
corYX1
```

```{r, echo=FALSE, comment=""}
a <- lm(combined$slope_egfr~combined$adeninecreat_in_nmmm)
summary(a)
```

## Correlation slope eGFR and baseline UACR

```{r, echo=FALSE, comment=""}
corYX2
```

```{r, echo=FALSE, comment=""}
b <- lm(combined$slope_egfr~combined$uacr_v3y0)
summary(b)
```

## Correlation baseline adenine and baseline UACR

```{r, echo=FALSE, comment=""}
corX1X2
```

```{r, echo=FALSE, comment=""}
c <- lm(combined$adeninecreat_in_nmmm~combined$uacr_v3y0)
summary(c)
```

## Range of effect sizes

```{r, echo=FALSE, comment=""}
power_test = power_interaction(n.iter = 1000,    # number of simulations
                  alpha = 0.05,                  # p-value
                  N = 1430  ,       # sample size
                  r.x1.y = -0.17,                   # correlation between x1 and y
                  r.x2.y =  -0.36,                  # correlation between x2 and y
                  r.x1.x2 = .1,                  # correlation between x1 and x2
                  r.x1x2.y = seq(0.01,0.1,0.01),           # correlation between x1x2 and y
                  cl = 2,                        # number of clusters for parallel analyses
                  detailed_results = TRUE,        # return detailed results       
                  k.x1=0,
                  k.x2=2,
                  k.y=0
                   )
power_test
```

## A correlation of x1x2.y equal to 0.07 gives 84% power

```{r, echo=FALSE, comment=""}
power_test = power_interaction(n.iter = 1000,    # number of simulations
                  alpha = 0.05,                  # p-value
                  N = 1430  ,       # sample size
                  r.x1.y = -0.17,                   # correlation between x1 and y
                  r.x2.y =  -0.36,                  # correlation between x2 and y
                  r.x1.x2 = .1,                  # correlation between x1 and x2
                  r.x1x2.y = 0.074,           # correlation between x1x2 and y
                  cl = 2,                        # number of clusters for parallel analyses
                  detailed_results = TRUE,        # return detailed results       
                  k.x1=0,
                  k.x2=2,
                  k.y=0
                   )
power_test
```

## Visualize the interaction

```{r, echo=FALSE, comment=""}
test_data = generate_interaction(
                  N = 1430,                        # sample size
                  r.x1.y = -0.17,                   # correlation between x1 and y
                  r.x2.y =  -0.36,                  # correlation between x2 and y
                  r.x1.x2 = .1,                 # correlation between x1 and x2
                  r.x1x2.y = 0.07,                 # correlation between x1x2 and y
                  k.x1 = 0,                       # x1 is binary
                  k.x2 = 2,                       # x2 is binary
                  k.y = 0,                        # y is binary
                  adjust.correlations = TRUE)     # Adjust correlations?  

plot_interaction(data =test_data )
```

## What is the prevalence of rapid eGFR decline at mean adenine?

Mean adenine is 75.3

```{r, echo=FALSE, comment=""}
logistic_mod <- glm(slope_egfr_le_minus_3 ~ adeninecreat_in_nmmm, data=combined, family = "binomial")

pred_data <- combined %>% filter(adeninecreat_in_nmmm>75 & adeninecreat_in_nmmm<76)
probabilities <- logistic_mod %>% predict(pred_data, type = "response")
```


