---
title: "CROCODILE estimates for power calculations"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(readxl)
library(tableone)
library(InteractionPoweR)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

```

```{r, include=FALSE}
data <- read_xlsx("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Grants/Sharma Bjornstad adenine R01/Adenine data/CROC Adenine Quantified Data_New.xlsx")
data <- data %>% filter(Diagnosis %in% c("Healthy Control","T1D"))

urine_data <- read_xlsx("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Grants/Sharma Bjornstad adenine R01/Adenine data/Crocodile_Urine Data_10-7-2022_Final_With Crocodile ID.xlsx", 
                        sheet = "Urine Adenine")
urine_data <- urine_data %>% filter(Group %in% c("Healthy Control","T1D"))
```

```{r, echo=FALSE, comment=""}
t1 <- CreateTableOne(data=data, vars=c("Total (Adnine)"), strata = "Diagnosis")
t1 <- print(t1,digits = 4,pdigits=4)

t2 <- CreateTableOne(data=urine_data, vars=c("Adenine in uM/mM Creatinine"), strata = "Group")
t2 <- print(t2,digits = 4,pdigits=4)

```

# Results

## Intrarenal adenine

```{r, echo=FALSE, comment=""}
kable(t1)
```

## Urine adenine

```{r, echo=FALSE, comment=""}
kable(t2)
```
