---
title: "Melanie Cree - TEAL Study"
author: "Laura Pyle"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
execute:
  echo: false
  message: false
---

```{r libraries}
#| include: false
library(tidyverse)
library(arsenal)
library(dplyr)
library(labelled)
library(nlme)
library(lme4)
library(emmeans)
library(sjPlot)
library(knitr)
```

```{r data import}
#| include: false
source("/Volumes/Peds Endo/Melanie Green/TEAL/Data_raw/190636TEAL_R_2023-12-05_1149.R")
data <- remove_labels(data)

# remove screen fails
data <- data %>% filter(!study_group == 3)

# wide dataset with needed variables
keep_wide <- data %>% select(subject_id, study_group.factor, age, bmi_cat.factor, tanner,
                             screen_wt, screen_height, screen_bmi, screen_bmi_percentile, screen_bmi_zscore,
                             baseline_wt, baseline_ht, baseline_bmi, baseline_bmi_perc, baseline_bmi_zscore,
                             mid_wt_2, mid_ht_2, mid_bmi_2, mid_bmi_perc_2, mid_bmi_zscore_2,
                             final_wt_3, final_ht_3, final_bmi_3, final_bmi_perc_3, final_bmi_zscore_3,
                             liver_fat_perc, liver_fat_perc_final,
                             dmets, mid_3dmets, dmets_final,
                             kcals_total, kcals_day_final,
                             t_ahi, t_ahi_final,
                             homa, matsuda, 
                             homa_final, matsuda_final 
                             )
keep_wide <- keep_wide %>% mutate_at(c("screen_wt", "screen_height", "screen_bmi", "screen_bmi_percentile", "screen_bmi_zscore",
                             "baseline_wt", "baseline_ht", "baseline_bmi", "baseline_bmi_perc", 'baseline_bmi_zscore',
                             "mid_wt_2", "mid_ht_2", "mid_bmi_2", "mid_bmi_perc_2", "mid_bmi_zscore_2",
                             "final_wt_3", "final_ht_3", "final_bmi_3", "final_bmi_perc_3", "final_bmi_zscore_3",
                             "liver_fat_perc", "liver_fat_perc_final",
                             "dmets", "mid_3dmets", "dmets_final",
                             "kcals_total", "kcals_day_final",
                             "t_ahi", "t_ahi_final",
                             "homa", "matsuda", 
                             "homa_final", "matsuda_final"), as.numeric)

# rename variables to make it easier to make a long dataset
keep_wide <- keep_wide %>% rename( screen_weight = screen_wt, 
                                   screen_bmipercentile = screen_bmi_percentile, 
                                   screen_bmizscore = screen_bmi_zscore,
                                   baseline_weight = baseline_wt, 
                                   baseline_height = baseline_ht, 
                                   baseline_bmipercentile = baseline_bmi_perc, 
                                   baseline_bmizscore = baseline_bmi_zscore,
                                   week8_weight = mid_wt_2, 
                                   week8_height = mid_ht_2, 
                                   week8_bmi = mid_bmi_2, 
                                   week8_bmipercentile = mid_bmi_perc_2, 
                                   week8_bmizscore = mid_bmi_zscore_2,
                                   week16_weight = final_wt_3, 
                                   week16_height = final_ht_3, 
                                   week16_bmi = final_bmi_3, 
                                   week16_bmipercentile = final_bmi_perc_3, 
                                   week16_bmizscore = final_bmi_zscore_3,
                                   baseline_liverfatperc = liver_fat_perc, 
                                   week16_liverfatperc = liver_fat_perc_final,
                                   baseline_dmets = dmets, 
                                   week8_dmets = mid_3dmets, 
                                   week16_dmets = dmets_final,
                                   baseline_kcals = kcals_total, 
                                   week16_kcals = kcals_day_final,
                                   baseline_tahi = t_ahi, 
                                   week16_tahi = t_ahi_final,
                                   baseline_homa = homa, 
                                   baseline_matsuda =  matsuda, 
                                   week16_homa = homa_final, 
                                   week16_matsuda = matsuda_final)


# calculate absolute weight change (baseline as reference)
keep_wide$week8_abswtchange <- keep_wide$week8_weight - keep_wide$baseline_weight
keep_wide$week16_abswtchange <- keep_wide$week16_weight - keep_wide$baseline_weight

# calculate percent weight change (baseline as reference)
keep_wide$week8_perwtchange <- (keep_wide$week8_abswtchange / keep_wide$baseline_weight ) * 100
keep_wide$week16_perwtchange <- (keep_wide$week16_abswtchange / keep_wide$baseline_weight) * 100

# create long dataset for mixed models
keep_long <- keep_wide %>% pivot_longer(cols = !c("subject_id", "study_group.factor", "age", "bmi_cat.factor", "tanner"),
                                        names_to = c("visit", ".value"), names_sep = "_", values_drop_na = T)
# create a variable equal to weight at baseline
wtbas <- keep_long %>% filter(visit=="baseline")
wtbas <- wtbas %>% select(subject_id, weight)
names(wtbas) <- c("subject_id", "baseline_weight")
keep_long <- merge(keep_long, wtbas, by="subject_id", all.x = T, all.y = T)
# create numeric time variable
keep_long$num_time <- ifelse(keep_long$visit == "screen", -4, 
                             ifelse(keep_long$visit == "baseline", 0, 
                                    ifelse(keep_long$visit == "week8", 8, 16)))

# create df without screening and baseline
keep_long_nobase <- keep_long %>% filter(visit == "week8" | visit == "week16")
```

```{r functions}
# what needs to be done
# fix the function below - getting an error on the model statement
# make sure it's printing the pieces I want (emmeans, pairs) and remove pieces not needed
# create adjusted version of the function

model_and_plot = function(outcome_name,df,pois = F){
  # Convert to numeric
  df[,outcome_name] = as.numeric(df[,outcome_name])
  # Fit a mixed model. Some of these are essentially count data and may require a Poisson model
  mod = lme(as.formula(paste0(outcome_name,"~as.factor(num_time)*study_group.factor, random=~1|subject_id, data="),df))
  anova_table <- anova.lme(mod, type="marginal")
  # Means by timepoint
  means = as.data.frame(emmeans(mod,c("num_time","study_group.factor")))
  means$num_time = c(-4,0,8,16)
  # Plot
  p <- plot_model(mod, type="emm", terms=c("num_time","study_group.factor"), title = "") + geom_line() + 
    labs(x="Weeks", y="Weight (kg)", colour = "") 
  # Print plot and model results
  print(p)
  print(kable(anova(mod),digits = 3,caption = "Type III ANOVA"))
  print(anova_table)
  print(kable(summary(mod)$coefficients,digits = 3,caption = "Fixed Effects"))
}
```

# Header 1

```{r message=FALSE,warning=FALSE,dpi=1200,results='asis'}
# NEED TO TURN THIS INTO A FUNCTION
mod <- lme(weight ~ visit*study_group.factor + baseline_weight,random=~1|subject_id,data = keep_long_nobase,na.action = na.omit)
anova_table <- anova.lme(mod, type="marginal")
ttable <- summary(mod)$tTable
mod_means <- emmeans(mod,c("visit","study_group.factor"))
mod_pairs <-  pairs(mod_means,adjust="tukey", simple="each")
plot_model(mod, type="emm", terms=c("visit","study_group.factor")) + geom_line()

# unadjusted model - include screen?
model_and_plot(outcome_name = "weight", df = keep_long)

# model adjusted for baselino weight
#model_adjusted(data = keep_long_nobase, outcome = "weight", covar = "baseline_weight")
```

