---
title: "Teen-LABS trajectories"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r libraries,echo=FALSE, include=F}
library(knitr)
library(tidyverse)
library(Hmisc)
library(readxl)
library(RColorBrewer)
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
```

```{r clean data,echo=FALSE}
# source("/Users/timvigers/GitHub/CHCO-Code/Petter Bjornstad/Teen-LABS/create_teen_labs_analysis_dataset.R")
load("/Users/pylell/Library/CloudStorage/OneDrive-SharedLibraries-UW/Bjornstad/Biostatistics Core Shared Drive/Teen Labs/Data_Cleaned/analysis_dataset.RData")

# keep only the proteins we need
analyte_keep <- analyte_info %>% filter(UniProt %in% c("P62979","P0CG47","P51668|P0CG47","P0CG48"))
apt_keep <- analyte_keep$AptName
#df_igf <- df %>% select(all_of(apt_keep))
#df_igf <- cbind(df$ID, df$visit, df_igf)
#colnames(df_igf[,1:2]) <- c ("ID","visit")

# read in estimated marginal means
emmdf <- read_xlsx("/Users/pylell/Library/CloudStorage/OneDrive-SharedLibraries-UW/Bjornstad/Biostatistics Core Shared Drive/Teen Labs/Results/Teen LABS emmeans.xlsx")
emmdf_keep <- emmdf %>% filter(UniProt %in% c("P62979","P0CG47","P51668|P0CG47","P0CG48"))
emmdf_keep$uniqname <- paste0(emmdf_keep$Target,"_",emmdf_keep$AptName)  

```


```{r,echo=FALSE}
p <- ggplot(emmdf_keep, aes(x=visit, y=emmean, colour=Target, group=uniqname)) +
    geom_line() + 
    geom_errorbar(aes(ymin=emmean-SE, ymax=emmean+SE), width=.1) +  
    xlab("") +
    ylab("Estimated marginal mean") + theme_bw() +
    scale_color_brewer(palette = "Dark2")

p
```
