---
title: "Teen-LABS IGF boxplots"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r libraries,echo=FALSE, include=F}
library(knitr)
library(tidyverse)
library(Hmisc)
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
```

```{r clean data,echo=FALSE}
# source("/Users/timvigers/GitHub/CHCO-Code/Petter Bjornstad/Teen-LABS/create_teen_labs_analysis_dataset.R")
load("/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Data_Cleaned/analysis_dataset.RData")

```

# Teen-LABS

```{r,echo=FALSE}
# keep only the proteins we need
analyte_igf <- analyte_info %>% filter(UniProt %in% c("P05019","P17936","P35858","P01241","P18065","P22692","P24593",
                                                         "P10912","P08833","P24592","P01019","P36955"))
apt_keep <- analyte_igf$AptName
#df_igf <- df %>% select(all_of(apt_keep))
#df_igf <- cbind(df$ID, df$visit, df_igf)
#colnames(df_igf[,1:2]) <- c ("ID","visit")

# calculate log of ratio of upregulated IGF1 aptamer and IGFBP3
df$igf1_igfbp3 <- log(exp(df$seq.2952.75)/exp(df$seq.2571.12))

p <- ggplot(df,aes(visit,seq.7735.17))+geom_boxplot(aes(fill=visit)) + ylab("log(PEDF)")
p

p <- ggplot(df,aes(visit,seq.9211.19))+geom_boxplot(aes(fill=visit)) + ylab("log(PEDF)")
p
```
