---
title: "Bariatric surgery and insulin sensitivity"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(tableone)
library(dplyr)
library(knitr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

home_dir = ifelse(.Platform$OS.type != "unix","E:/Nadeau/IMPROVE-T2D/Data raw","")
knitr::opts_knit$set(root.dir = home_dir)

```

```{r data, include=FALSE}
setwd(home_dir)
alldata <- read.csv("./IMPROVET2D-MMTTVariables_DATA_2022-07-12_1018.csv")

# select the participants
# IT2D-2,3,5,6,8,11-16 
data <- alldata %>% filter(subject_id %in% c("IT_02","IT_03","IT_05","IT_06","IT_08","IT_11","IT_12","IT_13","IT_14","IT_15","IT_16"))

# separate variables into MMTT and screening variables
screen <- data %>% filter(redcap_event_name=="screening_arm_1") %>% 
  select(subject_id,age_current,gender,screen_bmi,screen_bmi_percentile,screen_weight,hba1c,a1c_pre)
mmtt <- data %>% filter(redcap_event_name=="study_visits_arm_1") %>% select(subject_id,study_visit_mttt,mmtt_wt,mmtt_insulin_0,mmtt_insulin_10,
                          mmtt_insulin_20,mmtt_insulin_30,mmtt_insulin_45,mmtt_insulin_60,mmtt_insulin_90,mmtt_insulin_120,
                          mmtt_insulin_150,mmtt_insulin_180,mmtt_insulin_210,mmtt_insulin_240,mmtt_bg_0,mmtt_bg_10,
                          mmtt_bg_20,mmtt_bg_30,mmtt_bg_45,mmtt_bg_60,mmtt_bg_90,mmtt_bg_120,mmtt_bg_150,mmtt_bg_180,
                          mmtt_bg_210,mmtt_bg_240)
mmtt <- mmtt %>% filter(study_visit_mttt %in% c(1,2))

# calculate glucose AUC
source("C:/Users/pylell/Documents/GitHub/General-code/iauc.r")
mmtt$auc_glucose <- iAUC_insulin(data=mmtt,thresh=0,type="linear",times=c(0,10,20,30,45,60,90,120,150,180,210,240),
                          cols=c("mmtt_bg_0","mmtt_bg_10","mmtt_bg_20","mmtt_bg_30","mmtt_bg_45","mmtt_bg_60",
                                 "mmtt_bg_90","mmtt_bg_120","mmtt_bg_150","mmtt_bg_180","mmtt_bg_210",
                                 "mmtt_bg_240"))

# calculate insulin AUC
mmtt$auc_insulin <- iAUC_insulin(data=mmtt,thresh=0,type="linear",times=c(0,10,20,30,45,60,90,120,150,180,210,240),
                          cols=c("mmtt_insulin_0","mmtt_insulin_10","mmtt_insulin_20","mmtt_insulin_30","mmtt_insulin_45","mmtt_insulin_60",
                                 "mmtt_insulin_90","mmtt_insulin_120","mmtt_insulin_150","mmtt_insulin_180","mmtt_insulin_210",
                                 "mmtt_insulin_240"))

# calculate HOMA-IR
mmtt$homa_ir <- (mmtt$mmtt_bg_0*mmtt$mmtt_insulin_0)/405

# calculate HOMA-%B
mmtt$homa_b <- (360*mmtt$mmtt_insulin_0) / (mmtt$mmtt_bg_0 - 63)

# calculate Matsuda Index
mmtt$matsuda <- 10000/(sqrt(mmtt$mmtt_bg_0*mmtt$mmtt_insulin_0*
                  (((15*mmtt$mmtt_insulin_0)+(30*mmtt$mmtt_insulin_30)+(30*mmtt$mmtt_insulin_60)+(30*mmtt$mmtt_insulin_90)+(15*mmtt$mmtt_insulin_120))/120)*
                  (((15*mmtt$mmtt_bg_0)+(30*mmtt$mmtt_bg_30)+(30*mmtt$mmtt_bg_60)+(30*mmtt$mmtt_bg_90)+(15*mmtt$mmtt_bg_120))/120)))

# calculate Disposition Index
mmtt$isi <- (mmtt$mmtt_insulin_30 - mmtt$mmtt_insulin_0) / (mmtt$mmtt_bg_30-mmtt$mmtt_bg_0)
mmtt$odi <- (1/mmtt$mmtt_insulin_0) * mmtt$isi

# not sure what to do about hba1c - Kristen says not to adjust for it, but to treat it as an outcome
# so we'd need to look at change in A1c, so I need to find the 3 mo a1c variable

```

# Formulae used

HOMA-IR: mmtt_bg_0*mmtt_insulin_0/405

HOMA-B: (360*mmtt_insulin_0) / (mmtt_bg_0 - 63)

Matsuda Index: 10000/(sqrt(mmtt_bg_0 * mmtt_insulin_0 * 
                  (((15 * mmtt_insulin_0) + (30 * mmtt_insulin_30) + (30 * mmtt_insulin_60) + (30 * mmtt_insulin_90) + (15 * mmtt_insulin_120))/120) *
                  (((15 * mmtt_bg_0) + (30 * mmtt_bg_30) + (30 * mmtt_bg_60) + (30 * mmtt_bg_90) + (15 * mmtt_bg_120))/120)))

ODI: (1/mmtt_insulin_0) *  (mmtt_insulin_30 - mmtt_insulin_0) / (mmtt_bg_30-mmtt_bg_0)

# Methods

# Results

```{r echo=FALSE}
#kable(t1,caption = "")
```
<br>
