---
title: "IMPROVE-T2D 3 month analysis"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(arsenal)
library(dplyr)
library(knitr)
library(ggpubr)
library(nlme)
library(emmeans)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
```

```{r data, include=FALSE}
# read in screening data
source("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Nadeau/IMPROVE-T2D/Data raw/IMPROVET2D-ScreeningData_R_2024-02-27_1322.r")
screen <- data
data <- NULL
# select the participants
# IT2D-2,3,5,6,8,11-16, 18-20
screen <- screen %>% filter(subject_id %in% c("IT_02","IT_03","IT_05","IT_06","IT_08","IT_11","IT_12","IT_13","IT_14","IT_15","IT_16","IT_18","IT_19","IT_20"))

# read in repeating visit data
source("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Nadeau/IMPROVE-T2D/Data raw/IMPROVET2D-VisitData_R_2024-02-27_1323.r")
visit <- data
data <- NULL
# select the participants
# IT2D-2,3,5,6,8,11-16, 18-20
visit <- visit %>% filter(subject_id %in% c("IT_02","IT_03","IT_05","IT_06","IT_08","IT_11","IT_12","IT_13","IT_14","IT_15","IT_16","IT_18","IT_19","IT_20"))

# calculate glucose AUC
source("/Users/pylell/Documents/GitHub/General-code/iauc.r")
visit$auc_glucose <- iAUC_insulin(data=visit,thresh=0,type="linear",times=c(0,10,20,30,45,60,90,120,150,180,210,240),
                          cols=c("mmtt_bg_0","mmtt_bg_10","mmtt_bg_20","mmtt_bg_30","mmtt_bg_45","mmtt_bg_60",
                                 "mmtt_bg_90","mmtt_bg_120","mmtt_bg_150","mmtt_bg_180","mmtt_bg_210",
                                 "mmtt_bg_240"))

# calculate insulin AUC
for (i in 1:nrow(visit)){
  visit$auc_insulin[i] <- ifelse (!is.na(visit[i, "mmtt_insulin_0"]), 
                                   iAUC_insulin(data = visit[i,], thresh=0,type="linear",times=c(0,10,20,30,45,60,90,120,150,180,210,240),
                                    cols=c("mmtt_insulin_0","mmtt_insulin_10","mmtt_insulin_20","mmtt_insulin_30","mmtt_insulin_45","mmtt_insulin_60",
                                    "mmtt_insulin_90","mmtt_insulin_120","mmtt_insulin_150","mmtt_insulin_180","mmtt_insulin_210",
                                    "mmtt_insulin_240")), 
                                   NA) 
}

# calculate HOMA-IR
visit$homa_ir <- (visit$mmtt_bg_0*visit$mmtt_insulin_0)/405

# calculate HOMA-%B
visit$homa_b <- (360*visit$mmtt_insulin_0) / (visit$mmtt_bg_0 - 63)

# calculate Matsuda Index
visit$matsuda <- 10000/(sqrt(visit$mmtt_bg_0*visit$mmtt_insulin_0*
                  (((15*visit$mmtt_insulin_0)+(30*visit$mmtt_insulin_30)+(30*visit$mmtt_insulin_60)+(30*visit$mmtt_insulin_90)+(15*visit$mmtt_insulin_120))/120)*
                  (((15*visit$mmtt_bg_0)+(30*visit$mmtt_bg_30)+(30*visit$mmtt_bg_60)+(30*visit$mmtt_bg_90)+(15*visit$mmtt_bg_120))/120)))

# calculate Disposition Index
visit$isi <- (visit$mmtt_insulin_30 - visit$mmtt_insulin_0) / (visit$mmtt_bg_30-visit$mmtt_bg_0)
visit$odi <- (1/visit$mmtt_insulin_0) * visit$isi
```

# Results

## Descriptive statistics

```{r create_t1, include=FALSE}
#t1 <- tableby( ~ age_current +  gender.factor + race + ethnicity.factor, data = screen)
```

```{r t1, results='asis'}
#summary(t1)
```
