---
title: "PEDSNet PheWAS"
author: "Anna Furniss and Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(PheWAS)
library(dplyr)
library(ggplot2)
library(kableExtra)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "//data/dept/SOM/ACCORDS/PiFolders/PI_Davis/PEDSnet_Gender_Differences/DATA_Secure/B-ACCORDS_Analysts/SAS Data/PheWAS/SCA Data"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/PEDSNet/PheWAS/Data raw"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
}
knitr::opts_knit$set(root.dir = home_dir)
```

# Trisomy X

```{r, warning=FALSE, include=FALSE, cache=TRUE}
trisx <- read.csv("./TrisX_PheWAS_22.05.06.csv",colClasses = c('character','numeric','character','character','character','character'))
genotypes_trisx <- trisx %>% select(person_id,trisx)
p <- trisx %>% select(person_id,ICD9)
p$count <- 1
phenotypes_trisx <- createPhewasTable(p)
results=phewas(phenotypes=phenotypes_trisx,genotypes=genotypes_trisx, significance.threshold = "fdr")
results_d <- addPhecodeInfo(results)

results2=phewas(phenotypes=phenotypes_trisx,genotypes=genotypes_trisx)
results_d2 <- addPhecodeInfo(results2)

```

## Numbers of cases and controls

```{r, warning=FALSE, echo=FALSE, fig.height=5, fig.width=5}
a <- unique(trisx[,c("person_id","trisx")])
table(a$trisx)
```

## Manhattan plot

```{r, warning=FALSE, echo=FALSE, fig.height=5, fig.width=5}
phewasManhattan(results, title="", point.size=1.5, y.axis.interval=20, annotate.size=2,
                size.x.labels=5, max.y=320) 
```

## Significant results

```{r, warning=FALSE, echo=FALSE, fig.height=5, fig.width=5, comment=""}
kable(results_d[results_d$fdr&!is.na(results_d$p),c("phenotype","description","group","snp","beta","SE","OR","p","n_total","n_cases",
                                              "n_controls","allele_freq")]) %>%
  kable_styling("striped") %>% scroll_box(width="100%",height = "600px")
```

# Klinefelter

```{r, warning=FALSE, include=FALSE, cache=TRUE}
kline <- read.csv("//data/dept/SOM/ACCORDS/PiFolders/PI_Davis/PEDSnet_Gender_Differences/DATA_Secure/B-ACCORDS_Analysts/SAS Data/PheWAS/SCA Data/Kline_PheWAS.csv",colClasses = c('character','numeric','character','character','character','character'))
genotypes_kline <- kline %>% select(person_id,kline)
p <- kline %>% select(person_id,ICD9)
p$count <- 1
phenotypes_kline <- createPhewasTable(p)
results=phewas(phenotypes=phenotypes_kline,genotypes=genotypes_kline)
```

## Numbers of cases and controls

```{r, warning=FALSE, echo=FALSE, fig.height=5, fig.width=5}
a <- unique(kline[,c("person_id","kline")])
table(a$kline)
```

## Manhattan plot

```{r, warning=FALSE, echo=FALSE, fig.height=5, fig.width=5}
phewasManhattan(results, title="", point.size=1.5, y.axis.interval=20, annotate.size=2,
                size.x.labels=5, max.y=320)
```

## Significant results

```{r, warning=FALSE, echo=FALSE, fig.height=5, fig.width=5, comment=""}
kable(results_d[results_d$fdr&!is.na(results_d$p),c("phenotype","description","group","snp","beta","SE","OR","p","n_total","n_cases",
                                              "n_controls","allele_freq")]) %>%
  kable_styling("striped") %>% scroll_box(width="100%",height = "600px")
```

# Turner

```{r, warning=FALSE, include=FALSE, cache=TRUE}
turner <- read.csv("//data/dept/SOM/ACCORDS/PiFolders/PI_Davis/PEDSnet_Gender_Differences/DATA_Secure/B-ACCORDS_Analysts/SAS Data/PheWAS/SCA Data/Turner_PheWAS.csv",colClasses = c('character','numeric','character','character','character','character'))
genotypes_turner <- turner %>% select(person_id,turner)
p <- turner %>% select(person_id,ICD9)
p$count <- 1
phenotypes_turner <- createPhewasTable(p)
results=phewas(phenotypes=phenotypes_turner,genotypes=genotypes_turner)
```

## Numbers of cases and controls

```{r, warning=FALSE, echo=FALSE, fig.height=5, fig.width=5}
a <- unique(turner[,c("person_id","turner")])
table(a$turner)
```

## Manhattan plot

```{r, warning=FALSE, echo=FALSE, fig.height=5, fig.width=5}
phewasManhattan(results, title="", point.size=1.5, y.axis.interval=20, annotate.size=2,
                size.x.labels=5, max.y=320)
```

## Significant results

```{r, warning=FALSE, echo=FALSE, fig.height=5, fig.width=5, comment=""}
kable(results_d[results_d$fdr&!is.na(results_d$p),c("phenotype","description","group","snp","beta","SE","OR","p","n_total","n_cases",
                                              "n_controls","allele_freq")]) %>%
  kable_styling("striped") %>% scroll_box(width="100%",height = "600px")
```

# XYY

```{r, warning=FALSE, include=FALSE, cache=TRUE}
xyy <- read.csv("//data/dept/SOM/ACCORDS/PiFolders/PI_Davis/PEDSnet_Gender_Differences/DATA_Secure/B-ACCORDS_Analysts/SAS Data/PheWAS/SCA Data/XYY_PheWAS.csv",colClasses = c('character','numeric','character','character','character','character'))
genotypes_xyy <- xyy %>% select(person_id,xyy)
p <- xyy %>% select(person_id,ICD9)
p$count <- 1
phenotypes_xyy <- createPhewasTable(p)
results=phewas(phenotypes=phenotypes_xyy,genotypes=genotypes_xyy)
```

## Numbers of cases and controls

```{r, warning=FALSE, echo=FALSE, fig.height=5, fig.width=5}
a <- unique(xyy[,c("person_id","xyy")])
table(a$xyy)
```

## Manhattan plot

```{r, warning=FALSE, echo=FALSE, fig.height=5, fig.width=5}
phewasManhattan(results, title="", point.size=1.5, y.axis.interval=20, annotate.size=2,
                size.x.labels=5, max.y=320)
```

## Significant results

```{r, warning=FALSE, echo=FALSE, fig.height=5, fig.width=5, comment=""}
kable(results_d[results_d$fdr&!is.na(results_d$p),c("phenotype","description","group","snp","beta","SE","OR","p","n_total","n_cases",
                                              "n_controls","allele_freq")]) %>%
  kable_styling("striped") %>% scroll_box(width="100%",height = "600px")
```
