---
title: ""
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(readxl)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

home_dir = ifelse(.Platform$OS.type != "unix","E:\\Nadeau\\Nadeau Bromocriptine T1D DSMB\\Dissemination",
                  "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects")
knitr::opts_knit$set(root.dir = home_dir)


```

```{r, include=FALSE}
setwd(home_dir)
data <- read.csv("./BromocriptineData.csv")

# make a wide dataset
data_wide <- reshape(data,idvar="PTID",timevar = "TX",direction = "wide")

# calculate deltas (BCQR - PLA)
deltas <- data_wide[,4:28]- data_wide[,31:55]
c <- colnames(deltas)
c <- gsub("BCQR","delta",c)
colnames(deltas) <- c
data_wide <- cbind(data_wide, deltas)
```

# Background

# Methods

# Results

```{r echo=FALSE}
# for BP variables, just adjust for baseline
# but what is baseline?
mod <- lm(SBP.delta ~ SBP.Placebo, data=data_wide)

mod <- lm(SBP.delta ~ 1, data=data_wide)

```

```{r echo=FALSE}
vars <- c[4:14]

# group comparisons adjusted for age, sex, BMI
for (v in vars) {
  form = as.formula(paste0(v,"~T1DStatus+AgeYr+as.factor(THSA_Analysis_SEX)+BMI"))
  mod <- lm(form,data = data)
  print(noquote(c("Adjusted model for: ", noquote(v))))
  print(summary(mod))
  means <- emmeans(mod,"T1DStatus")
  print(means)
  #a <- Anova(mod,type="III")
  #print(a)
}
```

