---
title: "CF Data Registry Analysis"
author: "Casey Sakamoto"
date: "3/18/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(Hmisc)
library(readr)
library(knitr)
library(table1)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "S://Laura/Peds Endo/Christine Chan/CF registry data"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Christine Chan/CF registry data"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Christine Chan/CF registry data"
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r data load in, include=FALSE}
setwd("S://Laura/Peds Endo/Christine Chan/CF registry data")
# load in data 
CFF19_Demog <- read_csv("CFF19_DemogCFDiag_Del1.csv")
CFF19_Annualized <- read_csv("CFF19_Annualized_Del1.csv")
CFF19_CareEpisodes <- read_csv("CFF19_CareEpisodes_Del1.csv")
CFF19_encounters <- read_csv("CFF19_encountersMerged_Del1.csv")

```

```{r aim 1 code, include=FALSE}
# CFRD_status:
# 1	Normal Glucose Metabolism (includes normal, random, fasting, or OGTT)
# 2	Impaired Glucose Tolerance (FBG < 126, 2-h PG 140-199)
# 3	CFRD with or without fasting hyperglycemia ( 2-h PG >= 200)
# 4	Type 1 Diabetes
# 5	Type 2 Diabetes

# make a visit variable to iterate through
CFF19_encounters = CFF19_encounters %>% group_by(eDWID) %>% mutate(visit = row_number()) %>% ungroup()

# idea is to grab the lowest visit number that a subject has cfrd, then they have cfrd for the remainder of the visits
cfrd_status = CFF19_encounters %>% group_by(eDWID) %>% 
  filter(cfrd_status == 3) %>%
  mutate(cfrd_incident = case_when(visit == min(visit) ~ 1,
                                   TRUE ~ 0),
         incident_visit = min(visit)) %>% ungroup()

CFF19_encounters = full_join(CFF19_encounters, cfrd_status) %>% group_by(eDWID) %>% fill(incident_visit, .direction = "downup")
CFF19_encounters = CFF19_encounters %>% group_by(eDWID) %>% 
  mutate(cfrd_outcome = case_when(visit >= incident_visit ~ 1,
                                  TRUE ~ 0))
# prevalence/incidence
describe(CFF19_encounters$cfrd_outcome)
describe(CFF19_encounters$cfrd_incident)
CFF19_encounters = CFF19_encounters %>% mutate(cfrd_incident = ifelse(is.na(cfrd_incident), 0, cfrd_incident))
# data table with one row per subject year
cfrd_prevalence = CFF19_encounters %>% select(eDWID, reviewyear, cfrd_outcome, cfrd_incident) %>% distinct()
cfrd_prevalence = cfrd_prevalence %>% group_by(reviewyear, eDWID) %>% filter(cfrd_incident == max(cfrd_incident))

aim1_prev = cfrd_prevalence %>% group_by(reviewyear) %>% summarise(`CFRD Prevalence` = mean(cfrd_outcome),
                                                        `CFRD Incidence` = mean(cfrd_incident)*1000)
aim1_prev = aim1_prev %>% rename(`Review Year` = reviewyear)
rm(cfrd_status)



# combine data into one set
analysis = full_join(cfrd_prevalence, CFF19_Annualized, by = c("eDWID", "reviewyear" = "ReviewYear")) %>% distinct()
analysis = full_join(CFF19_Demog, analysis) %>% distinct()
# analysis = full_join(analysis, CFF19_CareEpisodes) %>% distinct()
analysis = analysis %>% select(eDWID, reviewyear,cfrd_outcome, cfrd_incident, Age_YrEnd, Gender, Race1:Race6, Hispanicrace, Diagnosis_year, 
                               Primarycauseofdeath, patient_education:pregnancy_outcome, smoking:smoking_household,family_income, #demog
                               A_FEV1, A_FVC,   NumPulmExacerbation,  Any_pe_assessment:A_medscurrentepisode7, # pulm function
                               A_pseudomonasaeruginosa, A_burkho_complex, 
                               A_othermicroorganisms1:A_othermicroorganisms2, A_fungalyeast1:A_fungalyeast3, # microbiome
                               MutClass:F508, A_IsOnEnzymes, # pancreas
                               NumHt:A_WHO_whz, A_salt_supplement:A_cf_vitamins, # nutrition/bmi
                               A_dornasealfa, A_PrimaryAirClear, A_bronchodilators1:A_bronchodilatorsinhaled5, oxygen_therapy, A_corticosteroids1:A_corticosteroids3,
                               A_pulmonarycomplications1:A_pulmonarycomplications5, A_othercomplications9, A_hepatobiliary1_3:A_cirrhosiscomplications7) 

# make time periods and age groups
# also label and factor cat variables/ clean up dataset
analysis = analysis %>% mutate(year_cat = case_when(reviewyear < 2010 ~ "2003-2009",
                                                    reviewyear < 2014 & reviewyear >= 2010 ~ "2010-2013",
                                                    reviewyear >= 2014 ~ "2014-2018"),
                               age_cat = case_when(Age_YrEnd < 10 ~ "< 10",
                                                   Age_YrEnd < 20 & Age_YrEnd >= 10 ~ "10-20",
                                                   Age_YrEnd < 30 & Age_YrEnd >= 20 ~ "20-30",
                                                   Age_YrEnd < 40 & Age_YrEnd >= 30 ~ "30-40",
                                                   Age_YrEnd < 50 & Age_YrEnd >= 40 ~ "40-50",
                                                   Age_YrEnd < 60 & Age_YrEnd >= 50 ~ "50-60",
                                                   Age_YrEnd < 70 & Age_YrEnd >= 60 ~ "60-70",
                                                   Age_YrEnd < 80 & Age_YrEnd >= 70 ~ "70-80",
                                                   Age_YrEnd >= 80 & Age_YrEnd < 90 ~ "80-90"),
                               race = case_when(Race1 == 1 ~ "White",
                                                Race2 == 1 ~ "Black or African American",
                                                Race3 == 1 ~ "American Indian or Alaska Native",
                                                Race4 == 1 ~ "Asian", 
                                                Race5 == 1 ~ "Native Hawaiian or Other Pacific Islander"),
                               employment = case_when(employment1 == 1 ~ "Part-Time",
                                                      employment2 == 1 ~ "FullTime Homemaker",
                                                      employment3 == 1 ~ "FullTime Employment",
                                                      employment4 == 1 ~ "Unemployed",
                                                      employment5 == 1 ~ "Student",
                                                      employment6 == 1 ~ "Disabled",
                                                      employment7 == 1 ~ "Retired"),
                               cirrhosiscomplications = case_when(A_cirrhosiscomplications1 == 1 ~ "Esophageal Varices",
                                                                  A_cirrhosiscomplications2 == 1 ~ "Gastric Varices",
                                                                  A_cirrhosiscomplications3 == 1 ~ "GI Bleed rel to varices",
                                                                  A_cirrhosiscomplications4 == 1 ~ "Splenomegaly",
                                                                  A_cirrhosiscomplications5 == 1 ~ "Hypersplenism",
                                                                  A_cirrhosiscomplications6 == 1 ~ "Ascites",
                                                                  A_cirrhosiscomplications7 == 1 ~ "Encephalopathy"),
                               bronchodilatorsinhaled = case_when(A_bronchodilatorsinhaled1 == 1 ~ "Short Acting beta agonist",
                                                                  A_bronchodilatorsinhaled2 == 1 ~ "Long Acting beta agonist",
                                                                  A_bronchodilatorsinhaled3 == 1 ~ "Short Acting anticholinergic",
                                                                  A_bronchodilatorsinhaled4 == 1 ~ "Long Acting anticholinergic",
                                                                  A_bronchodilatorsinhaled5 == 1 ~ "Comb beta agonist and anticholinergic")) %>%
  select(-(Race1:Race6), -(employment1:employmentuk), -(A_cirrhosiscomplications1:A_cirrhosiscomplications7), -(A_bronchodilatorsinhaled1:A_bronchodilatorsinhaled5))

analysis$year_cat = factor(analysis$year_cat, levels = c("2003-2009", "2010-2013", "2014-2018"))
analysis$age_cat = factor(analysis$age_cat, levels = c("< 10", "10-20", "20-30", "30-40", "40-50", "50-60", "60-70", "70-80", "80-90"))
analysis$Hispanicrace = factor(analysis$Hispanicrace, levels = c(1,2), labels = c("Hispanic Origin", "No Hispanic Origin"))
analysis$eDWID = factor(analysis$eDWID)



# aggregate variables based on year and subj
# first numerical variables (we'll avg them)
mean_na = function(x){
  return(mean(x, na.rm = T))
}

analysis_num = analysis %>% select(eDWID, year_cat, Age_YrEnd, A_FEV1, A_FVC, A_bmivalue, NumPulmExacerbation) %>% group_by(eDWID, year_cat) %>% 
  summarise(Age_yrEnd_avg = mean(Age_YrEnd),
            FEV1_avg = mean_na(A_FEV1),
            FVC_avg = mean_na(A_FVC),
            BMI_avg = mean_na(A_bmivalue),
            NumPulmExac_avg = mean_na(NumPulmExacerbation))

# aggregate categorical variables based on most frequent response
mode_na <- function(x) {
  uniqx <- unique(na.omit(x))
  uniqx[which.max(tabulate(match(x, uniqx)))]
}

analysis_cat = analysis %>% select(eDWID, year_cat, Gender, race, Hispanicrace, Primarycauseofdeath, patient_education:mother_education, family_income, marital_status, employment, smoking, second_smoke, MutClass:F508, A_PrimaryAirClear, oxygen_therapy, cirrhosiscomplications, bronchodilatorsinhaled )

analysis_cat = analysis_cat %>% group_by(eDWID, year_cat) %>% summarise(
  gender = mode_na(Gender),
  race = mode_na(race),
  hispanicrace = mode_na(Hispanicrace),
  Primarycauseofdeath = mode_na(Primarycauseofdeath),
  patient_education = mode_na(patient_education),
  father_education = mode_na(father_education),
  mother_education = mode_na(mother_education),
  family_income = mode_na(family_income),
  marital_status = mode_na(marital_status),
  employment = mode_na(employment),
  smoking = mode_na(smoking),
  second_smoke = mode_na(second_smoke),
  MutClass = mode_na(MutClass),
  Mutation1 = mode_na(Mutation1),
  Mutation2 = mode_na(Mutation2),
  Mutation3 = mode_na(Mutation3),
  F508 = mode_na(F508),
  primaryairclear = mode_na(A_PrimaryAirClear),
  oxygen_therapy = mode_na(oxygen_therapy),
  cirrhosiscomplications = mode_na(cirrhosiscomplications),
  bronchodilatorsinhaled = mode_na(bronchodilatorsinhaled)
  
)

# aggregate binary variables
# if any 1, then itll be a 1
any_bin = function(x){
  ifelse(1 %in% x, 1, 0)
}

analysis_bin = analysis %>% select(eDWID, year_cat, cfrd_outcome, cfrd_incident, pregnant,Any_pe_assessment, Any_pe_positive, A_pseudomonasaeruginosa:A_fungalyeast3, A_IsOnEnzymes, A_salt_supplement:A_dornasealfa, A_hemoptysistype1:A_hepatobiliary_old)

analysis_bin = analysis_bin %>% group_by(eDWID, year_cat) %>% summarise(
  cfrd_outcome = any_bin(cfrd_outcome),
  cfrd_incident = any_bin(cfrd_incident),
  pregnant = any_bin(pregnant),
  Any_pe_assessment = any_bin(Any_pe_assessment),
  Any_pe_positive = any_bin(Any_pe_positive),
  pseudomonasaeruginosa = any_bin(A_pseudomonasaeruginosa),
  burkho_complex = any_bin(A_burkho_complex),
  alcaligenes = any_bin(A_othermicroorganisms1),
  stenotrophomonas = any_bin(A_othermicroorganisms2),
  aspergillus = any_bin(A_fungalyeast1),
  candida = any_bin(A_fungalyeast2),
  scedosporium = any_bin(A_fungalyeast3),
  isonenzymes = any_bin(A_IsOnEnzymes),
  salt_supplement = any_bin(A_salt_supplement),
  cf_vitamins = any_bin(A_cf_vitamins),
  dornasealfa = any_bin(A_dornasealfa),
  hemoptysis_massive = any_bin(A_hemoptysistype1),
  hemoptysis_other = any_bin(A_hemoptysistype2),
  pneumothorax_chesttube = any_bin(A_pulmonarycomplications5),
  sinusdisease = any_bin(A_othercomplications9),
  liverdisease_cirr = any_bin(A_hepatobiliary1_3)
)

analysis_final = full_join(analysis_bin, analysis_num)
analysis_final = full_join(analysis_final, analysis_cat)
```

NOTE: Incomplete data dictionary:
Important ones:
f508
pe_assessment, meds assessment variables dont seem correct

Less so:
primarycauseofdeath: what is 0 and 1 (assuming alive and something else?)


```{r Aim 1 Prev}
kable(aim1_prev, digits = 3)
```
Incidence per year will is estimated as the number of incident CFRD diagnoses per 1,000 person-years of longitudinal data, with prevalent cases excluded.



```{r table1}
# create a rough table1 by year_cat and cfrd status? to look at patient characteristics
cfrd_table1 = table1(~ gender + race + hispanicrace + Age_yrEnd_avg + BMI_avg + as.factor(patient_education) + as.factor(father_education) + as.factor(mother_education) + 
                       as.factor(family_income) + as.factor(marital_status) + employment + as.factor(pregnant) + as.factor(smoking) + as.factor(second_smoke) + FEV1_avg +
                       FVC_avg + NumPulmExac_avg + as.factor(Any_pe_assessment) + as.factor(Any_pe_positive) + as.factor(oxygen_therapy) + bronchodilatorsinhaled +
                       as.factor(primaryairclear) + as.factor(isonenzymes) + as.factor(salt_supplement)+ as.factor(cf_vitamins) + as.factor(dornasealfa) +
                       as.factor(hemoptysis_massive) + as.factor(hemoptysis_other) + as.factor(pneumothorax_chesttube) + as.factor(sinusdisease) +
                       as.factor(liverdisease_cirr) + cirrhosiscomplications + as.factor(pseudomonasaeruginosa) + as.factor(burkho_complex) +
                       as.factor(alcaligenes)+ as.factor(stenotrophomonas) + as.factor(aspergillus) + as.factor(candida)+ as.factor(scedosporium)+
                       as.factor(MutClass) + as.factor(Mutation1) + as.factor(Mutation2) + as.factor(Mutation3) + as.factor(F508)
                       | year_cat*as.factor(cfrd_outcome),
                     render.continuous=c(.="Mean (SD)"),
                     data = analysis_final)



cfrd_table1
```