---
title: "Liver scRNA analysis"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    embed-resources: true
---

```{r libraries, echo=F, include = F}
library(tidyverse)
library(arsenal)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(Seurat)
```

```{r echo = F}
# Liver scRNA data processing
so_liver_sc <- readRDS("/Volumes/Peds Endo/Petter Bjornstad/scRNA/data_raw/PB_Liver_7SingleCellDatasets.RDS")

# Add missing liver meta data to Seurat object
meta_liver_raw <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/scRNA/data_clean/liver_biopsy_metadata_PN.csv")

meta_liver_sc <-  so_liver_sc@meta.data[,1:9] %>%
  dplyr::mutate(Cryostor_ID = gsub("-Liv", "", orig.ident)) %>%
  left_join(meta_liver_raw)

rownames(meta_liver_sc) <- rownames(so_liver_sc@meta.data)

so_liver_sc <- AddMetaData(so_liver_sc, meta_liver_sc)
so_liver_sc <- NormalizeData(so_liver_sc)
so_liver_sc <- ScaleData(so_liver_sc)
# PCA
so_liver_sc <- RunPCA(so_liver_sc, features = VariableFeatures(object = so_liver_sc))
ElbowPlot(so_liver_sc)
# Cluster cells
so_liver_sc <- FindNeighbors(so_liver_sc)
so_liver_sc <- FindClusters(so_liver_sc)
# Perform UMAP and tSNE
so_liver_sc <- RunUMAP(so_liver_sc, dims = 1:15)
DimPlot(so_liver_sc, reduction = "umap") 
```

```{r echo = F}
# Liver snRNA data processing
so_liver_sn <- readRDS("/Volumes/Peds Endo/Petter Bjornstad/scRNA/data_raw/NoRef_PetterLiver_ClinData_Labels_Char_041924.RDS")

meta_liver_sn <-  so_liver_sn@meta.data[,1:11] %>%
  dplyr::mutate(RNAlater_ID = SampleID) %>%
  left_join(meta_liver_raw)

rownames(meta_liver_sn) <- rownames(so_liver_sn@meta.data)
```

## scRNA UMAP

```{r echo=F}

```

## snRNA UMAP


## Obese vs. Obese + T2D
### Descriptive table
```{r echo = F}
# Descriptive stats
liver_meta_raw_sc <- liver_meta_raw %>%
  filter(Cryostor_ID!="")
form <- paste("diagnosis_of_diabetes", paste(colnames(liver_meta_raw_sc)[6:36], collapse = " + "), sep = " ~ ")

summary(arsenal::tableby(formula = as.formula(form), data = liver_meta_raw_sc, test = F))

```



## MASLD Y/N
### Descriptive table

```{r echo = F}
# Descriptive stats
# liver_meta_raw_sc <- liver_meta_raw %>%
#   filter(Cryostor_ID!="")
# form <- paste("masld", paste(colnames(liver_meta_raw_sc)[6:36], collapse = " + "), sep = " ~ ")
# 
# summary(arsenal::tableby(formula = as.formula(form), data = liver_meta_raw_sc, test = F))

```

## OSA Y/N
### Descriptive table

```{r echo = F}
# Descriptive stats
liver_meta_raw_sc <- liver_meta_raw %>%
  filter(Cryostor_ID!="")
form <- paste("diagnosis_of_osa", paste(colnames(liver_meta_raw_sc)[6:36], collapse = " + "), sep = " ~ ")

summary(arsenal::tableby(formula = as.formula(form), data = liver_meta_raw_sc, test = F))

```

## GLP-1RA Y/N
### Descriptive table

```{r echo = F}
# Descriptive stats
liver_meta_raw_sc <- liver_meta_raw %>%
  filter(Cryostor_ID!="")
form <- paste("glp1agonist", paste(colnames(liver_meta_raw_sc)[6:36], collapse = " + "), sep = " ~ ")

summary(arsenal::tableby(formula = as.formula(form), data = liver_meta_raw_sc, test = F))

```

## Insulin Y/N
### Descriptive table

```{r echo = F}
# Descriptive stats
liver_meta_raw_sc <- liver_meta_raw %>%
  filter(Cryostor_ID!="")
form <- paste("insulin", paste(colnames(liver_meta_raw_sc)[6:36], collapse = " + "), sep = " ~ ")

summary(arsenal::tableby(formula = as.formula(form), data = liver_meta_raw_sc, test = F))

```

## Kidney disease Y/N
### Descriptive table

```{r echo = F}
# # Descriptive stats
# liver_meta_raw_sc <- liver_meta_raw %>%
#   filter(Cryostor_ID!="")
# form <- paste("kidneydisease", paste(colnames(liver_meta_raw_sc)[6:36], collapse = " + "), sep = " ~ ")
# 
# summary(arsenal::tableby(formula = as.formula(form), data = liver_meta_raw_sc, test = F))

```
