---
title: "Pima youth onset vs. adult onset"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}

library(knitr)
library(survival)
library(ranger)
library(ggplot2)
library(dplyr)
library(ggfortify)

alldata <- read.csv("E:\\Petter Bjornstad\\Pima\\Youth vs. adult onset kidney disease\\Data_raw\\pima_yo.csv")
vital <- read.csv("E:\\Petter Bjornstad\\Pima\\Youth vs. adult onset kidney disease\\Data_raw\\Vital Status.csv")

# inpimayo <- as.data.frame(alldata$NIH)
# inpimayo$inpimayo <- 1
# colnames(inpimayo) <- c("NIH","inpimayo")
# invital <- as.data.frame(vital$NIH)
# invital$invital <- 1
# colnames(invital) <- c("NIH","invital")
# check <- merge(inpimayo,invital,by="NIH",all.x = T, all.y = T)

# only keep the IDs in pima_yo
alldata <- merge(alldata,vital,by="NIH",all.x=TRUE,all.y=FALSE)

# need to estimate DOB using biospy date and age at biopsy
alldata$BIOP_DATE <- as.Date(as.character(alldata$BIOP_DATE),format="%m/%d/%Y")
alldata$DOD <- as.Date(as.character(alldata$DOD),format="%m/%d/%y")
alldata$ESRD_DT <- as.Date(as.character(alldata$ESRD_DT),format="%m/%d/%y")
alldata$dob <- alldata$BIOP_DATE - (alldata$AGE_BIOP*365.25)

# estimate date of dx
alldata$date_of_dx <- alldata$dob + (alldata$AGE_ON*365.25)

# calculate time to death and censoring time for death
# assume all participants followed through 12/31/2019
# when calculating time to death, need to use date of dx as start date
# otherwise, adults will look like they had a longer time to death b/c they had a longer time to dx
alldata$death_time <- NA
alldata[alldata$DEAD==1,]$death_time <- (alldata[alldata$DEAD==1,]$DOD - alldata[alldata$DEAD==1,]$date_of_dx)/365.25
alldata[alldata$DEAD==0,]$death_time <- (as.Date('2019/12/31') - alldata[alldata$DEAD==0,]$date_of_dx)/365.25

# calculate time to ESKD and censoring time for ESKD
alldata$eskd_time <- NA
alldata[alldata$ESRD==1,]$eskd_time <- (alldata[alldata$ESRD==1,]$ESRD_DT - alldata[alldata$ESRD==1,]$date_of_dx)/365.25
alldata[alldata$ESRD==0,]$eskd_time <- (as.Date('2019/12/31') - alldata[alldata$ESRD==0,]$date_of_dx)/365.25

# compare time to death
km_death <- with(alldata, Surv(death_time,DEAD))
km_death_fit_21 <- survfit(Surv(death_time,DEAD)~youth21, data=alldata)
autoplot(km_death_fit_21)
km_death_test_21 <- survdiff(Surv(death_time,DEAD)~youth21, data=alldata)
km_death_fit_25 <- survfit(Surv(death_time,DEAD)~youth25, data=alldata)
autoplot(km_death_fit_25)
km_death_test_25 <- survdiff(Surv(death_time,DEAD)~youth25, data=alldata)

# compare time to ESKD
km_eskd <- with(alldata, Surv(eskd_time,ESRD))
km_eskd_fit_21 <- survfit(Surv(eskd_time,ESRD)~youth21, data=alldata)
autoplot(km_eskd_fit_21)
km_eskd_test_21 <- survdiff(Surv(eskd_time,ESRD)~youth21, data=alldata)
km_eskd_fit_25 <- survfit(Surv(eskd_time,ESRD)~youth25, data=alldata)
autoplot(km_eskd_fit_25)
km_eskd_test_25 <- survdiff(Surv(eskd_time,ESRD)~youth25, data=alldata)


# need to think about competing risks analysis for ESKD?
# also, how are we going to account for age in these analyses - need to adjust

```

# Background


# Methods


# Results


```{r, echo=FALSE}
kable(tab_targeted_group,caption = "Descriptive statistics for targeted metabolites, by group.")
```
