---
title: "Pima youth onset vs. adult onset"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}

library(knitr)
library(tableone)
library(emmeans)

alldata <- read.csv("E:\\Petter Bjornstad\\Pima\\Youth vs. adult onset kidney disease\\Data_raw\\pima_yo.csv",
                    na.strings = c("NA",""," "))

# convert to numeric
alldata$SMAC_TRI <- as.numeric(sub(",","",as.character(alldata$SMAC_TRI)))
alldata$ACR <- as.numeric(sub(",","",as.character(alldata$ACR)))
alldata$RPF <- as.numeric(sub(",","",as.character(alldata$RPF)))

# convert to factor
alldata$SEX <- as.factor(alldata$SEX)
alldata$MED_INS <- as.factor(alldata$MED_INS)
alldata$MED_RAS <- as.factor(alldata$MED_RAS)

# export for SAS
write.csv(alldata,"E:\\Petter Bjornstad\\Pima\\Youth vs. adult onset kidney disease\\Data_raw\\export.csv")


tab1vars <- c("AGE_ON","SEX","MED_INS","MED_RAS","AGE_BIOP","DUR_BIOP","HBA1C","BMI","SBP","DBP","SMAC_CHOL","SMAC_TRI",
              "ACR","GFR","RPF","HBA1C")

tab1a <- CreateTableOne(vars=tab1vars,strata="youth25",data=alldata)
tab1a <- print(tab1a,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,nonnorm=c("SMAC_TRI","ACR"),
               exact=c("SEX"))

tab1b <- CreateTableOne(vars=tab1vars,strata="youth21",data=alldata)
tab1b <- print(tab1b,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,nonnorm=c("SMAC_TRI","ACR"))

morphvar <- c("GBM","VVMES","VVINT","GV","C_P_SCLER")

mods <- function(outcome) {
  print(paste("Regression of ",outcome," on youth onset (<25 years) vs. adult onset"))
  x <- lm(as.formula(paste(outcome, "~ youth25 + SEX + AGE_BIOP + HBA1C + GFR + BMI ")), data=alldata)
  em <- emmeans(x, specs=pairwise ~ youth25)
  x1 <- lm(as.formula(paste(outcome, "~ youth25 + SEX + AGE_BIOP + HBA1C + BMI ")), data=alldata)
  em1 <- emmeans(x1, specs=pairwise ~ youth25)
  x2 <- lm(as.formula(paste(outcome, "~ youth25 + SEX + AGE_BIOP + HBA1C + GFR + BMI + MEDIA")), data=alldata)
  em2 <- emmeans(x2, specs=pairwise ~ youth25)
  x3 <- lm(as.formula(paste(outcome, "~ youth25 + SEX + HBA1C + GFR + BMI + DUR_BIOP")), data=alldata)
  em3 <- emmeans(x3, specs=pairwise ~ youth25)
  res <- list(summary(x),em,summary(x1),em1,summary(x2),em2,summary(x3),em3)
  return(res)
}

mods21 <- function(outcome) {
  print(paste("Regression of ",outcome," on youth onset (<21 years) vs. adult onset"))
  x <- lm(as.formula(paste(outcome, "~ youth21 + SEX + AGE_BIOP + HBA1C + GFR + BMI ")), data=alldata)
  em <- emmeans(x, specs=pairwise ~ youth21)
  x1 <- lm(as.formula(paste(outcome, "~ youth21 + SEX + AGE_BIOP + HBA1C + BMI ")), data=alldata)
  em1 <- emmeans(x1, specs=pairwise ~ youth21)
  x2 <- lm(as.formula(paste(outcome, "~ youth21 + SEX + AGE_BIOP + HBA1C + GFR + BMI + MEDIA ")), data=alldata)
  em2 <- emmeans(x, specs=pairwise ~ youth21)
  res <- list(summary(x),em,summary(x1),em1,summary(x2),em2)
  return(res)
}

modage <- function(outcome) {
  print(paste("Regression of ",outcome," on age of onset"))
  x <- lm(as.formula(paste(outcome, "~ AGE_ON + SEX + AGE_BIOP + HBA1C + GFR + BMI")), data=alldata)
  x1 <- lm(as.formula(paste(outcome, "~ AGE_ON + SEX + AGE_BIOP + HBA1C + BMI")), data=alldata)
  x2 <- lm(as.formula(paste(outcome, "~ AGE_ON + SEX + AGE_BIOP + HBA1C + GFR + BMI + MEDIA")), data=alldata)
  res <- list(summary(x),summary(x1),summary(x2))
  return(res)
}

```


```{r, echo=FALSE}
kable(tab1a,caption = "Descriptive statistics for demographics and clinical variables in participants with youth onset T2D 
      (onset <25 years) vs adult onset.")
```
<br>

```{r, echo=FALSE}
kable(tab1b,caption = "Descriptive statistics for demographics and clinical variables in participants with youth onset T2D 
      (onset <21 years) vs adult onset.")
```
<br>

```{r, echo=FALSE}
mods("GBM")
```

\newpage

```{r, echo=FALSE}
mods("VVMES")
```

\newpage

```{r, echo=FALSE}
mods("VVINT")
```

\newpage

```{r, echo=FALSE}
mods("GV")
```

\newpage

```{r, echo=FALSE}
mods("C_P_SCLER")
```

\newpage

```{r, echo=FALSE}
mods21("GBM")
```

\newpage

```{r, echo=FALSE}
mods21("VVMES")
```

\newpage

```{r, echo=FALSE}
mods21("VVINT")
```

\newpage

```{r, echo=FALSE}
mods21("GV")
```

\newpage

```{r, echo=FALSE}
mods21("C_P_SCLER")
```

\newpage

```{r, echo=FALSE}
modage("GBM")
```

\newpage

```{r, echo=FALSE}
modage("VVMES")
```

\newpage

```{r, echo=FALSE}
modage("VVINT")
```

\newpage

```{r, echo=FALSE}
modage("GV")
```

\newpage

```{r, echo=FALSE}
modage("C_P_SCLER")
```

\newpage
