---
title: "Pima"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,dpi = 600,cache = TRUE)
knitr::opts_knit$set(root.dir = "/home/tim/Work/Petter Bjornstad/Pima/Youth vs. adult onset kidney disease")
library(mixOmics)
library(readxl)
library(limma)
library(knitr)
library(tidyverse)
set.seed(1017)
```

# Morphometric parameters (variables of tissue integrity):
## These are the most important ones:
- GBM
- VVMES
- VVINT
- GV
- P_SCLER
## There are less important, but could be worth looking at:
- SV
- VPC
- VVPC
- NVPC
- P_FPW
- P_FEN
- VVAT_NS
- VVATTT_NS
- VVPT_NS
- VVDT_NS
- VVTT_NS
- GV_GLOMS
- P_SCLER
# Functional parameters (variables of kidney function):
- GFR
- RPF
- SBP
- DBP

```{r include=FALSE}
# Import data
clinical_data = read.csv("./Data_raw/pima_yo.csv",stringsAsFactors=F,na.strings = "")
um_data = read.csv("./Data_raw/UM_SS_Serum_yop.csv")
jos_dict = read_excel("./Data_raw/jos_ss_datadictionary.xlsx")
jos_data = read.csv("./Data_raw/jos_ss_yop.csv")
# Format
um_data$youth21 = clinical_data$youth21[match(um_data$NIH,clinical_data$NIH)]
um_data$youth25 = clinical_data$youth25[match(um_data$NIH,clinical_data$NIH)]
um_data = um_data %>% select(NIH,youth21,youth25,A2M_3708_62_1:ZNRF3_14122_132_3)
um_data[,4:ncol(um_data)] = lapply(um_data[,4:ncol(um_data)],log)
```

