---
title: "Diet and activity metabolomics"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)

knitr::opts_chunk$set(echo = FALSE)

#source("C:\\Users\\pylell\\Documents\\GitHub\\Green-diet-and-exercise-metabolomics\\analysis_nounk_nomiss.r")

setwd("H:\\Endocrinology\\Green\\Metabolomics papers\\Diet and exercise\\Data\\")

library(readxl)
# load NormalizeMets first, metabolomics second
library(NormalizeMets)
#library(metabolomics)
library(pca3d)
library(pcaMethods)
library(ggplot2)
library(rgl)
library(stringr)
library(data.table)
library(dplyr)
library(mixOmics)
library(Hmisc)
library("FactoMineR")
library("factoextra")
library(tableone)
library(gdata)
library(forcats)
library(limma)
library(metabomxtr)
library(BiocParallel)

register(SnowParam(exportglobals = FALSE))

# read and transpose data
#mydata <- read_excel(path="H:\\Endocrinology\\Green\\Metabolomics papers\\Diet and exercise\\Data\\raw data for metaboanalyst no null.xlsx",sheet=1 )
# read in new dataset from Haseeb with identified unknowns
mydata <- read_excel(path="H:\\Endocrinology\\Green\\Metabolomics papers\\Diet and exercise\\Data\\updated data with identified unknowns 1.2.19 no null.xlsx",sheet=1 )
mydata <- as.data.frame(mydata)
mydata <- mydata[!is.na(mydata$Name),]
alldata <- as.data.frame(t(mydata[,-1]))
colnames(alldata) <- mydata$Name
colnames(alldata) <- str_remove_all(colnames(alldata),fixed(" (M-H)-"))
colnames(alldata) <- str_remove(colnames(alldata),fixed(" (M+Cl)-"))
colnames(alldata) <- str_remove(colnames(alldata),fixed(" (M-H)-[-H2O]"))
colnames(alldata) <- str_remove(colnames(alldata),fixed(" (M-H)+[-H2O]"))
colnames(alldata) <- str_remove(colnames(alldata),fixed(" (M+Cl)+[-H2O]"))
colnames(alldata) <- str_remove(colnames(alldata),fixed(" (M+Cl)-"))
colnames(alldata) <- str_remove(colnames(alldata),fixed(" (M+H)-"))
colnames(alldata) <- str_remove(colnames(alldata),fixed(" [-H2O]"))
colnames(alldata) <- str_remove(colnames(alldata),fixed("[-H2O]"))
colnames(alldata) <- str_remove(colnames(alldata),fixed(" (2M-H)+"))
colnames(alldata) <- str_remove(colnames(alldata),fixed(" (M+H)+"))
colnames(alldata) <- str_remove(colnames(alldata),fixed(" (M+K)+"))
colnames(alldata) <- str_remove(colnames(alldata),fixed(" (M+Na)+"))

source("C:\\Users\\pylell\\Documents\\GitHub\\General-code\\temp_table1.r")
source("C:\\Users\\pylell\\Documents\\GitHub\\General-code\\foldchange.r")
source("C:\\Users\\pylell\\Documents\\GitHub\\General-code\\editcolnames.r")

# create variable for ID
for (i in 1:nrow(alldata)) {
  alldata$longid[i] <- row.names(alldata)[i]
}
alldata$longid <- gsub("\\s", "", alldata$longid) 
alldata$id <- gsub("OGTT0", "", alldata$longid) 
alldata$id <- gsub("BCTP0", "", alldata$id) 
alldata$id <- gsub("PCOS6164-", "", alldata$id)
alldata$id <- gsub("PCOSHS6164-", "", alldata$id)
alldata$id <- gsub("Control6164-", "", alldata$id)
alldata$uniqueid <- paste(substr(alldata$longid,1,1),alldata$Batch,alldata$id,sep="")
row.names(alldata) <- alldata$uniqueid

# check how  many compounds are known
check_knowns <- alldata[, -grep("UNK",colnames(alldata))]

# convert to numeric
num <- alldata[ ,!(colnames(alldata) %in% c("Batch","id","longid","uniqueid"))]
fwrite(num,"C:\\Temp\\temp.csv")
newnum <- fread("C:\\Temp\\temp.csv",colClasses = "numeric")
alldata <- alldata[ ,(colnames(alldata) %in% c("Batch","id","uniqueid"))]
alldata <- cbind(alldata,newnum)

# keep only diet condition since that has less missing data
gooddata <- alldata[alldata$Batch=="diet",]
for (i in 1:nrow(gooddata)) {
  gooddata$PCOS[i] <- ifelse(substring(row.names(gooddata[i,]),1,1)=="P",1,0)
}
gooddata$Group <- gooddata$PCOS
gooddata <- cbind(gooddata[,1:3],gooddata[,6748:6749],gooddata[,4:6747])
final <- NULL
final$featuredata <- gooddata[,-c(1:5)]
final$sampledata <- as.data.frame(gooddata[,5])
colnames(final$sampledata) <- "Group"
rownames(final$sampledata) = rownames(final$featuredata)
final$metdata <- as.data.frame(colnames(final$featuredata))
colnames(final$metdata)="Metabolite"

# no imputation
final_nomiss <- final
# now we should have an object with featuredata, sampledata, and groupdata

# make a version with only knowns
final_nomiss_nounk <- NULL
final_nomiss_nounk$featuredata <- final_nomiss$featuredata[, -grep("UNK",colnames(final_nomiss$featuredata))]
final_nomiss_nounk$sampledata <- final_nomiss$sampledata
final_nomiss_nounk$metabolitedata <- final_nomiss$metabolitedata[-grep("UNK",final_nomiss$metabolitedata)]

# log transform both the entire dataset and the known dataset
final_nomiss.log <- NULL
temp <- final_nomiss$featuredata
final_nomiss.log <- LogTransform(temp)
final_nomiss.log$sampledata <- final_nomiss$sampledata
final_nomiss.log$metabolitedata <- final_nomiss$metabolitedata
final_nomiss_nounk.log <- NULL
temp <- final_nomiss_nounk$featuredata
final_nomiss_nounk.log <- LogTransform(temp)
final_nomiss_nounk.log$sampledata <- final_nomiss_nounk$sampledata
final_nomiss_nounk.log$metabolitedata <- final_nomiss_nounk$metabolitedata

# add variable for PCOS
# NOTE: DEBUG CODE USING ONLY KNOWNS
nomissdf_pcos <- final_nomiss.log$featuredata
#nomissdf_pcos <- final_nomiss_nounk.log$featuredata
nomissdf_pcos <- as.data.frame(nomissdf_pcos)
for (i in 1:nrow(nomissdf_pcos)) {
 nomissdf_pcos$PCOS[i] <- ifelse(substring(row.names(nomissdf_pcos[i,]),1,1)=="P",1,0)
}
#nomissdf_pcos <- cbind(nomissdf_pcos[,6745],nomissdf_pcos[1:6744])
#colnames(nomissdf_pcos) <- c("PCOS",colnames(nomissdf_pcos[,2:6745]))
nomissdf_pcos <- cbind(nomissdf_pcos[,ncol(nomissdf_pcos)],nomissdf_pcos[1:ncol(nomissdf_pcos)-1])
colnames(nomissdf_pcos) <- c("PCOS",colnames(nomissdf_pcos[,2:ncol(nomissdf_pcos)]))

# choose vars of interest
yvars <- colnames(nomissdf_pcos)[2:ncol(nomissdf_pcos)]
table(apply(nomissdf_pcos[,yvars],2,function(x){sum(is.na(x))}))

# examine a few distributions
par(mfrow = c(2, 2))
hist(nomissdf_pcos$`S-ADENOSYL-L-HOMOCYSTEINE`  ,main="S-ADENOSYL-L-HOMOCYSTEINE",xlab=NULL)
hist(nomissdf_pcos$`ARACHIDONIC ACID` ,main="ARACHIDONIC ACID",xlab=NULL)
hist(nomissdf_pcos$`c8-OCTANOYLCARNITINE`  ,main="c8-OCTANOYLCARNITINE",xlab=NULL)
hist(nomissdf_pcos$`c18:2-Linoleyl carnitine`  ,main="Pc18:2-Linoleyl carnitine",xlab=NULL)

# set reference group to controls
nomissdf_pcos$PCOS <- as.factor(as.character(nomissdf_pcos$PCOS))
nomissdf_pcos$PCOS <- relevel(nomissdf_pcos$PCOS,ref="0")
fullModel <- ~PCOS|PCOS
reducedModel <- ~1|1
fullModelResults<-mxtrmod(ynames=yvars,mxtrModel=fullModel,data=nomissdf_pcos,nNA=3)
reducedModelResults <- mxtrmod(ynames=yvars,mxtrModel = reducedModel,data=nomissdf_pcos,fullModel = fullModel,nNA=3)
finalResult<-mxtrmodLRT(fullmod=fullModelResults,redmod=reducedModelResults,adj="BH")

# how many tests are significant?
sig <- nrow(finalResult[finalResult$adjP<0.05,])

# put together results table
PCOS.Prop<-round(exp(fullModelResults$xInt+fullModelResults$x_PCOS1)/ (1+exp(fullModelResults$xInt+fullModelResults$x_PCOS1)),digits=2)
Control.Prop<-round(exp(fullModelResults$xInt)/(1+exp(fullModelResults$xInt)),digits=2)
PCOS.Mean<-round(fullModelResults$zInt+fullModelResults$z_PCOS1,digits=2)
Control.Mean<-round(fullModelResults$zInt,digits=2)
PCOS.MeanDiff<-round(fullModelResults$z_PCOS1,digits=2)
finalResultTable<-data.frame(Metabolite=fullModelResults$.id,PCOS.Prop=PCOS.Prop,
                             Control.Prop=Control.Prop,PCOS.Mean=PCOS.Mean,
                             Control.Mean=Control.Mean,Mean.Difference=PCOS.MeanDiff,
                             FDR.Adj.P=round(finalResult$adjP,digits=4))

finalResultTable[finalResultTable$FDR.Adj.P<0.05,]

# testing model on metabdata
#data(metabdata)
#yvars <- colnames(metabdata)[10:ncol(metabdata)]
#yvars<-colnames(metabdata)[24:27]
#metabdata$PHENO<-relevel(metabdata$PHENO,ref="MomLowFPG")
#fullModel <- ~PHENO|PHENO
#reducedModel <- ~1
#fullModelResults<-mxtrmod(ynames=yvars,mxtrModel=fullModel,data=metabdata)


