---
title: "Proteomics and DKD - TODAY Pathway Analyses"
author: "Laura Pyle, Ye Ji Choi & Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
execute:
  echo: false
  message: false
---

```{r libraries}
#| include: false
library(tidyverse)
library(ggrepel)
library(clusterProfiler)
library(ReactomePA)
library(patchwork)
library(FDRestimation)
library(dplyr)
library(ggplot2)
library(MatchIt)
library(tableone)
```

```{r data import}
set.seed(3654)

# NELL1 plots
df <- read.csv("/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/soma_harmonized_dataset.csv")
df$seq.6544.33 <- log(df$seq.6544.33)
temp <- df[,c("record_id", "visit", "procedure", "gfr_bsa_plasma", "seq.6544.33", "group", "age")]
temp <- temp %>% filter(!is.na(seq.6544.33)) %>% filter(!is.na(gfr_bsa_plasma)) %>% filter(visit == "baseline")
p1 <- ggplot(temp, aes(x=group, y=seq.6544.33)) + geom_boxplot() + 
                     ylab("log(NELL1)")
p2 <- temp %>% ggplot(aes(age, seq.6544.33, fill = group)) +  
                     geom_point() + 
                     geom_smooth(method = "lm") + 
                     ylab("log(NELL1)") + 
                     scale_x_continuous(limits = c(0, 45))

# identify RH, RH2, and IMPROVE samples with high NELL1 seq.6544.33 and biopsy
df_rri <- df %>% filter(study %in% c("IMPROVE", "RENAL-HEIR", "RENAL-HEIRitage")) 
df_keep <- df_rri %>% filter(procedure == "bold_mri") %>% filter(visit == "baseline")
df_keep <- df_keep %>% select(record_id, visit, procedure, seq.6544.33, group, sex, age)
# now get kit IDs from biopsy
df_biopsy <- df_rri %>% filter(study %in% c("IMPROVE", "RENAL-HEIR", "RENAL-HEIRitage")) %>% filter(!is.na(kit_id)) %>% filter(procedure == "kidney_biopsy") %>% filter(visit == "baseline") %>% filter(group == "Type 2 Diabetes")
df_biopsy_keep <- df_biopsy %>% select(record_id, kit_id)
df_keep <- full_join(df_keep, df_biopsy_keep, by = "record_id")
df_keep <- df_keep %>% filter(!is.na(seq.6544.33)) %>% filter(!is.na(kit_id)) %>% filter(!(kit_id %in% c(" ","")))

# identify HC samples from CROCODILE
croc <- read.csv("/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/soma_harmonized_dataset.csv")
croc$seq.6544.33 <- log(croc$seq.6544.33)
croc_hc <- croc %>% filter(study == "CROCODILE") %>% filter(group == "Lean Control") %>% filter(procedure == "bold_mri")
croc_hc_keep <- croc_hc %>% select(record_id, visit, procedure, seq.6544.33, group, sex, age)
# now get kit IDs from biopsy
croc_biopsy <- croc %>% filter(study == "CROCODILE") %>% filter(group == "Lean Control") %>% filter(!is.na(kit_id)) %>% filter(procedure == "kidney_biopsy")
croc_biopsy_keep <- croc_biopsy %>% select(record_id, kit_id)
croc_hc_keep <- full_join(croc_hc_keep, croc_biopsy_keep, by = "record_id")
croc_hc_keep <- croc_hc_keep %>% filter(!is.na(seq.6544.33)) %>% filter(!is.na(kit_id))

# match based on sex and age - total of 5 samples each
df_selected <- df_keep %>% dplyr::arrange(desc(seq.6544.33)) %>% slice_head(n = 5)
# combine the two dfs
for_match <- rbind(croc_hc_keep, df_selected)
for_match$sexnum <- ifelse(for_match$sex == "Female", 1, 2)
for_match$Tr <- ifelse(for_match$group == "Type 2 Diabetes", 1, 0)

# now just need to match HCs from CROC by sex and age
# not sure if NELL1 should be taken into account or not - query pending to Petter
res <- matchit(Tr ~ sex + age, method = "nearest", data = for_match, exact = ~ sex)
res
summary(res, un = TRUE)
output <- match.data(res)
output <- output %>% arrange(subclass)
write.csv(output, "/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Weining Lu/T2D_HC_matches.csv",
          row.names = F)

res <- read.csv("/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Weining Lu/T2D_HC_matches.csv")
#res$seq.6544.33 <- exp(res$seq.6544.33)
t1 <- CreateTableOne(data = res, vars = c("age", "sex", "seq.6544.33"), strata = "group")
t1 <- print(t1)
```

