---
title: "YQOL Survey Scoring (R)"
author: "Casey Sakamoto"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(arsenal)
library(readxl)
library(tidyverse)
library(performance)
library(knitr)
library(lubridate)
library(stringr)
knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "S://PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Melanie Green"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Melanie Green"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Melanie Green"
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r data import}
# long form data :) , id, visit, 16 questions for scoring
teal_yqol = read_excel("S:/Laura/Peds Endo/Melanie Green/Quality of Life/TEAL_Youth Quality of Life Data.xlsx")
```

```{r scoring}
# t score of these questions : (Raw score - min possible score)/(possible Q Range) * 100
# All questions on the TEAL QOL are low 0 and high 10, with no reverse coding needed
# so the formula can be reduced to: t = (Q - 0)/10 *100 = Q*10
# sum the scores and take the average for final score qol_total = avg((q1:q16)*10)
teal_yqol = teal_yqol %>% mutate(tot_sum = select(., `Question 1 (R07)`:`Question 16 (R38)`) %>% rowSums()*10) # total raw =  (sum(tQ1:tQ16))
teal_yqol = teal_yqol %>% mutate(tot_qol = tot_sum/16, .keep="unused") # total qol = (total raw/16)
```

```{r score output csv}
write.csv(teal_yqol, "S:/Laura/Peds Endo/Melanie Green/Quality of Life/TEAL_YQOL_Scored.csv")
```