---
title: "EarlyGlargine_analysis"
author: "Casey Sakamoto"
date: "2/11/2022"
output: pdf_document
---

```{r setup, include=FALSE}
library(arsenal)
library(readxl)
library(readr)
library(Hmisc)
library(tidyverse)
library(performance)
library(knitr)
library(lubridate)
library(stringr)
library(table1)
knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "S:/Laura/Peds Endo/Ohman/Early glargine prospective"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Ohman/Early glargine prospective"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Ohman/Early glargine prospective"
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r table1 comments, include=FALSE}
# TABLE
# 
# For this we will compare the Control group (Late glargine) vs the Intervention (Early glargine) group 
#  
# 1.	Patient Characteristics table
# a.	Sex (nih_sex, column Q)
# b.	Age range (age_at_consent, column P)
# c.	Race/ethnicity (nih_race and nih_ethnicity; columns R and S) 
# d.	New onset vs Established T1DM (diabetes_diagnosis; column AY) 
#                                                                i.      For established T1DM:
# 1.       Duration of T1D (column AZ)
# 2.       Home regimen (columns BA-BE)
# e.	HbA1c (column CQ)
#                                                                i.      Early vs Late groups
#                                                              ii.      New onset vs Established 
# f.	or first pH; column CD
#                                                                i.      Early vs Late groups
#                                                              ii.      New onset vs Established 
# g.	or first bicarb; column CH
#                                                                i.      Early vs Late groups
#                                                              ii.      New onset vs Established 
# h.	Glargine dose/kg (column AS)
#                                                                i.      Early vs Late groups
#                                                              ii.      New onset vs Established 
#                                                              
#                                                              
# Per Laura, It seems like the simplest approach to this is making several tables, one separating by trt and the other by diabetes diag
```

```{r Patient Characteristics}
# table 1
#  cont.rmstat = list(c("mediqr"))
EG_demog_table1 =  table1( ~ nih_sex + age_at_consent + nih_race + nih_ethnicity + diabetes_diagnosis + hba1c + ph + bicarbonate + glargine_dose_per_kg
                        | study_group, data = EG_patient_char, topclass="Rtable1-zebra",
                         render.continuous=c( "Median [IQR]"="Median [Q1, Q3]"))

T1D_lab_table1 =  table1( ~ `duration_of_t1d (years)` + home_regimen + hba1c + ph + bicarbonate + glargine_dose_per_kg 
                       | diabetes_diagnosis, data = EG_patient_char, topclass="Rtable1-zebra",
                        render.continuous=c( "Median [IQR]"="Median [Q1, Q3]"))


EG_demog_table1 # between study groups, most variables look very similar; hba1c, bicarbonate may be a bit different
T1D_lab_table1 # between t1d status, hba1c, bicarbonate, glargine dose may be a bit different
```

Primary outcome is: Rate of rebound IV within 12 hours of IV insulin discontinuation (based on glucometer; column CN). IV insulin stop time = column AN. 
a.	Early vs Late groups 
b.	Total % >180 mg/dL 
c.	And using BG cutoffs of 180-250 mg/dL, 250-300, or >300


glucometer variable: glucometer
iv insulin stop time variable: iv_insulin_stop

did they have glucose > 180 for 12 hr within iv stop?
```{r Primary Outcome}
# need to derive the outcome variable: first filter out values that are before iv stop, or after 12 hr post stop
EG_primary_outcome = EG_primary_outcome %>% filter(timediff > 0 & timediff < 12)

# look at glucometer values within the 12hr window (note: a few 180's so i opted for 180 as the cutoff rather than 179)
EG_primary_outcome = EG_primary_outcome %>% mutate(hg_12hr = case_when(glucometer >=  180 ~ 1,
                                                                             TRUE ~ 0))
# hyperglycemia: did they have glucose > 180 ANY time within 12 hr of iv stop
EG_primary_outcome = EG_primary_outcome %>% group_by(`Patient ID`) %>% mutate(hyperglycemia = max(hg_12hr))

# check proportion of those who got Hyperglycemia
EG_prop = EG_primary_outcome %>% group_by(`Patient ID`) %>% summarise("hyperglycemia" = max(hyperglycemia))
mean(EG_prop$hyperglycemia) #.76 got hg
```

