---
title: "Estimates for power calculation"
author: "Laura Pyle"
date: "2023-11-26"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tableone)
library(knitr)

knitr::opts_chunk$set(echo = TRUE)

data <- read.csv("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Simon sleep/R01 application fall 2023/TEAL data for power calculations clean.csv")
data[,3:ncol(data)] <- apply(data[,3:ncol(data)], 2, as.numeric)

# calculate change
data$delta_matsuda <- data$Final.Matsuda -  data$Baseline.Matsuda
data$delta_HOMA <- data$Final.HOMA - data$Baseline.HOMA
data$delta_LFF <- data$Final.LFF - data$Baseline.LFF
data$delta_FAI <- data$Final.FAI - data$Baseline.FAI
data$delta_free_T <- data$Final.free.T - data$Baseline.free.T

# for this, keep only diet participants
diet <- data %>% filter(Study.Group..GLP.1.or.Diet. == "Diet")
```

```{r, include=FALSE}
t1 <- CreateTableOne(data=data, vars=c("delta_matsuda", "delta_HOMA", "delta_LFF", "delta_FAI", "delta_free_T"))
t1 <- print(t1)
```

```{r, include=TRUE}
kable(t1)
```
