---
title: "WatchPAT vs. PSG Deming Regression"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(knitr)
library(mcr)
library(dplyr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Melanie Green/Watchpat/Data raw"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r data, include=FALSE}
data <- read.csv("./PSG x WatchPAT 11.9.22.csv")
data <- data %>% filter(!is.na(PSG...AHI))

dem.reg <- mcreg(x=data$WatchPAT...AHI,y=data$PSG...AHI, method.reg = "Deming")
```

Deming regression was performed with PSG AHI as the independent variable and WatchPAT AHI as the dependent variable. Therefore, the following equation can be used to estimate the WatchPAT AHI based on a PSG AHI value:

$$PSG_{AHI} = \beta_0 + \beta_1 * WatchPAT_{AHI}$$

where $\beta_0$ is the intercept from the Deming regression and $\beta_1$ is the slope from the Deming regression.

```{r echo=FALSE, comment=""}
kable(summary(dem.reg))
```

