---
title: "CALICO Exploratory Data Analysis"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    fig-width: 12
    fig-height: 9
    page-layout: full
    theme:
      light: flatly
      dark: darkly
bibliography: /home/tim/Documents/Miscellaneous/zotero.bib
csl: /home/tim/GitHub/styles/american-medical-association.csl
editor: source
---

```{r setup}
#| include: false
library(redcapAPI)
library(dplyr)
library(tidyr)
library(childsds)
library(gtsummary)
library(ggplot2)
```

```{r data import}
#| include: false
# Import from REDCap
unlockREDCap(c(rcon = "CALICO"),
  keyring = "API_KEYs",
  envir = 1,
  url = "https://redcap.ucdenver.edu/api/"
)
demo <- exportReportsTyped(rcon,
  report_id = 126039, validation = skip_validation
)
aim1 <- exportReportsTyped(rcon,
  report_id = 125363, validation = skip_validation
)
```

```{r data cleaning}
#| message: false
#| warning: false
# Format race columns
races <- c(
  "Caucasian", "African American", "Asian", "Pacific Islander",
  "American Indian or Alaska Native", "Other", "Unknown"
)
demo$Race <- apply(demo[, grep("race", colnames(demo))], 1, function(r) {
  w <- which(r == "Checked")
  if (length(w) == 0) {
    return("Unknown")
  } else if (length(w) > 1) {
    "More than one"
  } else {
    return(races[w])
  }
})
demo$Race <- factor(demo$Race,
  levels = c(
    "African American", "American Indian or Alaska Native", "Asian",
    "Caucasian", "More than one", "Other", "Pacific Islander", "Unknown"
  ),
  labels = c(
    "African American", "American Indian or Alaska Native", "Asian",
    "Caucasian", "More than one/Other/Unknown", "More than one/Other/Unknown",
    "More than one/Other/Unknown", "More than one/Other/Unknown"
  )
)
# Select demographics columns
demo <- demo %>% select(
  record_number, site, Race, ethnicity, insur_type, pcosdx_irregular_menses,
  pcosdx_age, pcosdx_anxietydx_age
)
# First clinic visit only
aim1 <- aim1 %>%
  group_by(record_number) %>%
  slice_min(redcap_repeat_instance) %>%
  select(-redcap_repeat_instrument, -redcap_repeat_instance) %>%
  ungroup()
# Combine
aim1 <- left_join(aim1, demo) %>%
  select(record_number, site:pcosdx_anxietydx_age, everything())
# Variable formatting
aim1$cv_a1c <- as.numeric(aim1$cv_a1c)
# BMI categories

# Drop empty levels
aim1 = droplevels(aim1)
```

# Demographics

```{r}
#| label: tbl-table-1
#| tbl-cap: Participant demographics
demo %>%
  select(-record_number) %>%
  tbl_summary(missing_text = "(Missing)")
```

# Aim 1 comparisons

## By race

```{r}
#| label: tbl-table-1-race
#| tbl-cap: Stratified by race
aim1 %>%
  select(-record_number) %>%
  tbl_summary(by = Race, missing_text = "(Missing)") %>%
  add_overall() %>%
  add_p(test.args = all_tests("fisher.test") ~ list(simulate.p.value = T)) %>%
  separate_p_footnotes()
```

## By ethnicity

```{r}
#| label: tbl-table-1-ethnicity
#| tbl-cap: Stratified by ethnicity
aim1 %>%
  select(-record_number) %>%
  tbl_summary(by = ethnicity, missing_text = "(Missing)") %>%
  add_overall() %>%
  add_p(test.args = all_tests("fisher.test") ~ list(simulate.p.value = T)) %>%
  separate_p_footnotes()
```

# Data questions

1. How do we want to combine the race groups?
  - Currently, "Other", "Pacific Islander", and "Unknown" are grouped with those who checked more than one box.
