---
title: "CALICO Exploratory Data Analysis"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
    theme:
      light: flatly
      dark: darkly
bibliography: /home/tim/Documents/Miscellaneous/zotero.bib
csl: /home/tim/GitHub/styles/american-medical-association.csl
editor: source
---

```{r setup}
#| include: false
library(tidyverse)
library(Hmisc)
library(DataExplorer)
library(gtsummary)
```

```{r data cleaning}
#| message: false
# For some reason the API export doesn't look correct for this study, so we're
# using reports for now
source("/home/tim/GitHub/CHCO-Code/Melanie Green/CALICO/CALICO_demographics.r")
demo <- data
source("/home/tim/GitHub/CHCO-Code/Melanie Green/CALICO/CALICO_aim1.r")
# Limit to clinic visits only
data <- data %>% filter(!is.na(redcap_repeat_instrument))
# Remove those with asterisk in ID
demo <- demo[-grep("\\*", demo$record_number), ]
data <- data[-grep("\\*", data$record_number), ]
# First visit only
data <- data %>%
  group_by(record_number) %>%
  filter(row_number() == 1)
demo = demo %>% filter(record_number %in% data$record_number)
```

# Demographics

```{r}
demo %>%
  select(
    site.factor:pcosdx_irregular_menses.factor, pcosdx_age, pcosdx_anxietydx_age
  ) %>%
  tbl_summary(missing_text = "(Missing)")
```


# Data cleaning

- Participants with an asterisk in their study ID were excluded.

```{r}
#| eval: true
#| message: false
create_report(data,
  quiet = T,
  output_file = "OneDrive/Vigers/BDC/Janet Snell-Bergeon/CALICO/Reports/aim1_eda.html",
  config = configure_report(
    plot_correlation_args = list(
      "cor_args" = list(use = "pairwise.complete.obs"),
      "theme_config" = list(
        legend.position = "bottom",
        axis.text.x = element_text(angle = 90)
      )
    )
  )
)
```
