---
title: "Guideline Utilization in CALICO"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    fig-width: 12
    fig-height: 9
    page-layout: full
    theme:
      light: flatly
      dark: darkly
bibliography: /home/timvigers/Documents/Miscellaneous/zotero.bib
csl: /home/timvigers/Documents/GitHub/styles/american-medical-association.csl
editor: source
execute:
  warning: false
---

```{r setup}
#| include: false
library(tidyverse)
library(gtsummary)
knitr::opts_knit$set(root.dir = "/home/timvigers/OneDrive/Vigers/BDC/Janet Snell-Bergeon/CALICO")
```

```{r data import}
#| include: false
# Load data
load("./Data_Clean/analysis_data.RData")
# Lists of variables
diagnostic_cat <- c(
  "labs_this_visit___4", "labs_this_visit___5", "labs_this_visit___10",
  "labs_this_visit___11", "labs_this_visit___12", "labs_this_visit___33"
)
diagnostic_cont <- c("cv_17ohp", "cv_ft", "cv_tt", "cv_tsh")
demo_vars <- c(demo_vars, "pcosdx_specialty")
# Make 1 year dataset
one_year <- df %>%
  group_by(record_number) %>%
  filter(cv_monthssincepcosdx <= 12) %>%
  summarise(
    across(all_of(demo_vars), ~ first(.x, na_rm = F)),
    across(all_of(diagnostic_cat), ~ any(.x == "Checked")),
    across(all_of(diagnostic_cont), ~ any(!is.na(.x)))
  )
# Set table options
mycontrols <-
  tableby.control(numeric.stats = c("Nmiss2", "meansd", "medianq1q3", "range"))
```

# Within 1 year of diagnosis

## Data cleaning

For the following analysis, we filtered the dataset to visits where `cv_monthssincepcosdx <= 12`. Then, we grouped the data by participant ID and checked whether any of the labs were performed at any visit (for checkbox variables we looked for any visit marked "Checked" and for continuous variables we looked for any non-missing values). Participants who had the test performed were marked "TRUE" and others marked "FALSE."

7 participants were missing the `pcosdx_specialty` field.

## Overall

```{r}
one_year %>%
  select(-record_number, -site) %>%
  tbl_summary(by = pcosdx_specialty,label = labels(df)) %>%
  add_p(test.args = all_tests("fisher.test") ~ list(simulate.p.value = TRUE)) %>%
  separate_p_footnotes() %>%
  modify_footnote(everything() ~ NA)
```
