---
title: "CALICO Health Disparities Analyses"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    fig-width: 12
    fig-height: 9
    page-layout: full
    theme:
      light: flatly
      dark: darkly
editor: source
---

```{r setup}
#| include: false
library(Hmisc)
library(tidyverse)
library(arsenal)
library(gtsummary)
library(performance)
library(ggstats)
home_dir <- switch(Sys.info()["sysname"],
  "Darwin" = "/Users/timvigers/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Vigers/BDC/Janet Snell-Bergeon/CALICO",
  "Linux" = "/home/timvigers/OneDrive/Vigers/BDC/Janet Snell-Bergeon/CALICO"
)
knitr::opts_knit$set(root.dir = home_dir)
```

```{r data import and cleaning}
#| include: false
# Load data
load("./Data_Clean/analysis_data.RData")
# Select columns, remove "Other" and "Military" insurance,
# combine races
df$combined_race[df$combined_race == "Pacific Islander"] <- "Other"
df$combined_race[df$combined_race == "American Indian or Alaska Native"] <-
  "Other"
df$combined_race <- droplevels(df$combined_race)
df$combined_race <- relevel(df$combined_race, ref = "Caucasian")
df$insur_type <- factor(df$insur_type,
  levels = c(
    "Public", "Private", "Military", "None", "Other {insur_other}"
  ),
  labels = c(
    "Public/None/Military/Other", "Private", "Public/None/Military/Other",
    "Public/None/Military/Other", "Public/None/Military/Other"
  )
)
df$insur_type <- relevel(df$insur_type, ref = "Private")
# Labels
label(df$insur_type) <- "Insurance Type"
label(df$combined_race) <- "Race"
```

# Medications by months since diagnosis

```{r}
metformin <- expand.grid(
  id = unique(df$record_number),
  cv_monthssincepcosdx = 0:max(round(df$cv_monthssincepcosdx), na.rm = T),
  stringsAsFactors = F
)
metformin <- left_join(
  metformin,
  df %>%
    mutate(
      id = as.character(record_number),
      cv_monthssincepcosdx = as.numeric(round(cv_monthssincepcosdx))
    ) %>%
    select(id, cv_monthssincepcosdx, cv_medications___1)
) %>% arrange(id)
```
