---
title: "Therapeutic alliance"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=F}
# required libraries
library(knitr)
library(haven)
library(tableone)
library(nlme)
library(lme4)
library(emmeans)
library(lavaan)
library(plyr)
library(arsenal)
library(Hmisc)
```

```{r, include=F}
data <- read_sav("E:\\Lauren Shomaker\\Psychotherapy alliance MS\\Data\\Shomaker Truncated-v4.21.20.sav")
data <- arrange(data,coh,group,ther)
data$newcoh <- NA

# fix cohort numbers - have same number used with group 0 as group 1
data[data$coh==2,]$newcoh <- ifelse(data[data$coh==2,]$group==1,21,22)
data[data$coh==3,]$newcoh <- ifelse(data[data$coh==3,]$group==1,31,32)
data[data$coh==4,]$newcoh <- ifelse(data[data$coh==4,]$group==1,41,42)
data[data$coh==5,]$newcoh <- ifelse(data[data$coh==5,]$group==1,51,52)
data[data$coh==6,]$newcoh <- ifelse(data[data$coh==6,]$group==1,61,62)
data[data$coh==7,]$newcoh <- ifelse(data[data$coh==7,]$group==1,71,72)
data[data$coh==8,]$newcoh <- ifelse(data[data$coh==8,]$group==1,81,82)
data[data$coh==9,]$newcoh <- ifelse(data[data$coh==9,]$group==1,91,92)
data[data$coh==10,]$newcoh <- ifelse(data[data$coh==10,]$group==1,101,102)
data[data$coh==11,]$newcoh <- ifelse(data[data$coh==11,]$group==1,111,112)
data[data$coh==12,]$newcoh <- ifelse(data[data$coh==12,]$group==1,121,122)

# read in corrected LOC data
loc <- read_sav("E:\\Lauren Shomaker\\Psychotherapy alliance MS\\Data\\Shomaker Truncated-v8.26.20.sav")
comparedf(data,loc)
keep_loc <- loc[,c("id","locm1bpresence","locm112wpresence","locm112mpresence","locm136mpresence","locm1b1","locm112w","locm112m","locm136m")]
data <- arrange(data,id)
keep_loc <- arrange(keep_loc,id)
loc$keep_loc <- NULL
data <- cbind(data,keep_loc)

# calculate new LOC variables 
data$locp1y <- data$locm112m - data$locm1b1
data$locp3y <- data$locm136m - data$locm1b1

# export data for Mplus
#write.csv(data,"H:\\Endocrinology\\Shomaker\\Psychotherapy alliance MS\\Data\\export for mplus.csv",
#          col.names = F,row.names=F,na="*")
write.table(data, file = "E:\\Lauren Shomaker\\Psychotherapy alliance MS\\Data\\export for mplus.csv", col.names = FALSE, row.names = FALSE, sep = ",",na="*")

# export data for SAS for plotting
write.csv(data, "E:\\Lauren Shomaker\\Psychotherapy alliance MS\\Data\\export for SAS.csv",na="")

# looking at correlations between change scores

# ++++++++++++++++++++++++++++
# flattenCorrMatrix
# ++++++++++++++++++++++++++++
# cormat : matrix of the correlation coefficients
# pmat : matrix of the correlation p-values
flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}
yes <- c("BO16","BOTX16","BO112","BOTX112","TA16","TATX16","TA112","TATX112","bmip1y","bmip3y","bmizp1y","bmizp3y",
         "locp1y","locp3y","bdip1y","bdip3y","anxp1y","anxp3y","staxp1y","staxp3y","socp1y","socp3y","sasp1y","sasp3y")
corrout <- rcorr(as.matrix(data[,yes]), type = "spearman")
corrout <- flattenCorrMatrix(corrout$r, corrout$P)
corrout$cor <- round(corrout$cor,4)
corrout$p <- round(corrout$p,4)

```

```{r, echo=FALSE}
kable(corrout, caption="Correlations between change scores")
```
<br>


