---
title: "CAMP study analysis"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

library(tableone)
library(knitr)
library(dplyr)
library(arsenal)

home_dir = ifelse(.Platform$OS.type != "unix","E:\\Lauren Shomaker\\CAMP",
                  "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects")
knitr::opts_knit$set(root.dir = home_dir)
```


```{r data, include=FALSE}
data <- read.csv("E:\\Lauren Shomaker\\CAMP\\export.csv")

# factors
data$mini_meetscriteria___1.38 <- as.factor(data$mini_meetscriteria___1.38)
data$mini_meetscriteria___2.38 <- as.factor(data$mini_meetscriteria___2.38)
data$race_corr_table <- as.factor(data$race_corr_table)
data$race_ethnicity <- as.factor(data$race_ethnicity)
data$ede3monthsloc.38 <- as.factor(data$ede3monthsloc.38)
data$edeLOCpresence.0 <- as.factor(data$edeLOCpresence.0)

# calculate change in weight, BMI Z-score, and BMI percentile from SV to EoTx
data$delta_bmi <- data$bmi_kgm2.38 - data$firsttri_bmi_kgm2.0
data$delta_bmiz <- data$zscore.38 - data$firsttri_bmi_zscore.0
data$delta_bmip <- data$bmi_percentile.38 - data$firsttri_percentile.0

# change in social functioning
data$delta_sastot <- data$sastot.38-data$sastot.0
data$delta_fatherfigure_negtot <- data$nri_ff_negtot.38-data$nri_ff_negtot.0
data$delta_fatherfigure_suptot <- data$nri_ff_suptot.38-data$nri_ff_suptot.0
data$delta_motherfigure_negtot <- data$nri_mf_negtot.38-data$nri_mf_negtot.0
data$delta_motherfigure_suptot <- data$nri_mf_suptot.38-data$nri_mf_suptot.0
data$delta_romanticfigure_negtot <- data$nri_rf_negtot.38-data$nri_rf_negtot.0
data$delta_romanticfigure_suptot <- data$nri_rf_suptot.38-data$nri_rf_suptot.0
data$delta_samesex_negtot <- data$nri_ssf_negtot.38-data$nri_ssf_negtot.0
data$delta_samesex_suptot <- data$nri_ssf_suptot.38-data$nri_ssf_suptot.0

# change in perceived stress
data$delta_psstot <- data$pss10_total.38-data$pss10_total.0

# change in depression
data$delta_cesdtot <- data$cesdtot.38-data$cesdtot.0
data$delta_edinburghtot <- data$edinburgh_total.38 - data$edinburgh_total.0

# change in overeating
data$delta_eestot <- data$ees_tot.38-data$ees_tot.0

# change in physical activity
data$delta_light <- data$actigraph_light.38-data$actigraph_light.0
data$delta_sedentary <- data$actigraph_sedentary.38-data$actigraph_sedentary.0
data$delta_mvpa <- data$average_mvpa_per_day.38-data$average_mvpa_per_day.0
# for those who don't have sufficient valid days at either baseline or follow-up, set delta to missing
data$delta_light <- ifelse(data$actigraph_valid_days.0==1 & data$actigraph_valid_days.38==1, data$delta_light, NA)
data$delta_sedentary <- ifelse(data$actigraph_valid_days.0==1 & data$actigraph_valid_days.38==1, data$delta_sedentary, NA)
data$delta_mvpa <- ifelse(data$actigraph_valid_days.0==1 & data$actigraph_valid_days.38==1, data$delta_mvpa, NA)

# change in sleep
data$delta_totalsleep <- data$total_sleep_time.38-data$total_sleep_time.0
data$delta_waso <- data$wake_after_sleep_onset.38-data$wake_after_sleep_onset.0
data$delta_sleepeff <- data$sleep_efficiency.38-data$sleep_efficiency.0
```

```{r, include=FALSE}

# table of acceptability
acc_vars <- c("SessionAtt","participate_again","enjoy_participating","recommend_study","end_interest")
t1 <- CreateTableOne(data=data,vars = acc_vars,strata = "group_condition")
t1 <- print(t1)

# table of gestational weight gain
wt_vars <- c("delta_bmi","delta_bmiz","delta_bmip")
t2 <- CreateTableOne(data=data,vars = wt_vars,strata = "group_condition")
t2 <- print(t2)

# table of social functioning
ss_vars <- c("delta_sastot","delta_fatherfigure_negtot","delta_fatherfigure_suptot","delta_motherfigure_negtot","delta_motherfigure_suptot",
             "delta_romanticfigure_negtot","delta_romanticfigure_suptot","delta_samesex_negtot","delta_samesex_suptot")
t3 <- CreateTableOne(data=data,vars = ss_vars,strata = "group_condition")
t3 <- print(t3)

# table of perceived stress
t4 <- CreateTableOne(data=data,vars = "delta_psstot",strata = "group_condition")
t4 <- print(t4)

# table of depressive symptoms
dep_vars <- c("delta_cesdtot","delta_edinburghtot","mini_meetscriteria___1.38","mini_meetscriteria___2.38")
t5 <- CreateTableOne(data=data,vars = dep_vars,strata = "group_condition")
t5 <- print(t5)

# table of overeating
overeat_vars <- c("delta_eestot","edeLOCpresence.0","ede3monthsloc.38")
t6 <- CreateTableOne(data=data,vars = overeat_vars,strata = "group_condition")
t6 <- print(t6)

# table of PA
pa_vars <- c("delta_light","delta_sedentary","delta_mvpa")
t7 <- CreateTableOne(data=data,vars = pa_vars,strata = "group_condition")
t7 <- print(t7)

# table of sleep
sleep_vars <- c("delta_totalsleep","delta_waso","delta_sleepeff")
t8 <- CreateTableOne(data=data,vars = sleep_vars,strata = "group_condition")
t8 <- print(t8)

```

# Background

# Methods

# Results

## Descriptive statistics

```{r echo=FALSE, include=FALSE}
# table of sleep
desc_vars <- c("age.0","gestational weeks_fractional.0","race_corr_table","race_ethnicity","prepreght_cm.0","prepregwt_kg.0",
               "prepreg_bmi_percentile","prepreg_weightstatus.0","prepreght_cm.0","prepregwt_kg.0","prepreg_bmi_percentile.0",
               "prepreg_weightstatus.0","measuredht_cm.0","measuredwt_kg.0","firsttri_bmi_kgm2.0","firsttri_bmi_zscore.0",
               "firsttri_percentile.0","weightstatus.0")
desc_table <- CreateTableOne(data=data,vars = desc_vars,strata = "group_condition")
desc_table <- print(desc_table)
```

```{r echo=FALSE}
kable(desc_table)
```

## Unadjusted comparisons

### Acceptability

```{r, include=FALSE}
t1 <- tableby(data=data, group_condition ~ SessionAtt+participate_again+enjoy_participating+recommend_study+end_interest,
                     numeric.test="kwt",numeric.stats=c("Nmiss2","median","q1q3"))
```

```{r echo=FALSE, include=TRUE, results='asis'}
summary(t1)
```

### Gestational weight gain

```{r, include=FALSE}
t2 <- tableby(data=data, group_condition ~ delta_bmi+delta_bmiz+delta_bmip,
                     numeric.test="kwt",numeric.stats=c("Nmiss2","median","q1q3"))
```

```{r echo=FALSE, include=TRUE, results='asis'}
summary(t2)
```

### Social functioning

```{r, include=FALSE}
t3 <- tableby(data=data, group_condition ~ delta_sastot+delta_fatherfigure_negtot+delta_fatherfigure_suptot+delta_motherfigure_negtot+delta_motherfigure_suptot+           delta_romanticfigure_negtot+delta_romanticfigure_suptot+delta_samesex_negtot+delta_samesex_suptot,
                     numeric.test="kwt",numeric.stats=c("Nmiss2","median","q1q3"))
```

```{r echo=FALSE, include=TRUE, results='asis'}
summary(t3)
```

### Perceived stress

```{r, include=FALSE}
t4 <- tableby(data=data, group_condition ~ delta_psstot,
                     numeric.test="kwt",numeric.stats=c("Nmiss2","median","q1q3"))
```

```{r echo=FALSE, include=TRUE, results='asis'}
summary(t4)
```

### Depression

```{r, include=FALSE}
t5 <- tableby(data=data, group_condition ~ delta_cesdtot+delta_edinburghtot+mini_meetscriteria___1.38+mini_meetscriteria___2.38,
                     numeric.test="kwt",numeric.stats=c("Nmiss2","median","q1q3"))
```

```{r t5=FALSE, include=TRUE, results='asis'}
summary(t5)
```

### Overeating

```{r, include=FALSE}
t6 <- tableby(data=data, group_condition ~ delta_eestot+edeLOCpresence.0+ede3monthsloc.38,
                     numeric.test="kwt",numeric.stats=c("Nmiss2","median","q1q3"))
```

```{r t5=FALSE, include=TRUE, results='asis'}
summary(t6)
```

### Physical activity

```{r, include=FALSE}
t7 <- tableby(data=data, group_condition ~ delta_light+delta_sedentary+delta_mvpa,
                     numeric.test="kwt",numeric.stats=c("Nmiss2","median","q1q3"))
```

```{r t5=FALSE, include=TRUE, results='asis'}
summary(t7)
```

### Sleep

```{r, include=FALSE}
t8 <- tableby(data=data, group_condition ~ delta_totalsleep+delta_waso+delta_sleepeff,
                     numeric.test="kwt",numeric.stats=c("Nmiss2","median","q1q3"))
```

```{r t5=FALSE, include=TRUE, results='asis'}
summary(t8)
```

