---
title: "UWMDI Biostatistics and Bioinformatics Needs Assessment"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

library(knitr)
library(arsenal)
library(dplyr)
library(tidyr)

data <- read.csv('/Users/pylell/Library/CloudStorage/OneDrive-SharedLibraries-UW/Admin/Needs assessment/UWMDIBiostatisticsAn_DATA_LABELS_2025-01-16_0855.csv')


```

# Response summary

```{r, include=FALSE}
t1 <- tableby( ~ `What.is.your.primary.role.` + `Years.of.research.experience.` +
                 `Which.statistical.software.do.you.currently.use..if.any...Select.all.that.apply...choice.R.` + 
                 `Which.statistical.software.do.you.currently.use..if.any...Select.all.that.apply...choice.SAS.` + 
                 `Which.statistical.software.do.you.currently.use..if.any...Select.all.that.apply...choice.SPSS.` +
                 `Which.statistical.software.do.you.currently.use..if.any...Select.all.that.apply...choice.Stata.` +
                 `Which.statistical.software.do.you.currently.use..if.any...Select.all.that.apply...choice.Python.` +
                 `Which.statistical.software.do.you.currently.use..if.any...Select.all.that.apply...choice.MATLAB.` +
                 `Which.statistical.software.do.you.currently.use..if.any...Select.all.that.apply...choice.Other.` +
                 `If.you.selected.other..please.specify..1` + 
                 R + SAS + SPSS + Stata + Python + MATLAB + `If.you.selected.other..please.rate.your.proficiency.` +
                 `How.frequently.do.you.require.statistical.support.` +
                 `How.frequently.do.you.require.statistical.support.` +
                 `What.types.of.support.do.you.need...Select.all.that.apply...choice.Study.design.` +
                 `What.types.of.support.do.you.need...Select.all.that.apply...choice.Data.analysis.guidance.statistical.method.selection.` +
                 `What.types.of.support.do.you.need...Select.all.that.apply...choice.Data.analysis.` +
                 `What.types.of.support.do.you.need...Select.all.that.apply...choice.Manuscript.statistical.review.` +
                 `What.types.of.support.do.you.need...Select.all.that.apply...choice.Software.training.` + 
                 `What.types.of.support.do.you.need...Select.all.that.apply...choice.Advanced.statistical.technique.support.` +
                 `What.types.of.support.do.you.need...Select.all.that.apply...choice.Power.calculations.grant.writing.` +
                 `What.types.of.support.do.you.need...Select.all.that.apply...choice.Bioinformatics.omics.data.analysis.` +
                 `Please.provide.additional.detail.if.needed.` +
                 `What.are.your.primary.statistical.analysis.challenges.` + 
                 `Do.you.have.funding.for.statistical.collaboration.` +
                 `If.yes..please.specify.` +
                 `Please.list.any.training.topics.you.would.find.valuable.` +
                 `Preferred.training.format...select.all.that.apply...choice.In.person.workshops.` +
                 `Preferred.training.format...select.all.that.apply...choice.Webinars.` +
                 `Preferred.training.format...select.all.that.apply...choice.One.on.one.consultations.` +
                 `Preferred.training.format...select.all.that.apply...choice.Hands.on.computer.labs.` +
                 `Preferred.training.format...select.all.that.apply...choice.Other.` +
                 `If.you.selected.other..please.specify..2` +
                 `What.additional.computational.resources.would.benefit.your.research...choice.High.performance.computing.cluster.` +
                 `What.additional.computational.resources.would.benefit.your.research...choice.Cloud.computing.resources.` +
                 `What.additional.computational.resources.would.benefit.your.research...choice.Advanced.statistical.software.licenses.` +
                 `What.additional.computational.resources.would.benefit.your.research...choice.Additional.computational.hardware.` +
                 `What.additional.computational.resources.would.benefit.your.research...choice.Other.` +
                 `If.you.selected.other..please.specify..3` +
                 `Are.there.specific.emerging.statistical.methods.or.techniques.critical.to.your.research.that.are.not.currently.supported.` +
                 `Please.provide.any.additional.feedback.or.suggestions.` +
                 `Name.` + `Please.check.here.if.you.would.like.us.to.reach.out.to.you.to.schedule.a.meeting.initial.consultation...choice.Yes.`, 
                 data = data)

```

```{r, include=TRUE, results='asis'}
summary(t1)
```