---
title: "TODAY proteomics and metabolomics integration"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)
library(survival)
library(broom)
library(emmeans)
library(ggvenn)
library(mixOmics)
library(data.table)
library(MOFA2)
library(readxl)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward"
}
knitr::opts_knit$set(root.dir = home_dir)

set.seed(3654)
source("~/Documents/Github/CHCO-Code/Petter Bjornstad/TODAY proteomics metabolomics/Proteomics analyses/easy_elasticnet.R")
```

```{r, include=FALSE}
setwd(home_dir)
# load somalogic data, with QC samples already excluded
load("./Somalogic data raw/soma.Rdata")

# load analyte info
load("./Somalogic data raw/analytes.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# load baseline risk factors
load("./Clinical data/TODAY/baserisk.Rdata")

# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% dplyr::group_by(releaseid) %>% dplyr::filter(row_number()==1)
# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# the above section of code used to work but seems to have broken....this should accomplish the same thing?
#base <- soma %>% filter(visit==1)

# merge in complication data
base <- left_join(base, comorb, by="releaseid")
# this was previously:
# base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# merge in baseline risk factors
base <- left_join(base, baserisk, by="releaseid")
# this was previously:
#base <- merge(base, baserisk, by="releaseid",all.x=T, all.y=F)

# log transform UAlbCreat
base$log_UAlbCreat <- log(base$UAlbCreat + 0.0000001)

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# are there proteins with low variability?
no_var = caret::nearZeroVar(base[,seq])
# none

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)

# scale by SD
base_log_scale <- base_log
predictors <- colnames(base_log[seq])
for (i in 1:length(predictors)) {
  base_log_scale[,paste0(predictors[i])] <- base_log_scale[,paste0(predictors[i])]/sd(unlist(base_log[,paste0(predictors[i])]))
}

# filter to top 100 proteins by effect size
# first, will try without doing any filtering on metabolites
f = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/Results/Linear and Cox models/TODAY somalogic Cox models scaled baseline adjusted.xlsx"
# MIC.OR.MIC
mic.or.mac_keep = read_excel(f,sheet = "MIC.OR.MAC CPH")
mic.or.mac_keep <- arrange(mic.or.mac_keep,adj.p.value)
mic.or.mac_drop <- mic.or.mac_keep[101:nrow(mic.or.mac_keep),"AptName"]
rownames(mic.or.mac_drop) <- mic.or.mac_drop$AptName
mic.or.mac_drop <- as.data.frame(t(mic.or.mac_drop))
mic.or.mac <- base_log_scale %>% dplyr::select(-colnames(mic.or.mac_drop))
# GLYCEMIA
glyc_keep = read_excel(f,sheet = "GLYC CPH")
glyc_keep <- arrange(glyc_keep,adj.p.value)
glyc_drop <- glyc_keep[101:nrow(glyc_keep),"AptName"]
rownames(glyc_drop) <- glyc_drop$AptName
glyc_drop <- as.data.frame(t(glyc_drop))
glyc <- base_log_scale %>% dplyr::select(-colnames(glyc_drop))
# save two dfs of protein data for each outcome
proteins_alb <- mic.or.mac
proteins_alb_keep <- is_seq(names(proteins_alb))
proteins_alb <- proteins_alb[,proteins_alb_keep]
proteins_glyc <- glyc
proteins_glyc_keep <- is_seq(names(proteins_glyc))
proteins_glyc <- proteins_glyc[,proteins_glyc_keep]

# read in urine metabolomics
load("./Metabolomic data/urine.Rdata")
urine$Date.Drawn <- as.Date(urine$Date.Drawn,format = "%m/%d/%Y")
urine <- urine %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)
check_urine_vars <- function(.x) grepl("nM/mM", .x)
urine_keep <- check_urine_vars(names(urine))
urine_final <- cbind(urine$releaseid, urine[urine_keep])
urine_final[,2:ncol(urine_final)] <- log(urine_final[,2:ncol(urine_final)]) 
colnames(urine_final) <- c("releaseid",colnames(urine_final[,2:ncol(urine_final)]))

# read in plasma metabolomics
load("./Metabolomic data/plasma.Rdata")
plasma$Date.Drawn <- as.Date(plasma$Date.Drawn,format = "%m/%d/%Y")
plasma <- plasma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)
check_plasma_vars <- function(.x) grepl("uM", .x)
plasma_keep <- check_plasma_vars(names(plasma))
plasma_final <- cbind(plasma$releaseid, plasma[plasma_keep])
plasma_final[,2:ncol(plasma_final)] <- log(plasma_final[,2:ncol(plasma_final)]) 
colnames(plasma_final) <- c("releaseid",colnames(plasma_final[,2:ncol(plasma_final)]))

# keep those with complete data
# there are a few people with metabolomics but not proteomics
urine_final <- urine_final %>% filter(releaseid %in% base_log$releaseid)
plasma_final <- plasma_final %>% filter(releaseid %in% base_log$releaseid)
comorb <- comorb %>% filter(releaseid %in% base_log$releaseid)
urine_final <- urine_final %>% arrange(releaseid)
plasma_final <- plasma_final %>% arrange(releaseid)
comorb <- comorb %>% arrange(releaseid)
proteins_alb <- cbind(base_log$releaseid, proteins_alb)
colnames(proteins_alb) <- c("releaseid",colnames(proteins_alb[,2:ncol(proteins_alb)]))
proteins_alb <- proteins_alb %>% arrange(releaseid)
proteins_glyc <- cbind(base_log$releaseid, proteins_glyc)
colnames(proteins_glyc) <- c("releaseid",colnames(proteins_glyc[,2:ncol(proteins_glyc)]))
proteins_glyc <- proteins_glyc %>% arrange(releaseid)

# make df with all omics variables for elastic net
# first albuminuria
df_elastic_net_alb <- left_join(comorb, proteins_alb, by = "releaseid")
df_elastic_net_alb <- left_join(df_elastic_net_alb, urine_final, by = "releaseid")
df_elastic_net_alb <- left_join(df_elastic_net_alb, plasma_final, by = "releaseid")
proteins_alb$releaseid <- NULL
# then glycemia
df_elastic_net_glyc <- left_join(comorb, proteins_glyc, by = "releaseid")
df_elastic_net_glyc <- left_join(df_elastic_net_glyc, urine_final, by = "releaseid")
df_elastic_net_glyc <- left_join(df_elastic_net_glyc, plasma_final, by = "releaseid")
urine_final$releaseid <- NULL
plasma_final$releaseid <- NULL
proteins_glyc$releaseid <- NULL

# store predictor data in lists
X_albuminuria <- list(proteins = proteins_alb, urine_metabolites = urine_final, plasma_metabolites = plasma_final)
X_glycemia <- list(proteins = proteins_glyc, urine_metabolites = urine_final, plasma_metabolites = plasma_final)
# store outcome data as Y
Y_albuminuria <- comorb$MIC.OR.MAC
Y_glycemia <- comorb$GLYC


```

# DIABLO

## Albuminuria

### Quick model

```{r}
# First just a quick model to see if this works 
# This is not a sparse model, no variable selection performed
diablo.albuminuria.quick <- block.plsda(X_albuminuria, Y_albuminuria, near.zero.var = TRUE)
plotIndiv(diablo.albuminuria.quick)
plotVar(diablo.albuminuria.quick)
```

### Optimized model

#### Examine number of components to retain

```{r}
# Create design matrix - weights of 1 favor extraction of correlation structure,
# while weights closer to 0 favor prediction
design_alb <- matrix(0.1, ncol = length(X_albuminuria), nrow = length(X_albuminuria),
                 dimnames = list(names(X_albuminuria), names(X_albuminuria)))
diag(design_alb) <- 0
design_glyc <- matrix(0.1, ncol = length(X_glycemia), nrow = length(X_glycemia),
                 dimnames = list(names(X_glycemia), names(X_glycemia)))
diag(design_glyc) <- 0

# examine the number of components
# first fit a model without variable selection
diablo.albuminuria.comp <- block.plsda(X_albuminuria, Y_albuminuria, near.zero.var = TRUE, ncomp = 5, design = design_alb)
perf.diablo.albuminuria.comp <- perf(diablo.albuminuria.comp, validation = "Mfold", folds = 5, nrepeat = 5)
plot(perf.diablo.albuminuria.comp)
# 2 components seems sufficient, although 3 is better

# output optimal number of components according to prediction distance and type of error rate
perf.diablo.albuminuria.comp$choice.ncomp$WeightedVote
ncomp <- perf.diablo.albuminuria.comp$choice.ncomp$WeightedVote["Overall.ER", "max.dist"]

# choose optimal number of variables in each dataset
set.seed(3654)
test.keepX <- list(proteins = c(1:9, seq(10, 100, 5)),
                   urine_metabolites = c(1:9, seq(10, 25, 5)),
                    urine_metabolites = c(1:9, seq(10, 25, 5)))
#tune.diablo.albuminuria <- tune.block.splsda(X_albuminuria, Y_albuminuria, ncomp = 2,
#                                             test.keepX = test.keepX, design = design_alb,
#                                             validation = "Mfold", folds = 5, nrepeat = 1,
#                                             dist = "max.dist", near.zero.var = TRUE)
#list.keepX <- tune.diablo.albuminuria$choice.keepX
list.keepX <- list(proteins = c(100,25),
                   urine_metabolites = c(2,2),
                    plasma_metabolites = c(1,3))
list.keepX

# final model
diablo.albuminuria <- block.splsda(X_albuminuria, Y_albuminuria, ncomp = ncomp, keepX = list.keepX,
                                   design = design_alb, near.zero.var = TRUE)
vars.albuminuria.proteins1 <- as.data.frame(selectVar(diablo.albuminuria, block = "proteins", comp = 1))
vars.albuminuria.proteins1$AptName <- vars.albuminuria.proteins1$proteins.name
vars.albuminuria.proteins2 <- as.data.frame(selectVar(diablo.albuminuria, block = "proteins", comp = 2))
vars.albuminuria.proteins2$AptName <- vars.albuminuria.proteins2$proteins.name
seq.to.prot <- analytes %>% dplyr::select(AptName,TargetFullName,Target)
vars.albuminuria.proteins1 <- merge(vars.albuminuria.proteins1, seq.to.prot, by = "AptName")
vars.albuminuria.proteins2 <- merge(vars.albuminuria.proteins2, seq.to.prot, by = "AptName")
vars.albuminuria.urine1 <- as.data.frame(selectVar(diablo.albuminuria, block = "urine_metabolites", comp = 1))
vars.albuminuria.urine2 <- as.data.frame(selectVar(diablo.albuminuria, block = "urine_metabolites", comp = 2))
vars.albuminuria.plasma1 <- as.data.frame(selectVar(diablo.albuminuria, block = "plasma_metabolites", comp = 1))
vars.albuminuria.plasma2 <- as.data.frame(selectVar(diablo.albuminuria, block = "plasma_metabolites", comp = 2))

plotDiablo(diablo.albuminuria, ncomp = 1)
plotDiablo(diablo.albuminuria, ncomp = 2)
plotDiablo(diablo.albuminuria, ncomp = 3)
plotDiablo(diablo.albuminuria, ncomp = 4)
plotIndiv(diablo.albuminuria, legend = TRUE, ind.names = FALSE)
plotVar(diablo.albuminuria, var.names= FALSE, style= 'graphics', 
        legend = TRUE, pch = c(16, 17, 15), cex = c(2,2,2), 
        col= c('darkorchid', 'brown1', 'lightgreen'), title= 'TCGA, DIABLO comp 1 - 2')
circosPlot(diablo.albuminuria, cutoff = 0.4, line = TRUE, 
           color.blocks = c('darkorchid','brown1','lightgreen'),
           color.cor = c("chocolate3",'grey20'), size.labels = 1.5, size.variables = 0.3)
#network(diablo.albuminuria, blocks = c(1,2,3), cutoff = 0.3,
#        color.node = c('darkorchid','brown1','lightgreen'),
#        save = "pdf", name.save = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY #subaward/Multiomics integration/DIABLO/Plots/network_albuminuria.pdf")
plotLoadings(diablo.albuminuria, comp = 1, contrib = "max", method = "median")

cimDiablo(diablo.albuminuria, color.blocks = c('darkorchid','brown1','lightgreen'),
          comp = 1, legend.position = "right", save = "png",
          name.save = '/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/Multiomics integration/DIABLO/Plots/cim_albuminuria')

perf.diablo.albuminuria <- perf(diablo.albuminuria, validation = 'Mfold', folds = 5, 
                                nrepeat = 1, dist = "max.dist")
perf.diablo.albuminuria$MajorityVote.error.rate
perf.diablo.albuminuria$WeightedVote.error.rate
auc.diablo.albuminuria.proteins <- auroc(diablo.albuminuria, roc.block = "proteins", roc.comp = 4)
auc.diablo.albuminuria.urine <- auroc(diablo.albuminuria, roc.block = "urine_metabolites", roc.comp = 4)
auc.diablo.albuminuria.plasma <- auroc(diablo.albuminuria, roc.block = "plasma_metabolites", roc.comp = 4)
```

# Glycemia

## Quick model

```{r}
# First just a quick model to see if this works 
# This is not a sparse model, no variable selection performed
diablo.glycemia.quick <- block.plsda(X_glycemia, Y_glycemia, near.zero.var = TRUE)
plotIndiv(diablo.glycemia.quick)
plotVar(diablo.glycemia.quick)
```

### Optimized model

#### Examine number of components to retain

```{r}
# Create design matrix - weights of 1 favor extraction of correlation structure,
# while weights closer to 0 favor prediction
design_glyc <- matrix(0.1, ncol = length(X_glycemia), nrow = length(X_glycemia),
                 dimnames = list(names(X_glycemia), names(X_glycemia)))
diag(design_glyc) <- 0

# examine the number of components
# first fit a model without variable selection
diablo.glycemia.comp <- block.plsda(X_glycemia, Y_glycemia, near.zero.var = TRUE, ncomp = 5, design = design_glyc)
perf.diablo.glycemia.comp <- perf(diablo.glycemia.comp, validation = "Mfold", folds = 5, nrepeat = 5)
plot(perf.diablo.glycemia.comp)

# output optimal number of components according to prediction distance and type of error rate
perf.diablo.glycemia.comp$choice.ncomp$WeightedVote
ncomp <- perf.diablo.glycemia.comp$choice.ncomp$WeightedVote["Overall.ER", "mahalanobis.dist"]

# choose optimal number of variables in each dataset
test.keepX <- list(proteins = c(1:9, seq(10, 100, 5)),
                   urine_metabolites = c(1:9, seq(10, 25, 5)),
                    urine_metabolites = c(1:9, seq(10, 25, 5)))
#tune.diablo.glycemia <- tune.block.splsda(X_glycemia, Y_glycemia, ncomp = 2,
#                                             test.keepX = test.keepX, design = design_glyc,
#                                             validation = "Mfold", folds = 5, nrepeat = 1,
#                                             dist = "max.dist", near.zero.var = TRUE)
#list.keepX <- tune.diablo.glycemia$choice.keepX
list.keepX <- list(proteins = c(3,25),
                   urine_metabolites = c(4,3),
                   plasma_metabolites = c(25,20))
list.keepX

# final model
diablo.glycemia <- block.splsda(X_glycemia, Y_glycemia, ncomp = ncomp, keepX = list.keepX,
                                   design = design_glyc, near.zero.var = TRUE)
vars.glycemia.proteins1 <- as.data.frame(selectVar(diablo.glycemia, block = "proteins", comp = 1))
vars.glycemia.proteins1$AptName <- vars.glycemia.proteins1$proteins.name
vars.glycemia.proteins2 <- as.data.frame(selectVar(diablo.glycemia, block = "proteins", comp = 2))
vars.glycemia.proteins2$AptName <- vars.glycemia.proteins2$proteins.name
seq.to.prot <- analytes %>% dplyr::select(AptName,TargetFullName,Target)
vars.glycemia.proteins1 <- merge(vars.glycemia.proteins1, seq.to.prot, by = "AptName")
vars.glycemia.proteins2 <- merge(vars.glycemia.proteins2, seq.to.prot, by = "AptName")
vars.glycemia.urine1 <- as.data.frame(selectVar(diablo.glycemia, block = "urine_metabolites", comp = 1))
vars.glycemia.urine2 <- as.data.frame(selectVar(diablo.glycemia, block = "urine_metabolites", comp = 2))
vars.glycemia.plasma1 <- as.data.frame(selectVar(diablo.glycemia, block = "plasma_metabolites", comp = 1))
vars.glycemia.plasma2 <- as.data.frame(selectVar(diablo.glycemia, block = "plasma_metabolites", comp = 2))

plotDiablo(diablo.glycemia, ncomp = 1)
plotDiablo(diablo.glycemia, ncomp = 2)
plotIndiv(diablo.glycemia, legend = TRUE, ind.names = FALSE)
plotVar(diablo.glycemia, var.names= FALSE, style= 'graphics', 
        legend = TRUE, pch = c(16, 17, 15), cex = c(2,2,2), 
        col= c('darkorchid', 'brown1', 'lightgreen'), title= 'TCGA, DIABLO comp 1 - 2')
circosPlot(diablo.glycemia, cutoff = 0.4, line = TRUE, 
           color.blocks = c('darkorchid','brown1','lightgreen'),
           color.cor = c("chocolate3",'grey20'), size.labels = 1.5, size.variables = 0.3)
#network(diablo.glycemia, blocks = c(1,2,3), cutoff = 0.3,
#        color.node = c('darkorchid','brown1','lightgreen'),
#        save = "pdf", name.save = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY #subaward/Multiomics integration/DIABLO/Plots/network_glycemia.pdf")
plotLoadings(diablo.glycemia, comp = 1, contrib = "max", method = "median")

cimDiablo(diablo.glycemia, color.blocks = c('darkorchid','brown1','lightgreen'),
          comp = 1, legend.position = "right", save = "png",
          name.save = '/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/Multiomics integration/DIABLO/Plots/cim_glycemia')

perf.diablo.glycemia <- perf(diablo.glycemia, validation = 'Mfold', folds = 5, 
                                nrepeat = 1, dist = "max.dist")
perf.diablo.glycemia$MajorityVote.error.rate
perf.diablo.glycemia$WeightedVote.error.rate
auc.diablo.glycemia.proteins <- auroc(diablo.glycemia, roc.block = "proteins", roc.comp = 2)
auc.diablo.glycemia.urine <- auroc(diablo.glycemia, roc.block = "urine_metabolites", roc.comp = 2)
auc.diablo.glycemia.plasma <- auroc(diablo.glycemia, roc.block = "plasma_metabolites", roc.comp = 2)
```

# MOFA - Albuminuria

```{r}
# stopped here - need to make sure there are separate work flows for albuminuria and glycemia
set.seed(3654)

prot_matrix <- t(as.matrix(proteins_alb))
urine_matrix <- t(as.matrix(urine_final))
plasma_matrix <- t(as.matrix(plasma_final))

data <- list(prot_matrix, urine_matrix, plasma_matrix)
MOFAobject <- create_mofa(data)
views_names(MOFAobject) <- c("proteins", "urine_met", "plasma_met")

plot_data_overview(MOFAobject)

data_opts <- get_default_data_options(MOFAobject)
data_opts$scale_views <- TRUE

model_opts <- get_default_model_options(MOFAobject)

train_opts <- get_default_training_options(MOFAobject)
train_opts$convergence_mode <- "fast"
train_opts$verbose <- TRUE

MOFAobject <- prepare_mofa(
  object = MOFAobject,
  data_options = data_opts,
  model_options = model_opts,
  training_options = train_opts
)

outfile = file.path(tempdir(), "mofa_model.hdf5")
MOFAobject.trained <- run_mofa(MOFAobject, outfile, use_basilisk = TRUE)
#features_names(MOFAobject.trained) <- list(colnames(proteins), colnames(urine_final), colnames(plasma_final))

# add metadata
samples_metadata <- data.frame(
  sample = samples_names(MOFAobject.trained),
  albuminuria = base_log$MIC.OR.MAC,
  loss_glycemia = base_log$GLYC,
  days_to_mic.or.mac = base_log$DAYSTOMIC.OR.MAC,
  days_to_glyc = base_log$DAYSTOGLYC,
  releaseid = base_log$releaseid
)
colnames(samples_metadata) <- c("sample","albuminuria","loss_glycemia","DAYSTOMIC.OR.MAC","DAYSTOGLYC",
                                "releaseid")
samples_metadata(MOFAobject.trained) <- samples_metadata

head(MOFAobject.trained@cache$variance_explained)
plot_variance_explained(MOFAobject.trained, x="view", y="factor")

plot_factor(MOFAobject.trained,
            factors = 1:3,
            color_by = "albuminuria",
            shape_by = "loss_glycemia")
plot_factor(MOFAobject.trained,
            factors = c(1,2,3),
            color_by = "albuminuria",
            shape_by = "loss_glycemia",
            dodge = TRUE,
            add_violin = TRUE,
            violin_alpha = 0.25)
plot_factors(MOFAobject.trained,
             factors = 1:3,
             color_by = "albuminuria",
             shape_by = "loss_glycemia")
plot_weights(MOFAobject.trained,
             view = "proteins",
             factor = 1,
             nfeatures = 10,
             scale = T,
             abs = F)
plot_top_weights(MOFAobject.trained,
                 view = "proteins",
                 factor = 1,
                 nfeatures = 10)
factors_df <- get_factors(MOFAobject.trained, as.data.frame = T)
factors_mat_temp <- get_factors(MOFAobject.trained, factors = "all")
factors_mat <- as.data.frame(factors_mat_temp$group1)
factors_mat <- cbind(factors_mat, base_log$DAYSTOGLYC, base_log$DAYSTOMIC.OR.MAC,
                     base_log$GLYC, base_log$MIC.OR.MAC)

mod <- coxph(data = factors_mat, 
               Surv(base_log$DAYSTOGLYC, base_log$GLYC)~ Factor1+Factor2+Factor3+
               Factor4+Factor5+Factor6+Factor7+Factor8+Factor9+Factor10+Factor11+
               Factor12+Factor13+Factor14)
tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
mod_alb <- coxph(data = factors_mat, 
               Surv(base_log$DAYSTOMIC.OR.MAC, base_log$MIC.OR.MAC)~ Factor1+Factor2+Factor3+
               Factor4+Factor5+Factor6+Factor7+Factor8+Factor9+Factor10+Factor11+
               Factor12+Factor13+Factor14)
tidymod_alb <- tidy(mod_alb, exponentiate=TRUE, conf.int = TRUE)

# can we relabel the variables as the target names?

```

# Elastic net on combined dataset

# Albuminuria

```{r}

# STILL NOT SELECTING ANYTHING!!
alb_nozero <- df_elastic_net_alb[!df_elastic_net_alb$DAYSTOMIC.OR.MAC == 0,]
preds <- c(colnames(proteins_alb), colnames(urine_final), colnames(plasma_final))

alb_select = easy_elasticnet(data = alb_nozero,outcome = "MIC.OR.MAC",
                           predictors = alb_nozero[,preds], out = "min.error",
                           model_type = "cox",time = "DAYSTOMIC.OR.MAC", cv_method="kfold", folds = 10)
# this won't work for metabolites
retained_vars = analytes[analytes$AptName %in% alb_select, c("Target","TargetFullName")]

# testing
alb_select = easy_elasticnet(data = alb_nozero,outcome = "MIC.OR.MAC",
                           predictors = alb_nozero[colnames(alb_nozero) %in% preds], out = "1se.error",
                           model_type = "cox",time = "DAYSTOMIC.OR.MAC", cv_method="kfold", folds = 10)
# this won't work for metabolites
retained_vars = analytes[analytes$AptName %in% alb_select, c("Target","TargetFullName")]

# maybe need to do some kind of filtering within each layer???
```

# Glycemia

```{r}

```