---
title: "Prospective analysis of CF outcomes"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(stringr)
library(dplyr)
library(readxl)
library(childsds)
library(nlme)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

# get REDCap data and exclude HCs
source("E:\\Christine Chan\\Prospective analysis\\Data raw\\CGMInHealthyControls-DataForProspectiveAn_R_2021-06-02_0929.r")
data <- data[data$group_category != 1,]
write.csv(data$subject_id,"C:\\temp\\IDs.csv",row.names = F)

# get rid of double data entry
data$dde <- str_detect(data$subject_id,"--")
data <- filter(data,dde=="FALSE")

# keep the first visit
data$rpt <- str_detect(data$subject_id,"\\.1")
data <- filter(data,rpt=="FALSE")

# rename and get rid of variables
data$MRN <- str_trim(data$medical_record_number)
data$medical_record_number <- NULL
data$dde <- NULL
data$rpt <- NULL

# one patient is in twice with different IDs - keep the first
data <- data[data$subject_id != 138,]

# read in and merge insulin data
ins <- read.csv("E:\\Christine Chan\\Prospective analysis\\Data raw\\Insulin Start date and prospective data-- Eileen cleanup.csv",
                na.strings = c(""," ",NA))
# there can be duplicates in this file - keep the one with earliest date of consent
ins <- ins[!is.na(ins$Date.of.Consent),]
ins <- arrange(ins,MRN,desc(Date.of.Consent))   
ins <- ins %>% group_by(MRN) %>% filter(row_number() == 1)
#ins$subject_id <- ins$Subject.ID
ins$rpt <- str_detect(ins$Subject.ID,"\\.1")
ins <- filter(ins,rpt=="FALSE")
ins$Subject.ID <- NULL
ins$rpt <- NULL
ins$Last.Name <- NULL
ins$First.Name <- NULL
ins$Reconsented. <- NULL
ins$DOB <- NULL
ins$Date.of.Consent <- NULL
ins$Date.of.Reconsent <- NULL
ins$Long.Acting.insulin.dose.at.start..units..Lantus.Levemir <- NULL
ins$Weight..kg. <- NULL
ins$insulin.dose.at.start..units.kg. <- NULL
ins$Short.Acting.Insulin.Dose..units. <- NULL
ins$Insulin.with.steroid.burst <- NULL
ins$notes.about.insulin <- NULL
ins$date.of.long.acting.insulin.start <- ifelse(ins$date.of.long.acting.insulin.start=="N/A",NA,ins$date.of.long.acting.insulin.start)
ins$date.of.long.acting.insulin.start <- ifelse(ins$date.of.long.acting.insulin.start=="N/A (transitioned)",NA,ins$date.of.long.acting.insulin.start)
ins$date.of.long.acting.insulin.start <- ifelse(ins$date.of.long.acting.insulin.start=="01/26/2016 (ish)","01/26/2016",ins$date.of.long.acting.insulin.start)
# looks like there are duplicates in the insulin data file
# find MRNs that are in REDCap and work with those
ins_keep <- ins[ins$MRN %in% data$MRN,]
#write.csv(ins_keep,"E:\\Christine Chan\\Prospective analysis\\Data clean\\insulin_checking.csv")

# create a new variable called encounter date, which will be used to link all the results in the various sheets
data1 <- data
data1$Encounter_date <- as.Date(data1$date_of_visit)

# read in PFTs
pfts <- read_xlsx("E:\\Christine Chan\\Prospective analysis\\Data raw\\Updated Full List for Elin_Data_Updated2021_06_17.xlsx",sheet="PFTs")
pfts$Encounter_date <- as.Date(pfts$`Encounter date`)
pfts$`Encounter date` <- NULL
pfts$`First Name` <- NULL
pfts$`Last Name` <- NULL
# there seem to be some dups
pfts$`Date of Consent` <- NULL
pfts <- unique(pfts)
# keep PFTs where MRN matches data1, then merge
pfts_keep <- pfts[pfts$MRN %in% data1$MRN,]
data2 <- merge(data1,pfts_keep,by=c("MRN","Encounter_date"),all.x = T,all.y = T)
write.csv(data2,'C:\\temp\\data2.csv')

# read in OGTT and A1c data
ogtt <- read_xlsx("E:\\Christine Chan\\Prospective analysis\\Data raw\\Updated Full List for Elin_Data_Updated2021_06_17.xlsx",sheet="OGTTandA1C")
ogtt$Encounter_date <- as.Date(ogtt$`Date of Test`)
ogtt$`Date of Test` <- NULL
ogtt$`Date of Consent` <- NULL
ogtt$`First Name` <- NULL
ogtt$`Last Name` <- NULL
ogtt <- unique(ogtt)
# keep OGTTs where MRN matches data2, then merge
ogtt_keep <- ogtt[ogtt$MRN %in% data2$MRN,]
data3 <- merge(data2,ogtt_keep,by=c("MRN","Encounter_date"),all.x = T,all.y = T)
write.csv(data3,'C:\\temp\\data3.csv')

# read in sputum data
sputum <- read_xlsx("E:\\Christine Chan\\Prospective analysis\\Data raw\\Updated Full List for Elin_Data_Updated2021_06_17.xlsx",sheet="Sputum")
sputum$Encounter_date <- as.Date(sputum$CultureDate)
sputum$CultureDate <- NULL
sputum$first_name <- NULL
sputum$last_name <- NULL
sputum$`Date of Earliest Consent` <- NULL
sputum <- unique(sputum)
# keep sputum where MRN matches data3, then merge
sputum_keep <- sputum[sputum$MRN %in% data3$MRN,]
data4 <- merge(data3,sputum_keep,by=c("MRN","Encounter_date"),all.x = T,all.y = T)
write.csv(data4,'C:\\temp\\data4.csv')

# read in modulator data
mods <- read_xlsx("E:\\Christine Chan\\Prospective analysis\\Data raw\\Updated Full List for Elin_Data_Updated2021_06_17.xlsx",sheet="Modulators")
mods$`First Name` <- NULL
mods$`Last Name` <- NULL
mods$`Date of Consent` <- NULL
#mods$check1 <- ifelse(mods$`Earliest Kalydeco Date After Consent` < mods$`Earliest Orkambi Date After Consent`,0,1)
#mods$check2 <- ifelse(mods$`Earliest Orkambi Date After Consent` < mods$`Earliest Symdeko Date After Consent`,0,1)
#mods$check3 <- ifelse(mods$`Earliest Symdeko Date After Consent` < mods$`Earliest Trikafta Date After Consent`,0,1)
# for all patients Kalydeco < Orkambi < Symdeko < Trikafta
mods <- unique(mods)
# keep mods where MRN matches data4, then merge
mods_keep <- mods[mods$MRN %in% data4$MRN,]
data5 <- merge(data4,mods_keep,by="MRN",all.x = T,all.y = T)
write.csv(data5,'C:\\temp\\data5.csv')
# could create vars to indicate on each type of modulator at the encounter date, but for now will just create one variable for any modulator
data5$earliest_mod <- NA
data5$earliest_mod <- pmin(data5$`Earliest Kalydeco Date`,data5$`Earliest Orkambi Date`,data5$`Earliest Symdeko Date`,data5$`Earliest Trikafta Date`,na.rm = T)

# read in admits
admits <- read_xlsx("E:\\Christine Chan\\Prospective analysis\\Data raw\\Updated Full List for Elin_Data_Updated2021_06_17.xlsx",sheet="Admits_List")
admits$`First Name` <- NULL
admits$`Last Name` <- NULL
admits$`Date of Consent` <- NULL
admits <- unique(admits)
# count number of admits
admit_sum <- admits %>% select(MRN) %>% group_by(MRN) %>% mutate(admit_num=n())
admit_sum <- unique(admit_sum)
admit_pex_sum <- admits[admits$`Reason(s) for Admit`=="Pulmonary Exacerbation",] %>% select(MRN) %>% group_by(MRN) %>% mutate(admit_pex_num=n())
admit_pex_sum <- unique(admit_pex_sum)
admit_sum <- merge(admit_sum,admit_pex_sum,by="MRN",all.x = T,all.y = T)
# keep admits where MRN matches data5, then merge
admit_sum_keep <- admit_sum[admit_sum$MRN %in% data5$MRN,]
data6 <- merge(data5,admit_sum_keep,by="MRN",all.x = T,all.y = T)
data6$admit_num <- ifelse(is.na(data6$admit_num),0,data6$admit_num)
data6$admit_pex_num <- ifelse(is.na(data6$admit_pex_num),0,data6$admit_pex_num)

# merge in insulin data
data6 <- merge(data6,ins_keep,by="MRN",all.x = T,all.y = F)
data6$date.of.long.acting.insulin.start <- as.Date(data6$date.of.long.acting.insulin.start,format = "%m/%d/%Y")
data6$Date.of.Short.Acting.Insulin.Start <- as.Date(data6$Date.of.Short.Acting.Insulin.Start,format = "%m/%d/%Y")

# create a variable for on insulin at time of encounter
data6$on_insulin <- ifelse(is.na(data6$date.of.long.acting.insulin.start) & is.na(data6$Date.of.Short.Acting.Insulin.Start),0,
                           ifelse((!is.na(data6$date.of.long.acting.insulin.start) & data6$Encounter_date >= data6$date.of.long.acting.insulin.start) |
                             (!is.na(data6$Date.of.Short.Acting.Insulin.Start) & data6$Encounter_date >= data6$Date.of.Short.Acting.Insulin.Start),1,0))
# create a variable for earliest insulin start (first get rid of the date from REDCap)
data6$insulin_start_date <- NULL
data6$insulin_start_date <- pmin(data6$date.of.long.acting.insulin.start,data6$Date.of.Short.Acting.Insulin.Start,na.rm = T)

# drop some variables
data7 <- data6 %>%  select(-starts_with('exclusion')) %>%  select(-starts_with('stored_blood')) %>% select(-(fam_history_diabetes_notes:respiratory_comments)) %>%  
              select(-starts_with('day_')) %>%  select(-starts_with('tanner')) %>% select(-(extremities:sensor_exp_date)) %>%
              select(-c("actiwatch_serial_number","actiwatch_epoch_length","comments_about_stored_bloo","notes","cgm_data_complete","actiwatch_success_failure",
                        "actiwatch_serial_number","actiwatch_epoch_length","actiwatch_notes","average_bed_time","average_get_up_time","actiwatch_data_complete",
                        "consent.factor","re_consent_for_prospective.factor","general.factor","heent.factor","neck.factor","cv.factor","respiratory.factor",
                        "abdomen.factor","extremities.factor","neuro.factor","skin.factor","cgm_device.factor","cgm_placement.factor",
                        "demographics_and_anthropometrics_complete.factor","frequent_sampling_ogtt.factor","ogtt_grc_2hr.factor","cgm_data_success_failure.factor",
                        "cgm_data_gaps_filled_in.factor","insulin_post_study.factor","num_days_good_data.factor","total_sensor_readings.factor","cgm_data_complete.factor",
                        "actiwatch_success_failure.factor","actiwatch_data_complete.factor","Encounter location","actiwatch_serial_number","address","city_sate_zip_code",
                        "phone_number","email","agreed_to_future_contact","abdomen_comments","sensor_placement_time","ipro_placement_time","cgm_placement",
                        "cgm_placement_notes","demographics_and_anthropometrics_complete","agreed_to_future_contact.factor","consent","re_consent_for_prospective",
                        "lab_data_complete","cgm_data_success_failure","cgm_data_gaps_filled_in","number_of_gaps_filled_in","total_time_filled_in"   ))
 
# find date of CFRD dx (2 hour glucose > 200, HbA1c >=6.5)
CFRD <- data7[,c("MRN","Encounter_date","Hbg A1C","poc_a1c","OGTT 2 Hour","lab_ogtt_2_hour_glucose")]
CFRD$dia_visit <- ifelse(CFRD$`Hbg A1C`>=6.5 | CFRD$poc_a1c >=6.5 | CFRD$`OGTT 2 Hour`>= 200 | CFRD$lab_ogtt_2_hour_glucose >= 200, 1, NA)
CFRD <- CFRD %>% filter(CFRD$dia_visit==1)
CFRD_date <- CFRD %>% arrange(MRN,Encounter_date) %>% group_by(MRN) %>% filter(row_number()==1)
CFRD_date$CFRD_date <- as.Date("")
CFRD_date$CFRD_date <- CFRD_date$Encounter_date
CFRD_date <- CFRD_date[,c("MRN","CFRD_date")]
data8 <- merge(data7,CFRD_date,by="MRN",all.x = T,all.y = T)

# create time variable
# what is the start date? Date of CGM placement
# need to take out date of CGM placement and merge back
cgm_place <- data8[,c("MRN","date_cgm_placement")]
cgm_place <- cgm_place[!is.na(cgm_place$date_cgm_placement),]
data8$date_cgm_placement <- NULL
data8 <- merge(data8,cgm_place,by="MRN",all.x = T, all.y=T)
data8$date_cgm_placement <- as.Date(data8$date_cgm_placement)
data8$days <- data8$Encounter_date - data8$date_cgm_placement

# create var for CFRD or not
data8$has_CFRD <- ifelse(is.na(data8$CFRD_date) | data8$Encounter_date < data8$CFRD_date,0,1) 

# need to consolidate BMI variables - but do we want BMI percentile and/or Zscore?
data8$height <- ifelse(is.na(data8$height),data8$`Height in cm`,data8$height)
data8$height_visit_2 <- NULL
data8$`Height in cm` <- NULL
data8$average_height <- NULL
data8$bmi <- NULL
data8$bmi_percentile_visit_1 <- NULL
data8$bmi_percentile_visit_2 <- NULL
data8$bmi_visit_2 <- NULL
data8$bmi_z_score <- NULL
data8$bmi_z_score_visit_2 <- NULL
data8$`BMI absolute` <- NULL
data8$weight <- ifelse(is.na(data8$weight),data8$`Weight in kg`,data8$weight)
data8$weight_visit_2 <- NULL
data8$`Weight in kg` <- NULL
data8$average_weight <- NULL
data8$bmi <- data8$weight / ((data8$height/100)**2)
# need age and sex at every visit
# first have to take DOB out and merge back in
dob <- data8[,c("MRN","date_of_birth")]
dob <- dob[!is.na(dob$date_of_birth),]
data8$date_of_birth <- NULL
data8 <- merge(data8,dob,by="MRN",all.x = T, all.y=T)
data8$date_of_birth <- as.Date(data8$date_of_birth)
data8$age <- as.numeric(data8$Encounter_date - data8$date_of_birth)/365.25
gender <- data8[,c("MRN","gender.factor")]
gender <- gender[!is.na(gender$gender.factor),]
data8$gender.factor <- NULL
data8$gender <- NULL
data8 <- merge(data8,gender,by="MRN",all.x = T, all.y = T)

# calculate percentile and Z-score
data8$bmi_percentile <- sds(data8$bmi,age=data8$age,sex=data8$gender.factor,male="Male",female="Female",ref=cdc.ref,item = "bmi",type = "perc")
data8$bmiZ <- sds(data8$bmi,age=data8$age,sex=data8$gender.factor,male="Male",female="Female",ref=cdc.ref,item = "bmi",type = "SDS")

# now PFTs - need to be careful of raw data and percents
data8$fvc <- ifelse(is.na(data8$fvc),data8$FVC,data8$fvc)
# I think fev might be both raw data and percent
data8$fev1_percent <- ifelse(is.na(data8$fev1_percent),data8$FEV1,data8$fev1_percent)

# create baseline predictor variables
# may need to add other vars, or vars calculated from fsOGTT, but will pick CGM vars for now
pred <- data8[,c("MRN","average_sensor","standard_deviation","min_sensor","max_sensor","q1_sensor","median_sensor","q3_sensor","estimated_a1c","excursions_over_120",
                 "min_spent_over_120","percent_time_over_120","excursions_over_140","min_spent_over_140","percent_time_over_140","excursions_over_180","min_spent_over_180",
                 "percent_time_over_180","excursions_over_200","min_spent_over_200","percent_time_over_200","excursions_over_250","min_spent_over_250","percent_time_over_250",
                 "avg_excur_over_140_per_day","avg_excur_over_200_per_day","excursions_under_54","min_spent_under_54","percent_time_under_54","excursions_under_60",
                 "min_spent_under_60","percent_time_under_60","excursions_under_70","min_spent_under_70","percent_time_under_70","daytime_auc","daytime_avg_sensor_glucose",
                 "daytime_min_sensor_glucose","daytime_max_sensor_glucose","daytime_sd","nighttime_auc","nighttime_avg_sens_glucose","nighttime_min_sens_glucose",
                 "nighttime_max_sens_glucose","nighttime_sd","auc_over_180","average_auc_180","auc_over_98","average_auc_over_98","total_auc","average_auc_per_day",
                 "mean_amp_glycemic_ex","r_mage","m_value","lability_index","adrr","j_index","lbgi","hbgi","conga","modd","grade","mag","cov","interquartile_range")]
data8 <- data8 %>% select(-c("average_sensor","standard_deviation","min_sensor","max_sensor","q1_sensor","median_sensor","q3_sensor","estimated_a1c","excursions_over_120",
                 "min_spent_over_120","percent_time_over_120","excursions_over_140","min_spent_over_140","percent_time_over_140","excursions_over_180","min_spent_over_180",
                 "percent_time_over_180","excursions_over_200","min_spent_over_200","percent_time_over_200","excursions_over_250","min_spent_over_250","percent_time_over_250",
                 "avg_excur_over_140_per_day","avg_excur_over_200_per_day","excursions_under_54","min_spent_under_54","percent_time_under_54","excursions_under_60",
                 "min_spent_under_60","percent_time_under_60","excursions_under_70","min_spent_under_70","percent_time_under_70","daytime_auc","daytime_avg_sensor_glucose",
                 "daytime_min_sensor_glucose","daytime_max_sensor_glucose","daytime_sd","nighttime_auc","nighttime_avg_sens_glucose","nighttime_min_sens_glucose",
                 "nighttime_max_sens_glucose","nighttime_sd","auc_over_180","average_auc_180","auc_over_98","average_auc_over_98","total_auc","average_auc_per_day",
                 "mean_amp_glycemic_ex","r_mage","m_value","lability_index","adrr","j_index","lbgi","hbgi","conga","modd","grade","mag","cov","interquartile_range"))
pred$nmiss <- apply(is.na(pred), 1, sum) 
pred <- pred[pred$nmiss != 64,]
data9 <- merge(data8,pred,by="MRN",all.x = T, all.y = T)
  
# final datasets - with and without insulin, 1 year, 3 years, all time points
final_alltime_withins <- data9 
final_1yr_withins <- data9 %>% filter(days<=365)
final_3yr_withins <- data9 %>% filter(days<=365*3)
final_alltime_noins <- data9 %>% filter(on_insulin==0)
final_1yr_noins <- data9 %>% filter(on_insulin==0) %>% filter(days<=365)
final_3yr_noins <- data9 %>% filter(on_insulin==0) %>% filter(days<=365*3)
dfs <- c("final_alltime_withins","final_1yr_withins","final_3yr_withins","final_alltime_noins","final_1yr_noins","final_3yr_noins")

# are CGM variables predictive of BMI and PFT change?
mod <- lme(bmiZ ~ days + average_sensor,random=~1|MRN,data = final_alltime_withins,na.action = na.omit)
mod_anova <- anova.lme(mod, type="marginal")

for (i in 1:length(dfs)) {
  mod <- lme(bmiZ ~ days + average_sensor,random=~1|MRN,data = final_alltime_withins,na.action = na.omit)
  mod_anova <- anova.lme(mod, type="marginal")
}

```

# Background

# Methods

# Results

```{r echo=FALSE}
kable(t1,caption = "")
```
<br>
