---
title: "HIP urine sex steroids"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
editor: visual
---

```{r include=FALSE}
library(dplyr)
library(knitr)
library(nlme)
library(emmeans)
library(lme4)
library(lmerTest)
library(knitr)
library(ggplot2)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "B:/Projects/Erin Cobry/Inpatient CGM study/"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Megan Kelsey/Kelsey HIP/"
}
knitr::opts_knit$set(root.dir = home_dir)
setwd(home_dir)
```

```{r include=TRUE, warning=FALSE, message=F}
# Import data
setwd(home_dir)
data <- read.csv("./Data raw/Final Data Set _KK_05_31_2022_SG_Checked_NS_AB.csv",na.strings = c(""," ","."))
data <- data %>% filter(!is.na(Visit.Date))
data <- data %>% filter(!Visit.Date=="")
data <- data %>% filter(!Obese.Lean=="")
data$X <- NULL
data$Visit.Date<- as.Date(data$Visit.Date, format="%m/%d/%y")

# do I need to merge in Tanner stage info, plot steroids using coded visits like 2a, 2b for the first and second visits during TS 2
# not sure what this is going to look like since some people have more visits than others

# one patient has two samples with the same first date

# for now I will just plot vs. time from 1st visit
# for some people, the first visit is not #1
first <- data %>% arrange(Visit.Date) %>% group_by(HIP.ID) %>% filter(Visit.Date == min(Visit.Date))
first_keep <- first %>% select(c(HIP.ID,VISIT.NUMBER,Visit.Date))
first_keep$first.VISIT.NUMBER <- first_keep$VISIT.NUMBER
first_keep$first.Visit.Date <- first_keep$Visit.Date
first_keep$Visit.Date <- NULL
first_keep$VISIT.NUMBER <- NULL
data <- merge(data, first_keep, by="HIP.ID")

# need to check above once missing dates are filled in....when I merge first_keep back to data, there are IDs data that are not in first_keep, because of missing visit dates
data$time <- data$Visit.Date - data$first.Visit.Date
data$time_num <- as.numeric(data$time)

# fix Lean/Obese values
data$Obese.Lean[data$Obese.Lean=="O "] <- "O"
data$Obese.Lean <- as.factor(data$Obese.Lean)

```

```{r include=TRUE, warning=FALSE, message=F}
# trying to add interaction but getting an error
model_and_plot = function(outcome_name,ylab,group_var,pred,df,pois = F,plot){
  # Convert to numeric
  df[,outcome_name] = as.numeric(df[,outcome_name])
  # Fit a mixed model. 
  mod <- lme(as.formula(paste0(outcome_name,"~time_num*",pred)),random=~1|HIP.ID,df,na.action=na.omit)
  # Plot
  p = ggplot(df,aes_string(x = "time",y = outcome_name, group = group_var, color=as.factor(df$Obese.Lean))) +
    geom_line(alpha=0.5) + geom_smooth(aes(group=as.factor(df$Obese.Lean))) +
    theme_bw() +xlab("Days") + ylab(ylab) +  scale_color_discrete(name ="Obese/Lean", labels=c("Lean","Obese")) 
  # Print plot and model results
  if(plot==1){print(p)}
  print(kable(anova.lme(mod,type="marginal"),digits = 3,caption = "Type III ANOVA"))
  print(kable(summary(mod)$tTable,digits = 3,caption = "Fixed Effects"))
}

```

# Questions

1\) Use "corrected by SG" variables?

2\) How to include Tanner stage?

3\) What is the primary comparison of interest?

4\) Include treated participants?

5\) I needed to restrict follow-up time to 1500 days for LH to get models to converge. Should we do something similar for other outcomes?

# Results

## LH corrected by SG

```{r include=TRUE, warning=FALSE, message=F}
model_and_plot(outcome_name = "LH.Corrected.by.SG",pred="Obese.Lean",df=data[data$time<1500 & !is.na(data$Obese.Lean),],group_var = "HIP.ID",ylab="LH.Corrected.by.SG",plot="1")
```

## FSH corrected by SG

```{r include=TRUE, warning=FALSE, message=F}
model_and_plot(outcome_name = "FSH.Corrected.by.SG",pred="Obese.Lean",df=data[!is.na(data$Obese.Lean),],group_var = "HIP.ID",ylab="FSH.Corrected.by.SG",plot="1")

```

## E1c corrected for SG

```{r include=TRUE, warning=FALSE, message=F}
model_and_plot(outcome_name = "E1c.Corrected.for.SG",pred="Obese.Lean",df=data[!is.na(data$Obese.Lean),],group_var = "HIP.ID",ylab="E1c.Corrected.by.SG",plot="1")
```
