---
title: "Samples for multiome"
author: "Laura Pyle"
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    page-layout: full
editor: source
---

```{r}
#| include: false
library(tidyverse)
library(arsenal)
library(knitr)
# Import and filter
#df <- read.csv("/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv", na.strings = "")
df <- read.csv("/Users/pylell/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv", na.strings = "")
df <- df %>% filter(visit == "baseline")
# Select variables for T1
df <- df %>%
  select(
    record_id, visit, weight, bmi,
    sex, race, ethnicity,group,
    bod_pod_body_fat, gfr_raw_plasma, gfr_bsa_plasma,
    ff, acr_u,albuminuria_cat, elevated_albuminuria,
    contains("fsoc_"), map, sbp, dbp, fbg, hba1c, airg, acprg,
    contains("glom_volume"), mes_matrix_area, mes_index,
    contains("mes_volume"), contains("egfr"), glom_nuc_count,
    metformin_timepoint, insulin_med_timepoint,
    sglti_timepoint, raasi_timepoint,
    lc_f, rc_f, lm_f, rm_f, adc_left, adc_right, bold_l_bl_cortex, bold_r_bl_cortex,
    kit_id
  ) %>%
  group_by(record_id, visit) %>%
  summarise_all(~ last(na.omit(.x)))

# RH2-11-O and RH-77-T do not have LN samples
# try to find replacements who have PET and MRI data and match on demographics
ids <- c("RH2-43-T","RH2-42-T","RH2-36-O","RH2-22-T","RH2-21-T",
         "RH2-19-T","RH2-07-O","RH-93-T","RH2-51-T","RH2-38-T",
         "RH2-23-T","RH2-55-T","RH2-53-T","CRC-39","CRC-58","CRC-54","CRC-56")
# the people below have LN 
ids_have_ln <- c("RH2-07-O","RH2-14-T","RH2-21-T","RH2-38-T","RH2-23-T","RH2-22-T","RH2-36-O","RH2-43-T",
                 "RH2-42-T","RH2-53-T","RH2-51-T","RH2-55-T","RH2-59-T","RH-67-T","RH-91-T","RH-93-T",
                 "IT_19","IT_20")
# who's left?
df_potential <- df %>% filter(record_id %in% ids_have_ln)
df_potential <- df_potential %>% filter(!(record_id %in% ids))
# of those left, who has BOLD and MRI?
df_potential <- df_potential %>% filter(!is.na(lc_f))
df_potential <- df_potential %>% filter(!is.na(adc_left))

# these are the IDs we are going to keep
ids <- c("RH2-43-T","RH2-42-T","RH2-36-O","RH2-22-T","RH2-21-T",
         "RH2-19-T","RH2-07-O","RH-93-T","RH2-51-T","RH2-38-T",
         "RH2-23-T","RH2-55-T","RH2-53-T","CRC-39","CRC-58","CRC-11","CRC-56",
         "RH2-14-T")
df <- df %>% filter(record_id %in% ids)
df$group <- ifelse(df$record_id == "RH-93-T", "Obese Control", df$group)
# Get names
#var_names <- read.csv("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Data Harmonization/data_dictionary_master.csv", na.strings = "")
var_names <- read.csv("/Users/pylell/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Petter Bjornstad/Data Harmonization/data_dictionary_master.csv", na.strings = "")
vars <- colnames(df)[3:(ncol(df)-1)]
var_names <- var_names[var_names$variable_name %in% vars, ]
labels <- as.list(var_names$label)
names(labels) <- var_names$variable_name
```

```{r results='asis'}
#| label: tbl-t1
#| tbl-cap: Comparisons by Group (Full Cohort)
t1 <- tableby(group  ~ 
                sex + race + ethnicity + 
               weight + bmi + gfr_raw_plasma + gfr_bsa_plasma + 
               ff + wt(acr_u,"Nmiss", "median", "q1q3", "range") + 
               albuminuria_cat + elevated_albuminuria +
               map + sbp + eGFR_CKD_epi + eGFR_fas_cr +
               dbp + fbg + hba1c + airg + acprg + 
               metformin_timepoint + insulin_med_timepoint + sglti_timepoint + 
               raasi_timepoint, 
             data = df, test = FALSE)
summary(t1, labelTranslations = labels,pfootnote = T)
```
