---
title: "Teen-LABS IGF boxplots"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r libraries,echo=FALSE, include=F}
library(knitr)
library(tidyverse)
library(Hmisc)
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
```

```{r clean data,echo=FALSE}
# source("/Users/timvigers/GitHub/CHCO-Code/Petter Bjornstad/Teen-LABS/create_teen_labs_analysis_dataset.R")
load("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Data_Cleaned/analysis_dataset.RData")

# Import proteomics data for IMPROVE
load("/Volumes/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/IMPROVE T2D/Somalogic data/improve_soma.Rdata")
# Transform
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(improve_soma))
improve_soma <- improve_soma %>% modify_if(is_seq(names(.)), log)
improve_soma$record_id <- improve_soma$SampleDescription
improve_soma$visit <- improve_soma$TimePoint
improve_soma <- improve_soma %>%
  mutate(
    record_id = sub("IT2D-", "IT_", record_id),
    visit = case_when(
      visit == "BL" ~ "baseline",
      visit == "3M" ~ "3_months_post_surgery",
      visit == "12M" ~ "12_months_post_surgery"
    )
  )
improve_soma$visit = factor(improve_soma$visit,levels = c("baseline","3_months_post_surgery","12_months_post_surgery"))

# create df with only participants who have transcriptomics
# "IT_07_12M","IT_07_BL","IT_08_12M","IT_08_BL","IT_10_12M","IT_10_BL","IT_11_12M","IT_11_BL","IT_12_12M","IT_12_BL
improve_soma_transcriptomics <- improve_soma %>% filter(
  record_id %in% c("IT_07","IT_08","IT_10","IT_11","IT_12")
)


```

# Teen-LABS

```{r,echo=FALSE}
# keep only the proteins we need
analyte_igf <- analyte_info %>% filter(UniProt %in% c("P05019","P17936","P35858","P01241","P18065","P22692","P24593",
                                                         "P10912","P08833","P24592","P01019"))
apt_keep <- analyte_igf$AptName
#df_igf <- df %>% select(all_of(apt_keep))
#df_igf <- cbind(df$ID, df$visit, df_igf)
#colnames(df_igf[,1:2]) <- c ("ID","visit")

# calculate log of ratio of upregulated IGF1 aptamer and IGFBP3
df$igf1_igfbp3 <- log(exp(df$seq.2952.75)/exp(df$seq.2571.12))

p <- ggplot(df,aes(visit,seq.13741.36))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.13741.36))
p

p <- ggplot(df,aes(visit,seq.14088.38))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.14088.38))
p

p <- ggplot(df,aes(visit,seq.19581.15))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.19581.15))
p

p <- ggplot(df,aes(visit,seq.22985.160))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.22985.160))
p

p <- ggplot(df,aes(visit,seq.2570.72))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2570.72))
p

p <- ggplot(df,aes(visit,seq.2571.12))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2571.12))
p

p <- ggplot(df,aes(visit,seq.2685.21))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2685.21))
p

p <- ggplot(df,aes(visit,seq.2686.67))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2686.67))
p

p <- ggplot(df,aes(visit,seq.2771.35))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2771.35))
p

p <- ggplot(df,aes(visit,seq.2948.58))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2948.58))
p

p <- ggplot(df,aes(visit,seq.2950.57))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2950.57))
p

p <- ggplot(df,aes(visit,seq.2952.75))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2952.75))
p

p <- ggplot(df,aes(visit,seq.6605.17))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.6605.17))
p

p <- ggplot(df,aes(visit,seq.8406.17))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.8406.17))
p

p <- ggplot(df,aes(visit,seq.8462.18))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.8462.18))
p

p <- ggplot(df,aes(visit,seq.8469.41))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.8469.41))
p

p <- ggplot(df,aes(visit,seq.8819.3))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.8819.3))
p

p <- ggplot(df,aes(visit,seq.3484.60))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.3484.60))
p

p <- ggplot(df,aes(visit,igf1_igfbp3))+geom_boxplot(aes(fill=visit)) + ylab("log(IGF1/IGFBP3)")
p

p <- ggplot(df,aes(visit,exp(igf1_igfbp3)))+geom_boxplot(aes(fill=visit)) + ylab("IGF1/IGFBP3")
p
```

# IMPROVE - entire sample

```{r,echo=FALSE}
# keep only the proteins we need
analyte_igf <- analyte_info %>% filter(UniProt %in% c("P05019","P17936","P35858","P01241","P18065","P22692","P24593",
                                                         "P10912","P08833","P24592","P01019"))
apt_keep <- analyte_igf$AptName

# calculate log of ratio of upregulated IGF1 aptamer and IGFBP3
improve_soma$igf1_igfbp3 <- log(exp(improve_soma$seq.2952.75)/exp(improve_soma$seq.2571.12))

p <- ggplot(improve_soma,aes(visit,seq.13741.36))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.13741.36))
p

p <- ggplot(improve_soma,aes(visit,seq.14088.38))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.14088.38))
p

p <- ggplot(improve_soma,aes(visit,seq.19581.15))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.19581.15))
p

p <- ggplot(improve_soma,aes(visit,seq.22985.160))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.22985.160))
p

p <- ggplot(improve_soma,aes(visit,seq.2570.72))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.2570.72))
p

p <- ggplot(improve_soma,aes(visit,seq.2571.12))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.2571.12))
p

p <- ggplot(improve_soma,aes(visit,seq.2685.21))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.2685.21))
p

p <- ggplot(improve_soma,aes(visit,seq.2686.67))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.2686.67))
p

p <- ggplot(improve_soma,aes(visit,seq.2771.35))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.2771.35))
p

p <- ggplot(improve_soma,aes(visit,seq.2948.58))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.2948.58))
p

p <- ggplot(improve_soma,aes(visit,seq.2950.57))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.2950.57))
p

p <- ggplot(improve_soma,aes(visit,seq.2952.75))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.2952.75))
p

p <- ggplot(improve_soma,aes(visit,seq.6605.17))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.6605.17))
p

p <- ggplot(improve_soma,aes(visit,seq.8406.17))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.8406.17))
p

p <- ggplot(improve_soma,aes(visit,seq.8462.18))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.8462.18))
p

p <- ggplot(improve_soma,aes(visit,seq.8469.41))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.8469.41))
p

p <- ggplot(improve_soma,aes(visit,seq.8819.3))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.8819.3))
p

p <- ggplot(improve_soma,aes(visit,seq.3484.60))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma$seq.3484.60))
p

p <- ggplot(improve_soma,aes(visit,igf1_igfbp3))+geom_boxplot(aes(fill=visit)) + ylab("log(IGF1/IGFBP3)")
p

p <- ggplot(improve_soma,aes(visit,exp(igf1_igfbp3)))+geom_boxplot(aes(fill=visit)) + ylab("IGF1/IGFBP3")
p
```

# IMPROVE - subsample with transcriptomics

```{r,echo=FALSE}
# keep only the proteins we need
analyte_igf <- analyte_info %>% filter(UniProt %in% c("P05019","P17936","P35858","P01241","P18065","P22692","P24593",
                                                         "P10912","P08833","P24592","P01019"))
apt_keep <- analyte_igf$AptName

# calculate log of ratio of upregulated IGF1 aptamer and IGFBP3
improve_soma_transcriptomics$igf1_igfbp3 <- log(exp(improve_soma_transcriptomics$seq.2952.75)/exp(improve_soma_transcriptomics$seq.2571.12))

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.13741.36))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.13741.36))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.14088.38))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.14088.38))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.19581.15))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.19581.15))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.22985.160))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.22985.160))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.2570.72))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.2570.72))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.2571.12))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.2571.12))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.2685.21))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.2685.21))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.2686.67))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.2686.67))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.2771.35))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.2771.35))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.2948.58))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.2948.58))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.2950.57))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.2950.57))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.2952.75))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.2952.75))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.6605.17))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.6605.17))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.8406.17))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.8406.17))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.8462.18))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.8462.18))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.8469.41))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.8469.41))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.8819.3))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.8819.3))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,seq.3484.60))+geom_boxplot(aes(fill=visit)) + ylab(label(improve_soma_transcriptomics$seq.3484.60))
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,igf1_igfbp3))+geom_boxplot(aes(fill=visit)) + ylab("log(IGF1/IGFBP3)")
p

p <- ggplot(improve_soma_transcriptomics,aes(visit,exp(igf1_igfbp3)))+geom_boxplot(aes(fill=visit)) + ylab("IGF1/IGFBP3")
p
```
