---
title: "Teen-LABS: Changes in top proteins associated with loss of glycemic control in TODAY"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r libraries,echo=FALSE, include=F}
library(knitr)
library(tidyverse)
library(Hmisc)
library(readxl)
library(RColorBrewer)
library(ggpubr)
library(lme4)
library(lmerTest)
library(emmeans)
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
```

```{r clean data,echo=FALSE}
# source("/Users/timvigers/GitHub/CHCO-Code/Petter Bjornstad/Teen-LABS/create_teen_labs_analysis_dataset.R")
load("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Data_Cleaned/analysis_dataset.RData")
tldata <- df

# keep only the proteins we need
# keep top 20 proteins from univariate CPH analysis
load("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Proteomics and DKD/Data_Cleaned/analysis_dataset.RData")
df <- df %>% filter(visit == "baseline")
# select top 20 aptamers
top_glyc_df <- top_glyc_df %>% arrange(adj.p.value) %>% slice_head(n = 10)
seq_include <- top_glyc_df$AptName 


#analyte_igf <- analyte_info %>% filter(UniProt %in% c("P05019","P17936","P35858","P01241","P18065","P22692","P24593",
 #                                                        "P10912","P08833","P24592","P01019"))
#apt_keep <- analyte_igf$AptName


# read in estimated marginal means
emmdf <- read_xlsx("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/Teen LABS emmeans.xlsx")
emmdf_keep <- emmdf %>% filter(AptName %in% seq_include)
emmdf_keep$uniqname <- paste0(emmdf_keep$Target,"_",emmdf_keep$AptName)  

```

```{r,echo=FALSE}
p <- ggplot(emmdf_keep, aes(x=visit, y=emmean, colour=Target, group=uniqname)) +
    geom_line() + 
    geom_errorbar(aes(ymin=emmean-SE, ymax=emmean+SE), width=.1) +  
    xlab("") +
    ylab("Estimated marginal mean") + theme_bw() 
png('/Users/pylell/Dropbox/TODAY glycemic manuscript [shared]/Analysis output/Teen-LABS_changes_top_TODAY_glycemia_proteins.png', res = 300, width = 10, height = 10, units = "in")
p
dev.off()

p <- NULL
# loop through top 10 proteins and make separate plot for each
for (i in seq_include) {
  p[[i]] <- ggplot(emmdf_keep[emmdf_keep$AptName == i,], aes(x=visit, y=emmean, colour=Target, group=uniqname)) +
    geom_line() + 
    geom_errorbar(aes(ymin=emmean-SE, ymax=emmean+SE), width=.1) +  
    xlab("") +
    ylab("Mean") + theme_bw() + theme(legend.position = "top") + scale_color_discrete(name="")
}

panel_p <- ggarrange(p[["seq.9216.100"]],p[["seq.5122.92"]],p[["seq.3186.2"]],p[["seq.2705.5"]],p[["seq.18185.118"]],
                     p[["seq.5722.78"]],p[["seq.15487.164"]],p[["seq.3035.80"]],p[["seq.14068.29"]],p[["seq.16818.200"]],
                     ncol = 2, nrow = 5)
png('/Users/pylell/Dropbox/TODAY glycemic manuscript [shared]/Analysis output/Teen-LABS_changes_top_TODAY_glycemia_proteins.png', res = 300, width = 8, height = 10, units = "in")
panel_p
dev.off()
```

```{r,echo=FALSE}
vars <- c("HBA1C", "bmi")

# Parallel processing
rows <- lapply(vars, function(y) {
  f <- as.formula(paste0(y, "~ visit + (1|ID)"))
  m <- lmer(f, data = tldata)
  emm <- emmeans(m, specs = ~visit)
  # Contrast not necessary with current parameterization, but nice to have written
  c <- contrast(emm,
    method =
      list("Year 1 - Month 1" = c(0, 0, 1, 0, 0, 0, 0) - c(1, 0, 0, 0, 0, 0, 0))
  )
  c <- as.data.frame(c)
  c$AptName <- y
  return(c)
})

means <- lapply(vars, function(y) {
  f <- as.formula(paste0(y, "~ visit + (1|ID)"))
  m <- lmer(f, data = tldata)
  emm <- emmeans(m, specs = ~visit)
  # Contrast not necessary with current parameterization, but nice to have written
  c <- contrast(emm,
    method =
      list("Year 1 - Month 1" = c(0, 0, 1, 0, 0, 0, 0) - c(1, 0, 0, 0, 0, 0, 0))
  )
  c <- as.data.frame(c)
  c$AptName <- y
  return(emm)
})

lmm_res <- do.call(rbind, rows)

means_res <- NULL
for (i in 1:2) {
  temp <- summary(means[[i]])
  a <- vars[i]
  a <- rep(a,7)
  temp <- cbind(a, temp)
  means_res <- rbind(means_res, temp)
}

pclin <- NULL
# loop through top 10 proteins and make separate plot for each
for (i in vars) {
  pclin[[i]] <- ggplot(means_res[means_res$a == i,], aes(x=visit, y=emmean, colour=a, group=a)) +
    geom_line() + 
    geom_errorbar(aes(ymin=emmean-SE, ymax=emmean+SE), width=.1) +  
    xlab("") +
    ylab("Mean") + theme_bw() + theme(legend.position = "top") + scale_color_discrete(name="")
}

panel_pclin <- ggarrange(pclin[[1]],pclin[[2]], ncol = 2, nrow = 2)
png('/Users/pylell/Dropbox/TODAY glycemic manuscript [shared]/Analysis output/Teen-LABS_clinical_vars.png', res = 300, width = 8, height = 10, units = "in")
panel_pclin
dev.off()

```
