---
title: "Teen-LABS: Changes in top proteins associated with loss of glycemic control in TODAY"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r libraries,echo=FALSE, include=F}
library(knitr)
library(tidyverse)
library(Hmisc)
library(readxl)
library(RColorBrewer)
library(ggpubr)
library(lme4)
library(lmerTest)
library(emmeans)
library(parallel)
library(limma)
library(clusterProfiler)
library(ReactomePA)
library(enrichplot)
library(Hmisc)
library(knitr)
library(tidyverse)
library(gtsummary)
library(ggpubr)
library(nlme)
library(parallel)
library(emmeans)
library(RColorBrewer)
library(VennDiagram)
library(broom.mixed)
library(ggrepel)
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
```


```{r functions}
scaleFUN <- function(x) sprintf("%.2f", x)

# Volcano plot
volcano <- function(data, lab = "Target", xcol = "estimate", ycol = "p.value",
                    top = 15,
                    xlimit = c(-1, 1), ylimit = c(0, -log10(10e-7)),
                    xlabel = "Beta", pCutoff = 0.05, overlaps = 50,
                    log_t = F) {
  data <- as.data.frame(data)
  t <- data[data[, "p.value.adj"] <= pCutoff, ]
  if (log_t) {
    t <- t[order(abs(log(t[, ycol])), decreasing = F), ]
  } else {
    t <- t[order(abs(t[, ycol]), decreasing = F), ]
  }
  data$top <- data[, "AptName"] %in% t[1:top, "AptName"]
  #data$top <- data[, "AptName"] %in% t[t$Target %in% top, "AptName"]
  data$logp <- -log10(data[, ycol])
  data$fc <- data[, xcol]
  data$sig <- data[, ycol] <= pCutoff
  p <- ggplot(data = data, aes(x = fc, y = logp, color = sig)) +
    geom_hline(yintercept = -log10(pCutoff), linetype = "dashed") +
    geom_point(size = 2.5) +
    geom_label_repel(
      data = data[data$top, ], aes(label = Target), color = "black",
      max.overlaps = overlaps
    ) +
    scale_color_manual(values = c("grey", "#3e6dbf")) +
    xlab(xlabel) + scale_x_continuous(labels = scaleFUN) +
    ylab(bquote(~ -Log[10] ~ italic(P))) +
    theme_bw() +
    theme(legend.position = "none")
  return(p)
}
```


```{r clean data,echo=FALSE}
# read entire TL dataset
# source("/Users/timvigers/GitHub/CHCO-Code/Petter Bjornstad/Teen-LABS/create_teen_labs_analysis_dataset.R")
load("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Data_Cleaned/analysis_dataset.RData")
# Tim already log transformed proteins when creating dataframe
df$map <- NA
for (i in 1:nrow(df)) {
  df[i,]$map <- df[i,]$dbp + ((1/3) * (df[i,]$sbp - df[i,]$dbp))
}
tldata <- df

# top proteins from TODAY
load("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/Proteomics HTN/copy_of_old_analysis_dataset_for_HTN_response.RData")
df <- df[!is.na(df$htn),]
df <- df %>% filter(visit == "baseline")
df$htn <- droplevels(df$htn)
prot_include <- c("WFKN2","SEZ6L","NCAM-120","NCAM1","SCG3","Aminoacylase-1",
"WFKN2","ESPN","PURA1","SERB","CHL1","PEDF","LSAMP",
"Growth hormone receptor","OFUT1")
seq_include <- c("seq.13408.23","seq.19563.3","seq.4498.62",
"seq.20161.41","seq.7957.2","seq.3343.1","seq.3235.50","seq.24957.6",
"seq.13998.26","seq.24681.2","seq.8958.51","seq.7735.17","seq.2999.6",
"seq.2948.58","seq.5634.39")
top_htn <- top_htn_df %>%
  filter(AptName %in% seq_include) %>%
  slice_max(abs(log(estimate)), n = 21) %>%
  pull(AptName)

# read in estimated marginal means from TL
emmdf <- read_xlsx("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/Teen LABS emmeans.xlsx")
emmdf_keep <- emmdf %>% filter(AptName %in% seq_include)
emmdf_keep$uniqname <- paste0(emmdf_keep$Target,"_",emmdf_keep$AptName)  

qvals <- read_xlsx("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/Teen LABS change_from_m1.xlsx")
qvals <- qvals %>% select(AptName, `q value`)
emmdf_keep <- left_join(emmdf_keep, qvals, by = "AptName")

```

```{r,echo=FALSE}
#p <- ggplot(emmdf_keep, aes(x=visit, y=emmean, colour=Target, group=uniqname)) +
#    geom_line() + 
#    geom_errorbar(aes(ymin=emmean-SE, ymax=emmean+SE), width=.1) +  
#    xlab("") +
#    ylab("Estimated marginal mean") + theme_bw() 
#png('/Users/pylell/Dropbox/TODAY glycemic manuscript [shared]/Analysis output/Teen-LABS_changes_top_TODAY_glycemia_proteins.png', res = 300, width = 10, height = 10, units = "in")
#p
#dev.off()

p <- NULL
label <- NULL
# loop through top 10 proteins and make separate plot for each
for (i in seq_include) {
  label <- ifelse(unique(emmdf_keep[emmdf_keep$AptName == i,]$`q value` < 0.001), "q < 0.001", paste("q =", format(round(unique(emmdf_keep[emmdf_keep$AptName == i,]$`q value`),3),nsmall=3)))
  #y_space <- ifelse()
  p[[i]] <- ggplot(emmdf_keep[emmdf_keep$AptName == i,], aes(x=visit, y=emmean, colour=Target, group=uniqname)) +
    geom_line() + 
    geom_errorbar(aes(ymin=emmean-SE, ymax=emmean+SE), width=.1) +  
    xlab("") +
    ylab("Mean") + theme_bw() + theme(legend.position = "top") + scale_color_discrete(name="") +
      annotate(geom="text", y=emmdf_keep[emmdf_keep$AptName == i & emmdf_keep$visit == "Month 1",]$emmean + 0.18, x=1.25, col="red", label = label) +
     scale_y_continuous(expand = expansion(mult = c(0.1, 0.3)))
       #          label=paste("atop(' crt: '*",label,")"), parse=T)

}

panel_p <- ggarrange(p[["seq.13408.23"]],p[["seq.3235.50"]],
                     p[["seq.19563.3"]],p[["seq.4498.62"]],p[["seq.20161.41"]],p[["seq.7957.2"]],
                     p[["seq.3343.1"]],p[["seq.24957.6"]],p[["seq.13998.26"]],p[["seq.24681.2"]],
                     p[["seq.8958.51"]],p[["seq.7735.17"]],p[["seq.2999.6"]],p[["seq.2948.58"]],p[["seq.5634.39"]],
                     ncol = 3, nrow = 5)
png('/Users/pylell/Dropbox/TODAY HTN and DKD output/Teen-LABS_changes_top_TODAY_HTN_proteins.png', res = 300, width = 15, height = 10, units = "in")
panel_p
dev.off()
```

```{r,echo=FALSE}
vars <- c("HBA1C", "bmi")

# Parallel processing
rows <- lapply(vars, function(y) {
  f <- as.formula(paste0(y, "~ visit + (1|ID)"))
  m <- lmer(f, data = tldata)
  emm <- emmeans(m, specs = ~visit)
  # Contrast not necessary with current parameterization, but nice to have written
  c <- contrast(emm,
    method =
      list("Year 1 - Month 1" = c(0, 0, 1, 0, 0, 0, 0) - c(1, 0, 0, 0, 0, 0, 0))
  )
  c <- as.data.frame(c)
  c$AptName <- y
  return(c)
})

means <- lapply(vars, function(y) {
  f <- as.formula(paste0(y, "~ visit + (1|ID)"))
  m <- lmer(f, data = tldata)
  emm <- emmeans(m, specs = ~visit)
  # Contrast not necessary with current parameterization, but nice to have written
  c <- contrast(emm,
    method =
      list("Year 1 - Month 1" = c(0, 0, 1, 0, 0, 0, 0) - c(1, 0, 0, 0, 0, 0, 0))
  )
  c <- as.data.frame(c)
  c$AptName <- y
  return(emm)
})

lmm_res <- do.call(rbind, rows)

means_res <- NULL
for (i in 1:2) {
  temp <- summary(means[[i]])
  a <- vars[i]
  a <- rep(a,7)
  temp <- cbind(a, temp)
  means_res <- rbind(means_res, temp)
}

pclin <- NULL
# loop through top 10 proteins and make separate plot for each
for (i in vars) {
  pclin[[i]] <- ggplot(means_res[means_res$a == i,], aes(x=visit, y=emmean, colour=a, group=a)) +
    geom_line() + 
    geom_errorbar(aes(ymin=emmean-SE, ymax=emmean+SE), width=.1) +  
    xlab("") +
    ylab("Mean") + theme_bw() + theme(legend.position = "top") + scale_color_discrete(name="")
}

panel_pclin <- ggarrange(pclin[[1]],pclin[[2]], ncol = 2, nrow = 2)
png('/Users/pylell/Dropbox/TODAY glycemic manuscript [shared]/Analysis output/Teen-LABS_clinical_vars.png', res = 300, width = 8, height = 10, units = "in")
panel_pclin
dev.off()

```

```{r,echo=FALSE}
# test association over time of top HTN proteins with SBP
seqs <- analyte_info$AptName
# Parallel processing
cl <- makeForkCluster(8)
rows <- parLapply(cl, seqs, function(y) {
  f <- as.formula(paste0("sbp ~", y))
  m <- lme(f, random = ~1|record_id, data = df, na.action = na.omit)
  #res <- coef(summary(m))[4,]
  res <- tidy(m, effects = "fixed")
  res$protein <- y
  return(res)
})
stopCluster(cl)
# Save results
lmm_res <- data.frame(do.call(rbind, rows)) %>%
  dplyr::select(protein, term, estimate, p.value) %>%
  filter(term != "(Intercept)")
lmm_res$AptName <- analyte_info$AptName[match(lmm_res$protein, analyte_info$AptName)]
lmm_res$protein <- analyte_info$UniProt[match(lmm_res$AptName, analyte_info$AptName)]
lmm_res$Target <- analyte_info$Target[match(lmm_res$AptName, analyte_info$AptName)]
lmm_res$TargetFullName <- analyte_info$TargetFullName[match(lmm_res$AptName, analyte_info$AptName)]
lmm_res$Uniprot <- analyte_info$UniProt[match(lmm_res$AptName, analyte_info$AptName)]
lmm_res$p.value.adj <- p.adjust(lmm_res$p.value, method = "BH")
lmm_res <- lmm_res %>% arrange(p.value.adj)
openxlsx::write.xlsx(lmm_res, file = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/Teen LABS proteins SBP.xlsx")
lmm_res_reduced <- lmm_res %>% filter(term %in% seq_include)
lmm_res_reduced$p.value.adj <- NULL
openxlsx::write.xlsx(lmm_res_reduced, file = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/TODAY top HTN proteins vs. Teen LABS SBP.xlsx")

v <- volcano(lmm_res)
ggsave(
  filename = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results//Figures/SBP_volcano.jpeg", plot = v,
  width = 1600, height = 900, units = "px", scale = 2
)
```

```{r,echo=FALSE}
# test association over time of top HTN proteins with DBP
seqs <- analyte_info$AptName
# Parallel processing
cl <- makeForkCluster(8)
rows <- parLapply(cl, seqs, function(y) {
  f <- as.formula(paste0("dbp ~", y))
  m <- lme(f, random = ~1|record_id, data = df, na.action = na.omit)
  #res <- coef(summary(m))[4,]
  res <- tidy(m, effects = "fixed")
  res$protein <- y
  return(res)
})
stopCluster(cl)
# Save results
lmm_res <- data.frame(do.call(rbind, rows)) %>%
  dplyr::select(protein, term, estimate, p.value) %>%
  filter(term != "(Intercept)")
lmm_res$AptName <- analyte_info$AptName[match(lmm_res$protein, analyte_info$AptName)]
lmm_res$protein <- analyte_info$UniProt[match(lmm_res$AptName, analyte_info$AptName)]
lmm_res$Target <- analyte_info$Target[match(lmm_res$AptName, analyte_info$AptName)]
lmm_res$TargetFullName <- analyte_info$TargetFullName[match(lmm_res$AptName, analyte_info$AptName)]
lmm_res$Uniprot <- analyte_info$UniProt[match(lmm_res$AptName, analyte_info$AptName)]
lmm_res$p.value.adj <- p.adjust(lmm_res$p.value, method = "BH")
lmm_res <- lmm_res %>% arrange(p.value.adj)
openxlsx::write.xlsx(lmm_res, file = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/Teen LABS proteins DBP.xlsx")
lmm_res_reduced <- lmm_res %>% filter(term %in% seq_include)
lmm_res_reduced$p.value.adj <- NULL
openxlsx::write.xlsx(lmm_res_reduced, file = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/TODAY top HTN proteins vs. Teen LABS DBP.xlsx")

v <- volcano(lmm_res)
ggsave(
  filename = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results//Figures/DBP_volcano.jpeg", plot = v,
  width = 1600, height = 900, units = "px", scale = 2
)
```

