---
title: "Teen-LABS Proteomics - volcano plots"
author: "Laura Pyle"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
execute:
  echo: false
  message: false
---

```{r libraries}
#| include: false
library(limma)
library(clusterProfiler)
library(ReactomePA)
library(enrichplot)
library(Hmisc)
library(knitr)
library(tidyverse)
library(gtsummary)
library(ggpubr)
library(lmerTest)
library(parallel)
library(emmeans)
library(RColorBrewer)
library(VennDiagram)
library(broom.mixed)
library(readxl)
library(dplyr)
library(stringr)
library(ggrepel)
```

```{r functions}
volcano <- function(data, lab = "Target", xcol = "log(FC)", ycol = "p value",
                    top = 6,
                    xlimit = c(-1, 1), ylimit = c(0, -log10(10e-7)),
                    xlabel = "logFC", pCutoff = 0.05, overlaps = 10,
                    log_t = F) {
  data <- as.data.frame(data)
  t <- data[data[, "q value"] <= pCutoff, ]
  if (log_t) {
    t <- t[order(abs(log(t[, xcol])), decreasing = T), ]
  } else {
    t <- t[order(abs(t[, xcol]), decreasing = T), ]
  }
  data$top <- data[, "AptName"] %in% t[1:top, "AptName"]
  data$logp <- -log10(data[, ycol])
  data$fc <- data[, xcol]
  data$sig <- data[, ycol] <= pCutoff
  p <- ggplot(data = data, aes(x = fc, y = logp, color = sig)) +
    geom_hline(yintercept = -log10(pCutoff), linetype = "dashed") +
    geom_point(size = 2) +
    geom_label_repel(
      data = data[data$top, ], aes(label = Target), color = "black",
      max.overlaps = overlaps
    ) +
    scale_color_manual(values = c("grey", "#3e6dbf")) +
    xlab(xlabel) +
    ylab(bquote(~ -Log[10] ~ italic(P))) +
    theme_bw() +
    theme(legend.position = "none")
  return(p)
}

volcano_htn <- function(data, lab = "Target", xcol = "logFC", ycol = "p value",
                    top = c("ALDOB","carboxylesterase, liver","Semaphorin-6A","IL-18 Ra","NFASC","PLXD1"),
                    xlimit = c(-1, 1), ylimit = c(0, -log10(10e-7)),
                    xlabel = "log(FC)", pCutoff = 0.05, overlaps = 10,
                    log_t = F) {
  data <- as.data.frame(data)
  t <- data[data[, "q value"] <= pCutoff, ]
  if (log_t) {
    t <- t[order(abs(log(t[, xcol])), decreasing = T), ]
  } else {
    t <- t[order(abs(t[, xcol]), decreasing = T), ]
  }
#  data$top <- data[, "AptName"] %in% t[top %in% t$Target, "AptName"]
  data$top <- data[, "AptName"] %in% t[t$Target %in% top, "AptName"]
  data$logp <- -log10(data[, ycol])
  data$fc <- data[, xcol]
  data$sig <- data[, ycol] <= pCutoff
  p <- ggplot(data = data, aes(x = fc, y = logp, color = sig)) +
    geom_hline(yintercept = -log10(pCutoff), linetype = "dashed") +
    geom_point(size = 4) +
    geom_label_repel(
      data = data[data$top, ], aes(label = Target), color = "black",
      max.overlaps = overlaps, min.segment.length = 0, segment.color="red", label.size = 0.75
    ) +
    scale_color_manual(values = c("grey", "#3e6dbf")) +
    xlab(xlabel) +
    ylab(bquote(~ -Log[10] ~ italic(P))) +
    theme_bw() +
    theme(legend.position = "none")
  return(p)
}

```

```{r clean data}
df_m6 <- readxl::read_xlsx("/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/Teen LABS change_from_m1.xlsx", sheet = "visitMonth 6")
df_y1 <- readxl::read_xlsx("/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/Teen LABS change_from_m1.xlsx", sheet = "visitYear 1")
df_y2 <- readxl::read_xlsx("/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/Teen LABS change_from_m1.xlsx", sheet = "visitYear 2")
df_y3 <- readxl::read_xlsx("/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/Teen LABS change_from_m1.xlsx", sheet = "visitYear 3")
df_y4 <- readxl::read_xlsx("/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/Teen LABS change_from_m1.xlsx", sheet = "visitYear 4")
df_y5 <- readxl::read_xlsx("/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/Teen LABS change_from_m1.xlsx", sheet = "visitYear 5")
```

# Change from month 1 to month 6

```{r, include=FALSE}
v_m6 <- volcano_htn(df_m6)
ggsave(
  filename = "/Users/pylell/Dropbox/2024 Posters and Presentations/Resources (templates:previous presentations:posters)/Teen-LABS volcano plots/volcano_month6.jpeg",
  plot = v_m6, width = 1600, height = 900, units = "px", scale = 2.5
)
```

```{r, echo=FALSE, warning=FALSE}
v_m6
```

# Change from month 1 to year 1

```{r, include=FALSE}
v_y1 <- volcano_htn(df_y1)
ggsave(
  filename = "/Users/pylell/Dropbox/2024 Posters and Presentations/Resources (templates:previous presentations:posters)/Teen-LABS volcano plots/volcano_year1.jpeg",
  plot = v_y1, width = 1600, height = 900, units = "px", scale = 2.5
)
```

```{r, echo=FALSE, warning=FALSE}
v_y1
```

# Change from month 1 to year 2

```{r, include=FALSE}
v_y2 <- volcano_htn(df_y2)
ggsave(
  filename = "/Users/pylell/Dropbox/2024 Posters and Presentations/Resources (templates:previous presentations:posters)/Teen-LABS volcano plots/volcano_year2.jpeg",
  plot = v_y2, width = 1600, height = 900, units = "px", scale = 2.5
)
```

```{r, echo=FALSE, warning=FALSE}
v_y2
```

# Change from month 1 to year 3

```{r, include=FALSE}
v_y3 <- volcano_htn(df_y3)
ggsave(
  filename = "/Users/pylell/Dropbox/2024 Posters and Presentations/Resources (templates:previous presentations:posters)/Teen-LABS volcano plots/volcano_year3.jpeg",
  plot = v_y3, width = 1600, height = 900, units = "px", scale = 2.5
)
```

```{r, echo=FALSE, warning=FALSE}
v_y3
```

# Change from month 1 to year 4

```{r, include=FALSE}
v_y4 <- volcano_htn(df_y4)
ggsave(
  filename = "/Users/pylell/Dropbox/2024 Posters and Presentations/Resources (templates:previous presentations:posters)/Teen-LABS volcano plots/volcano_year4.jpeg",
  plot = v_y4, width = 1600, height = 900, units = "px", scale = 2.5
)
```

```{r, echo=FALSE, warning=FALSE}
v_y4
```

# Change from month 1 to year 5

```{r, include=FALSE}
v_y5 <- volcano_htn(df_y5)
ggsave(
  filename = "/Users/pylell/Dropbox/2024 Posters and Presentations/Resources (templates:previous presentations:posters)/Teen-LABS volcano plots/volcano_year5.jpeg",
  plot = v_y5, width = 1600, height = 900, units = "px", scale = 2.5
)
```

```{r, echo=FALSE, warning=FALSE}
v_y5
```
