---
title: "Teen-LABS IGF boxplots"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r libraries,echo=FALSE, include=F}
library(knitr)
library(tidyverse)
library(Hmisc)
library(readxl)
library(RColorBrewer)
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
```

```{r clean data,echo=FALSE}
# source("/Users/timvigers/GitHub/CHCO-Code/Petter Bjornstad/Teen-LABS/create_teen_labs_analysis_dataset.R")
load("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Data_Cleaned/analysis_dataset.RData")

# keep only the proteins we need
analyte_igf <- analyte_info %>% filter(UniProt %in% c("P05019","P17936","P35858","P01241","P18065","P22692","P24593",
                                                         "P10912","P08833","P24592","P01019"))
apt_keep <- analyte_igf$AptName
#df_igf <- df %>% select(all_of(apt_keep))
#df_igf <- cbind(df$ID, df$visit, df_igf)
#colnames(df_igf[,1:2]) <- c ("ID","visit")

# calculate log of ratio of upregulated IGF1 aptamer and IGFBP3
df$igf1_igfbp3 <- log(exp(df$seq.2952.75)/exp(df$seq.2571.12))

# read in estimated marginal means
emmdf <- read_xlsx("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/Teen LABS emmeans.xlsx")
emmdf_keep <- emmdf %>% filter(UniProt %in% c("P08833","P24593","P18065","P10912"))
emmdf_keep$uniqname <- paste0(emmdf_keep$Target,"_",emmdf_keep$AptName)  

```

# Figure for VSG MS

```{r,echo=FALSE}
p <- ggplot(emmdf_keep, aes(x=visit, y=emmean, colour=Target, group=uniqname)) +
    geom_line() + 
    geom_errorbar(aes(ymin=emmean-SE, ymax=emmean+SE), width=.1) +  
    xlab("") +
    ylab("Estimated marginal mean") + theme_bw() +
    scale_color_brewer(palette = "Dark2")

p
```

# All IGF proteins

```{r,echo=FALSE}
p <- ggplot(df,aes(visit,seq.13741.36))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.13741.36))
p

p <- ggplot(df,aes(visit,seq.14088.38))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.14088.38))
p

p <- ggplot(df,aes(visit,seq.19581.15))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.19581.15))
p

p <- ggplot(df,aes(visit,seq.22985.160))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.22985.160))
p

p <- ggplot(df,aes(visit,seq.2570.72))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2570.72))
p

p <- ggplot(df,aes(visit,seq.2571.12))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2571.12))
p

p <- ggplot(df,aes(visit,seq.2685.21))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2685.21))
p

p <- ggplot(df,aes(visit,seq.2686.67))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2686.67))
p

p <- ggplot(df,aes(visit,seq.2771.35))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2771.35))
p

p <- ggplot(df,aes(visit,seq.2948.58))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2948.58))
p

p <- ggplot(df,aes(visit,seq.2950.57))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2950.57))
p

p <- ggplot(df,aes(visit,seq.2952.75))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.2952.75))
p

p <- ggplot(df,aes(visit,seq.6605.17))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.6605.17))
p

p <- ggplot(df,aes(visit,seq.8406.17))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.8406.17))
p

p <- ggplot(df,aes(visit,seq.8462.18))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.8462.18))
p

p <- ggplot(df,aes(visit,seq.8469.41))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.8469.41))
p

p <- ggplot(df,aes(visit,seq.8819.3))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.8819.3))
p

p <- ggplot(df,aes(visit,seq.3484.60))+geom_boxplot(aes(fill=visit)) + ylab(label(df$seq.3484.60))
p

p <- ggplot(df,aes(visit,igf1_igfbp3))+geom_boxplot(aes(fill=visit)) + ylab("log(IGF1/IGFBP3)")
p

p <- ggplot(df,aes(visit,exp(igf1_igfbp3)))+geom_boxplot(aes(fill=visit)) + ylab("IGF1/IGFBP3")
p
```

```{r}
file.copy("/Users/pylell/Documents/GitHub/CHCO-Code/Petter Bjornstad/Teen-LABS/Teen-LABS_soma_igf_boxplots.html",
          "/Users/pylell/Dropbox/IMPROVE, Teen-LABS, TODAY combined analysis/Teen-LABS results/Proteomics/Teen-LABS_soma_igf_boxplots.html",overwrite = TRUE)

```
