---
title: "Teen-LABS Somascan analysis"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
    code_folding: hide
---

```{r libraries}
#| include: false
library(limma)
library(clusterProfiler)
library(ReactomePA)
library(enrichplot)
library(Hmisc)
library(knitr)
library(tidyverse)
library(gtsummary)
library(ggpubr)
library(nlme)
library(parallel)
library(emmeans)
library(RColorBrewer)
library(VennDiagram)
library(broom.mixed)
library(ggrepel)
#library(xlsx)
```

```{r clean data}
# source("/Users/timvigers/GitHub/CHCO-Code/Petter Bjornstad/Teen-LABS/create_teen_labs_analysis_dataset.R")
load("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Data_Cleaned/analysis_dataset.RData")
# Tim already log transformed proteins when creating dataframe
df$map <- NA
for (i in 1:nrow(df)) {
  df[i,]$map <- df[i,]$dbp + ((1/3) * (df[i,]$sbp - df[i,]$dbp))
}

# export baseline and 1 year data for Jeet
jeet <- df %>% dplyr::select(ID, visit, contains("seq")) %>% dplyr::filter(visit %in% c("Month 1", "Year 1"))
write.csv(jeet, "/Users/pylell/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Jeet/teen_labs_proteomics_jeet.csv")
write.csv(analyte_info, "/Users/pylell/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Jeet/analyte_info.csv")

# create new variable for UACR in mg/g
df$CREAU_g_dL <- df$CREAU / 1000
df$UACRATIO_mg_g <- df$ALBU / df$CREAU_g_dL  
label(df$UACRATIO_mg_g) <- "UACR (mg/g)"

# recode visit as numeric
df$visnum <-  
  case_when(
  df$visit == "Month 1" ~ 1,
  df$visit == "Month 6" ~ 6,
  df$visit == "Year 1" ~ 12,
  df$visit == "Year 2" ~ 24,
  df$visit == "Year 3" ~ 36,
  df$visit == "Year 4" ~ 48,
  df$visit == "Year 5" ~ 60,
  .default = NA
)

```

```{r functions}
scaleFUN <- function(x) sprintf("%.2f", x)

# Volcano plot
volcano <- function(data, lab = "Target", xcol = "estimate", ycol = "p.value",
                    top = 15,
                    xlimit = c(-1, 1), ylimit = c(0, -log10(10e-7)),
                    xlabel = "Beta", pCutoff = 0.05, overlaps = 50,
                    log_t = F) {
  data <- as.data.frame(data)
  t <- data[data[, "p.value.adj"] <= pCutoff, ]
  if (log_t) {
    t <- t[order(abs(log(t[, ycol])), decreasing = F), ]
  } else {
    t <- t[order(abs(t[, ycol]), decreasing = F), ]
  }
  data$top <- data[, "AptName"] %in% t[1:top, "AptName"]
  #data$top <- data[, "AptName"] %in% t[t$Target %in% top, "AptName"]
  data$logp <- -log10(data[, ycol])
  data$fc <- data[, xcol]
  data$sig <- data[, ycol] <= pCutoff
  p <- ggplot(data = data, aes(x = fc, y = logp, color = sig)) +
    geom_hline(yintercept = -log10(pCutoff), linetype = "dashed") +
    geom_point(size = 2.5) +
    geom_label_repel(
      data = data[data$top, ], aes(label = Target), color = "black",
      max.overlaps = overlaps
    ) +
    scale_color_manual(values = c("grey", "#3e6dbf")) +
    xlab(xlabel) + scale_x_continuous(labels = scaleFUN) +
    ylab(bquote(~ -Log[10] ~ italic(P))) +
    theme_bw() +
    theme(legend.position = "none")
  return(p)
}
```

## Longitudinal mixed models

```{r}
seqs <- analyte_info$AptName
# Parallel processing
cl <- makeForkCluster(8)
rows <- parLapply(cl, seqs, function(y) {
  f <- as.formula(paste0("bmi ~", y))
  m <- lme(f, random = ~1|ID, data = df, na.action = na.omit)
  #res <- coef(summary(m))[4,]
  res <- tidy(m, effects = "fixed")
  res$protein <- y
  return(res)
})
stopCluster(cl)
# Save results
lmm_res <- data.frame(do.call(rbind, rows)) %>%
  dplyr::select(protein, term, estimate, p.value) %>%
  filter(term != "(Intercept)")
lmm_res$AptName <- analyte_info$AptName[match(lmm_res$protein, analyte_info$AptName)]
lmm_res$protein <- analyte_info$UniProt[match(lmm_res$AptName, analyte_info$AptName)]
lmm_res$Target <- analyte_info$Target[match(lmm_res$AptName, analyte_info$AptName)]
lmm_res$TargetFullName <- analyte_info$TargetFullName[match(lmm_res$AptName, analyte_info$AptName)]
lmm_res$Uniprot <- analyte_info$UniProt[match(lmm_res$AptName, analyte_info$AptName)]
lmm_res$p.value.adj <- p.adjust(lmm_res$p.value, method = "BH")
lmm_res <- lmm_res %>% arrange(p.value.adj)
openxlsx::write.xlsx(lmm_res, file = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results/Teen LABS proteins BMI.xlsx")

v <- volcano(lmm_res)
ggsave(
  filename = "/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Teen Labs/Results//Figures/BMI_volcano.jpeg", plot = v,
  width = 1600, height = 900, units = "px", scale = 2
)
```

