---
title: "Teen-LABS Proteomics"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  revealjs:
    scrollable: true
    smaller: true
    self-contained: true
    theme: black
editor: source
---

```{r libraries}
#| include: false
library(tidyverse)
library(gtsummary)
library(Hmisc)
```

```{r import cleaned data}
load("/Volumes/Peds Endo/Petter Bjornstad/Teen Labs/Data_Cleaned/analysis_dataset.RData")
```

## Table 1: Participant characteristics

```{r}
df %>%
  select(
    SEX, age, ETHN, RACE, SURG, diab, diab_resolved, sbp, dbp, hrate, bfat, bmi,
    weight, height, UACRATIO, albuminuria, CYSC, visit
  ) %>%
  tbl_summary(by = visit, missing_text = "Missing") %>%
  modify_header(label = "**Visit**") %>%
  bold_labels() %>%
  as_kable_extra()
```

# Spaghetti plots!

```{r}
spagett <- function(dataframe = df, outcome) {
  p = ggplot(dataframe,aes(x=months,y=.data[[outcome]],color=ID,group = ID)) + 
    geom_point(alpha=0.5) + geom_line(alpha=0.5) +
    ylab(label(dataframe[,outcome])) + xlab("Months") +
    theme_bw() +
    theme(legend.position = "none") 
  return(p)
}
```

## Weight

```{r}
spagett(outcome = "weight")
```

## NELL1

```{r}
spagett(outcome = "seq.6544.33")
```


```{r Laura code}
#| eval: false
# get the names of proteins
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(dat))

# create df of proteins at month 1 and year 1 and take difference
dat_mo1 <- dat[dat$visit=="Month 1",]
dat_yr1 <- dat[dat$visit=="Year 1",]
dat_yr1 <- dat_yr1 %>% filter(dat_yr1$id %in% dat_mo1$id)
dat_mo1 <- dat_mo1 %>% filter(dat_mo1$id %in% dat_yr1$id)
dat_mo1 <- dat_mo1[,seq]
dat_yr1 <- dat_yr1[,seq]
dat_mo1 <- apply(dat_mo1,2,as.numeric)
dat_yr1 <- apply(dat_yr1,2,as.numeric)
dat_diff <- dat_yr1 - dat_mo1
```
