---
title: "TODAY urine metabolomics baseline analyses - Cox models"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)
library(survival)
library(broom)
library(stringr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
}
knitr::opts_knit$set(root.dir = home_dir)
setwd(home_dir)
```

```{r, include=FALSE}
load("./Metabolomic data/urine.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# take only the baseline samples
urine$Date.Drawn <- as.Date(urine$Date.Drawn,format = "%m/%d/%Y")
base <- urine %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)
base <- base %>% arrange(Date.Drawn)

# merge in nephropathy data
base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("nM/mM", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# are there proteins with low variability?
no_var = caret::nearZeroVar(base[,seq])
# none

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)

# scale by SD
base_log_scale <- base_log
predictors <- colnames(base_log[seq])
for (i in 1:length(predictors)) {
  base_log_scale[predictors[i]] <- base_log_scale[predictors[i]]/sd(base_log[,paste0(predictors[i])])
}

# now we need to change the format of the variable names
temp <- str_replace_all(colnames(base_log_scale[,seq]),"/","_")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"-","_")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"3","Three")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"2","Two")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"\\(s\\)","s")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"5","Five")
colnames(base_log_scale)[seq] <- temp
```

```{r, include=FALSE}
# Macroalbuminuria
result_MAC <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTOMAC, MAC)~",predictors[i])
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  result_MAC <- rbind(result_MAC,tidymod)
}
result_MAC$adj.p.value <- p.adjust(result_MAC$p.value, "fdr")
result_MAC <- result_MAC[order(result_MAC$p.value),] 

# Microalbuminuria
result_MIC <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTOMIC, MIC)~",predictors[i])
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  result_MIC <- rbind(result_MIC,tidymod)
}
result_MIC$adj.p.value <- p.adjust(result_MIC$p.value, "fdr")
result_MIC <- result_MIC[order(result_MIC$p.value),] 

# hyperfiltration
result_HYP <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTOHYP, HYP)~",predictors[i])
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  result_HYP <- rbind(result_HYP,tidymod)
}
result_HYP$adj.p.value <- p.adjust(result_HYP$p.value, "fdr")
result_HYP <- result_HYP[order(result_HYP$p.value),] 

# rapid eGFR decline
result_RAPID <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTORAPID, RAPID)~",predictors[i])
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  result_RAPID <- rbind(result_RAPID,tidymod)
}
result_RAPID$adj.p.value <- p.adjust(result_RAPID$p.value, "fdr")
result_RAPID <- result_RAPID[order(result_RAPID$p.value),] 

# hypertension
result_HTN <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTOHTN, HTN)~",predictors[i])
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  result_HTN <- rbind(result_HTN,tidymod)
}
result_HTN$adj.p.value <- p.adjust(result_HTN$p.value, "fdr")
result_HTN <- result_HTN[order(result_HTN$p.value),] 

# neuropathy
result_NEURO <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTONEURO, NEURO)~",predictors[i])
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  result_NEURO <- rbind(result_NEURO,tidymod)
}
result_NEURO$adj.p.value <- p.adjust(result_NEURO$p.value, "fdr")
result_NEURO <- result_NEURO[order(result_NEURO$p.value),] 

# retinopathy
result_RETINO <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTORETINO, RETINO)~",predictors[i])
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  result_RETINO <- rbind(result_RETINO,tidymod)
}
result_RETINO$adj.p.value <- p.adjust(result_RETINO$p.value, "fdr")
result_RETINO <- result_RETINO[order(result_RETINO$p.value),] 

# glycemic failure
result_GLYC <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTOGLYC, GLYC)~",predictors[i])
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  result_GLYC <- rbind(result_GLYC,tidymod)
}
result_GLYC$adj.p.value <- p.adjust(result_GLYC$p.value, "fdr")
result_GLYC <- result_GLYC[order(result_GLYC$p.value),] 

# write all results to file
setwd(home_dir)
wb <- createWorkbook()
addWorksheet(wb,"MAC CPH")
writeData(wb,"MAC CPH",result_MAC,rowNames = F)
addWorksheet(wb,"MIC CPH")
writeData(wb,"MIC CPH",result_MIC,rowNames = F)
addWorksheet(wb,"HYP CPH")
writeData(wb,"HYP CPH",result_HYP,rowNames = F)
addWorksheet(wb,"RAPID CPH")
writeData(wb,"RAPID CPH",result_RAPID,rowNames = F)
addWorksheet(wb,"HTN CPH")
writeData(wb,"HTN CPH",result_HTN,rowNames = F)
addWorksheet(wb,"NEURO CPH")
writeData(wb,"NEURO CPH",result_NEURO,rowNames = F)
addWorksheet(wb,"RETINO CPH")
writeData(wb,"RETINO CPH",result_RETINO,rowNames = F)
addWorksheet(wb,"GLYC CPH")
writeData(wb,"GLYC CPH",result_GLYC,rowNames = F)
saveWorkbook(wb,"./Results/Metabolomics Linear and Cox models/TODAY urine metabolomics Cox models scaled baseline unadjusted.xlsx",overwrite = TRUE)


```

# Results

Need to remember that the interpretation of the hazard ratios is as follows: for a one SD increase in the log of seqXXX, the risk is multiplied by....

```{r echo=FALSE, include=TRUE}

```
