---
title: "TODAY plasma metabolomics baseline analyses - Cox models with PLS variable selection"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)
library(survival)
library(broom)
library(stringr)
library(plsRcox)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/Peds Endo/Petter Bjornstad/TODAY subaward/"
}
knitr::opts_knit$set(root.dir = home_dir)
setwd(home_dir)
```

```{r, include=FALSE}
load("./Metabolomic data/plasma.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# load baseline risk factors
load("./Clinical data/TODAY/baserisk.Rdata")

# take only the baseline samples
plasma$Date.Drawn <- as.Date(plasma$Date.Drawn,format = "%m/%d/%Y")
base <- plasma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)
base <- base %>% arrange(Date.Drawn)

# merge in complication data
base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# merge in baseline risk factors
base <- merge(base, baserisk, by="releaseid",all.x=T, all.y=F)

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("uM", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# are there proteins with low variability?
no_var = caret::nearZeroVar(base[,seq])
base <- base[,-no_var]
# other metabolites have zero variance
base <- base %>% select(!Adenine.in.uM)
base <- base %>% select(!`DL-Homocystine.in.uM`)
base <- base %>% select(!Sulpiride.in.uM)
base <- base %>% select(!Nicotinic_acid.in.uM)
base <- base %>% select(!Quinolinic.Acid.in.uM)
base <- base %>% select(!`5-Hydroxyindoleacetic.Acid.in.uM`)
seq <- is_seq(names(base))

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)

# scale by SD
base_log_scale <- base_log
predictors <- colnames(base_log[seq])
for (i in 1:length(predictors)) {
  base_log_scale[predictors[i]] <- base_log_scale[predictors[i]]/sd(base_log[,paste0(predictors[i])])
}

# now we need to change the format of the variable names
temp <- str_replace_all(colnames(base_log_scale[,seq]),"/","_")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"-","_")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"3","Three")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"2","Two")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"\\(s\\)","s")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"5","Five")
colnames(base_log_scale)[seq] <- temp

base_log_scale$DAYSTOMAC <- as.numeric(base_log_scale$DAYSTOMAC)
base_log_scale$MAC <- as.numeric(base_log_scale$MAC)
```

## Refit model for MAC with variables selected by PLS

```{r, include=FALSE}
set.seed(3654)
plscox_MAC <- plsRcoxmodel(Xplan = base_log_scale[seq], time=base_log_scale$DAYSTOMAC, time2=base_log_scale$MAC, 
                           type="right", scaleX = FALSE, scaleY = FALSE, sparse=TRUE,nt=2)
coefs_sig <- plscox_MAC$Coeffs[!plscox_MAC$Coeffs==0,]
names_sig <- names(coefs_sig)
names_sig <- paste(names_sig,collapse=" + ")
# relaxed PLS - fit model with retained variables
form <- paste("Surv(DAYSTOMAC, MAC)~",names_sig)
final_mod_MAC <- coxph(data = base_log_scale, formula = as.formula(form))
```

```{r, include=TRUE, comment=""}
# concordance is the same as Harrell's C
summary(final_mod_MAC)
```

## Refit model for MAC and adjust for HbA1c, trig, SBP, and SI

```{r, include=FALSE}
form <- paste("Surv(DAYSTOMAC, MAC)~",names_sig,"+HbA1c+log_trig+sbp+si_1_ins0")
final_mod_MAC_adj <- coxph(data = base_log_scale, formula = as.formula(form))
```

```{r, include=TRUE, comment=""}
# concordance is the same as Harrell's C
summary(final_mod_MAC_adj)
```

## Refit model for MIC with variables selected by PLS

```{r, include=FALSE}
plscox_MIC <- plsRcoxmodel(Xplan = base_log_scale[seq], time=base_log_scale$DAYSTOMIC, time2=base_log_scale$MIC, 
                           type="right", scaleX = FALSE, scaleY = FALSE, sparse=TRUE,nt=2)
coefs_sig <- plscox_MIC$Coeffs[!plscox_MIC$Coeffs==0,]
names_sig <- names(coefs_sig)
names_sig <- paste(names_sig,collapse=" + ")
# relaxed PLS - fit model with retained variables
form <- paste("Surv(DAYSTOMIC, MIC)~",names_sig)
final_mod_MIC <- coxph(data = base_log_scale, formula = as.formula(form))
```

```{r, include=TRUE, comment=""}
# concordance is the same as Harrell's C
summary(final_mod_MIC)
```

## Refit model for MIC and adjust for HbA1c, trig, SBP, and SI

```{r, include=FALSE}
form <- paste("Surv(DAYSTOMIC, MIC)~",names_sig,"+HbA1c+log_trig+sbp+si_1_ins0")
final_mod_MIC_adj <- coxph(data = base_log_scale, formula = as.formula(form))
```

```{r, include=TRUE, comment=""}
# concordance is the same as Harrell's C
summary(final_mod_MIC_adj)
```


