---
title: "ATTEMPT Ancillary"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    embed-resources: true
editor: visual
---

```{r libraries, echo=F, include = F}
library(tidyverse)
library(arsenal)
library(dplyr)
library(REDCapR)
library(lubridate)
```

```{r load-data, echo = F, include = F}
# Load dictionary function and file
source("/Users/choiyej/GitHub/YC_CHCO/R Functions/label_harmonized_function.R")

token_dat <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/api_tokens.csv")
attempt_token <- token_dat$Token[token_dat$Study == "ATTEMPT"]
attempt_dat <- redcap_read(redcap_uri = "https://redcap.ucdenver.edu/api/",
                           token = attempt_token)
```

```{r echo = F, include=F}
race_names <- c(
  "American Indian or Alaskan Native",
  "Asian",
  "Hawaiian or Pacific Islander",
  "Black or African American",
  "White",
  "Unknown",
  "Other"
)
ethnicity_names <- c(
  "Hispanic",
  "Non-Hispanic",
  "Unknown")

dat <- attempt_dat$data %>%
  group_by(subject_id) %>%
  fill(everything(), .direction = "down") %>%
  ungroup() %>% rowwise() %>%
  dplyr::mutate(redcap_event_name = case_when(redcap_event_name == "visit_2_arm_1" ~ "Visit 2",
                                              redcap_event_name == "visit_3_arm_1" ~ "Visit 3",
                                              T ~ "Screening"),
                age = case_when(is.na(bx_date) ~ age_consent,
                                T ~ as.integer((bx_date - dob) / dyears(1))),
                race = case_when(sum(c_across(starts_with("race___")), na.rm = TRUE) == 0 ~ "Unknown",
                                 sum(c_across(starts_with("race___")), na.rm = TRUE) > 1 ~ "More than one race",
                                 race___1 == 1 ~ race_names[1],
                                 race___2 == 1 ~ race_names[2],
                                 race___3 == 1 ~ race_names[3],
                                 race___4 == 1 ~ race_names[4],
                                 race___5 == 1 ~ race_names[5],
                                 race___6 == 1 ~ race_names[6],
                                 race___7 == 1 ~ race_names[7]),
                ethnicity = case_when(sum(c_across(starts_with("ethnicity___")), na.rm = TRUE) == 0 ~ "Unknown",
                                 sum(c_across(starts_with("ethnicity___")), na.rm = TRUE) > 1 ~ "More than one ethnicity",
                                 ethnicity___1 == 1 ~ ethnicity_names[1],
                                 ethnicity___2 == 1 ~ ethnicity_names[2],
                                 ethnicity___3 == 1 ~ ethnicity_names[3]),
                diabetes_duration = case_when(redcap_event_name == "Screening" ~ as.integer((consent_date - t1d_date) / dyears(1)),
                                              T ~ as.integer((bx_date - t1d_date) / dyears(1))))

```

```{r echo = F, results='asis'}
summary(tableby(redcap_event_name ~ age + sex + race + ethnicity + diabetes_duration + vitals_height + vitals_weight + vitals_bmi + vitals_sbp + vitals_dbp + vitals_pulse + vitals_rr + vitals_temp +  pt_ + inr + ptt + bun + abo + abo_rh + hgb + hct + plt + creat , data = dat), test = F, total = F)
```
