---
title: "ATTEMPT Denver Descriptives"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    embed-resources: true
---

```{r libraries, echo=F, include = F}
library(tidyverse)
library(arsenal)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(readxl)
library(purrr)
source("/Users/choiyej/GitHub/YC_CHCO/R Functions/label_harmonized_function.R")
```

```{r load-data, echo = F, include = F, message=FALSE}
attempt_file = "/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/ATTEMPT/Data Raw/ATTEMPT_AnalyticalDatasets_Denver.xlsx"
attempt_mri_file = "/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/ATTEMPT/Data Raw/ATTEMPT_MRI_SK_LHSC_TorontoLondon.csv"
attempt_mri_labs_file = "/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/ATTEMPT/Data Raw/ATTEMPT_MRI_HCT_SBP_TorontoLondon.csv"
attempt_file_031425 = "/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/ATTEMPT/Data Raw/ATTEMPT_DenverDataRequest_20250314.csv"

# non-Denver data formatting to match
attempt_mri <- read.csv(attempt_mri_file) %>%
  dplyr::rename(mri_r2_kidney_r = rk_r2s_mean,
                mri_r2_cortex_r = rc_r2s_mean,
                mri_r2_kidney_l = lk_r2s_mean,
                mri_r2_cortex_l = lc_r2s_mean) %>%
  dplyr::mutate(mri_date = as.Date(mri_date, format = "%m/%d/%y"),
                site = case_when(subject_id < 20000 ~ "Toronto",
                                 subject_id < 30000 ~ "London"))
attempt_mri_labs <- read.csv(attempt_mri_labs_file) %>%
  dplyr::mutate(mri_date = as.Date(mri_date, format = "%m/%d/%y"),
                date_visit = as.Date(date_visit, format = "%m/%d/%y"))

dict <- read_excel(attempt_file, sheet = "Data Dictionary", na = c("NA", "")) %>%
  select(Variable_Name, Label) %>%
  as.data.frame() 

demo <- read_excel(attempt_file, sheet = "ATTEMPT_Demographics", na = c("NA", ""))
anthro <- read_excel(attempt_file, sheet = "ATTEMPT_Anthropometrics", na = c("NA", ""))
medfamsmoking <- read_excel(attempt_file, sheet = "ATTEMPT_MedFamSmokingHx", na = c("NA", ""))
diabetesman <- read_excel(attempt_file, sheet = "ATTEMPT_DiabetesManagement", na = c("NA", ""))
glucosemon <- read_excel(attempt_file, sheet = "ATTEMPT_GlucoseMonitoring", na = c("NA", ""))
urinelab <- read_excel(attempt_file, sheet = "ATTEMPT_LocalUrineLabs", na = c("NA", ""))
urine_24h <- read_excel(attempt_file, sheet = "ATTEMPT_Urine24h", na = c("NA", "")) %>%
  mutate(date_visit = urine24h_start_date,
         urine24h_start_time = format(as.POSIXct(urine24h_start_time), "%H:%M"),
         urine24h_stop_time = format(as.POSIXct(urine24h_stop_time), "%H:%M"))
urineemu <- read_excel(attempt_file, sheet = "ATTEMPT_UrineEMU", na = c("NA", ""))
bloodlab_local <- read_excel(attempt_file, sheet = "ATTEMPT_LocalBloodLabs", na = c("NA", ""))
bloodlab_central <- read_excel(attempt_file, sheet = "ATTEMPT_CentralBloodLabs", na = c("NA", ""))
compliance <- read_excel(attempt_file, sheet = "ATTEMPT_Compliance", na = c("NA", ""))
egfr <- read_excel(attempt_file, sheet = "ATTEMPT_eGFR", na = c("NA", ""))
mgfr <- read_excel(attempt_file, sheet = "ATTEMPT_mGFR", na = c("NA", ""))
mri <- read_excel(attempt_file, sheet = "ATTEMPT_BoldMRI", na = c("NA", "")) %>%
  bind_rows(attempt_mri)
randomization <- read_excel("/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/ATTEMPT/Data Raw/ATTEMPT_Randomization_Denver.xlsx",
                            sheet = "ATTEMPT_Randomization", na = c("NA", ""))
attempt_031425 <- read.csv(attempt_file_031425) %>%
  dplyr::mutate(date_visit = as.Date(date_visit, format = "%m/%d/%y"),
                urine24h_start_date = as.Date(urine24h_start_date, format = "%m/%d/%y"),
                urine24h_stop_date = as.Date(urine24h_stop_date, format = "%m/%d/%y"),
                target_glucose_low_mmoll = case_when(target_glucose_low_mmoll == "<10"  ~ "10",
                                                     T ~ target_glucose_low_mmoll),
                target_glucose_low_mmoll = as.numeric(target_glucose_low_mmoll),
                target_glucose_high_mmoll = case_when(target_glucose_high_mmoll == "<10"  ~ "10",
                                                      T ~ target_glucose_high_mmoll),
                target_glucose_high_mmoll = as.numeric(target_glucose_high_mmoll), 
                across(starts_with("emu_1_a"), as.character),
                across(starts_with("emu_2_a"), as.character),
                across(starts_with("emu_3_a"), as.character),
                across(starts_with("emu_urine"), as.character),
                across(where(~ any(grepl("^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$", .))), 
                       ~ format(as.POSIXct(.), "%H:%M")),
                urine24h_volume_litres = as.character(urine24h_volume_litres),
                urine24h_volume_24h_litres = as.character(urine24h_volume_24h_litres)) %>%
  dplyr::rename("age_baseline"="age")

data_frames <- list(
  demo = demo, randomization = randomization, anthro = anthro, 
  medfamsmoking = medfamsmoking, diabetesman = diabetesman, 
  glucosemon = glucosemon, urinelab = urinelab, 
  urineemu = urineemu, urine_24h = urine_24h, 
  bloodlab_local = bloodlab_local, 
  bloodlab_central = bloodlab_central, compliance = compliance, 
  egfr = egfr, mgfr = mgfr, mri = mri, attempt_mri_labs = attempt_mri_labs,
  attempt_031425)

data_frames <- lapply(data_frames, function(df) {
  df %>%
    mutate(visit = case_when(str_detect(visit, "V1|V2|R1") ~ "PRE",
                             str_detect(visit, "V3") ~ "Safety",
                             str_detect(visit, "V4|V5|R3") ~ "POST"))
})


```

```{r echo = F, warning = F, message = F}
# Define categories
# Race
eth_names <- c("White",
               "Black",
               "Latin / South American",
               "Arab / West Asian",
               "Japanese / Korean / Filipino",
               "South East Asian",
               "Mixed")

merged_data <- purrr::reduce(data_frames, ~ full_join(.x, .y)) %>%
  group_by(subject_id, visit) %>%
  fill(-c(visit), .direction = "downup") %>%
  ungroup() %>% rowwise() %>%
  dplyr::mutate(across(where(is.logical), ~ ifelse(.x, "Yes", "No")),
                across(where(~ any(grepl("^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$", .))), 
                       ~ format(as.POSIXct(.), "%H:%M")),
                ethnicity = case_when(ethnicity_categorized == 1 ~ eth_names[1], 
                                      ethnicity_categorized == 2 ~ eth_names[2],
                                      ethnicity_categorized == 3 ~ eth_names[3], 
                                      ethnicity_categorized == 4 ~ eth_names[4], 
                                      ethnicity_categorized == 5 ~ eth_names[5], 
                                      ethnicity_categorized == 6 ~ eth_names[6], 
                                      ethnicity_categorized == 7 ~ eth_names[7]),
                sex = case_when(sex == 1  ~ "Male", sex == 2 ~ "Female"),
                treatment_arm = case_when(treatment_arm == "A" ~ "Placebo",
                                          treatment_arm == "B" ~ "Dapagliflozin 5mg",
                                          T ~ "UNK"),
                microalbumin_urine24h = case_when(microalbumin_urine24h == "< 5"  ~ "2.5",
                                                  T ~ microalbumin_urine24h),
                microalbumin_urine24h_mgL = as.numeric(microalbumin_urine24h) * 1000,
                creatinine_urine24h_gL = creatinine_urine24h * 0.11312,
                # uaer_24 = microalbumin_urine24h_mgL / creatinine_urine24h_gL,
                mri_r2_cortex_l = case_when(!is.na(mri_r2_cortex_l) ~ as.numeric(mri_r2_cortex_l)),
                mri_r2_cortex_r = case_when(!is.na(mri_r2_cortex_r) ~ as.numeric(mri_r2_cortex_r)),
                mri_r2_medulla_l = case_when(!is.na(mri_r2_cortex_l) ~ as.numeric(mri_r2_medulla_l)),
                mri_r2_medulla_r = case_when(!is.na(mri_r2_cortex_r) ~ as.numeric(mri_r2_medulla_r)),
                mri_r2_kidney_l = case_when(!is.na(mri_r2_cortex_l) ~ as.numeric(mri_r2_kidney_l)),
                mri_r2_kidney_r = case_when(!is.na(mri_r2_cortex_r) ~ as.numeric(mri_r2_kidney_r)),
                avg_c_r2 = mean(c(mri_r2_cortex_l, mri_r2_cortex_r)),
                avg_m_r2 = mean(c(mri_r2_medulla_l, mri_r2_medulla_r)),
                avg_k_r2  = mean(c(mri_r2_kidney_l, mri_r2_kidney_r)),
                hba1c = hba1c_percent*100,
                emu_1_albumin_mgl = case_when(grepl("<", emu_1_albumin_mgl) ~ "2.5",
                                              T ~ emu_1_albumin_mgl),
                emu_1_albumin_mgl = as.numeric(emu_1_albumin_mgl), 
                emu_1_acr_mgmmol = emu_1_albumin_mgl/emu_1_creatinine_umoll*1000,
                emu_2_albumin_mgl = case_when(grepl("<", emu_2_albumin_mgl) ~ "2.5",
                                              T ~ emu_2_albumin_mgl),
                emu_2_albumin_mgl = as.numeric(emu_2_albumin_mgl), 
                emu_2_acr_mgmmol = emu_2_albumin_mgl/emu_2_creatinine_umoll*1000,
                emu_3_albumin_mgl = case_when(grepl("<", emu_3_albumin_mgl) ~ "2.5",
                                              T ~ emu_3_albumin_mgl),
                emu_3_albumin_mgl = as.numeric(emu_3_albumin_mgl), 
                emu_3_acr_mgmmol = emu_3_albumin_mgl/emu_3_creatinine_umoll*1000,
                emu_urine_acr_mean = mean(c(emu_1_acr_mgmmol, emu_2_acr_mgmmol, emu_3_acr_mgmmol))) %>% ungroup() %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA, last(na.omit(.x)))),
                   across(where(is.numeric),  ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(subject_id, visit)) %>%
  filter(visit %in% c("PRE", "POST"))

merged_data$visit <- factor(merged_data$visit, levels = c("PRE", "POST"))
merged_data$treatment_arm <- factor(merged_data$treatment_arm, levels = c("Placebo", "Dapagliflozin 5mg", "UNK"))

dict <- label_harmonized_dict(merged_data, dict) %>%
  mutate(ethnicity = "Ethnicity",
         treatment_arm = "Treatment",
         # uaer_24 = "UAER (24h)",
         avg_c_r2 = "Avg cortical R2*",
         avg_m_r2 = "Avg medulla R2*",
         avg_k_r2 = "Avg kidney R2*",
         age_baseline = "Age (Baseline)",
         hba1c = "HbA1c")
merged_data <- label_harmonized(merged_data, dict)

## list of those with MRI to send to Luping (4/18/25)
# mri_complete <- merged_data %>%
#   filter(!is.na(mri_r2_cortex_r)) %>%
#   select(subject_id, visit, mri_date) %>%
#   dplyr::mutate(mri_date = as.Date(as.POSIXct(mri_date, origin = "1970-01-01", tz = "UTC"))) %>%
#   arrange(subject_id)
# write.csv(mri_complete, "/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/ATTEMPT/Data Clean/attempt_list_of_mri_ids.csv", row.names = F)
```

# Descriptive tables

### Baseline visit
```{r echo = F, results = 'asis'}
# baseline
summary(arsenal::tableby(treatment_arm ~ age_baseline + sex + ethnicity + t1d_duration +
                           weight_kg + height_m + bmi_kgm2 + bmi_percentile + 
                           sbp_mmhg	+ dbp_mmhg + hba1c + 
                           kwt(emu_urine_acr_mean, "Nmiss", "medianq1q3", "range") + 
                           egfr_ckdepi40_cr + egfr_ckidu25_cr + mgfr_si + 
                           mgfr_si_adjusted + mgfr_bm_adult + avg_c_r2 + avg_m_r2 + avg_k_r2,  
                         data = subset(merged_data, visit == "PRE")),total = F)
```

### Follow up visit
```{r echo = F, results = 'asis'}
# post treatment
summary(arsenal::tableby(treatment_arm ~ age_baseline + sex + ethnicity + t1d_duration +
                           weight_kg + height_m + bmi_kgm2 + bmi_percentile + 
                           sbp_mmhg	+ dbp_mmhg + hba1c + 
                           kwt(emu_urine_acr_mean, "Nmiss", "medianq1q3", "range") + 
                           egfr_ckdepi40_cr + egfr_ckidu25_cr + mgfr_si + 
                           mgfr_si_adjusted + mgfr_bm_adult + avg_c_r2 + avg_m_r2 + avg_k_r2,  
                         data = subset(merged_data, visit == "POST")), total = F)
```

### Placebo
```{r echo = F, results = 'asis'}
# placebo
summary(arsenal::paired(visit ~ age_baseline + sex + ethnicity + t1d_duration +
                           weight_kg + height_m + bmi_kgm2 + bmi_percentile + 
                           sbp_mmhg	+ dbp_mmhg + hba1c + 
                           signed.rank(emu_urine_acr_mean, "Nmiss", "medianq1q3", "range") + 
                           egfr_ckdepi40_cr + egfr_ckidu25_cr + mgfr_si + 
                           mgfr_si_adjusted + mgfr_bm_adult + avg_c_r2 + avg_m_r2 + avg_k_r2,  
                         data = subset(merged_data, treatment_arm == "Placebo"), id = subject_id), total = F)
```

### Dapagliflozin 5mg
```{r echo = F, results = 'asis'}
# treatment
summary(arsenal::paired(visit ~ age_baseline + sex + ethnicity + t1d_duration +
                           weight_kg + height_m + bmi_kgm2 + bmi_percentile + 
                           sbp_mmhg	+ dbp_mmhg + hba1c + 
                           signed.rank(emu_urine_acr_mean, "Nmiss", "medianq1q3", "range") + 
                           egfr_ckdepi40_cr + egfr_ckidu25_cr + mgfr_si + 
                           mgfr_si_adjusted + mgfr_bm_adult + avg_c_r2 + avg_m_r2 + avg_k_r2,  
                         data = subset(merged_data, treatment_arm == "Dapagliflozin 5mg"), id = subject_id), total = F)
```


uaer instead of uacr for 24hr collection (urine albumin*24hr volume) 
  or urine albumin or microalbumin* urine volume * 1000 / 1440
