---
title: "CROCODILE urine metabolomics"
author: "Laura Pyle, Ye Ji Choi"
date: "today"
date-format: long
execute: 
  echo: false
  warning: false
  messages: false
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
---

```{r libraries}
#| include: false
library(Seurat)
library(future)
library(tidyverse)
library(colorspace)
library(patchwork)
library(ggdendro)
library(cowplot)
library(ggpubr)
library(rstatix)
library(table1)
library(GSVA)
library(Biobase)
library(ReactomeGSA)
library(GSEABase)
library(msigdbr)
library(kableExtra)
library(knitr)
library(MetaboDiff)
```

# Import CROC data from RedCap
```{r}
load("/run/user/1023/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/CROCODILE/Data_Cleaned/croc_data.RData")
dict <- read.csv("/run/user/1023/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Data Harmonization/data_dictionary_master.csv")
source("/home/yejichoi2/Documents/CHCO-Code/Petter Bjornstad/Resources/YC/R Functions/label_harmonized_function.R")

# Blood metabolomics
blood_metab <- c("citrate", "two_oxoglutarate", "succinate", 
                 "fumarate", "malate", "aspartate",
                 "glutamate", "alanine", "arginine", "cystine", "histidine", 
                 "leucine_isoleucine", "lysine", "methionine", "phenylalanine", 
                 "proline", "serine", "thereonine",
                 "tyrosine", "valine", "glutamine")
blood_metab_tca <- c("citrate", "succinate", "fumarate", "malate")

# Spatial metabolomics
spatial_metab <- dat %>% dplyr::select(ends_with("_tissue")) %>% colnames()
spatial_metab_tca <- c("isocitric_citric_acid_tissue",
                       "aconitic_acid_tissue",
                       "succinic_acid_tissue",
                       "fumaric_acid_tissue",
                       "malic_acid_tissue", 
                       "alpha_ketoglutaric_acid_tissue",
                       "oxaloacetic_acid_tissue")

# Urine metabolomics
urine_metab <- dat %>% dplyr::select(starts_with("az_")) %>% colnames()
urine_metab_tca <- c("az_citrate_negative", 
                     "az_isocitrate_negative",
                     "az_succinate_negative",
                     "az_malate_negative",
                     "az_oxalic_acid_negative")

urine_met_dat <- dat %>%
  dplyr::mutate(dplyr::across(urine_metab_tca, ~ na_if(., 0))) %>%
  dplyr::mutate(dplyr::across(urine_metab_tca, ~ . / az_urine_creatinine_mm)) %>%
  dplyr::mutate(dplyr::across(urine_metab_tca, log))

```

## Urine metabolites in HC vs. T1D (from AZ)
```{r echo - F}
hist(dat$az_urine_creatinine_mm)
hist(log(dat$az_citrate_negative))
hist(log(dat$az_isocitrate_negative))
hist(log(dat$az_succinate_negative))
hist(log(dat$az_malate_negative))
hist(log(dat$az_oxalic_acid_negative))

summary(arsenal::tableby(group ~ az_urine_creatinine_mm +
                           az_citrate_negative + 
                           az_isocitrate_negative +
                           az_succinate_negative +
                           az_malate_negative +
                           az_oxalic_acid_negative, 
                         data = urine_met_dat), total = F)

summary(arsenal::tableby(group ~ az_urine_creatinine_mm +
                           kwt(az_citrate_negative, "Nmiss", "median", "q1q3", "range")  + 
                           kwt(az_isocitrate_negative, "Nmiss", "median", "q1q3", "range")  +
                           kwt(az_succinate_negative, "Nmiss", "median", "q1q3", "range")  +
                           kwt(az_malate_negative, "Nmiss", "median", "q1q3", "range")  +
                           kwt(az_oxalic_acid_negative, "Nmiss", "median", "q1q3", "range") , 
                         data = dat), total = F)
```

