---
title: "CROCODILE scRNA Pseudobulk"
author: "Ye Ji Choi & Laura Pyle"
date: "today"
date-format: long
execute: 
  echo: false
  warning: false
  messages: false
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
---

```{r libraries}
#| include: false
library(Seurat)
library(future)
library(tidyverse)
library(colorspace)
library(patchwork)
library(ggdendro)
library(cowplot)
library(ggtree)
library(ggpubr)
library(rstatix)
library(table1)
library(GSVA)
library(Biobase)
library(ReactomeGSA)
library(GSEABase)
library(GSVAdata)
library(msigdbr)
library(kableExtra)
library(knitr)
```

```{r}
so <- readRDS("/home/yejichoi/Documents/seurat_data_CRC.RDS")
source("/home/yejichoi/Documents/CHCO-Code/Petter Bjornstad/CROCODILE/crocodile_functions.R")
```

# Pseudobulk (PT only)
```{r}
so_pt <- subset(so, LR_clusters == "PT")
sample_id <- so_pt$michigan_id
raw_data = Seurat::GetAssayData(so_pt, assay = "RNA", slot = "counts")
av_counts <- apply(raw_data, 1, function(raw_data) {
  by(raw_data, sample_id , sum)
})
av_counts <- t(data.frame(av_counts))

group_list <- so_pt@meta.data %>% dplyr::select(michigan_id, Group) %>% distinct(michigan_id, .keep_all = T)
rownames(group_list) <- group_list$michigan_id
so_pseudobulk <- CreateSeuratObject(meta.data = group_list, counts = av_counts)
Idents(so_pseudobulk) <- so_pseudobulk$orig.ident

# Fadhl's alternative psudobulk method
so_subset <- subset(so, subset = LR_clusters %in% tubular_cells)
sample_id <- so_subset$michigan_id
raw_data = Seurat::GetAssayData(so_subset, assay = "RNA", slot = "counts")
av_counts <- apply(raw_data, 1, function(raw_data) {
  by(raw_data, sample_id, sum)
})
av_counts <- t(data.frame(av_counts))

group_list <- so@meta.data %>% dplyr::select(michigan_id, Group) %>% distinct(michigan_id, .keep_all = T)
rownames(group_list) <- group_list$michigan_id
so_subset <- CreateSeuratObject(meta.data = group_list, counts = av_counts)
Idents(so_subset) <- so_subset$orig.ident
```