---
title: "crocodile_care_t1d_analysis"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
editor: visual
---

```{r libraries}
#| include: false
library(Seurat)
library(future)
library(tidyverse)
library(colorspace)
library(patchwork)
library(ggdendro)
library(cowplot)
library(ggtree)
library(ggpubr)
library(rstatix)
library(table1)
library(GSVA)
library(Biobase)
library(ReactomeGSA)
library(GSEABase)
library(GSVAdata)
library(msigdbr)
library(kableExtra)
library(knitr)
library(readxl)
```

```{r scRNA data setup}
#| include: false
# Parallel processing
plan(multicore, workers = 16)
options(future.globals.maxSize=2e9)
# Import
# so <- readRDS("/Volumes/Peds Endo/Petter Bjornstad/scRNA/data_clean/seurat_data_no_computations.RDS")
so <- readRDS("/run/user/1014/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/scRNA/data_clean/seurat_data_no_computations.RDS")
# CROCODILE only
so <- so[, grepl("CRC", so$michigan_id)]
# Exclude control with IgA
so <- subset(so, T2D_HC_Phil != "HC_igA")
so$Group <- so$T2D_HC_Phil
# Normalize and scale
so <- NormalizeData(so)
so <- ScaleData(so)
# PCA
so <- RunPCA(so, features = VariableFeatures(object = so))
# ElbowPlot(so)
# Cluster cells
so <- FindNeighbors(so)
so <- FindClusters(so)
# Perform UMAP and tSNE
so <- RunUMAP(so, dims = 1:30)
# so = RunTSNE(so,dim.embed = 3)
# General cell types as identifiers
so$generaltype <- sub("_.*", "", so$LR_clusters)
Idents(so) <- so$LR_clusters
```

# Differential expression

In the table below, T1D are group 1 and HC are group 2. Negative values indicate that the gene is more highly expressed in the second group (HC).

```{r}
# function for de.markers
de.markers <- function(seurat_object, genes, group.by, id1, id2, celltype, extension){
  m = FindMarkers(seurat_object, features = NULL, group.by = group.by,ident.1 = id1, 
                  ident.2 = id2, subset.ident = celltype,verbose = F, logfc.threshold=0.001,
                  min.pct = 0.001)
  m$p_val_adj = p.adjust(m$p_val,method = "fdr")
  m <- m %>% 
    rownames_to_column('gene') %>%
    arrange(p_val) %>%
    column_to_rownames('gene') %>%
    dplyr::select(avg_log2FC,pct.1,pct.2,p_val,p_val_adj)
  
  genes_subset <- rownames(m)[m$p_val <= 0.05]

  if (length(genes_subset) > 0){
    assign(paste0("genes_subset", extension), genes_subset, envir = .GlobalEnv)
  }
  assign(paste0("m", extension), m, envir = .GlobalEnv)
  return(knitr::kable(m))
}
```

```{r}
# de.markers(so, genes = NULL, "Group", id2 = "HC", id1 = "T1D", "PT", "_PT")
# de.markers(so, genes = NULL, "Group", id2 = "HC", id1 = "T1D", "EC", "_EC")
# de.markers(subset(so, celltype == "EC-AEA"), genes = NULL, "Group", id2 = "HC", id1 = "T1D", "EC", "_EC_AEA")
# de.markers(subset(so, celltype == "EC-GC"), genes = NULL, "Group", id2 = "HC", id1 = "T1D", "EC", "_EC_GC")
# de.markers(subset(so, celltype == "EC-LYM"), genes = NULL, "Group", id2 = "HC", id1 = "T1D", "EC", "_EC_LYM")
# de.markers(subset(so, celltype == "EC-PTC"), genes = NULL, "Group", id2 = "HC", id1 = "T1D", "EC", "_EC_PTC")
# de.markers(so, genes = NULL, "Group", id2 = "HC", id1 = "T1D", "MAC", "_MAC")
# de.markers(so, genes = NULL, "Group", id2 = "HC", id1 = "T1D", "MON", "_MON")
```

```{r}
# write.csv(m_PT, "/run/user/1014/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/CROCODILE/Data_Cleaned/CRC_care_t1d_PT_DEG_0.01.csv")
# write.csv(m_EC, "/run/user/1014/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/CROCODILE/Data_Cleaned/CRC_care_t1d_EC_DEG_0.01.csv")
# write.csv(m_EC_AEA, "/run/user/1014/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/CROCODILE/Data_Cleaned/CRC_care_t1d_EC_AEA_DEG_0.01.csv")
# write.csv(m_EC_GC, "/run/user/1014/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/CROCODILE/Data_Cleaned/CRC_care_t1d_EC_GC_DEG_0.01.csv")
# write.csv(m_EC_LYM, "/run/user/1014/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/CROCODILE/Data_Cleaned/CRC_care_t1d_EC_LYM_DEG_0.01.csv")
# write.csv(m_EC_PTC, "/run/user/1014/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/CROCODILE/Data_Cleaned/CRC_care_t1d_EC_PTC_DEG_0.01.csv")
# write.csv(m_MAC, "/run/user/1014/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/CROCODILE/Data_Cleaned/CRC_care_t1d_MAC_DEG_0.01.csv")
# write.csv(m_MON, "/run/user/1014/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/CROCODILE/Data_Cleaned/CRC_care_t1d_MON_DEG_0.01.csv")
```

## Bar plot
```{r}
add_direction <- function (df) 
{
    df <- df %>% mutate(direction = case_when((avg_log2FC > 0) ~ "Upregulated", 
    (avg_log2FC <= 0) ~ "Downregulated"))
    df$direction <- factor(df$direction, levels = c("Downregulated", 
        "Upregulated", "NS"))
    return(df)
}

```

```{r}
de.markers(so, genes = NULL, "Group", id2 = "HC", id1 = "T1D", "T", "_tcell")

gene_list <- c("PLEK", "ITGB1", "GZMA", "CCL5", "GZMB","CD8B")
direction_colors <- c("Upregulated" = "#588157", "Downregulated" = "#f4a261", "NS" = "#eaeaea")

m_tcell <- add_direction(m_tcell)
m_tcell <- rownames_to_column(m_tcell, var = "gene")
m_tcell <- m_tcell %>% arrange(desc(abs(avg_log2FC))) %>% dplyr::filter(gene %in% gene_list)
m_tcell$gene <- factor(m_tcell$gene, levels = m_tcell$gene)

# Combined plot
t.barplot_hum <- ggplot(m_tcell, aes(x = gene, y = avg_log2FC, fill = direction)) +
  geom_col(show.legend = T) +
  scale_fill_manual(values = direction_colors) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 25),
        panel.grid = element_blank(),
        strip.background = element_rect(fill = "white", color = "white"),
        panel.spacing = unit(-1, 'lines'),
        legend.position = "none",
        aspect.ratio = 0.9/1,
        text = element_text(size = 25),
        plot.title = element_text(),
        plot.tag.position = c(0.1,0.95)) +
  scale_y_continuous(position = "left", limits = c(0, 0.5),
                     breaks = c(0, 0.25,  0.5)) +
  labs(x = NULL, y = "Avg Log2FC", fill = "Log2FC Direction  ",
      title = "Upregulated T-cell \ntranscripts in humans\n(kidneys)", tag = "B") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", size = 0.2) 

ggsave(filename = "/home/yejichoi/Documents/lin_temp_folder/CROC_CARET1D_tcell_barplot_only.jpeg",
       plot = t.barplot_hum, scale = 3.5,
       width = 600, height = 500,units = "px")

rownames(m_tcell) <- m_tcell$gene
t.table <- m_tcell %>%
    dplyr::mutate(p_val_rounded = round(p_val, 4),
                  p_val = p_format(p_val_rounded, trailing.zero = T, accuracy = 0.001, digits = 3),
                  pct.1 = sprintf("%.3f", pct.1),
                  pct.2 = sprintf("%.3f", pct.2),
                  avg_log2FC = sprintf("%.3f", avg_log2FC)) %>%
    dplyr::select(pct.1, pct.2)
t.table <- ggtexttable(t.table,
      cols = c("   T1D     ", "     HC   "),
      theme = ttheme("blank", base_size = 25)
    ) %>%
      tab_add_hline(at.row = 1:2, row.side = "top", linewidth = 1) %>%
      tab_add_title(paste("% Expressed in T-cells", sep = ""), size = 25) 

plot_table <- ggarrange(t.barplot, NULL, t.table,
                                 nrow = 1, widths = c(1,-0.1,1), common.legend = F)
plot_table

ggsave(filename = "/home/yejichoi/Documents/lin_temp_folder/CROC_CARET1D_tcell_bar_combined.jpeg",
       plot = plot_table, scale = 3.5,
       width = 1000, height = 500,units = "px")
```

```{r}
mice_deg <- read.csv("/run/user/1014/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Grants/CaRe-T1D/mice_cell_cd8tcell_deg.csv")
mice_deg <- add_direction(mice_deg)
mice_genes <- c("GZMA", "GZMB", "PLEK", "CD8B1", "CCL5", "ITGB1")
mice_deg <- subset(mice_deg, gene %in% mice_genes)
mice_deg$gene <- factor(mice_deg$gene, levels = mice_genes)

# Combined plot
tmice.barplot <- ggplot(mice_deg, aes(x = gene, y = avg_log2FC, fill = direction)) +
  geom_col(show.legend = T) +
  scale_fill_manual(values = direction_colors) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 25),
        panel.grid = element_blank(),
        strip.background = element_rect(fill = "white", color = "white"),
        panel.spacing = unit(-1, 'lines'),
        legend.position = "none",
        aspect.ratio = 0.9/1,
        text = element_text(size = 25),
        plot.title = element_text(),
        plot.tag.position = c(0.1,0.95)) +
  scale_y_continuous(position = "left", limits = c(0, 1),
                     breaks = c(0, 0.25, 0.5, 0.75, 1)) +
  labs(x = NULL, y = "Avg Log2FC",
      title = "Upregulated T-cell \ntranscripts in mice \n(lesioned aorta)", tag = "A") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", size = 0.2) 

ggsave(filename = "/home/yejichoi/Documents/lin_temp_folder/CROC_CARET1D_tcell_mice_barplot_only.jpeg",
       plot = tmice.barplot, scale = 3.5,
       width = 600, height = 500,units = "px")

mice_human_plot <- ggarrange(tmice.barplot, t.barplot_hum, common.legend = F)
mice_human_plot

ggsave(filename = "/home/yejichoi/Documents/lin_temp_folder/CROC_CARET1D_tcell_mice_human_barplot.jpeg",
       plot = mice_human_plot, scale = 3.5,
       width = 1000, height = 600,units = "px")

```

```{r}
de.markers(so, genes = NULL, "Group", id2 = "HC", id1 = "T1D", "T", "_tcell")
cd8_genes <- c("LGALS3", "VIM", "LGALS1", "CAP1", "TAGLN2", "CD47", "VMP1", "SPECC1", "CD226", "PLEK", "ZYX", "ITGB1")
direction_colors <- c("Upregulated" = "#588157", "Downregulated" = "#ff8800", "NS" = "#eaeaea")

m_tcell <- add_direction(m_tcell)
m_tcell <- rownames_to_column(m_tcell, var = "gene")
m_tcell <- m_tcell %>% arrange(desc((avg_log2FC))) %>% dplyr::filter(gene %in% cd8_genes)
m_tcell$gene <- factor(m_tcell$gene, levels = m_tcell$gene)

# Combined plot
t.barplot <- ggplot(m_tcell, aes(x = gene, y = avg_log2FC, fill = direction)) +
  geom_col(show.legend = T) +
  scale_fill_manual(values = direction_colors,
                    labels = c("Downregulated    ",
                                "Upregulated    ")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 22),
        panel.grid = element_blank(),
        strip.background = element_rect(fill = "white", color = "white"),
        panel.spacing = unit(-1, 'lines'),
        legend.position = "top",
        aspect.ratio = 0.9/1,
        text = element_text(size = 25)) +
  scale_y_continuous(position = "left", limits = c(-0.5, 0.5),
                     breaks = c(- 0.5, -0.25, 0, 0.25,  0.5)) +
  labs(x = NULL, y = "Avg Log2FC", fill = "Log2FC Direction  ") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", size = 0.2) 

ggsave(filename = "/home/yejichoi/Documents/lin_temp_folder/CROC_CARET1D_cd8_tcell_barplot_only.jpeg",
       plot = t.barplot, scale = 3.5,
       width = 850, height = 500,units = "px")

rownames(m_tcell) <- m_tcell$gene
t.table <- m_tcell %>%
    dplyr::mutate(p_val_rounded = round(p_val, 4),
                  p_val = p_format(p_val_rounded, trailing.zero = T, accuracy = 0.001, digits = 3),
                  pct.1 = sprintf("%.3f", pct.1),
                  pct.2 = sprintf("%.3f", pct.2),
                  avg_log2FC = sprintf("%.3f", avg_log2FC)) %>%
    dplyr::select(pct.1, pct.2)
t.table <- ggtexttable(t.table,
      cols = c("   T1D     ", "     HC   "),
      theme = ttheme("blank", base_size = 25)
    ) %>%
      tab_add_hline(at.row = 1:2, row.side = "top", linewidth = 1) %>%
      tab_add_title(paste("% Expressed in T-cells", sep = ""), size = 25) 

plot_table <- ggarrange(t.barplot, NULL, t.table,
                                 nrow = 1, widths = c(1,-0.1,1), common.legend = F)
plot_table

ggsave(filename = "/home/yejichoi/Documents/lin_temp_folder/CROC_CARET1D_tcell_cd8_bar_combined.jpeg",
       plot = plot_table, scale = 3.5,
       width = 1200, height = 700,units = "px")


# Upregulated
m_tcell_up <- subset(m_tcell, avg_log2FC > 0)
t.barplot_cd8_hum <- ggplot(m_tcell_up, aes(x = gene, y = avg_log2FC, fill = direction)) +
  geom_col(show.legend = T) +
  scale_fill_manual(values = direction_colors,
                    labels = c("Upregulated    ")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 25),
        panel.grid = element_blank(),
        strip.background = element_rect(fill = "white", color = "white"),
        panel.spacing = unit(-1, 'lines'),
        legend.position = "top",
        aspect.ratio = 0.9/1,
        text = element_text(size = 25)) +
  scale_y_continuous(position = "left", limits = c(-0.5, 0.5),
                     breaks = c(- 0.5, -0.25, 0, 0.25,  0.5)) +
  labs(x = NULL, y = "Avg Log2FC", fill = "Log2FC Direction  ") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", size = 0.2) 

ggsave(filename = "/home/yejichoi/Documents/lin_temp_folder/CROC_CARET1D_cd8_tcell_up_barplot_only.jpeg",
       plot = t.barplot_cd8_hum, scale = 3.5,
       width = 600, height = 500,units = "px")

rownames(m_tcell_up) <- m_tcell_up$gene
t.table <- m_tcell_up %>%
    dplyr::mutate(p_val_rounded = round(p_val, 4),
                  p_val = p_format(p_val_rounded, trailing.zero = T, accuracy = 0.001, digits = 3),
                  pct.1 = sprintf("%.3f", pct.1),
                  pct.2 = sprintf("%.3f", pct.2),
                  avg_log2FC = sprintf("%.3f", avg_log2FC)) %>%
    dplyr::select(pct.1, pct.2)
t.table <- ggtexttable(t.table,
      cols = c("   T1D     ", "     HC   "),
      theme = ttheme("blank", base_size = 25)
    ) %>%
      tab_add_hline(at.row = 1:2, row.side = "top", linewidth = 1) %>%
      tab_add_title(paste("% Expressed in T-cells", sep = ""), size = 25) 

plot_table <- ggarrange(t.barplot, NULL, t.table,
                                 nrow = 1, widths = c(1,-0.1,1), common.legend = F)
plot_table

ggsave(filename = "/home/yejichoi/Documents/lin_temp_folder/CROC_CARET1D_tcell_cd8_bar_upreg.jpeg",
       plot = plot_table, scale = 3.5,
       width = 1000, height = 500,units = "px")

# Downregulated
m_tcell_down <- subset(m_tcell, avg_log2FC < 0)
t.barplot <- ggplot(m_tcell_down, aes(x = gene, y = avg_log2FC, fill = direction)) +
  geom_col(show.legend = T) +
  scale_fill_manual(values = direction_colors,
                    labels = c("Downregulated    ")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 25),
        panel.grid = element_blank(),
        strip.background = element_rect(fill = "white", color = "white"),
        panel.spacing = unit(-1, 'lines'),
        legend.position = "top",
        aspect.ratio = 0.9/1,
        text = element_text(size = 25)) +
  scale_y_continuous(position = "left", limits = c(-0.5, 0.5),
                     breaks = c(- 0.5, -0.25, 0, 0.25,  0.5)) +
  labs(x = NULL, y = "Avg Log2FC", fill = "Log2FC Direction  ") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", size = 0.2) 

ggsave(filename = "/home/yejichoi/Documents/lin_temp_folder/CROC_CARET1D_cd8_tcell_down_barplot_only.jpeg",
       plot = t.barplot, scale = 3.5,
       width = 600, height = 500,units = "px")

rownames(m_tcell_down) <- m_tcell_down$gene
t.table <- m_tcell_down %>%
    dplyr::mutate(p_val_rounded = round(p_val, 4),
                  p_val = p_format(p_val_rounded, trailing.zero = T, accuracy = 0.001, digits = 3),
                  pct.1 = sprintf("%.3f", pct.1),
                  pct.2 = sprintf("%.3f", pct.2),
                  avg_log2FC = sprintf("%.3f", avg_log2FC)) %>%
    dplyr::select(pct.1, pct.2)
t.table <- ggtexttable(t.table,
      cols = c("   T1D     ", "     HC   "),
      theme = ttheme("blank", base_size = 25)
    ) %>%
      tab_add_hline(at.row = 1:2, row.side = "top", linewidth = 1) %>%
      tab_add_title(paste("% Expressed in T-cells", sep = ""), size = 25) 

plot_table <- ggarrange(t.barplot, NULL, t.table,
                                 nrow = 1, widths = c(1,-0.1,1), common.legend = F)
plot_table

ggsave(filename = "/home/yejichoi/Documents/lin_temp_folder/CROC_CARET1D_tcell_cd8_bar_downreg.jpeg",
       plot = plot_table, scale = 3.5,
       width = 1000, height = 500,units = "px")

```

cell abundance of 
* cytotoxic t-cells, 
* natural killer cells and 
* cyclic t-cells differ between T1D vs. HC?

```{r}
# With NKC/NKT (since it's a mix with T cells)
cell_abundance_v1 <- so@meta.data %>% 
  filter(KPMP_celltype %in% c("cycT", "NKC/NKT", "T-CYT", "T")) %>%
  ggplot(aes(Group, fill = KPMP_celltype)) + 
  geom_bar(stat = "count", position = "fill") +
  theme_classic() +
  labs(x = NULL,
       y = "Proportion",
       fill = "T-Cell type") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  theme(plot.title = element_text(hjust=0.2, face="bold"),
        text = element_text(size = 27)) +
  ggtitle("Proportion of cells") +
  scale_fill_manual(values = c("#264653", "#2a9d8f", "#e9c46a", "#f4a261"))
ggsave(plot = cell_abundance_v1, filename = "/home/yejichoi/Documents/lin_temp_folder/T_cell_proportions.jpg", 
       scale = 3,
       width = 550,height = 1000,units = "px")

# Without NKC/NKT (since it's a mix with T cells)
cell_abundance_v2 <- so@meta.data %>% 
  filter(KPMP_celltype %in% c("cycT", "T-CYT", "T")) %>%
  ggplot(aes(Group, fill = KPMP_celltype)) + 
  geom_bar(stat = "count", position = "fill") +
  theme_classic() +
  labs(x = NULL,
       y = "Proportion",
       fill = "T-Cell type") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  theme(plot.title = element_text(hjust=0.2, face="bold"),
        text = element_text(size = 27)) +
  ggtitle("Proportion of cells") +
  scale_fill_manual(values = c("#2a9d8f", "#e9c46a", "#f4a261"))
ggsave(plot = cell_abundance_v2, filename = "/home/yejichoi/Documents/lin_temp_folder/T_cell_noNKT_proportions.jpg", 
       scale = 3,
       width = 550,height = 1000,units = "px")


```