---
title: "crocodile KNIGHT analysis"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
editor: visual
---

```{r libraries}
#| include: false
library(Seurat)
library(future)
library(tidyverse)
library(colorspace)
library(patchwork)
library(ggdendro)
library(cowplot)
library(ggtree)
library(ggpubr)
library(rstatix)
library(table1)
library(GSVA)
library(Biobase)
library(ReactomeGSA)
library(GSEABase)
library(GSVAdata)
library(msigdbr)
library(kableExtra)
library(knitr)
```

```{r scRNA data setup}
so <- readRDS("/home/yejichoi/Documents/seurat_data_CRC.RDS")
load("/run/user/1014/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/CROCODILE/Data_Cleaned/croc_data.RData")
sex_dat <- dat %>% dplyr::select(record_id, sex) %>%
  dplyr::rename("michigan_id" = "record_id")
sex_meta <- so@meta.data %>% left_join(sex_dat)
rownames(sex_meta) <- rownames(so@meta.data)
so <- AddMetaData(so, sex_meta)
```

# Differential expression

```{r}
# function for de.markers
de.markers <- function(seurat_object, genes, group.by, id1, id2, celltype, extension){
  m = FindMarkers(seurat_object, features = NULL, group.by = group.by,ident.1 = id1, 
                  ident.2 = id2, subset.ident = celltype,verbose = F, logfc.threshold=0,
                  min.pct = 0.001)
  m$p_val_adj = p.adjust(m$p_val,method = "fdr")
  m <- m %>% 
    rownames_to_column('gene') %>%
    arrange(p_val) %>%
    column_to_rownames('gene') %>%
    dplyr::select(avg_log2FC,pct.1,pct.2,p_val,p_val_adj)
  
  genes_subset <- rownames(m)[m$p_val <= 0.05]

  if (length(genes_subset) > 0){
    assign(paste0("genes_subset", extension), genes_subset, envir = .GlobalEnv)
  }
  assign(paste0("m", extension), m, envir = .GlobalEnv)
  return(knitr::kable(m))
}
```

In the table below, females are group 1 and males are group 2. Negative values indicate that the gene is more highly expressed in the second group (males).

```{r}
de.markers(subset(so, Group == "HC"), genes = NULL, "sex", id2 = "Male", id1 = "Female", "EC", "_EC_sex")
# de.markers(subset(so, celltype == "EC-AEA"), genes = NULL, "sex", id2 = "Male", id1 = "Female", "EC", "_EC_AEA_sex")
# de.markers(subset(so, celltype == "EC-GC"), genes = NULL, "sex", id2 = "Male", id1 = "Female", "EC", "_EC_GC_sex")
# de.markers(subset(so, celltype == "EC-LYM"), genes = NULL, "sex", id2 = "Male", id1 = "Female", "EC", "_EC_LYM_sex")
# de.markers(subset(so, celltype == "EC-PTC"), genes = NULL, "sex", id2 = "Male", id1 = "Female", "EC", "_EC_PTC_sex")
```

```{r}
write.csv(m_EC_sex, "/run/user/1014/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/CROCODILE/Data_Cleaned/HC_CRC_KNIGHT_EC_sex_DEG.csv")
```
