---
title: "CROCODILE descriptives with biopsy"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    embed-resources: true
editor: visual
---

```{r setup, include=F}
library(dplyr)
library(reticulate)
library(corrplot)
library(knitr)
library(Hmisc)
library(tidyverse)
library(scales)
library(kableExtra)
library(gtools)
library(superheat)
library(emmeans)
library(table1)
library(ggpubr)
library(arsenal)
library(Hmisc)
library(lme4)
library(nlme)
library(knitr)
library(MASS)
options(scipen = 999)
use_python("/usr/bin/python3", required = TRUE)
```

```{r include = F}
load("/Volumes/Peds Endo/Petter Bjornstad/CROCODILE/Data_Cleaned/croc_data.RData")
dat <- dat %>%
  filter(grepl("KL", kit_id))
```

```{r, include=F}
table_one <- tableby(group ~ age + sex + fe(race)  + fe(ethnicity) + + weight + height + kwt(bmi, "Nmiss", "median", "q1q3", "range") +  hba1c + diabetes_duration + sbp + dbp + pulse + creatinine_s + eGFR_fas_cr + eGFR_CKD_epi+  kwt(acr_u, "Nmiss", "median", "q1q3", "range") + kwt(aer_24, "Nmiss", "median", "q1q3", "range")  + fe(metformin_timepoint) + fe(insulin_med_timepoint) +  fe(sglti_timepoint) + fe(tzd_timepoint) + fe(raasi_timepoint) + fe(statin) + kidney_side + appendicular_lean_mass + musclemass, data = dat, total=F)

table_dxa <- tableby(group ~ dexa_body_fat + dexa_fat_kg + dexa_lean_kg + dexa_trunk_kg + p2_raw_m + p2_raw_leanm + p2_gc_m + p2_gc_leanm + baseline_ffa, data = dat, total=F)

table_kidney <- tableby(group ~ gfr_raw_plasma + erpf_raw_plasma + rvr + glomerular_pressure + total_kidney_volume_ml + left_kidney_volume_ml + right_kidney_volume_ml + avg_pcascl + pcasl3d_left + pcasl3d_right + avg_c_r2 + bold_l_bl_cortex + bold_r_bl_cortex + avg_m_r2 + bold_l_bl_medulla + bold_r_bl_medulla + avg_m_fsoc + fsoc_l_medulla + fsoc_r_medulla + avg_c_adc + adc_left + adc_right, data = dat, total=F)

table_morpho <- tableby(group ~ fia +	glom_tuft_area +	glom_volume_weibel +	glom_volume_wiggins +	glom_volume_con +	mes_matrix_area +	mes_index +	mes_volume_weibel +	mes_volume_wiggins +	mes_volume_con +	glom_nuc_count, data = dat, total=F)
#  + kwt(gbm_thick_harmmean, "Nmiss", "median", "q1q3", "range") + kwt(gbm_thick_artmean, "Nmiss", "median", "q1q3", "range")

table_pet <- tableby(group ~ lc_f +	rc_f +	avg_c_f +	lm_f +	rm_f +	avg_m_f +	lc_k1 +	rc_k1 +	avg_c_k1 +	lm_k1 +	rm_k1 + avg_m_k1 + lc_k2_wo_cyst_vw + rc_k2_wo_cyst_vw + avg_c_k2_wo_cyst_vw + lm_k2_wo_cyst_vw + rm_k2_wo_cyst_vw + avg_m_k2_wo_cyst_vw + lc_k2 + rc_k2 + avg_c_k2 + lm_k2 + rm_k2 + avg_m_k2 , data = dat, total=F)

table_lipids <- tableby(group ~ cholesterol + ldl + hdl + kwt(triglycerides, "median", "q1q3"), data = dat, total=F)
```

```{r results='asis'}
summary(table_one, pfootnote = T, digits = 1, digits.p = 3, digits.pct = 0)
summary(table_dxa, pfootnote = T, digits = 1, digits.p = 3, digits.pct = 0)
summary(table_kidney, pfootnote = T, digits = 3, digits.p = 3, digits.pct = 0)
summary(table_morpho, pfootnote = T, digits = 1, digits.p = 3, digits.pct = 0)
summary(table_pet, pfootnote = T, digits = 1, digits.p = 3, digits.pct = 0)
summary(table_lipids, pfootnote = T, digits = 1, digits.p = 3, digits.pct = 0)
```
