---
title: "CROCODILE Data Summary"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 5
    toc_float: yes
---

```{r setup, include=FALSE}
library(redcapAPI)
library(SmartEDA)
library(naniar)
library(knitr)
library(DT)
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
tokens = read.csv("/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Data Harmonization/api_tokens.csv")
rcon = redcapConnection(
  url = "https://redcap.ucdenver.edu/api/",token = tokens$Token[tokens$Study == "CROCODILE"]
)
crocodile = exportRecords(rcon,labels = F)
```

# Overall summary

```{r}
t1 = ExpData(crocodile,type=1)
kable(t1)
```

# By variable

```{r}
t2 = ExpData(crocodile,type=2)
datatable(t2)
```

# Missingness

```{r warning=FALSE,results='asis',fig.height=12,fig.width=12}
forms = exportInstruments(rcon)
for (r in 1:nrow(forms)) {
  f = forms$instrument_name[r]
  l = forms$instrument_label[r]
  df = exportRecords(rcon,forms = f)
  # Print
  cat("\n")
  cat(paste("##",l))
  cat("\n")
  print(vis_miss(df))
  cat("\n")
  if(sum(is.na(df))>0){
    cat("\n")
    print(gg_miss_upset(df))
    cat("\n")
  }
}
```
