---
title: "CROCODILE scRNAseq"
author: "Laura Pyle, Tim Vigers & Ye Ji Choi"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
---

```{r libraries}
#| include: false
library(Seurat)
library(annotables)
```

```{r scRNA data setup}
# Import
so = readRDS("/Users/timvigers/Library/CloudStorage/Dropbox/Work/Petter Bjornstad/scRNA/Data_Clean/seurat_data_no_computations.RDS")
# CROCODILE only
so <- so[, grepl("CRC", so$michigan_id)]
# Normalize and scale
so <- NormalizeData(so)
so <- ScaleData(so, features = rownames(so))
# PCA
so <- RunPCA(so, features = VariableFeatures(object = so))
# Cluster cells
so <- FindNeighbors(so)
so <- FindClusters(so)
# Perform UMAP
so <- RunUMAP(so, dims = 1:20)
# General cell types as identifiers
# so$generaltype <- sub("_.*", "", so$LR_clusters)
# Idents(so) <- so$generaltype
# Get genes of interest (TCA cycle)
genes = c("ACO1","ACO2","IDH1","IDH2","IDH3A","IDH3B","IDH3G","OGDH","OGDHL",
          "SUCLA2","SUCLG1","SUCLG2","SDHA","SDHB","SDHC","SDHD","FH","MDH1",
          "MDH2")
entrez_ids = grch38$entrez[match(genes,grch38$symbol)]
```

# UMAP

```{r}
p <- FeaturePlot(so, features = entrez_ids)
p <- LabelClusters(plot = p, id = "ident")
p
```

# Dot plot

```{r}
DotPlot(so, features = entrez_ids)
```
