---
title: "Voxelwise Functional Data Analysis"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 5
    toc_float: yes
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidyfun)
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
# Import data
df = read.csv("/Users/timvigers/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/CHCO/Petter Bjornstad/CROCODILE/Data_Cleaned/voxelwise_rows.csv")
# Split by region and parameter, delete unnecessary columns
lcortex_k1 = df[df$region == "lcortex" & df$parameter == "k1",]
lcortex_k1$region = NULL
lcortex_k1$parameter = NULL
lcortex_k1 = lcortex_k1[,colSums(is.na(lcortex_k1))<nrow(lcortex_k1)]

lcortex_k2 = df[df$region == "lcortex" & df$parameter == "k2",]
lcortex_k2$region = NULL
lcortex_k2$parameter = NULL
lcortex_k2 = lcortex_k2[,colSums(is.na(lcortex_k2))<nrow(lcortex_k2)]

lmedulla_k1 = df[df$region == "lmedulla" & df$parameter == "k1",]
lmedulla_k1$region = NULL
lmedulla_k1$parameter = NULL
lmedulla_k1 = lmedulla_k1[,colSums(is.na(lmedulla_k1))<nrow(lmedulla_k1)]

lmedulla_k2 = df[df$region == "lmedulla" & df$parameter == "k2",]
lmedulla_k2$region = NULL
lmedulla_k2$parameter = NULL
lmedulla_k2 = lmedulla_k2[,colSums(is.na(lmedulla_k2))<nrow(lmedulla_k2)]

rcortex_k1 = df[df$region == "rcortex" & df$parameter == "k1",]
rcortex_k1$region = NULL
rcortex_k1$parameter = NULL
rcortex_k1 = rcortex_k1[,colSums(is.na(rcortex_k1))<nrow(rcortex_k1)]

rcortex_k2 = df[df$region == "rcortex" & df$parameter == "k2",]
rcortex_k2$region = NULL
rcortex_k2$parameter = NULL
rcortex_k2 = rcortex_k2[,colSums(is.na(rcortex_k2))<nrow(rcortex_k2)]

rmedulla_k1 = df[df$region == "rmedulla" & df$parameter == "k1",]
rmedulla_k1$region = NULL
rmedulla_k1$parameter = NULL
rmedulla_k1 = rmedulla_k1[,colSums(is.na(rmedulla_k1))<nrow(rmedulla_k1)]

rmedulla_k2 = df[df$region == "rmedulla" & df$parameter == "k2",]
rmedulla_k2$region = NULL
rmedulla_k2$parameter = NULL
rmedulla_k2 = rmedulla_k2[,colSums(is.na(rmedulla_k2))<nrow(rmedulla_k2)]
# Convert to functional
fda_lcortex_k1 = tibble(record_id = lcortex_k1$record_id)
fda_lcortex_k1$lcortex_k1 = tfd(data.matrix(lcortex_k1[,2:ncol(lcortex_k1)]))
fda_lcortex_k2 = tibble(record_id = lcortex_k2$record_id)
fda_lcortex_k2$lcortex_k2 = tfd(data.matrix(lcortex_k2[,2:ncol(lcortex_k2)]))

fda_lmedulla_k1 = tibble(record_id = lmedulla_k1$record_id)
fda_lmedulla_k1$lmedulla_k1 = tfd(data.matrix(lmedulla_k1[,2:ncol(lmedulla_k1)]))
fda_lmedulla_k2 = tibble(record_id = lmedulla_k2$record_id)
fda_lmedulla_k2$lmedulla_k2 = tfd(data.matrix(lmedulla_k2[,2:ncol(lmedulla_k2)]))

fda_rcortex_k1 = tibble(record_id = rcortex_k1$record_id)
fda_rcortex_k1$rcortex_k1 = tfd(data.matrix(rcortex_k1[,2:ncol(rcortex_k1)]))
fda_rcortex_k2 = tibble(record_id = rcortex_k2$record_id)
fda_rcortex_k2$rcortex_k2 = tfd(data.matrix(rcortex_k2[,2:ncol(rcortex_k2)]))

fda_rmedulla_k1 = tibble(record_id = rmedulla_k1$record_id)
fda_rmedulla_k1$rmedulla_k1 = tfd(data.matrix(rmedulla_k1[,2:ncol(rmedulla_k1)]))
fda_rmedulla_k2 = tibble(record_id = rmedulla_k2$record_id)
fda_rmedulla_k2$rmedulla_k2 = tfd(data.matrix(rmedulla_k2[,2:ncol(rmedulla_k2)]))
# Merge
fda_df = full_join(fda_lcortex_k1,fda_lcortex_k2,by = "record_id")
```
