---
title: "SGLT2i manuscript - clinical characteristics"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 5
    toc_float: yes
---

```{r setup, include=FALSE}
library(tableone)
library(dplyr)
library(knitr)
library(questionr)
library(skimr)
library(readxl)
library(arsenal)
library(gtsummary)
library(stringr)
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
```

```{r include=FALSE}
# Import and clean data
df <- read.csv("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/soma_harmonized_dataset.csv", na.strings = "")
df <- df %>%
  filter(
    study %in% c("IMPROVE", "RENAL-HEIR","RENAL-HEIRitage", "CROCODILE"),
    !grepl("IT2D", co_enroll_id), participation_status == "Participated",
  ) %>%
  group_by(record_id, visit) %>%
  summarise(across(where(is.character), ~ last(na.omit(.x))),
    across(where(is.factor), ~ last(na.omit(.x))),
    across(where(is.numeric), ~ mean(.x, na.rm = T)),
    .groups = "drop"
  ) %>%
  mutate_all(~ ifelse(is.nan(.), NA, .))
df <- df %>% filter(visit == "baseline")

# select the sample IDs that Fadhl sent
ids_keep_sc <- read_xlsx("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Metallothionine/MT_sampleIDs_Laura.xlsx", sheet = "sc")
ids_keep_sc$record_id <- stringr::str_remove(ids_keep_sc$michigan_id, "_BL")
ids_keep_sc$michigan_id <- NULL
df_keep_sc <- left_join(ids_keep_sc, df, by = "record_id")

ids_keep_ST <- read_xlsx("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Metallothionine/MT_sampleIDs_Laura.xlsx", sheet = "ST")
ids_keep_ST$ID <- stringr::str_remove(ids_keep_ST$ID, "_BL")
ids_keep_ST$record_id <- ids_keep_ST$ID
ids_keep_ST$ID <- NULL
df_keep_ST <- left_join(ids_keep_ST, df, by = "record_id")

ids_keep_olink <- read_xlsx("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Metallothionine/MT_sampleIDs_Laura.xlsx", sheet = "Olink")
ids_keep_olink$record_id <- stringr::str_remove(ids_keep_olink$michigan_id, "_BL")
ids_keep_olink$michigan_id <- NULL
df_keep_olink <- left_join(ids_keep_olink, df, by = "record_id")

ids_keep_soma <- read_xlsx("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Metallothionine/MT_sampleIDs_Laura.xlsx", sheet = "somascan")
ids_keep_soma$record_id <- stringr::str_remove(ids_keep_soma$michigan_id, "_BL")
ids_keep_soma$michigan_id <- NULL
df_keep_soma <- left_join(ids_keep_soma, df, by = "record_id")
```

# Results

## Table 1 - SC

```{r, include=FALSE}
t1 <- tableby(T2D_HC_Phil ~ age + sex + race_ethnicity + bmi + dexa_body_fat + cholesterol + ldl + hdl + triglycerides +
                sbp + dbp + acr_u + albuminuria_cat + hba1c + creatinine_s + eGFR_fas_cr_cysc , 
              data = df_keep_sc)
```

```{r, include=TRUE, results='asis'}
summary(t1)
```

## Table 2 - ST

```{r, include=FALSE}
t2 <- tableby(T2D_HC ~ age + sex + race_ethnicity + bmi + dexa_body_fat + cholesterol + ldl + hdl + triglycerides +
                sbp + dbp + acr_u + albuminuria_cat + hba1c + creatinine_s + eGFR_fas_cr_cysc , 
              data = df_keep_ST)
```

```{r, include=TRUE, results='asis'}
summary(t2)
```

## Table 3 - Olink

```{r, include=FALSE}
t3 <- tableby(T2D_HC ~ age + sex + race_ethnicity + bmi + dexa_body_fat + cholesterol + ldl + hdl + triglycerides +
                sbp + dbp + acr_u + albuminuria_cat + hba1c + creatinine_s + eGFR_fas_cr_cysc , 
              data = df_keep_olink)
```

```{r, include=TRUE, results='asis'}
summary(t3)
```

## Table 4 - Soma

```{r, include=FALSE}
t4 <- tableby(T2D_HC ~ age + sex + race_ethnicity + bmi + dexa_body_fat + cholesterol + ldl + hdl + triglycerides +
                sbp + dbp + acr_u + albuminuria_cat + hba1c + creatinine_s + eGFR_fas_cr_cysc , 
              data = df_keep_soma)
```

```{r, include=TRUE, results='asis'}
summary(t4)
```
