---
title: "PEDSnet CAH growth curves"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
library(readr)
library(ggplot2)
library(quantregGrowth)
library(tidyverse)
library(skimr)
library(dplyr)
library(stringr)
library(growthcleanr)
library(data.table)
library(tableone)
library(gtsummary)
library(knitr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
```

```{r echo=FALSE}
ds <- read.csv("/Volumes/Shared/Shared Projects/Laura/Peds Endo/PEDSNet/CAH/Data_raw/CAH_BMI_Demo_23.09.18.csv")
ds <- ds %>% filter(cah == "case") # median BMI 18.4
ds$dob <- as.Date(ds$dob, format="%m/%d/%Y")
ds$measurement_date <- as.Date(ds$measurement_date, format = "%Y-%m-%d")
ds$age <- floor((ds$measurement_date - ds$dob)/365.25)
ds$age_days <- floor(ds$measurement_date - ds$dob)
ds$sex_num <- ifelse(ds$gender=="Male", 0, 1)
# some records have age <0 and age >18
ds <- ds %>% subset(age>=2)
ds <- ds %>% subset(age<=18) # median BMI 19.6, weight 38.8

# create a doubly long dataset with height and weight only, and keep the other variables separate
ds_weight <- ds[,c("person_id","age_days","sex_num","wgt")]
ds_weight$measurement <- ds_weight$wgt
ds_weight$wgt <- NULL
ds_weight$param <- "WEIGHTKG"
ds_height <- ds[,c("person_id","age_days","sex_num","hgt")]
ds_height$measurement <- ds_height$hgt
ds_height$hgt <- NULL
ds_height$param <- "HEIGHTCM"
ds_keep <- rbind(ds_weight,ds_height)
ds_keep <- as.data.table(ds_keep) # median weight 38.8

cleaned_data <- ds_keep[, gcr_result := cleangrowth(person_id, param, age_days, sex_num, measurement)]
cleaned_wt <- cleaned_data %>% filter(param=="WEIGHTKG" & gcr_result=="Include") # median weight 39.46
cleaned_wt$weight_kg <- cleaned_wt$measurement
cleaned_wt$measurement <- NULL
cleaned_wt$param <- NULL
cleaned_wt$gcr_result <- NULL # median weight 39.46
cleaned_ht <- cleaned_data %>% filter(param=="HEIGHTCM" & gcr_result=="Include")
cleaned_ht$height_cm <- cleaned_ht$measurement
cleaned_ht$measurement <- NULL
cleaned_ht$param <- NULL
cleaned_ht$gcr_result <- NULL
cleaned_ht$sex_num <- NULL
cleaned_data_wide <- left_join(cleaned_wt, cleaned_ht, by=c("person_id", "age_days"))
cleaned_data_wide$bmi <- cleaned_data_wide$weight_kg / (cleaned_data_wide$height_cm / 100)
#cleaned_data_wide$sex_num <- ifelse(!is.na(cleaned_data_wide$sex_num.x),cleaned_data_wide$sex_num.x,cleaned_data_wide$sex_num.y)
#cleaned_data_wide$sex_num.x <- NULL
#cleaned_data_wide$sex_num.y <- NULL
cleaned_data_wide$age <- as.numeric(floor(cleaned_data_wide$age_days/365.25)) # median BMI 28.26, max BMI >100
cleaned_data_wide_males <- cleaned_data_wide[cleaned_data_wide$sex_num==0,] # median BMI 27.92
cleaned_data_wide_females <- cleaned_data_wide[cleaned_data_wide$sex_num==1,] # median BMI 28.52

# CAH subset
ds_subset <- read.csv("/Volumes/Shared/Shared Projects/Laura/Peds Endo/PEDSNet/CAH/Data_raw/CAH_BMI_Demo_subset_23.10.03.csv")
ds_subset <- ds_subset %>% filter(cah == "case")
ds_subset$dob <- as.Date(ds_subset$dob, format="%m/%d/%Y")
ds_subset$measurement_date <- as.Date(ds_subset$measurement_date, format = "%Y-%m-%d")
ds_subset$age <- floor((ds_subset$measurement_date - ds_subset$dob)/365.25)
ds_subset$age_days <- floor(ds_subset$measurement_date - ds_subset$dob)
ds_subset$sex_num <- ifelse(ds_subset$gender=="Male", 0, 1)
# some records_subset have age <0 and age >18
ds_subset <- ds_subset %>% subset(age>=2)
ds_subset <- ds_subset %>% subset(age<=18)

# create a doubly long dataset with height and weight only, and keep the other variables separate
ds_subset_weight <- ds_subset[,c("person_id","age_days","sex_num","wgt")]
ds_subset_weight$measurement <- ds_subset_weight$wgt
ds_subset_weight$wgt <- NULL
ds_subset_weight$param <- "WEIGHTKG"
ds_subset_height <- ds_subset[,c("person_id","age_days","sex_num","hgt")]
ds_subset_height$measurement <- ds_subset_height$hgt
ds_subset_height$hgt <- NULL
ds_subset_height$param <- "HEIGHTCM"
ds_subset_keep <- rbind(ds_subset_weight,ds_subset_height)
ds_subset_keep <- as.data.table(ds_subset_keep)

cleaned_data_subset <- ds_subset_keep[, gcr_result := cleangrowth(person_id, param, age_days, sex_num, measurement)]
cleaned_wt_subset <- cleaned_data_subset %>% filter(param=="WEIGHTKG" & gcr_result=="Include")
cleaned_wt_subset$weight_kg <- cleaned_wt_subset$measurement
cleaned_wt_subset$measurement <- NULL
cleaned_wt_subset$param <- NULL
cleaned_wt_subset$gcr_result <- NULL
cleaned_ht_subset <- cleaned_data_subset %>% filter(param=="HEIGHTCM" & gcr_result=="Include")
cleaned_ht_subset$height_cm <- cleaned_ht_subset$measurement
cleaned_ht_subset$measurement <- NULL
cleaned_ht_subset$param <- NULL
cleaned_ht_subset$gcr_result <- NULL
cleaned_data_wide_subset <- merge(cleaned_wt_subset, cleaned_ht_subset, by=c("person_id", "age_days"), all.x = T, all.y = T)
cleaned_data_wide_subset$bmi <- cleaned_data_wide_subset$weight_kg / (cleaned_data_wide_subset$height_cm / 100)
cleaned_data_wide_subset$sex_num <- ifelse(!is.na(cleaned_data_wide_subset$sex_num.x),cleaned_data_wide_subset$sex_num.x,cleaned_data_wide_subset$sex_num.y)
cleaned_data_wide_subset$sex_num.x <- NULL
cleaned_data_wide_subset$sex_num.y <- NULL
cleaned_data_wide_subset$age <- floor(cleaned_data_wide_subset$age_days/365.25)
cleaned_data_wide_subset_males <- cleaned_data_wide[cleaned_data_wide$sex_num==0,]
cleaned_data_wide_subset_females <- cleaned_data_wide[cleaned_data_wide$sex_num==1,]

# write data for Natalie
#write.csv(cleaned_data_wide, "/Volumes/Shared/Shared Projects/Laura/Peds Endo/PEDSNet/CAH/Data_clean/CAH_cleaned_data.csv",
#          row.names = F)

# read in CDC data
# height
cdc_hgt <- read.csv("/Volumes/Shared/Shared Projects/Laura/Peds Endo/PEDSNet/CAH/Data_raw/statage.csv")
cdc_hgt$source <- "CDC"
cdc_hgt$param <- "HEIGHTCM"
cdc_hgt <- cdc_hgt %>% select(-c(L, M, S))
cdc_hgt$age <- cdc_hgt$Agemos / 12
cdc_hgt$agemo <- cdc_hgt$Agemos
cdc_hgt <- cdc_hgt %>% filter(age >=2 & age<=18)
cdc_hgt <- cdc_hgt %>% rename(p03="P3", p05="P5", p10="P10", p25="P25", p50="P50", p75="P75", p90="P90", p95="P95", p97="P97")
cdc_hgt_males <- cdc_hgt %>% filter(Sex==1)
cdc_hgt_females <- cdc_hgt %>% filter(Sex==2)
# weight
cdc_wgt <- read.csv("/Volumes/Shared/Shared Projects/Laura/Peds Endo/PEDSNet/CAH/Data_raw/wtage.csv")
cdc_wgt$source <- "CDC"
cdc_wgt$param <- "WEIGHTKG"
cdc_wgt <- cdc_wgt %>% select(-c(L, M, S))
cdc_wgt$age <- cdc_wgt$Agemos / 12
cdc_wgt$agemo <- cdc_wgt$Agemos
cdc_wgt <- cdc_wgt %>% filter(age >=2 & age<=18)
cdc_wgt <- cdc_wgt %>% rename(p03="P3", p05="P5", p10="P10", p25="P25", p50="P50", p75="P75", p90="P90", p95="P95", p97="P97")
cdc_wgt_males <- cdc_wgt %>% filter(Sex==1)
cdc_wgt_females <- cdc_wgt %>% filter(Sex==2)
# BMI
cdc_bmi <- read.csv("/Volumes/Shared/Shared Projects/Laura/Peds Endo/PEDSNet/CAH/Data_raw/bmiagerev.csv")
cdc_bmi$source <- "CDC"
cdc_bmi$param <- "BMI"
cdc_bmi$Agemos <- as.numeric(cdc_bmi$Agemos)
cdc_bmi$age <- cdc_bmi$Agemos / 12
cdc_bmi <- cdc_bmi %>% filter(age >=2 & age<=18)
cdc_bmi$P3 <- as.numeric(cdc_bmi$P3)
cdc_bmi$P5 <- as.numeric(cdc_bmi$P5)
cdc_bmi$P10 <- as.numeric(cdc_bmi$P10)
cdc_bmi$P25 <- as.numeric(cdc_bmi$P25)
cdc_bmi$P50 <- as.numeric(cdc_bmi$P50)
cdc_bmi$P75 <- as.numeric(cdc_bmi$P75)
cdc_bmi$P90 <- as.numeric(cdc_bmi$P90)
cdc_bmi$P95 <- as.numeric(cdc_bmi$P95)
cdc_bmi$P97 <- as.numeric(cdc_bmi$P97)
cdc_bmi$age <- cdc_bmi$Agemos / 12
cdc_bmi$agemo <- cdc_bmi$Agemos
cdc_bmi <- cdc_bmi %>% select(-c(L, M, S))
cdc_bmi <- cdc_bmi %>% rename(p03="P3", p05="P5", p10="P10", p25="P25", p50="P50", p75="P75", p90="P90", p95="P95", p97="P97")
cdc_bmi_males <- cdc_bmi %>% filter(Sex==1)
cdc_bmi_females <- cdc_bmi %>% filter(Sex==2)

# fit models to CDC data
# height
cdc_hgt_males <- subset(cdc_hgt_males, select=c(source, param, age, agemo, p03, p05, p10, p25, p50, p75, p90, p95, p97))
cdc_hgt_males.form05 <- gcrq(data=cdc_hgt_males, p05 ~ ps(age), tau=0.5)
cdc_hgt_males.form50 <- gcrq(data=cdc_hgt_males, p50 ~ ps(age), tau=0.5)
cdc_hgt_males.form95 <- gcrq(data=cdc_hgt_males, p95 ~ ps(age), tau=0.5)
cdc_hgt_females <- subset(cdc_hgt_females, select=c(source, param, age, agemo, p03, p05, p10, p25, p50, p75, p90, p95, p97))
cdc_hgt_females.form05 <- gcrq(data=cdc_hgt_females, p05 ~ ps(age), tau=0.5)
cdc_hgt_females.form50 <- gcrq(data=cdc_hgt_females, p50 ~ ps(age), tau=0.5)
cdc_hgt_females.form95 <- gcrq(data=cdc_hgt_females, p95 ~ ps(age), tau=0.5)
# weight
cdc_wgt_males <- subset(cdc_wgt_males, select=c(source, param, age, agemo, p03, p05, p10, p25, p50, p75, p90, p95, p97))
cdc_wgt_males.form05 <- gcrq(data=cdc_wgt_males, p05 ~ ps(age), tau=0.5)
cdc_wgt_males.form50 <- gcrq(data=cdc_wgt_males, p50 ~ ps(age), tau=0.5)
cdc_wgt_males.form95 <- gcrq(data=cdc_wgt_males, p95 ~ ps(age), tau=0.5)
cdc_wgt_females <- subset(cdc_wgt_females, select=c(source, param, age, agemo, p03, p05, p10, p25, p50, p75, p90, p95, p97))
cdc_wgt_females.form05 <- gcrq(data=cdc_wgt_females, p05 ~ ps(age), tau=0.5)
cdc_wgt_females.form50 <- gcrq(data=cdc_wgt_females, p50 ~ ps(age), tau=0.5)
cdc_wgt_females.form95 <- gcrq(data=cdc_wgt_females, p95 ~ ps(age), tau=0.5)
# BMI
cdc_bmi_males <- subset(cdc_bmi_males, select=c(source, param, age, agemo, p03, p05, p10, p25, p50, p75, p90, p95, p97))
cdc_bmi_males.form05 <- gcrq(data=cdc_bmi_males, p05 ~ ps(age), tau=0.5)
cdc_bmi_males.form50 <- gcrq(data=cdc_bmi_males, p50 ~ ps(age), tau=0.5)
cdc_bmi_males.form95 <- gcrq(data=cdc_bmi_males, p95 ~ ps(age), tau=0.5)
cdc_bmi_females <- subset(cdc_bmi_females, select=c(source, param, age, agemo, p03, p05, p10, p25, p50, p75, p90, p95, p97))
cdc_bmi_females.form05 <- gcrq(data=cdc_bmi_females, p05 ~ ps(age), tau=0.5)
cdc_bmi_females.form50 <- gcrq(data=cdc_bmi_females, p50 ~ ps(age), tau=0.5)
cdc_bmi_females.form95 <- gcrq(data=cdc_bmi_females, p95 ~ ps(age), tau=0.5)
```

# All CAH data

## Males and females

### Raw descriptive statistics - males

```{r echo=FALSE, include = FALSE}
t <- CreateTableOne(data=cleaned_data_wide_males, vars = c("height_cm", "weight_kg", "bmi"), 
                   strata = "age" )
t <- print(t, nonnormal = c("height_cm", "weight_kg", "bmi"))
kable(t)
```

```{r echo=FALSE, include = TRUE}
kable(t)
```

### Raw descriptive statistics - females

```{r echo=FALSE, include=FALSE}
t <- CreateTableOne(data=cleaned_data_wide_females, vars = c("height_cm", "weight_kg", "bmi"), 
                   strata = "age" )
t <- print(t, nonnormal = c("height_cm", "weight_kg", "bmi"))
kable(t)
```

```{r echo=FALSE, include=TRUE}
kable(t)
```

### Height

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide[!is.na(cleaned_data_wide$height_cm),], height_cm ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide[!is.na(cleaned_data_wide$height_cm),], height_cm ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="Height (cm)", xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,200))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,200,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,200,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
# axis(3, at=3:19, lwd=0.5, tck=1, cex.axis=0.95, padj=3.65)
```

### Weight

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide[!is.na(cleaned_data_wide$weight_kg),], weight_kg ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide[!is.na(cleaned_data_wide$weight_kg),], weight_kg ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="Weight (kg)", xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,140))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,140,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,140,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
# axis(3, at=3:19, lwd=0.5, tck=1, cex.axis=0.95, padj=3.65)
```

### BMI

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide[!is.na(cleaned_data_wide$bmi),], bmi ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide[!is.na(cleaned_data_wide$bmi),], bmi ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
# something is odd here - the raw median BMI is 28.26, but the plotted BMI is almost 40
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab=expression(BMI ~ kg/m^"2"), xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,70))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,70,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,70,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
# axis(3, at=3:19, lwd=0.5, tck=1, cex.axis=0.95, padj=3.65)
```

## Males

### Height

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_males, height_cm ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_males, height_cm ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="Height (cm)", xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,200))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,200,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,200,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
lines(x=cdc_hgt_males$age, y=cdc_hgt_males$p05,  lwd=2, type = "l", lty=1, col="darkorange3")
lines(x=cdc_hgt_males$age, y=cdc_hgt_males$p50,  lwd=2, lty=1, col="darkorange3")
lines(x=cdc_hgt_males$age, y=cdc_hgt_males$p95,  lwd=2, lty=1, col="darkorange3")

```

### Weight

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_males, weight_kg ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_males, weight_kg ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="Weight (kg)", xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,140))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,140,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,140,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
lines(x=cdc_wgt_males$age, y=cdc_wgt_males$p05,  lwd=2, type = "l", lty=1, col="darkorange3")
lines(x=cdc_wgt_males$age, y=cdc_wgt_males$p50,  lwd=2, lty=1, col="darkorange3")
lines(x=cdc_wgt_males$age, y=cdc_wgt_males$p95,  lwd=2, lty=1, col="darkorange3")
```

### BMI

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_males, bmi ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_males, bmi ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab=expression(BMI ~ kg/m^"2"), xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,70))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,70,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,70,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
lines(x=cdc_bmi_males$age, y=cdc_bmi_males$p05,  lwd=2, type = "l", lty=1, col="darkorange3")
lines(x=cdc_bmi_males$age, y=cdc_bmi_males$p50,  lwd=2, lty=1, col="darkorange3")
lines(x=cdc_bmi_males$age, y=cdc_bmi_males$p95,  lwd=2, lty=1, col="darkorange3")
```

## Females

### Height

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_females, height_cm ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_females, height_cm ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="Height (cm)", xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,200))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,200,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,200,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
lines(x=cdc_hgt_females$age, y=cdc_hgt_females$p05,  lwd=2, type = "l", lty=1, col="darkorange3")
lines(x=cdc_hgt_females$age, y=cdc_hgt_females$p50,  lwd=2, lty=1, col="darkorange3")
lines(x=cdc_hgt_females$age, y=cdc_hgt_females$p95,  lwd=2, lty=1, col="darkorange3")
```

### Weight

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_females, weight_kg ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_females, weight_kg ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="Weight (kg)", xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,140))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,140,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,140,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
lines(x=cdc_wgt_females$age, y=cdc_wgt_females$p05,  lwd=2, type = "l", lty=1, col="darkorange3")
lines(x=cdc_wgt_females$age, y=cdc_wgt_females$p50,  lwd=2, lty=1, col="darkorange3")
lines(x=cdc_wgt_females$age, y=cdc_wgt_females$p95,  lwd=2, lty=1, col="darkorange3")
```

### BMI

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_females, bmi ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_females, bmi ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab=expression(BMI ~ kg/m^"2"), xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,70))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,70,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,70,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
lines(x=cdc_bmi_females$age, y=cdc_bmi_females$p05,  lwd=2, type = "l", lty=1, col="darkorange3")
lines(x=cdc_bmi_females$age, y=cdc_bmi_females$p50,  lwd=2, lty=1, col="darkorange3")
lines(x=cdc_bmi_females$age, y=cdc_bmi_females$p95,  lwd=2, lty=1, col="darkorange3")
```

# CAH subset

## Males and females

### Height

```{r echo=FALSE}
# fit the model
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_subset, height_cm ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_subset, height_cm ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="Height", xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,200))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,200,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,200,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
# axis(3, at=3:19, lwd=0.5, tck=1, cex.axis=0.95, padj=3.65)
```

### Weight

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_subset, weight_kg ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_subset, weight_kg ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="Weight", xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,140))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,140,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,140,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
# axis(3, at=3:19, lwd=0.5, tck=1, cex.axis=0.95, padj=3.65)
```

### BMI

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_subset, bmi ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_subset, bmi ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="BMI", xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,80))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,80,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,80,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
# axis(3, at=3:19, lwd=0.5, tck=1, cex.axis=0.95, padj=3.65)
```

## Males

### Height

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_subset_males, height_cm ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_subset_males, height_cm ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="Height (cm)", xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,200))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,200,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,200,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
lines(x=cdc_hgt_males$age, y=cdc_hgt_males$p05,  lwd=2, type = "l", lty=1, col="darkorange3")
lines(x=cdc_hgt_males$age, y=cdc_hgt_males$p50,  lwd=2, lty=1, col="darkorange3")
lines(x=cdc_hgt_males$age, y=cdc_hgt_males$p95,  lwd=2, lty=1, col="darkorange3")
```

### Weight

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_subset_males, weight_kg ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_subset_males, weight_kg ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="Weight (kg)", xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,140))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,140,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,140,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
lines(x=cdc_wgt_males$age, y=cdc_wgt_males$p05,  lwd=2, type = "l", lty=1, col="darkorange3")
lines(x=cdc_wgt_males$age, y=cdc_wgt_males$p50,  lwd=2, lty=1, col="darkorange3")
lines(x=cdc_wgt_males$age, y=cdc_wgt_males$p95,  lwd=2, lty=1, col="darkorange3")
```

### BMI

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_subset_males, bmi ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_subset_males, bmi ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab=expression(BMI ~ kg/m^"2"), xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,70))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,70,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,70,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
lines(x=cdc_bmi_males$age, y=cdc_bmi_males$p05,  lwd=2, type = "l", lty=1, col="darkorange3")
lines(x=cdc_bmi_males$age, y=cdc_bmi_males$p50,  lwd=2, lty=1, col="darkorange3")
lines(x=cdc_bmi_males$age, y=cdc_bmi_males$p95,  lwd=2, lty=1, col="darkorange3")
```

## Females

### Height

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_subset_females, height_cm ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_subset_females, height_cm ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="Height (cm)", xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,200))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,200,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,200,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
lines(x=cdc_hgt_females$age, y=cdc_hgt_females$p05,  lwd=2, type = "l", lty=1, col="darkorange3")
lines(x=cdc_hgt_females$age, y=cdc_hgt_females$p50,  lwd=2, lty=1, col="darkorange3")
lines(x=cdc_hgt_females$age, y=cdc_hgt_females$p95,  lwd=2, lty=1, col="darkorange3")
```

### Weight

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_subset_females, weight_kg ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_subset_females, weight_kg ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab="Weight (kg)", xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,140))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,140,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,140,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
lines(x=cdc_wgt_females$age, y=cdc_wgt_females$p05,  lwd=2, type = "l", lty=1, col="darkorange3")
lines(x=cdc_wgt_females$age, y=cdc_wgt_females$p50,  lwd=2, lty=1, col="darkorange3")
lines(x=cdc_wgt_females$age, y=cdc_wgt_females$p95,  lwd=2, lty=1, col="darkorange3")
```

### BMI

```{r echo=FALSE}
# fit the model
set.seed(3654)
tau2=c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
tau3=c(0.1, 0.5, 0.9)
mform <-gcrq(data=cleaned_data_wide_subset_females, bmi ~ ps(age, monotone=1), tau=tau2)
mform_red <- gcrq(data=cleaned_data_wide_subset_females, bmi ~ ps(age, monotone=1), tau=tau3)
```

```{r echo=FALSE}
plot(mform, lwd=2, legend=TRUE, 
     lty=1, cex=0.5,col=1,xaxt="n",yaxt="n",
     ylab=expression(BMI ~ kg/m^"2"), xlab="Age (yrs))", xlim=c(0,18),ylim=c(0,70))
axis(1, at=0:18, lwd=0.5, tck=1, cex.axis=0.95, padj=-1.7)
axis(2, at=seq(0,70,10), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
axis(4, at=seq(0,70,5), lwd=0.5, tck=1, cex.axis=0.95, las=1, hadj=0.5)
lines(x=cdc_bmi_females$age, y=cdc_bmi_females$p05,  lwd=2, type = "l", lty=1, col="darkorange3")
lines(x=cdc_bmi_females$age, y=cdc_bmi_females$p50,  lwd=2, lty=1, col="darkorange3")
lines(x=cdc_bmi_females$age, y=cdc_bmi_females$p95,  lwd=2, lty=1, col="darkorange3")
```
