---
title: "Renal HEIRitage Analysis"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    theme: default
    page-layout: full
    embed-resources: true
editor: visual
---

```{r, include = F}
library(dplyr)
library(tidyr)
library(table1)
library(Hmisc)
library(rstatix)
library(purrr)
library(kableExtra)
library(knitr)
library(arsenal)
library(data.table)
library(ggpubr)
library(smplot2)
library(magrittr)
library(ppcor)
source("/Users/choiyej/GitHub/YC_CHCO/R Functions/correlation_function.R")
```

```{r, include = F}
# Import data and data dictionary
dat <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv", na.strings = c(" ", "", "-9999",-9999))
dict <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/data_dictionary_master.csv", na.strings = c(" ", "", "-9999",-9999)) %>%
  dplyr::select(variable_name, label)

# Limit dataset to IMPROVE, RH, RH2, and collapse to 1 row per participant
dat <- dat %>%
  filter(study == "RENAL-HEIRitage"|study == "RENAL-HEIR"|study == "IMPROVE") %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
            across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
            .by = c(record_id)) %>%
  #filter(participation_status!="Removed"|is.na(participation_status)) %>%
  mutate(race_ethnicity_condensed = case_when(race == "White" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino White",
                                              race == "Black or African American" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino Black",
                                              ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
                                              T ~ "Not Hispanic or Latino Other")) %>%
  mutate(elevated_albuminuria = case_when(elevated_albuminuria == "Yes" ~ "Elevated albuminuria",
                                          elevated_albuminuria == "No" ~ "Normoalbuminuria")) %>% 
  mutate_at(vars(starts_with("fsoc")), function(x) case_when(x < 0 ~ 0, T~x)) 

# Add follow up time to co-enrolled list
dat <- dat %>%
  group_by(mrn) %>%   
  dplyr::mutate(date_diff = as.numeric(interval(min(date), date), unit = "years")) %>%
  group_by(mrn, date_diff) %>%
  distinct(mrn, .keep_all = T)

# Calculate variables of interest
dat %<>% ungroup() %>%
  mutate(m_i = gir_190 / steady_state_insulin,
         ht_tkv = total_kidney_volume_ml/height,
         avg_c_f = rowMeans(dplyr::select(., lc_f, rc_f), na.rm = T),
         avg_m_f = rowMeans(dplyr::select(., lm_f, rm_f), na.rm = T),
         avg_c_k2 = rowMeans(dplyr::select(., lc_k2, rc_k2), na.rm = T),
         avg_m_k2 = rowMeans(dplyr::select(., lm_k2, rm_k2), na.rm = T),
         avg_c_vb = rowMeans(dplyr::select(., lc_vb, rc_vb), na.rm = T),
         avg_m_vb = rowMeans(dplyr::select(., lm_vb, rm_vb), na.rm = T),
         avg_c_k1 = rowMeans(dplyr::select(., lc_k1, rc_k1), na.rm = T),
         avg_m_k1 = rowMeans(dplyr::select(., lm_k1, rm_k1), na.rm = T),
         avg_bl_cortex = rowMeans(dplyr::select(., bold_l_bl_cortex, bold_r_bl_cortex), na.rm = T),
         avg_bl_medulla = rowMeans(dplyr::select(., bold_l_bl_medulla, bold_r_bl_medulla), na.rm = T),
         avg_fsoc_medulla = rowMeans(dplyr::select(., fsoc_l_medulla, fsoc_r_medulla), na.rm = T),
         avg_fsoc_cortex = rowMeans(dplyr::select(., fsoc_l_cortex, fsoc_r_cortex), na.rm = T),
         avg_pcasl3d = rowMeans(dplyr::select(., pcasl3d_left, pcasl3d_right), na.rm = T),
         avg_k1_wo_cyst = rowMeans(dplyr::select(., ltot_k1_wo_cyst, rtot_k1_wo_cyst), na.rm = T),
         avg_k2_wo_cyst = rowMeans(dplyr::select(., ltot_k2_wo_cyst, rtot_k2_wo_cyst), na.rm = T),
         egfr_hyper = case_when(eGFR_fas_cr >= 135 ~ "Yes", eGFR_fas_cr < 135 ~ "No"),
         insulin_cpep = steady_state_insulin / steady_state_cpeptide,
         smr = case_when(!is.na(breast_tanner) ~ breast_tanner,
                         !is.na(testicular_volume) ~ ceiling(testicular_volume),
                         sex == "Female" & age >= 14 & group == "Type 2 Diabetes"|
                           sex == "Male" & age >= 16  & group == "Type 2 Diabetes" ~ 5,
                         sex == "Female" & age >= 16 ~ 5,
                         sex == "Male" & age >= 17 ~ 5),
         followup = case_when(date_diff == 0 ~ "Baseline",
                              T ~ "Follow up"),
         total_kidney_volume_ml_merged = case_when(is.na(total_kidney_volume_ml) ~ total_kidney_volume_ml_manual,
                                                   T ~ total_kidney_volume_ml),
         ht_adj_tkv_merged = total_kidney_volume_ml_merged / height)
dat$smr <- as.factor(dat$smr)

dict <- setNames(data.frame(t(dict[ , - 1])), dict[ , 1])
dict %<>%
  mutate(date_diff = "Follow up time (years)",
         elevated_albuminuria = "Elevated Albuminuria",
         m_i = "M/I",
         race_ethnicity_condensed = "Race/Ethnicity",
         lc_k2_f = "Left Cortex K2/F (g/min)",
         rc_k2_f = "Right Cortex K2/F (g/min)",
         lm_k2_f = "Left Medulla K2/F (g/min)",
         rm_k2_f = "Right Medulla K2/F (g/min)",
         avg_c_f = "Average Cortex F (ml/min/g)",
         avg_m_f = "Average Medulla F (ml/min/g)",
         avg_c_k2 = "Average Cortex K2 (1/min) ",
         avg_m_k2 = "Average Medulla K2 (1/min) ",
         avg_c_vb = "Average Cortex vb",
         avg_m_vb = "Average Medulla vb",
         avg_c_k1 = "Average Cortex k1 (ml/g/min)",
         avg_m_k1 = "Average Medulla k1 (ml/g/min)",
         rtot_k1_wo_cyst = "Voxel-wise right k1",
         ltot_k1_wo_cyst = "Voxel-wise left k1",
         rtot_k2_wo_cyst = "Voxel-wise right k2",
         ltot_k2_wo_cyst = "Voxel-wise left k2",
         avg_k1_wo_cyst = "Voxel-wise Average k1",
         avg_k2_wo_cyst = "Voxel-wise Average k2",
         avg_c_k2_f = "Average Cortex k2/F",
         avg_c_k2_k1 = "Average Cortex k2/k1",
         erpf_raw_plasma = "RPF from plasma clearance",
         avg_pcasl3d = "Average cortex 3D ASL",
         avg_bl_cortex = "Average cortex R2*",
         avg_bl_medulla = "Average medulla R2*",
         avg_fsoc_medulla = "Average FSOC medulla",
         avg_fsoc_cortex = "Average FSOC cortex",
         insulin_cpep = "Insulin/C-peptide ratio",
         ht_tkv = "Height adjusted TKV",
         ht_adj_tkv_merged = "Height adjusted TKV",
         total_kidney_volume_ml_merged = "Total TKV")

# Label data
dict <- dict[intersect(names(dat), names(dict))]
dict[setdiff(names(dat), names(dict))] <- ""
Hmisc::label(dat) = dict[match(names(dat), names(dict))]

# Subset to participants who have follow up data
rh_rh2 <- dat %>% group_by(mrn) %>%
  filter(max(row_number()) == 2)

# Subset to RH2 visits only
rh2 <- dat %>% group_by(mrn) %>%
  filter(max(row_number())==row_number() & !is.na(rh2_id))
```

# RH and RH2 (Baseline vs. follow up)

```{r echo = F, results='asis'}

#mGFR, RPF, kidney MRI (R1 and R2*), and tubular injury markers
# RH & RH2, baseline vs. follow up
summary(tableby(followup ~ age + group + diabetes_duration + sex + fe(race_ethnicity_condensed) + bmi + weight + height + waistcm + kwt(hba1c, "Nmiss", "median", "q1q3", "range") + sbp + dbp + cholesterol + ldl + hdl + total_kidney_volume_ml_merged + ht_adj_tkv_merged + kwt(triglycerides, "Nmiss", "median", "q1q3", "range") + kwt(eGFR_fas_cr, "Nmiss", "median", "q1q3", "range") + kwt(eGFR_fas_cr_cysc, "Nmiss", "median", "q1q3", "range") + kwt(acr_u, "Nmiss", "median", "q1q3", "range") + fe(elevated_albuminuria) + date_diff + gfr_raw_plasma + gfr_bsa_plasma + erpf_raw_plasma + erpf_bsa_plasma + avg_bl_cortex+ avg_bl_medulla + avg_fsoc_cortex + avg_fsoc_medulla + gloms + glom_nuc_count + glom_tuft_area + glom_volume_con + gloms_gs + mes_matrix_area + mes_matrix_area + mes_nuc_count + mes_volume_con + fia, data = rh_rh2, test = F))
```

# RH2 as cross-sectional

```{r echo = F, results='asis'}
# RH2 as cross-sectional
summary(tableby(group ~ age + diabetes_duration + sex + fe(race_ethnicity_condensed) + bmi + weight + height + waistcm + kwt(hba1c, "Nmiss", "median", "q1q3", "range") + sbp + dbp + cholesterol + ldl + hdl + total_kidney_volume_ml_merged + ht_adj_tkv_merged + kwt(triglycerides, "Nmiss", "median", "q1q3", "range") + kwt(eGFR_fas_cr, "Nmiss", "median", "q1q3", "range") + kwt(eGFR_fas_cr_cysc, "Nmiss", "median", "q1q3", "range") + kwt(acr_u, "Nmiss", "median", "q1q3", "range") + fe(elevated_albuminuria) + date_diff + gfr_raw_plasma + gfr_bsa_plasma + erpf_raw_plasma + erpf_bsa_plasma + avg_bl_cortex+ avg_bl_medulla + avg_fsoc_cortex + avg_fsoc_medulla + gloms + glom_nuc_count + glom_tuft_area + glom_volume_con + gloms_gs + mes_matrix_area + mes_matrix_area + mes_nuc_count + mes_volume_con + fia, data = rh2, test=F))
```

# Changes over time

## GFR

```{r echo = F, warning = F, message = F}
ggplot(rh_rh2, aes(x = followup, y = gfr_bsa_plasma)) +
  geom_boxplot() + 
  geom_point(aes(x = followup, y = gfr_bsa_plasma, color = group)) +
  geom_line(aes(x = followup, y = gfr_bsa_plasma, group = mrn, color = group)) +
  facet_wrap(vars(group)) +
  theme_bw()

ggplot(rh_rh2, aes(x = date_diff, y = gfr_bsa_plasma)) +
  geom_point(aes(x = date_diff, y = gfr_bsa_plasma, color = group)) +
  geom_line(aes(x = date_diff, y = gfr_bsa_plasma, group = mrn, color = group)) +
  facet_wrap(vars(group)) +
  theme_bw()
```

## HbA1c

```{r echo = F, warning = F, message = F}
ggplot(rh_rh2, aes(x = followup, y = log(hba1c))) +
  geom_boxplot() + 
  geom_point(aes(x = followup, y = log(hba1c), color = group)) +
  geom_line(aes(x = followup, y = log(hba1c), group = mrn, color = group)) +
  facet_wrap(vars(group)) +
  theme_bw()

ggplot(rh_rh2, aes(x = date_diff, y = log(hba1c))) +
  geom_point(aes(x = date_diff, y = log(hba1c), color = group)) +
  geom_line(aes(x = date_diff, y = log(hba1c), group = mrn, color = group)) +
  facet_wrap(vars(group)) +
  theme_bw()
```

## UACR

```{r echo = F, warning = F, message = F}
ggplot(rh_rh2, aes(x = followup, y = log(acr_u))) +
  geom_boxplot() + 
  geom_point(aes(x = followup, y = log(acr_u), color = group)) +
  geom_line(aes(x = followup, y = log(acr_u), group = mrn, color = group)) +
  facet_wrap(vars(group)) +
  theme_bw()

ggplot(rh_rh2, aes(x = date_diff, y = log(acr_u))) +
  geom_point(aes(x = date_diff, y = log(acr_u), color = group)) +
  geom_line(aes(x = date_diff, y = log(acr_u), group = mrn, color = group)) +
  facet_wrap(vars(group)) +
  theme_bw()
```

## TKV

```{r echo = F, warning = F, message = F}
ggplot(rh_rh2, aes(x = followup, y = total_kidney_volume_ml_merged)) +
  geom_boxplot() + 
  geom_point(aes(x = followup, y = total_kidney_volume_ml_merged, color = group)) +
  geom_line(aes(x = followup, y = total_kidney_volume_ml_merged, group = mrn, color = group)) +
  facet_wrap(vars(group)) +
  theme_bw()

ggplot(rh_rh2, aes(x = date_diff, y = total_kidney_volume_ml_merged)) +
  geom_point(aes(x = date_diff, y = total_kidney_volume_ml_merged, color = group)) +
  geom_line(aes(x = date_diff, y = total_kidney_volume_ml_merged, group = mrn, color = group)) +
  facet_wrap(vars(group)) +
  theme_bw()
```

## Correlations

```{r echo = F}
# source("/Users/choiyej/GitHub/CHCO-Code/Petter Bjornstad/Resources/YC/R Functions/label_harmonized_function.R")
# source("/Users/choiyej/GitHub/CHCO-Code/Petter Bjornstad/Resources/YC/R Functions/correlation_function.R")
# 
# #png(height = 1000, width = 1100, file = "/Users/choiyej/GitHub/YC_CHCO/RH/correlation4.png", res = 170)
# corr_plot_modified(data = dat, 
#                    X = c("acr_u"),
#                    Y = c("avg_c_k2",
#                          "avg_m_k2"), 
#                    cor_method = "spearman")
##dev.off()
```
