---
title: "Growth attenuation therapy analysis"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Davis/Growth attenuation analysis/Data raw"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r data, include=FALSE}
source("./GrowthAttenuationThe-DemographicsMedicalH_R_2022-04-10_2011.r")
demo <- data
data <- NULL

source("./GrowthAttenuationThe-BoneAge_R_2022-04-10_2017.r")
bone_age <- data
data <- NULL

source("./GrowthAttenuationThe-Labs_R_2022-04-10_2014.r")
labs <- data
data <- NULL


```


```{r echo=FALSE}
kable(t1,caption = "")
```
<br>
