---
title: "CT Entry"
author: "Ye Ji Choi"
format: html
editor: visual
---

```{r include = F}
library(dplyr)
library(arsenal)
dat <- read.csv("/Volumes/Peds Endo/Petter Bjornstad/Data Harmonization/Data Clean/harmonized_dataset.csv")
dat <- dat %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
            across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
            .by = record_id) %>%
  mutate(race_ethnicity_condensed = case_when(race == "White" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino White",
                                              race == "Black or African American" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino Black",
                                              ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
                                              T ~ "Not Hispanic or Latino Other")) %>%
  mutate(m_i = raw_m / steady_state_insulin,
         ht_tkv = total_kidney_volume_ml/height,
         lc_k2_f = lc_k2/lc_f,
         rc_k2_f = rc_k2/rc_f,
         lm_k2_f = lm_k2/lm_f,
         rm_k2_f = rm_k2/rm_f,
         lc_k2_k1 = lc_k2/lc_k1,
         rc_k2_k1 = rc_k2/rc_k1,
         lm_k2_k1 = lm_k2/lm_k1,
         rm_k2_k1 = rm_k2/rm_k1,
         avg_c_f = rowMeans(dplyr::select(., lc_f, rc_f), na.rm = T),
         avg_m_f = rowMeans(dplyr::select(., lm_f, rm_f), na.rm = T),
         avg_c_k2 = rowMeans(dplyr::select(., lc_k2, rc_k2), na.rm = T),
         avg_m_k2 = rowMeans(dplyr::select(., lm_k2, rm_k2), na.rm = T),
         avg_c_vb = rowMeans(dplyr::select(., lc_vb, rc_vb), na.rm = T),
         avg_m_vb = rowMeans(dplyr::select(., lm_vb, rm_vb), na.rm = T),
         avg_c_k1 = rowMeans(dplyr::select(., lc_k1, rc_k1), na.rm = T),
         avg_m_k1 = rowMeans(dplyr::select(., lm_k1, rm_k1), na.rm = T),
         avg_bl_cortex = rowMeans(dplyr::select(., bold_l_bl_cortex, bold_r_bl_cortex), na.rm = T),
         avg_bl_medulla = rowMeans(dplyr::select(., bold_l_bl_medulla, bold_r_bl_medulla), na.rm = T),
         avg_fsoc_medulla = rowMeans(dplyr::select(., fsoc_l_medulla, fsoc_r_medulla), na.rm = T),
         avg_pcasl3d = rowMeans(dplyr::select(., pcasl3d_left, pcasl3d_right), na.rm = T),
         avg_k1_wo_cyst = rowMeans(dplyr::select(., ltot_k1_wo_cyst, rtot_k1_wo_cyst), na.rm = T),
         avg_k2_wo_cyst = rowMeans(dplyr::select(., ltot_k2_wo_cyst, rtot_k2_wo_cyst), na.rm = T))

```

# PENGUIN
```{r}
summary(tableby(group ~ age + sex + race + p2_raw_m + gfr_raw_plasma + erpf_raw_plasma + avg_c_k2, data = subset(dat, study == "PENGUIN"|(study =="CROCODILE" & group == "Lean Control")), test = F))
```

# RENAL-HEIR
```{r}
summary(tableby(group ~ age + sex + race + raw_m + gfr_raw_plasma + erpf_raw_plasma + avg_pcasl3d + avg_bl_cortex, data = subset(dat, study == "RENAL-HEIR"), test = F))
```

# CROCODILE
```{r}
summary(tableby(group ~ age + sex + race + p2_raw_m + gfr_raw_plasma + erpf_raw_plasma + avg_fsoc_medulla + avg_pcasl3d + avg_bl_cortex, data = subset(dat, study == "CROCODILE"), test = F))
```