---
title: "SCH Market Share"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: rtf_document

---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyr)
library(ggplot2)
library(arsenal)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

```{r, include=FALSE}
sch <- read.csv("/Users/pylell/Library/CloudStorage/OneDrive-SharedLibraries-UW/CASSIDY/Preliminary data/2024.12.16 Diabetes Data Request.csv")

visits_by_zip <- sch %>% group_by(Patient.Zip) %>% summarise(visit_count = sum(Visits))
sum <- sch %>% summarise(sum(Visits))
```

# Results

## Table 1

```{r, include=FALSE}
t1 <- tableby(randomization_grp ~ AgeAtVisit1 + Biological.Sex + race_eth + Primary.Bariatric.Surgical.Procedure +
                                              Months.post.MBS.at.Enrollment + Obesity.Class.at.Enrollment + Qualifying.Inclusion.Criteria +
                                              Health.Insurance.Type + Primary.caregiver.s.highest.level.of.education. +
                                              Household.income.numeric + food_insecurity + height_m + wt + bmi + bmiz + bmip95 +
                                              sbp + dbp +
                                              hr + kwt(labs_a1c, "Nmiss2", "median", "q1q3") + kwt(labs_trig, "Nmiss2", "median", "q1q3") + 
                                              labs_hdl + labs_ldl + kwt(labs_alt, "Nmiss2", "median", "q1q3") +
                                              cesd_score + cesd_score_ge20, data = t1_data)
```

```{r, include=TRUE, results='asis'}
summary(t1)
```


