---
title: "US Census estimates"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
    code_folding: hide
---

```{r libraries}
#| include: false
library(knitr)
library(tidyverse)
library(tidyr)
library(arsenal)
library(stringr)
```

```{r clean data}
# read data by age and sex
age_sex <- read.csv('/Users/pylell/Library/CloudStorage/OneDrive-SharedLibraries-UW/CASSIDY/Preliminary data/US Census/cc-est2023-agesex-53.csv')
# select 2023
age_sex <- age_sex %>% filter(YEAR == 5)
# keep needed vars
age_sex <- age_sex %>% select(CTYNAME, UNDER5_TOT, AGE513_TOT, AGE1417_TOT, AGE1824_TOT, AGE2544_TOT, UNDER5_MALE, UNDER5_FEM, AGE513_MALE, AGE513_FEM,
                              AGE1417_MALE, AGE1417_FEM, AGE1824_MALE, AGE1824_FEM, AGE2544_MALE, AGE2544_FEM)
# calculate total in age groups we need
age_sex <- age_sex %>% mutate(UNDER18_TOT = rowSums(across(c(UNDER5_TOT, AGE513_TOT, AGE1417_TOT))))
age_sex <- age_sex %>% mutate(AGE1844_TOT = rowSums(across(c(AGE1824_TOT, AGE2544_TOT))))
age_sex <- age_sex %>% mutate(UNDER18_MALE = rowSums(across(c(UNDER5_MALE, AGE513_MALE, AGE1417_MALE))))
age_sex <- age_sex %>% mutate(AGE1844_MALE = rowSums(across(c(AGE1824_MALE, AGE2544_MALE))))
age_sex <- age_sex %>% mutate(UNDER18_FEMALE = rowSums(across(c(UNDER5_FEM, AGE513_FEM, AGE1417_FEM))))
age_sex <- age_sex %>% mutate(AGE1844_FEMALE = rowSums(across(c(AGE1824_FEM, AGE2544_FEM))))

# sum across all counties
age_sex_wa <- age_sex %>% summarise(across(c(UNDER18_TOT, AGE1844_TOT, 
                                             UNDER18_MALE, AGE1844_MALE,
                                             UNDER18_FEMALE, AGE1844_FEMALE), sum))

# sum across King, Snohomish, Pierce counties
age_sex_3cty <- age_sex %>% filter(CTYNAME %in% c("King County", "Pierce County", "Snohomish County")) %>% summarise(across(c(UNDER18_TOT, AGE1844_TOT, 
                                             UNDER18_MALE, AGE1844_MALE,
                                             UNDER18_FEMALE, AGE1844_FEMALE), sum))

# read alldata - with race/ethnicity
alldata <- read.csv('/Users/pylell/Library/CloudStorage/OneDrive-SharedLibraries-UW/CASSIDY/Preliminary data/US Census/cc-est2023-alldata-53.csv')
# select 2023
alldata <- alldata %>% filter(YEAR == 5)
# select age groups
alldata <- alldata %>% filter(AGEGRP %in% c(1, 2, 3, 4, 5, 6, 7, 8, 9))
# keep needed vars
alldata <- alldata %>% select(CTYNAME, WA_MALE, WA_FEMALE, BA_MALE, BA_FEMALE, IA_MALE, IA_FEMALE, AA_MALE, AA_FEMALE, NA_MALE, NA_FEMALE, TOM_MALE, TOM_FEMALE)
# calculate total in ethnicities
alldata <- alldata %>% mutate(WA_TOTAL = rowSums(across(c(WA_MALE, WA_FEMALE))))
alldata <- alldata %>% mutate(BA_TOTAL = rowSums(across(c(BA_MALE, BA_FEMALE))))
alldata <- alldata %>% mutate(IA_TOTAL = rowSums(across(c(IA_MALE, IA_FEMALE))))
alldata <- alldata %>% mutate(AA_TOTAL = rowSums(across(AA_MALE, AA_FEMALE)))
alldata <- alldata %>% mutate(NA_TOTAL = rowSums(across(AA_MALE, AA_FEMALE)))
alldata <- alldata %>% mutate(TOM_TOTAL = rowSums(across(TOM_MALE, TOM_FEMALE)))


```{r}
t <- tableby(count ~ race + age, data = wa_wide_t)
```

```{r, include=TRUE, results='asis'}
summary(t)
```
