---
title: "WA Office of Financial Management estimates"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
    code_folding: hide
---

```{r libraries}
#| include: false
library(knitr)
library(tidyverse)
library(tidyr)
library(arsenal)
library(stringr)
```

```{r clean data}
# read in county file
county <- read.csv('/Users/pylell/Library/CloudStorage/OneDrive-SharedLibraries-UW/CASSIDY/Preliminary data/WA OFM/ofm_pop_sade_county_2020_to_2023.csv')
county <- county %>% filter(Area.Name %in% c("Washington", "King"))
county <- county %>% filter(Year == "2023")
county <- county %>% filter(Age.Group %in% c("0-4", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40-44"))

# read in county file with special age groups
county_s <- read.csv('/Users/pylell/Library/CloudStorage/OneDrive-SharedLibraries-UW/CASSIDY/Preliminary data/WA OFM/ofm_pop_sade_county_2020_to_2023_s.csv')
county_s <- county_s %>% filter(Area.Name %in% c("Washington", "King"))
county_s <- county_s %>% filter(Year == "2023")
county_s <- county_s %>% filter(Age.Group %in% c("0-17", "0-19", "0-2", "12-17", "15", "16", "17", "17-22", "17-29",
                                             "18", "18-39", "19", "5-17"))
county_s$X <- NULL

# combine df
df <- rbind(county, county_s)
df <- df %>% select(!c(Area.ID, Year))
# convert to numeric
df[,3:ncol(df)] <- apply(df[,3:ncol(df)], 2, as.numeric)
# separate df by state/county
wa <- df %>% filter(Area.Name == "Washington")
kc <- df %>% filter(Area.Name == "King")

# reshape
wa_wide <- reshape(wa, timevar = "Age.Group", direction = "wide", idvar = "Area.Name")
# get 18-44 totals
wa_wide$`Total.18-44` <- wa_wide$`Total.18-39` + wa_wide$`Total.40-44`
wa_wide$`White.Total.18-44` <- wa_wide$`White.Total.18-39` + wa_wide$`White.Total.40-44`
wa_wide$`Black.Total.18-44` <- wa_wide$`Black.Total.18-39` + wa_wide$`Black.Total.40-44`
wa_wide$`AIAN.Total.18-44` <- wa_wide$`AIAN.Total.18-39` + wa_wide$`AIAN.Total.40-44`
wa_wide$`NHOPI.Total.18-44` <- wa_wide$`NHOPI.Total.18-39` + wa_wide$`NHOPI.Total.40-44`
wa_wide$`Asian.Total.18-44` <- wa_wide$`Asian.Total.18-39` + wa_wide$`Asian.Total.40-44`
wa_wide$`Two.or.More.Races.Total.18-44` <- wa_wide$`Two.or.More.Races.Total.18-39` + wa_wide$`Two.or.More.Races.Total.40-44`
wa_wide$`Male.Total.18-44` <- wa_wide$`Male.18-39` + wa_wide$`Male.40-44`
wa_wide$`Male.Total.0-17` <- wa_wide$`Male.0-17`
wa_wide$`Female.Total.18-44` <- wa_wide$`Female.18-39` + wa_wide$`Female.40-44`
wa_wide$`Female.Total.0-17` <- wa_wide$`Female.0-17`
# get 0-44 totals
wa_wide$`Total.0-44` <- wa_wide$`Total.0-17` + wa_wide$`Total.18-44`
wa_wide$`White.Total.0-44` <- wa_wide$`White.Total.0-17` + wa_wide$`White.Total.18-44`
wa_wide$`Black.Total.0-44` <- wa_wide$`Black.Total.0-17` + wa_wide$`Black.Total.18-44`
wa_wide$`AIAN.Total.0-44` <- wa_wide$`AIAN.Total.0-17` + wa_wide$`AIAN.Total.18-44`
wa_wide$`NHOPI.Total.0-44` <- wa_wide$`NHOPI.Total.0-17` + wa_wide$`NHOPI.Total.18-44`
wa_wide$`Asian.Total.0-44` <- wa_wide$`Asian.Total.0-17` + wa_wide$`Asian.Total.18-44`
wa_wide$`Two.or.More.Races.Total.0-44` <- wa_wide$`Two.or.More.Races.Total.0-17` + wa_wide$`Two.or.More.Races.Total.18-44`
wa_wide$`Female.Total.0-44` <- wa_wide$`Female.Total.0-17` + wa_wide$`Female.Total.18-44`
wa_wide$`Male.Total.0-44` <- wa_wide$`Male.Total.0-17` + wa_wide$`Male.Total.18-44`
# keep needed vars
wa_wide <- wa_wide %>% select(`Total.0-17`,`White.Total.0-17`, `Black.Total.0-17`, `AIAN.Total.0-17`, `NHOPI.Total.0-17`, `Asian.Total.0-17`, `Two.or.More.Races.Total.0-17`,
                              `Total.18-44`,`White.Total.18-44`, `Black.Total.18-44`, `AIAN.Total.18-44`, `NHOPI.Total.18-44`, `Asian.Total.18-44`, `Two.or.More.Races.Total.18-44`,
                              `Total.0-44`,`White.Total.0-44`, `Black.Total.0-44`, `AIAN.Total.0-44`, `NHOPI.Total.0-44`, `Asian.Total.0-44`, `Two.or.More.Races.Total.0-44`,
                              `Male.Total.0-44`,`Female.Total.0-44`)
wa_wide_t <- as.data.frame(t(wa_wide))
wa_wide_t$age <- str_extract(rownames(wa_wide_t), "(?<=Total.).*")
wa_wide_t$race <- str_extract(rownames(wa_wide_t), "^(.*?.*?.*?)(?=Total.)")
wa_wide_t$race <- ifelse(wa_wide_t$race == "", "Total", wa_wide_t$race)
wa_wide_t$count <- wa_wide_t$`1`
wa_wide_t <- wa_wide_t %>% select(race, age, count)
```

```{r}
t <- tableby(count ~ race + age, data = wa_wide_t)
```

```{r, include=TRUE, results='asis'}
summary(t)
```
